### PR TITLE
fix(cloud-masthead): address various visual bugs

### PR DESCRIPTION
**Pull request by m4olivei**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9926
https://jsw.ibm.com/browse/ADCMS-2742

### Description

Minor CSS changes were necessary to address all four issues as laid out nicely in the issue / ticket.

### Changelog

**Changed**

- fix arrow color on cloud masthead category header
- fix unintended vertical scroll bar in the cloud masthead
- fix hover color of the mega menu category link description 
- fix focus styles on top nav link

### CODE REVIEW

**Comment by annawen1** [comment]
@m4olivei I'm adding the `feature-flag` label so we can view the experimental deploy previews which contain the cloud masthead stories

Closing + re-opening PR to re-trigger the deploy preview jobs

**Comment by andy-blum** [comment]
@jwitkowski79 this is ready for design review whenever you have a few minutes!

https://ibmdotcom-web-components-experimental.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/9927/index.html?path=/story/components-cloud-masthead--default

**Comment by jwitkowski79** [comment]
@andy-blum @m4olivei Hello! Just one small change. On the heading level 1 hover state, the arrow color changes from icon-01 to blue 60. On hover, the arrow color should stay the icon-01 color. I've attached a screenshot of the bug and a screen shot of the design specs. Everything else looks great! Thanks!
Screen_Shot_2023-01-23_at_9_22_24_AM

Screen Shot 2023-01-23 at 9 24 07 AM

**Comment by proeung** [comment]
@jwitkowski79 @m4olivei I apologize in advance for anything that I might have missed during my absence, however, the changes outlined in the scope of this ticket (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9926) and https://jsw.ibm.com/browse/ADCMS-2742 look to be the same as what we have already implemented in the `feat/masthead-v2` branch that's part of the Masthead v2.0.0 updates (see EPIC - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9208).

If I remember correctly, as part of the navigation consolidation effort, we're looking to switch the tag and CDN files within the Drupal `/cloud` web segment to use `<dds-masthead-container>` instead of `<dds-cloud-masthead-container>` tag. This ensures that the `/cloud` web segment is using the same component tag that embodies the design changes/updates that are part of v2. Additionally, this allows us to eventually depreciate the `components/masthead/cloud` directory and the usage of `<dds-cloud-masthead-container>`.

**Example of the Cloud masthead data using the Masthead v2 component updates** - https://5p5s3w.csb.app/

Unless this plan has changed? @andy-blum or @jkaeser Do either of you know?

Screen Shot 2023-01-23 at 3 18 17 PM

**Comment by andy-blum** [comment]
@proeung I don't believe the plan has changed, but I think this PR is important to fix the design bugs that are currently present that won't be remedied by `feat/masthead-v2` for quite some time.

**Comment by proeung** [comment]
@andy-blum I see. So the changes here are a stop-gap solution until we have transitioned the custom elements used within the `/cloud` web segment to the V2 updates. If that's the case then, please disregard my message above, however, we should file this task under the Masthead V2 phase two effort so that we can work on making the changes in the `ibm-cloud` sub-theme to reflect the changes when it's ready. I'll note that as a follow-up to this JIRA ticket - https://jsw.ibm.com/browse/ADCMS-2742.

**Review by proeung — APPROVED** [review]
LGTM from a code perspective!

@jwitkowski79 or @oliviaflory Can you help do another round of design QA when you have a moment?

**Comment by oliviaflory** [comment]
@jwitkowski79 @proeung looks fine to me based on the Jira ticket. I am assuming no changes are being made to the mobile menu to align to the new v2 masthead?

PS. Welcome back @proeung! 🎉

**Review by oliviaflory — APPROVED** [review]

**Comment by m4olivei** [comment]
> I am assuming no changes are being made to the mobile menu to align to the new v2 masthead?

Correct! This is only including changes to the cloud masthead at the desktop breakpoint.

**Comment by proeung** [comment]
> Doing some additional digging today but are these small UI changes ok to merge or should we hold off?

@jwitkowski79 This was my original question concerning this work (see - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9927#issuecomment-1400950410). I believe, @kjwhitla owns this on the Cloud side, but let's get on a quick call about this.

**Comment by jwitkowski79** [comment]
@proeung So based on our discussion, this is ok to merge. Joseph stated that Keegan is coordinating the cloud nav and that it's okay to merge these visual stop gaps down.

**Pull request merged**
