### PR TITLE
fix(image): add image caption to aria-describedby attribute

### LINKED ISSUE #9001: [Image – Default variant]: QA: The image caption is not programmatically associated
### Description

Page element:
Image Caption

Issue : The image caption is not programmatically associated

Expected: The adjacent caption can be associated with the image using the aria-describedby. The following link can be refered for more details. 
https://www.w3.org/TR/WCAG20-TECHS/ARIA15.html#:~:text=A%20feature%20of%20WAI%2DARIA,help%20users%20understand%20complex%20images.

Repro Steps: When the caption is not programmatically associated with the adjacent image, Screen reader user may not able to corelate the additional information related to the image. This Impacts Screen reader users.

### Component(s) impacted

Image

### Browser

Firefox

### Carbon for IBM.com version

v1.35.0-rc.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

Carbon for IBM.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)

Fixes #9001 

### Description

Adds a new `id` to the image's caption element and includes that id in the image's `aria-describedby` attribute. This allows the image to be described by _both_ the contents of the `long-description` slot and any caption text.

Additionally, added a storybook knob for the "long description" text for manual testing.

### Changelog

**Changed**

- Added image caption to `aria-describedby` elements

### CODE REVIEW

**Comment by andy-blum** [comment]
Screen Shot 2022-10-03 at 1 10 21 PM

**Review by IgnacioBecerra — APPROVED** [review]
LGTM, thanks @andy-blum

**Review by RichKummer — APPROVED** [review]

**Comment by kennylam** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by gopinathan-n** [comment]
Screen Reader now identifies the aria-describedby.

**Pull request merged**
