### PR TITLE
feat(footer): added custom adjunct links

### PR DESCRIPTION
**Pull request by RaphaelAmadeu**
### Related Ticket(s)

#5591

### Description

I've added custom adjunct links to the bottom of the legal nav.

image

### CODE REVIEW

**Comment by DragosRistici** [comment]
Hey, Raph, thank you for taking this on! We are close. 

1. The React footer stories, except the Adjunct legal links one, have this error:
Screenshot 2021-06-08 at 09 45 46

2. The vertical spacing between the 2 adjunct legal links should be 8px. Right now it is 4px:
Screenshot 2021-06-08 at 09 49 57
Screenshot 2021-06-08 at 09 51 27

3.  The links should have 4 cols - 32px, but measured without the right hang:
Screenshot 2021-06-08 at 09 55 17

4. The spacing between the Legal links and the Adjunct legal links should be 48px. There's a 32 + 16 + 8 now. 
Screenshot 2021-06-08 at 09 57 10 Screenshot 2021-06-08 at 09 57 16 Screenshot 2021-06-08 at 09 57 21

5. For mobile, the links are 4 cols - 32px. For some reason, the links are on 2 columns on mobile. 

What it is now:
Screenshot 2021-06-08 at 10 04 05
Screenshot 2021-06-08 at 10 03 53

What it should be on big and small mobile (4 cols - 32px):
Screenshot 2021-06-08 at 10 03 02
Screenshot 2021-06-08 at 10 02 54

Thanks!

**Comment by DragosRistici** [comment]
Hey, Raph, thank you for the updates. We are almost there. Little things to correct: 

### 1. Container should be 4cols - 32px. It looks like there's a difference between the first link and the second link. 

Screenshot 2021-06-16 at 17 32 21
Screenshot 2021-06-16 at 17 35 44
Screenshot 2021-06-16 at 17 36 59


### 2. For the medium breakpoint, its still 4 cols - 32px. 
Screenshot 2021-06-16 at 17 39 06
Screenshot 2021-06-16 at 17 41 54
### 3. For the mobile, the same issue. Container cuts into the width. Its 4 cols - 32px. 
Screenshot 2021-06-16 at 17 57 49




Other than that, it's good. Thank you for taking the time to adjust it, Raph.

**Comment by DragosRistici** [comment]
Also, @RaphaelAmadeu unexpected consequence: The other footer stories got an extra spacing due to the Adjunct container added to the bottom anyway. This changes also the Short and the Micro footer variants.

Screenshot 2021-06-16 at 18 20 34

Screenshot 2021-06-16 at 18 22 18
Screenshot 2021-06-16 at 18 24 12
Screenshot 2021-06-16 at 18 23 50

**Comment by DragosRistici** [comment]
Hey, Raph. Checked this morning. We are almost there. Hoping to see these 2 little things taking care of. 

1. The Micro footer container for the legal links to check the unwanted container modified width.
Screenshot 2021-06-16 at 20 02 25
Screenshot 2021-06-16 at 20 01 36

2. Containers for the two Adjunct legal links to be 4 cols - 32px
Screenshot 2021-06-17 at 16 29 23

**Comment by DragosRistici** [comment]
@RaphaelAmadeu Hey, Raph, any news on this guy here? When you're ready, gimme a buzz. Thx!

**Comment by DragosRistici** [comment]
Hey, @RaphaelAmadeu, there are a small number of Percy issues:

### 1. Added this padding left here that means 2 more pixels for the legal links. Was it necessary? 

Screenshot 2021-06-21 at 14 31 05
 Screenshot 2021-06-21 at 14 33 29
 
 
### 2. For some reason, Content group pictograms changed placement and looks out of grid. Let me know what's up here, if i need to open a new issue for it.
– Content group pictograms 
Screenshot 2021-06-21 at 15 04 46

I see more top spacing diffs, but seems like because of meantime changes. Let me know when things are good to go. Thx.

**Comment by kennylam** [comment]
Looks good @RaphaelAmadeu! Any chance you and @guilhermelMoraes can work out using the same selectors and CSS for this? The web components version is being added in #6432 and the markup is so simple I don't see why the styles should be in two different files.

**Review by guilhermelMoraes — APPROVED** [review]
LGTM, @RaphaelAmadeu! 👍🏻 
@kennylam chatting with Raph, we've decided to wait for his PR to get approved and merged so that I can pull these changes in and integrate them with my PR.

**Comment by DragosRistici** [comment]
We will have as stories:


Footer
```
|--- Default
|--- Default Language only
|--- Short
|--- Short Language only
|--- Micro
|--- Micro Language only
```

and add as a knob only for the first 4 (Micro stories are excluded):

`Adjunct legal links [ Yes / No ]`
By default, the Adjunct are `No`.

**Comment by jeffchew** [comment]
@RaphaelAmadeu can you update snapshot files? And is it ready for @DragosRistici to review again?

**Comment by DragosRistici** [comment]
Looks great! Let's resolve this minor story naming consistency and ima check Percy. 

Screenshot 2021-06-24 at 14 10 28

**Review by kennylam — APPROVED** [review]
LGTM thanks @RaphaelAmadeu!

**Review by DragosRistici — APPROVED** [review]
Looks good to me, @RaphaelAmadeu! Thank you!

**Comment by DragosRistici** [comment]
One last thing, @RaphaelAmadeu : its Adjunct **`legal`** links, not Adjunct links. Please, adjust the story names. Other than that, its good from me. Please, do this and i will re-approve it.

**Review by shixiedesign — APPROVED** [review]
Looks good! Dragos's last comment appears fixed

**Comment by DragosRistici** [comment]
> Looks good! Dragos's last comment appears fixed

Yup. Waiting on 2 more images from Percy and we're good to go.

**Review by DragosRistici — APPROVED** [review]
Thank you. Looks great!

**Pull request merged**
