### PR TITLE
chore(content-block-simple): use CSS grid for layout

### PR DESCRIPTION
**Pull request by asudoh**
### Related Ticket(s)

Refs #4174.

### Description

Updates `<dds-content-block-simple>` to use CSS grid for layout so it properly alignes to Carbon grid lines considering contents both one using gutter and one not using gutter.

### Changelog

**Changed**

- `<dds-content-block-simple>` to use CSS grid for layout.
- `<dds-content-block-simple>` story:
  - Use `<dds-card-cta>` instead of `<dds-text-cta>`.
  - Use `<dds-image-with-caption>` instead of `<dds-image>`.
- `<dds-callout-media>` so it won't be affected by change in `<dds-content-block-simple>`.
- Several fixes to `<dds-link-list>`:
  - Ensure the max width calculation is based on the content.
  - Eliminate negative margin adjustment for Web Components to ensure it doesn't rely on certain padding in the parent container.
- Fix icon placement of `<dds-link-list-item-cta>`.

### CODE REVIEW

**Comment by asudoh** [comment]
@ariellalgilmore Thank you for your comments in Percy! Backed out the change to link list as many components depend on link list and it's hard to make changes to all components to compensate for link list change at this point.

**Review by ariellalgilmore — APPROVED** [review]
LGTM!!! Thanks for the updates @asudoh! I think you just need to update your snapshots one more time

**Comment by asudoh** [comment]
Per update in the linked issue, the task is scheduled after the January release, and thus should me merged _after_ the code freeze. Thanks everybody for your input!

**Comment by jeffchew** [comment]
> Per update in the linked issue, the task is scheduled after the January release, and thus should me merged _after_ the code freeze. Thanks everybody for your input!

Thanks @asudoh , as discussed with the team we will hold on this merge til after code freeze this Friday.

**Comment by jeffchew** [comment]
@asudoh since this is past code freeze, we can merge this in. Can you resolve merge conflicts?

**Comment by asudoh** [comment]
Thank you for the ping @jeffchew - Done.

**Pull request merged**
