### PR TITLE
fix(tag-group): ensuring tags can be gray

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#9890

### Description
Ensured that the carbon tag can be gray when used within Tag Group.

### Changelog

**Removed**

- removed tag group condition that would change a tag color to green if gray was chosen

### CODE REVIEW

**Comment by ariellalgilmore** [comment]
Should the first tag in this tag group still be green?

[web-components]
Screen Shot 2023-02-01 at 8 13 31 AM

[react-wrappper]
Screen Shot 2023-02-01 at 8 14 57 AM

**Comment by IgnacioBecerra** [comment]
@ariellalgilmore Technically the default color should be green, according to the old specs from Shixie iirc, but wondering what @oliviaflory or @RichKummer might think now?

Should the default color of the regular carbon tag be Grey, or green?

**Comment by oliviaflory** [comment]
@IgnacioBecerra @ariellalgilmore I'm going to attempt to answer without using the word "default" so I am not mixing up what is "default" in the Carbon tag vs "default" in the Card.

In the issue #9890 Jared states
>When I add a Carbon tag to a component and pick the color "gray" in the dropdown, the tag will display as green tag, not gray. This needs to be updated so when gray is selected as the tag color, the tag displays as a gray tag.

>This bug seems to appear where ever Carbon tags are being used and isn't component specific.

I think this is the desired outcome:
- The user/author/developer can opt to use the `gray` Carbon tag within any component (ie Cards, Structured list, Pricing table). (I am assuming they would 
- Within the card component story, they/we do want to show the first tag in the card set to the `green` Carbon tag, which is most commonly used by AEM for tagging a product as "Most popular".

From the way the issue was phrased, it sounded like even if the developer set a tag to `gray` it would display as `green`?

When I look at the [Tag group story](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/9972/index.html?path=/story/components-tag-group--default&knob-Add%20tags:_Default=true&knob-CTA:_Default=Learn%20more&knob-Card%20style:_Default=none&knob-Eyebrow:_Default=Industry&knob-Heading:_Default=Aerospace%20and%20defence), and change the tag type knob to `Carbon tag` they all are green. Is that part of what Jared is having trouble with?

I hope this is helpful!

**Comment by annawen1** [comment]
@IgnacioBecerra I'm a little confused by the description and changelog for the PR, we're not changing the default color to grey are we? We're just allowing the gray color to show when adopter specifies "gray" in the type

**Comment by IgnacioBecerra** [comment]
@annawen1 Yeah, you're right, that's all we're doing. I'm gonna update the changelog and description.

**Review by RichKummer — APPROVED** [review]
Seeing that the theme can be swapped to `gray` and shows the correct colors, LGTM!

**Review by ariellalgilmore — APPROVED** [review]
LGTM!

**Pull request merged**
