### PR TITLE
fix(video-player): account for video players in shadowroots

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)
- Issue - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10228
- As pointed out in [ADCMS-2137](https://jsw.ibm.com/browse/ADCMS-2137), there are console errors around the video player components.

### Description

PR addresses two console errors:

1. The video-player-container was previously using `ownerDocument` where `getRootNode()` should have been. This lead to a problem where `.getElementById` was returning null and then we tried to access non-existent properties of null.
2. The video-player on `firstUpdated` wants to use it's parent container's value of `backgroundMode`. This was wrongly assuming a video-container always existed as a parent and that it's value of `backgroundMode` is always set

### Changelog

**Changed**

- video player bugfixes

### CODE REVIEW

**Review by proeung — APPROVED** [review]
Looks good from a code perspective.

As for testing/verification of this PR, can you adjust the codeSandbox example of the `tabs-extended-media` component (see [link](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/examples/codesandbox/components/tabs-extended-media/index.html#L26)) to include examples of the video player?

See this Code Sandbox for an example - https://codesandbox.io/s/purple-hill-x0xm5e?file=/index.html | https://x0xm5e.csb.app/

**Comment by proeung** [comment]
@andy-blum Any thoughts? https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10227#pullrequestreview-1337808782

Can we get a review from the @carbon-design-system/carbon-for-ibm-com-members team?

**Comment by proeung** [comment]
@andy-blum When you're free, can you follow up on my feedback here (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10227#issuecomment-1478489491) so that we can merge/close out this PR?

**Comment by proeung** [comment]
@andy-blum Thanks for updating the code sandbox example!

@carbon-design-system/carbon-for-ibm-com-members Can we get a review from your team? Thanks!

**Comment by andy-blum** [comment]
as noted here: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10342#issuecomment-1520670511


we can ignore the failed checks for the react package - a11y check is not required

and specifically errors like this one, that's causing the ci-check for react package to fail, is what we're looking into in the main branch, so please ignore those:

```
@carbon/ibmdotcom-react:   ● Test suite failed to run
@carbon/ibmdotcom-react:     TypeError: Cannot redefine property: window
@carbon/ibmdotcom-react:       28 | global.TextEncoder = TextEncoder;
@carbon/ibmdotcom-react:       29 | global.TextDecoder = TextDecoder;
@carbon/ibmdotcom-react:     > 30 |
@carbon/ibmdotcom-react:          | ^
@carbon/ibmdotcom-react:       31 | // mock matchMedia to resolve JSOM error
@carbon/ibmdotcom-react:       32 | Object.defineProperty(window, 'matchMedia', {
@carbon/ibmdotcom-react:       33 |   writable: true,
```

**Pull request merged**
