### PR TITLE
fix(feature-card-block-large): changed hover background color

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)

#3965

### Description

Background color was not changing upon hover, changed to match the medium/regular feature card blocks.

### Changelog

**Changed**

- Changed background color to `$background-ui` on hover

### CODE REVIEW

**Review by jeffchew — APPROVED** [review]
Thanks @IgnacioBecerra !

**Review by kennylam — APPROVED** [review]
Looks good thanks @IgnacioBecerra!

**Comment by annawen1** [comment]
@IgnacioBecerra one comment, I believe the background color should change not only when you hover over the text portion of the card, but if you hover anywhere in the feature card (even the image) the background should change color

**Review by annawen1 — APPROVED** [review]
LGTM!

**Pull request merged**
