### PR TITLE
fix(card-link): changed style to expressive-heading-02

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#5397

### Description
The current font style for `CardLink` and `CTACard` was using `$body-long-02`, while it should be using `$expressive-heading-02`. This PR changes the styles for both React and Web Components.

### Changelog

**Changed**

- changed `CardLink` and `CTACard` styles to using `$expressive-heading-02`
- updated `CardLink` Web Component README to remove the use of `<p>` for proper stylings to be applied

### CODE REVIEW

**Comment by oliviaflory** [comment]
1. Text alignment is off in the heading of Content block simple with aside elements in React (actually all layout components "with aside elements". Not sure if this is caused in this PR, so lmk if I should open a separate issue 
Screen Shot 2021-04-07 at 12 59 46 PM

2. The CTA card or Card link is not spanning full width on mobile as I expected in most layout component examples
Preview
Screen Shot 2021-04-07 at 1 00 48 PM
Expectation
Screen Shot 2021-04-07 at 1 01 35 PM

3. Commented in Percy, the Card group body text changed to $expressive-heading-02, but should remain as $body-long-02
Screen Shot 2021-04-07 at 1 05 49 PM

**Comment by IgnacioBecerra** [comment]
Hi @oliviaflory! For the heading with aside element issue, it's not caused by this PR, but I think I may know what's actually causing it. If you open a separate issue for this, you can assign me to it. 

And the other two issues have been fixed in the latest commit 👍

**Comment by photodow** [comment]
Are we just changing the font size? Should we be using the card link component here instead? Otherwise why do we have the component? Does that make sense?

**Review by jeffchew — APPROVED** [review]
LGTM!

**Comment by IgnacioBecerra** [comment]
With the latest commit, I made it so only the Web Components Card Link is updated. I also left over the fix for CTA not spanning full width.

**Review by oliviaflory — APPROVED** [review]
Approving with understanding that other issues will be fixed in #5740 and logo grid PR will fix those Percy differences

**Pull request merged**
