### PR TITLE
feat(slug): new cwc component

### LINKED ISSUE #11072: Slug Web Component
As shown in the C4AI [status table](https://github.com/orgs/carbon-design-system/projects/73/views/6?pane=info), the experimental styles for the slug component have been created and are being used by the React implementation.

By referencing the [design spec](https://github.com/orgs/carbon-design-system/projects/73/views/6?pane=issue&itemId=42224788) and React slug, we should be ready to implement the web component slug.

**Blocked by:**
- https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11048
```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

Closes #11072 

### Description

Create new Slug component
Screenshot 2023-11-16 at 10 54 56 AM

### Changelog

**New**

- slug component
- slug-action-button component (extended from cds-button) necessary to get styles
- stories

**Changed**

- updated @carbon/styles to latest which included new slug styles
- icon-button to have proper ghost color styles
- updated toggle-top for proper handling on close and set `alignment` to reflect true

### CODE REVIEW

**Review by annawen1 — APPROVED** [review]
Tech-wise this looks good to me!

**Comment by annawen1** [comment]
should we add the codesandbox examples too for WC and React wrapper?

**Review by aagonzales — CHANGES_REQUESTED** [review]
It looks good, just one thing. The dot in the large inline + hollow slug should be larger at 8px

image

**Comment by ariellalgilmore** [comment]
@aagonzales thanks! just updated and the deploy preview should be fixed now

**Review by aagonzales — APPROVED** [review]
Alright, everything looks good!

**Pull request merged**
