### PR TITLE
feat(card-group): add react wrapper stories and example

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#6905 

### Description

Create react wrapper stories for Card Group. Also, a codesandbox example.

For testing go to the react wrapper deploy preview and make sure all the Card Group stories work as expected with the different knobs. Also, can check the docs in the storybook tab

### Changelog

**New**

- react-wrapper story and readme
- codesandbox example

**Changed**

- web-component card-group styles to import web-component card styles
- updated web-component readme card-in-card example

### CODE REVIEW

**Review by photodow — COMMENTED** [review]
- [ ] collapsed with card in card is missing a border for some reason
image
- [ ] I really don't know where `with card links` came into the picture. Are we creating more work for us to remove that by adding that here?

**Comment by ariellalgilmore** [comment]
@photodow updated the with `card-in-card` story.  The `with card link` comes back to here: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6934

**Review by photodow — APPROVED** [review]
- [ ] Small issue when I change knob from narrow to collapsed the vertical spacing goes away. This actually appears to be an existing issue. If you can fix it here great, otherwise we can save it for a later PR.

image

**Review by jeffchew — APPROVED** [review]
LGTM!

**Pull request merged**
