### PR TITLE
fix(leadspace): remove image from centered leadspace with no image

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#5417 

### Description

Image displaying when rendering without image. Added condition to check for image `defaultSrc`

### Changelog

**Changed**

- update condition for `_renderImage()`

### CODE REVIEW

**Comment by IgnacioBecerra** [comment]
Screen Shot 2021-03-11 at 8 45 55 AM

Thanks @ariellalgilmore! The broken image doesn't show up anymore, but the background color still defaults to the gradient instead of remaining under the g100 theme.

I think this could be fixed by changing the breakpoint [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/packages/web-components/src/components/leadspace/leadspace.scss#L14-L20) to `sm` since the Web Components seems to be handling the gradient differently than in React.

**Comment by ariellalgilmore** [comment]
> Screen Shot 2021-03-11 at 8 45 55 AM
> 
> Thanks @ariellalgilmore! The broken image doesn't show up anymore, but the background color still defaults to the gradient instead of remaining under the g100 theme.
> 
> I think this could be fixed by changing the breakpoint [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/packages/web-components/src/components/leadspace/leadspace.scss#L14-L20) to `sm` since the Web Components seems to be handling the gradient differently than in React.

oh forgot to add that! thanks @IgnacioBecerra!

**Review by IgnacioBecerra — APPROVED** [review]
LGTM, thanks @ariellalgilmore!

**Comment by jeffchew** [comment]
@ariellalgilmore can you check Percy results? Looks like the opacity layer isn't behaving properly in some places.

**Comment by jeffchew** [comment]
Is it me or the opacity layer a bit bolder than it should be?

Screen Shot 2021-03-11 at 6 22 37 PM

**Comment by ariellalgilmore** [comment]
> Is it me or the opacity layer a bit bolder than it should be?
> 
> Screen Shot 2021-03-11 at 6 22 37 PM

haha yeah it's not just you. Working on this. the styles are a bit weird

**Review by jeffchew — APPROVED** [review]
Thank you @ariellalgilmore !

**Pull request merged**
