### PR TITLE
fix(table-of-contents): support dark theme

### PR DESCRIPTION
**Pull request by asudoh**
Refs #4214.

### Changelog

**Changed**

- Support dark theme in table of contents, both in React and in Web Components.

### CODE REVIEW

**Review by IgnacioBecerra — APPROVED** [review]
LGTM!

**Review by jeffchew — APPROVED** [review]
LGTM!

**Comment by jeffchew** [comment]
@asudoh I started going through the visual changes, can you confirm some of them look right? There are a lot in the React one.

**Comment by asudoh** [comment]
Thank you for pointing it out @jeffchew - Fixed.

**Pull request merged**
