### PR TITLE
fix(card): update storybook knobs

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#5651

### Description

Update Web components, React, and React wrapper stories. Changed knobs to be updated to design.

### Changelog

**Changed**

- cleaned up card storybook

### CODE REVIEW

**Comment by photodow** [comment]
This is absolutely fantastic. Thank you for this! Here are a couple things I noticed.

Card default
- [ ] Small thing, but can we use the same image across the libraries?
- [ ] Outline doesn't appear to be working correctly in the React wrapper.
- [ ] Also seeing some link color difference in the React wrapper inverse?
- [ ] Can we keep the order of knobs the same? React looks like outline card got moved to the top.
- [ ] I wonder what Shixie or Olivia would think, but I wonder if we could combine outline and inverse into like a style dropdown? I don't think we want to demo those two together? Just thinking out loud here.

Card pictogram
- [ ] How are we missing this in React? 😱
- [ ] Isn't copy supposed to be present on both top or bottom? (have we not made that update yet?)
- [ ] same suggestion on styles inverse and outline

Card static
- [ ] Image has a hover state
- [ ] The card in react in general has a hover state
- [ ] Looks like the issue is asking for a dynamic CTA toggle. When on the input copy field comes back? Wonder if we should add this to all variations actually.
- [ ] Are we missing tags in react?

**Review by photodow — APPROVED** [review]
- [ ] Card static still has hover states in React
- [ ] Tags appear to be missing in the React version
- [ ] Might be good to still make the CTA copy dynamic across all card stories, or at least the default. similar to how you did it in static.

Other wise looks great.

**Review by jeffchew — APPROVED** [review]
LGTM!

**Comment by jeffchew** [comment]
@ariellalgilmore did changes to storybook impact the e2e tests?

image

**Pull request merged**
