### PR TITLE
fix(Masthead): Search field does not display auto suggest results

### PR DESCRIPTION
**Pull request by Valentin-Sorin-Nicolae**
### Related Ticket(s)

Closes [#10741](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10741)

https://jsw.ibm.com/browse/ADCMS-3669

### Description

Expected Result:
When a keyword is typed into the Search field, the auto suggest results displays 10 results below the field.

Actual Result:
When viewing the Masthead With Custom Typeahead component, if a keyword is typed into the search field there are no auto suggest results displayed.

Steps to Reproduce

    Launch https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components
    Expand the "Masthead" in the components list
    Select the Masthead "With custom typeahead" example
    Input a valid keyword into the Search field
    Observe no auto suggest results are displayed.

### Changelog

**New**

 ibmdocs-dev.mybluemix.net replaced with ibm.com

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by Valentin-Sorin-Nicolae** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by andy-blum** [comment]
recheck

**Comment by andy-blum** [comment]
The [deploy preview](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/10795/iframe.html?args=&id=components-masthead--with-custom-typeahead&viewMode=story) isn't working, but I think it's a CORS issue.

Typing in the letter `a` kicks off a network request to [this endpoint](https://www.ibm.com/docs/api/v1/suggest?query=a&lang=undefined&categories=&limit=6), which does appear to return a valid result, but the network request fails.

Screenshot 2023-08-04 at 9 27 34 AM

**Review by andy-blum — APPROVED** [review]

**Review by IgnacioBecerra — COMMENTED** [review]
LGTM, thanks for fixing this!

**Review by IgnacioBecerra — APPROVED** [review]

**Pull request merged**
