### PR TITLE
feat(cta): add new cta types

### LINKED ISSUE #8785: [CTA]: Expose additional icon types to `cta-type` attribute
**Engineering info:**  
- Innovation Team engineer: 
- Innovation Team FE JIRA Ticket: https://jsw.ibm.com/browse/HC-2482
- AEM BE JIRA Ticket: https://jsw.ibm.com/browse/ADCMS-2283
- DPO consulting engineer: N/A

----------------

### The problem

- Currently, the `cta-type` attribute/prop supports the following SVG icons
  - Local
  - Jump
  - External
  - Download
  - Video
  
Screen Shot 2022-05-03 at 1 51 54 PM

- However, within the AEM CMS, we need to be able to ultize SVG icons for `PDF` and `Blog` content (see attached)

image (78)

### The solution

- There are certain options within the AEM CMS dropdown that are inconsistent with the options/labels that are in the dotcom library and I’d like to use this issue as a way to help add missing icons and help AEM adjust their naming convention to align to the current `cta-type`  attribute (eg. `PDF` should be `Download`).
- Expose Carbon's Blog SVG icon or any other icons in the CTA type rendering.
- @oliviaflory @RichKummer I'd like to see if this is something that can be added to the C4IBM Web Component package, however, if not, we can look at implementing these options on C4AEM. However, the caveat here is that we'll need to extend the `cta` component and have AEM reference that file in addition to the other files that they're already consuming from C4AEM. Might have a slight performance impact, but nothing too pressing. Let me know what you both think.

### Application/website

AEM

### Business priority

Medium Priority = upcoming release but is not pressing

### What time frame would this ideally be needed by (if applicable)

- Would be great to include this change in the next release as AEM is in the midst of changing the usage of Font Family as a means to render the icon and adjust to fully adopt SVG code coming from C4IBM.

### Examples

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)

Closes #8785 

### Description

This PR updates the CTA mixin and the CTA defs to add new types of CTAs
- New Tab
- PDF
- Blog

The new tab type tacks on to the external type's logic to add `target="_blank"`, and the pdf type is added to the type-checking/console warning for use of the `download` prop.

### Changelog

**New**

- New types added to CTAs (new tab, pdf, blog)

### CODE REVIEW

**Review by proeung — APPROVED** [review]
LGTM! The additional CTA types are rendering correctly.

Screen Shot 2022-06-08 at 4 57 55 PM

**Review by RichKummer — APPROVED** [review]
LGTM! Thanks @andy-blum !

**Comment by RichKummer** [comment]
Just saw Percy picked up this issue in Web components. It seems to be rendering fine when I run it though. This might be an issue with Percy but can you double check @andy-blum ?

Card link
Screen Shot 2022-06-10 at 11 27 08 AM


Card
Screen Shot 2022-06-10 at 11 27 19 AM

**Comment by RichKummer** [comment]
@andy-blum Still looks good and Percy's passing, but looks like the React wrapper isn't building 😢

**Comment by andy-blum** [comment]
@RichKummer  the Jenkins failure seems unrelated - let's see how the CI checks go after merging in the latest changes from main.

**Review by ariellalgilmore — APPROVED** [review]
LGTM! Thanks for the updates

**Pull request merged**
