### PR TITLE
feat(cta-section): add logo & aspect ratio support

### LINKED ISSUE #8849: [CTA Section with Content Items]: Expose new image ratios
**Engineering info:**  
- Innovation Team engineer: 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2475
- DPO consulting engineer:

-----

### The problem

- This "Layout Component" is part of the Product Use Cases v1 Template (see EPIC - [AEMSITES-94](https://jsw.ibm.com/browse/AEMSITES-94))
- These changes from coming from the Interfaces Team (cc: @jwitkowski79)
- Design Specs
   - PDF: https://ibm.ent.box.com/file/958328867245?s=296kh5b2y5pe3mlbad7y2kdiny46k713
   - Figma: https://www.figma.com/file/0qjKUHD652dqE9BdjId9YY/Templates?node-id=1130%3A29863

Screen Shot 2022-05-16 at 11 24 21 AM

### The solution

- Add an attribute/prop (eg. `logo-ratio`) for the different image ratios that we're supporting. The container of the logo item should be adjusted based on the defined ratio (see specs).
- Add "logo" to the SB content type knob

@oliviaflory @kennylam Feel free to add/adjust this solution area.

### Application/website

AEM

### Business priority

Medium Priority = upcoming release but is not pressing

### What time frame would this ideally be needed by (if applicable)

We'd like to get these modifications in for the v.1.35.0 release.

### Examples

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)

Closes #8849

### Description

PR adds ability in storybook to view cta-section items with logos, as well as constrain those logos to a given aspect ratio

### Changelog

**New**

- Adds a new `logo` option to the content item type knob
- Adds handling for a `logo-ratio` attribute

### CODE REVIEW

**Comment by RichKummer** [comment]
Hey @andy-blum - took a look through and found a few things, @jwitkowski79 might have some other feedback

**New variant**
1. It looks like there's `16px` padding on the left of the logo that is pushing the logo out of alignment with the copy. See below:

Screen Shot 2022-06-02 at 10 00 53 AM

2. The logo looks bigger than the specs. The logo asset should come in at `96px x 48px`. In the SB version, it's `160px x 80px`

Compare with the specs:
168628175-ee8387bd-d116-4383-b606-fb3933727187

3. It looks like the container around the logo asset has extra padding at the bottom. It should be `32px` from the bottom of the image asset. There should also be `64px` padding between the bottom of the CTA and the image asset - I can't tell if this is the case but it looks like the container around the logo asset might be bumping that up as well.

Screen Shot 2022-06-02 at 10 17 05 AM


**Storybook**
1. The default value for the _Logo Aspect Ratio_ shows nothing (but seems to be 2:1). Could we just make the default 2:1 with no invisible value?
2. Can you change the copy for the control to _Logo aspect ratio_ (sentence case).
3. Could you make the _Logo aspect ratio_ control only appear if the _Content item type_ is set to `Logo`? You can see this for `Link list - End of section`.

https://user-images.githubusercontent.com/15643582/171646200-82528d33-15d3-4424-bfc1-747110379688.mov

**Comment by jwitkowski79** [comment]
@RichKummer @andy-blum Hello! Just chiming in with a couple of additional things that will need to be looked at:     
- bottom padding of the content item is off- should match current [CTA block with content items](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-cta-section--with-content-items) at 64px padding at the bottom between the CTA’s and the horizontal rule. The bottom padding should also match at md and sm breakpoints. Md is at 64px and sm is at 32px.
Screen Shot 2022-06-02 at 2 17 13 PM

- I’d also double check the top padding of each content item. I can’t tell because of the logo padding but it looks like when the image asset is set to pictogram, the top padding is 32px. It should match the current [CTA block with content items](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-cta-section--with-content-items) with 64px at desktop,  64px and sm at 32px

- The bottom padding for the entire component will also need to be adjusted. You’ll probably need to remove the additional 64px at the bottom to match what is currently happening in the C4IBM.com library to match the 160px padding along the bottom of the component
Screen Shot 2022-06-02 at 2 28 08 PM

**Comment by jwitkowski79** [comment]
@andy-blum One more thing. In the Storybook knobs: for the logo image type, can we limit the image ratios to 2:1 and 1:1? Just discussed this with @oliviaflory and we don't see a need to display a 16:9 logo or a 4:3 logo.

**Comment by andy-blum** [comment]
@jwitkowski79 @RichKummer The spacing that Jen pointed out was changed 8 days ago as part of #8900 

Which spacing is correct?

**Comment by RichKummer** [comment]
> @jwitkowski79 @RichKummer The spacing that Jen pointed out was changed 8 days ago as part of #8900
> Which spacing is correct?

It looks like this was an update from the original specs - that's my fault, I was looking at the original specs for that ticket. Would it be possible to revert the spacing updates to match Jen's design for this?

**Comment by oliviaflory** [comment]
> Bottom padding of the content item is off- should match the current [CTA block with content items](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-cta-section--with-content-items) at 64px padding at the bottom between the CTA’s and the horizontal rule. The bottom padding should also match at md and sm breakpoints. Md is at 64px and sm is at 32px.

> The spacing that Jen pointed out was changed 8 days ago as part of https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8900
Which spacing is correct?

@jwitkowski79 @RichKummer @andy-blum jumping in here, the most recent spec file does have 32px between the content items and horizontal rule, so I think how Andy has it now is correct. It was previously at 64px bottom padding and may still look like that in the current storybook because we have yet to release the fix Andy referenced.

Screen Shot 2022-06-03 at 3 52 06 PM

----
> The bottom padding for the entire component will also need to be adjusted. You’ll probably need to remove the additional 64px at the bottom to match what is currently happening in the C4IBM.com library to match the 160px padding along the bottom of the component

We have recently discovered some odd things happening where padding is stacking within the web components package that may be causing some issues with the bottom padding in components. In this case I'm seeing 32px from the last content items, 96px from the layout and 64px from the content block.
**Content items**
Screen Shot 2022-06-03 at 3 40 42 PM
**Layout**
Screen Shot 2022-06-03 at 3 41 28 PM
**Block**
Screen Shot 2022-06-03 at 3 40 59 PM

**Review by proeung — APPROVED** [review]
LGTM!

**Review by kennylam — APPROVED** [review]
LGTM!

**Pull request merged**
