### PR TITLE
chore(React Masthead): Keep Search Bar Active if User Selects Text

### PR DESCRIPTION
**Pull request by mcastre**
### Related Ticket(s)

Resolves [#4074](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4074)

### Description

Check if state.val has a length in handleClickOutside() before dispatching 'setSearchClosed'

{{If applicable, include a screenshot indicating an example or examples of what the PR is changing in the application}}

### Changelog

**New**

- {{new thing}}

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Review by kennylam — COMMENTED** [review]
@mcastre Thanks for contributing! One issue is that clicking outside the search will close the autosuggestions and keep the input open.

image

**Comment by mcastre** [comment]
@kennylam so im not sure what fix you are looking for. In the original issue description, the problem is that the user is moving their mouse outside of the search box to select text, and once the user clicks off, the search bar disappears. However, this was how the search bar was originally intended to behave, as outlined in the comments on line 170 in react/src/components/Masthead/MastheadSearch.js. 

With my PR, the fix i implemented keeps the search bar open if there is text entered in search. If the user didnt want to search anymore, they have multiple ways to close it, the X icon, clicking outside, or clearing the text, which is how most search bars work out in the world. Im not exactly sure what the expected behavior is?

**Comment by kennylam** [comment]
> If the user didnt want to search anymore, they have multiple ways to close it, the X icon, **clicking outside**,

This is what I meant. Clicking outside no longer closes the search if there is an input value, it only clears the autosuggestions.

@wonilsuhibm @oliviaflory Are you ok with this behavior?

**Comment by wonilsuhibm** [comment]
@kennylam Product Discovery team confirmed that this is the desired behavior. Unless @oliviaflory has other concerns, I agree with this request.

**Review by kennylam — APPROVED** [review]
LGTM thanks @mcastre!

**Pull request merged**
