### PR TITLE
fix(content-item-horizontal): fix media overflow on mobile

### LINKED ISSUE #10841: [Content Item Horizontal w/ Featured Media]: Horizontal overflow on `sm` breakpoint
JIRA: https://jsw.ibm.com/browse/ADCMS-3757

### Description

When the viewport is less than 383px wide, the featured media item overflows its container and causes a horizontal scrollbar to appear. This is because the featured media item is placed on a grid four columns wide, but is told to span 12 columns. The grid auto-creates grid tracks 5-12 and the grid-gaps stack up causing the item to overflow its container.

Component at <383px

Screenshot 2023-08-17 at 12 46 05 PM

Screenshot 2023-08-17 at 12 45 44 PM

Component at 1055px:
Screenshot 2023-08-17 at 12 45 25 PM

Component at 1056px:
Screenshot 2023-08-17 at 12 45 14 PM

### Component(s) impacted

Content Item Horizontal

### Browser

Chrome

### Carbon for IBM.com version

latest v1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

ibm.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components/iframe.html?id=components-content-item-horizontal--with-media-featured&viewMode=story

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by pjudge**
### Related Ticket(s)

Closes #10841

### Description

The Content Item horizontal component with featured media displayed an overflow of its media on mobile (really any breakpoint below large). This was due to the media being set to span 12 cols on larger screens, when the grid is actually 12 cols wide, but then on smaller screens the grid is 4 cols. The media was updated to span 4 cols to match its grid on screens smaller than "lg".

### Changelog

**Changed**

- updates the styles package for Content Item Horizontal Featured Media to set media's column span to match its grid.

### CODE REVIEW

**Review by andy-blum — APPROVED** [review]
Code and preview both look good.

**Review by annawen1 — APPROVED** [review]
LGTM!

**Comment by ariellalgilmore** [comment]
@pjudge if you want this part of the release might be easier to make a new branch off the release branch

**Comment by pjudge** [comment]
Closing as this has been transferred here for the RC https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10857

**Pull request closed without merging**
