### PR TITLE
fix(radio-button): add missing slot optioin

### LINKED ISSUE #11288: The slots no longer work on radio buttons
### Description

The slots no longer work on the radio buttons / checkbox:

✅ Application with `@carbon/web-components@2.0.1`:
https://stackblitz.com/edit/vitejs-vite-58y3ua?file=package.json

Screenshot 2024-01-02 at 3 00 56 PM

❌ Application with `@carbon/web-components@2.1.1`:
https://stackblitz.com/edit/vitejs-vite-txbijy?file=package.json

Screenshot 2024-01-02 at 3 01 10 PM

### Component(s) impacted

Radio button & Checkbox

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

IBM Quantum

### Package

@carbon/web-components

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

Closes #11288 
### Description

fixes slot for radio-button
### Changelog

**New**

- {{new thing}}

**Changed**

- accidentally got removed .... but adding `<slot>` around `${labelText}`

**Removed**

- {{removed thing}}

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me!

**Comment by abdonrd** [comment]
@ariellalgilmore I just see you release [@carbon/web-components@2.1.2](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/releases/tag/%40carbon%2Fweb-components%402.1.2)

Shouldn't this have this PR? It seems that he has not been part:
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/commits/%40carbon/web-components%402.1.2/

Thanks!

**Comment by ariellalgilmore** [comment]
Since there is a workaround, this PR will go into the next release. We start code freeze on the next release this Friday

**Comment by abdonrd** [comment]
For our case there is no workaround: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11288#issuecomment-1875833213

But ok, we can wait until next release.

**Pull request merged**
