### PR TITLE
fix(leadspace): adjust left position of leadspace to cover Safari gap

### PR DESCRIPTION
**Pull request by m4olivei**
### Related Ticket(s)

Closes: [#9896](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9896)
[ADCMS-2853](https://jsw.ibm.com/browse/ADCMS-2853)

### Description

This implements a workaround to cover off the Safari edge case bug with the Leadspace component. Nudging the svg gradient by -1px, and covering that adjustment to the right edge with `calc`.

### Testing instructions

- [ ] Open the Leadspace component in Storybook in Safari. Zoom in and out with browser controls.
- [ ] You should no longer exhibit the issue of the gradient peeking out from the background as noted in the issue, and represented here for reference:
211601432-e4f67595-ee7f-4a6f-b3cd-ee8384cc1767
- [ ] Review in Chrome / Firefox, should be no regressions
- [ ] Test the "Lead space > Centered *" stories to ensure no regressions have appeared there either.

### Changelog

**Changed**

- Adjusted SVG leadspace gradient position to cover an edge case bug in Safari

### CODE REVIEW

**Review by jkaeser — APPROVED** [review]
@m4olivei LGTM 👍  Tested in Chrome, Firefox, and Safari, and all looks good.

**Review by andy-blum — APPROVED** [review]
LGTM

**Comment by proeung** [comment]
@kennylam or @annawen1 Can we get a review from your team? Thanks!

**Comment by m4olivei** [comment]
Friendly bump for @kennylam and @annawen1 to take a look when you get a chance. I've updated the testing instructions here so that it's hopefully more clear and easier to verify.

**Review by annawen1 — APPROVED** [review]
LGTM! Thanks for the detailed testing instructions @m4olivei 👌

**Pull request merged**
