### PR TITLE
feat(playground-test): created playground story

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#8968

### Description
Created a Playground Story containing a dropdown knob that is able to bring any component inside a Dotcom Shell wrapper with an optional ToC/horizontal ToC. This is in preparation for the component grid audit that is a follow up to this issue.

### Changelog

**New**

- added Playground story to add every single component individually to be wrapped in Dotcom shell or ToC
- added propSet parameters to a couple components in order for the stories to be imported properly

### CODE REVIEW

**Comment by ariellalgilmore** [comment]
Getting an error when looking at the deploy preview `undefined is not an object (evaluating 'storyParameters') `

**Comment by IgnacioBecerra** [comment]
@ariellalgilmore Fixed it, I'm getting/saving the current story so whenever it refreshes it displays again without needing to choose it from the dropdown all over again, but forgot to set a default if there's nothing stored in `localStorage` at first, hence the error lol

**Review by RichKummer — COMMENTED** [review]
**EDIT:** Noticed your note on merging so this may not be relevant!

Took a look at the Percy results and it looks like there would be a rollback of `Universal banner`. @IgnacioBecerra you may need to merge from `main`?

Screen Shot 2022-06-16 at 5 54 27 PM

**Comment by IgnacioBecerra** [comment]
@RichKummer I'll update the branch anyway, since to we'll need the most updated components to make sure the grid placement is right 👍

**Review by kennylam — APPROVED** [review]
LGTM! Just need to resolve those conflicts.

**Comment by RichKummer** [comment]
Percy picked up an odd issue where it looks like `Card - pictogram` is no longer interactive in this build. Tried this out in the Web components Storybook. If this wouldn't effect `Card`, I can approve it but the Pictogram version looks like it's effected for some reason.

https://user-images.githubusercontent.com/15643582/174390588-a2b67b5d-0e6a-4450-bfc4-a4800259699d.mov

**Comment by ariellalgilmore** [comment]
Also there are some conflicts now that card-section-images has been deprecated

**Comment by RichKummer** [comment]
Dropping the **[Figma file](https://www.figma.com/file/JT1ab7qQikb0LLO8L9ho9c/ToC-build?node-id=0%3A1)** here in case we update later.

**Pull request closed without merging**
