### PR TITLE
fix(video-player): fixed focus state

### PR DESCRIPTION
**Pull request by RaphaelAmadeu**
### Related Ticket(s)

#5660 

### Description

I've updated the focus state for the video player so it matches the designs specs.

New: 
image

Before:

### CODE REVIEW

**Comment by shixiedesign** [comment]
Almost! The focus outlines should be inset. See details here https://cognitive-app.slack.com/archives/GTKP57FMJ/p1617828313061300

**Comment by shixiedesign** [comment]
Perfect on Web components! But not seeing focus on React... is this normal? I thought they share styles. @RaphaelAmadeu

**Comment by RaphaelAmadeu** [comment]
> Perfect on Web components! But not seeing focus on React... is this normal? I thought they share styles. @RaphaelAmadeu

@shixiedesign 
It should be working properly on react now. Thanks for the review!

**Review by shixiedesign — APPROVED** [review]
👍 👍 👍

**Review by jeffchew — APPROVED** [review]
LGTM!

**Pull request merged**
