### PR TITLE
fix(storybook): capitalization errors

### PR DESCRIPTION
**Pull request by NSDrowned**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5553

### Description

Fixes capitalization errors and missing spaces in component names

### CODE REVIEW

**Review by shixiedesign — APPROVED** [review]
Small changes but feels sooooo much better now. Thank you!! 
Side note - is Percy acting weird? I'm not expecting any visual changes from this PR so maybe there's something about the test?

**Comment by NSDrowned** [comment]
@shixiedesign I agree, it looks very organized now 😎 

I checked Percy and it says over 60 tests are missing for some reason. Not sure if the name change affects it. Will investigate.

**Comment by jeffchew** [comment]
> @shixiedesign I agree, it looks very organized now 😎
> 
> I checked Percy and it says over 60 tests are missing for some reason. Not sure if the name change affects it. Will investigate.

Yes, the name change will trigger them as new snapshots, look under the `changed` list. We will probably have to go through and make sure everything visually looks ok and we aren't missing anything.

**Comment by jeffchew** [comment]
@NSDrowned can you go into the `tests-e2e` package and update the URLs being used for the e2e tests? Make sure to point at the full screen urls:

image

**Review by jeffchew — CHANGES_REQUESTED** [review]
I think it might be safe to approve the React and Web Components percy builds, but the e2e ones need to be updated since the URLs being tested against have changed. Once those are fixed, I think that this one should be good to merge.

**Comment by NSDrowned** [comment]
@jeffchew, OK, will update them right away

**Comment by jeffchew** [comment]
Thanks @NSDrowned ! Looks like a few are still missed:

image

**Comment by jeffchew** [comment]
@NSDrowned I'm going to see what's going on here, looks like it's running out of memory...

image

**Comment by jeffchew** [comment]
@NSDrowned I took the liberty of seeing if doubling the max buffer for lerna helps us at all: 

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/55ae16f7757c2e5aad955684e7be630320b10618/.github/workflows/ci-check.yml#L24

**Comment by NSDrowned** [comment]
@jeffchew, looks like the same `MaxBufferError: stderr maxBuffer exceeded` error came up

**Review by jeffchew — APPROVED** [review]
Thanks @NSDrowned !

**Pull request merged**
