### PR TITLE
feat(feature-card): enable color scheme selection

### LINKED ISSUE #10072: [YOUR TITLE]: Brief description
### The problem

Carbon core has introduced a stroke on the `tile` component, which we will adapt to C4IBM.com's `card` components. Both `feature card – large` and `feature card – medium` should add the border.

**Question:** Does this need changes to `card` that `feature card` would inherit?

### The solution

[Updated visual specs](https://www.figma.com/file/29lZzs4QtVwho2OM6OapT9/UI-component--feature--card--design-specs-2.0.0?node-id=0%3A1&t=NJH4gfup40hc9a1O-1)
[Design exploration](https://www.figma.com/file/KIN3VcIgOClFR4Pp4fG2dz/Feature-card-%E2%80%93-regular-color-scheme?node-id=0%3A1&t=MAwSb3tVqX8qyOKx-1)

Note that the border uses different brand colors across the four themes. There is a new token added in v11 to handle this.

### Application/website

C4IBM.com

### Business priority

Medium Priority = upcoming release but is not pressing

### What time frame would this ideally be needed by (if applicable)

_No response_

### Examples

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### LINKED ISSUE #10073: [feature card]: Add regular color scheme
### The problem

The `feature card` uses an inverse background that limits its usage with the lighter and brighter brand direction. To handle this, we should add a color scheme property that enables the adopter to use both inverse (current) styles and regular (new) styles. 

The regular color scheme variant should become the default color scheme for the component, with the option to use the inverse theming.

### The solution

**[v2 specs using v11 tokens](https://www.figma.com/file/DmgpvpEV6m4eJNMgKOLPmy/Feature-card-v2?type=design&node-id=407%3A13763&mode=design&t=KjAlkdgoGz9F76r6-1)**

**[Updated design spec using v10 tokens](https://www.figma.com/file/DmgpvpEV6m4eJNMgKOLPmy/Feature-card-v2?node-id=0%3A1&t=odOm6RCUS1LuV2we-1)**

[Design exploration](https://www.figma.com/file/KIN3VcIgOClFR4Pp4fG2dz/Feature-card-%E2%80%93-regular-color-scheme?node-id=0%3A1&t=MAwSb3tVqX8qyOKx-1)

**Note:** the specs contain a new border styles added in #10073.

Feature card - medium – Theme styles

### Application/website

C4IBM.com

### Business priority

Medium Priority = upcoming release but is not pressing

### What time frame would this ideally be needed by (if applicable)

_No response_

### Examples

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### LINKED ISSUE #10306: [Feature card – large]: Updates to @lg and @md
### The problem

As part of the v2 updates, we are shifting `feature card – large` to a 2:1 aspect ratio for `@lg` and `@md` breakpoint

### The solution

[Updated design spec](https://www.figma.com/file/DmgpvpEV6m4eJNMgKOLPmy/Feature-card-v2?node-id=0%3A1&t=odOm6RCUS1LuV2we-1)

**Update highlights**
1. `@lg` and `@md` will use a 2:1 aspect ratio for the entire feature card
2. See [TBD] for v11 tile updates using a solid border.
3. Updated alignment for copy and padding
4. Truncation rule for body copy that is >32px from the icon at the bottom right. The heading does not truncate.
5. When `@lg` and `@md`, the heading type token is changed to `$heading-03`. 
6. When `@md`, the body copy type token is changed to `$body-01`
7. Global – padding below eyebrow is adjusted from `16px` to `8px`

Screen Shot 2023-04-05 at 7 44 39 PM

### Application/website

C4IBM.com

### Business priority

Medium Priority = upcoming release but is not pressing

### What time frame would this ideally be needed by (if applicable)

_No response_

### Examples

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by emyarod**
### Related Ticket(s)

Closes #10306
Closes #10072 
Closes #10073

### Description

This PR scopes the current feature card styles under the inverse color scheme attribute and inherits the regular color scheme styles from the card component

note: currently testing with `border-subtle-selected` token due to the desired `border-tile` token being behind an upstream feature flag

### Changelog

**New**

- color scheme story knob

**Changed**

- scoped v1 styles to `color-scheme="inverse"`

### CODE REVIEW

**Comment by RichKummer** [comment]
Hey @emyarod , still going through it but picked up a few things:

1. When `feature card` is using the inverse `color-scheme`, the icon should use `$inverse-link`. This applies to both sizes.
Screenshot 2023-08-04 at 2 58 55 PM

2. Noticed that `feature card medium` is flush with the column in WC, but in the specs they should extend halfway into the gutter. Is this just a Storybook issue, or is this baked into the component?

Current build:
Screenshot 2023-08-04 at 3 09 10 PM

Design specs:
Screenshot 2023-08-04 at 3 06 10 PM

3. For `feature card large`, the background token is set to `$ui-background`, but for v1 the token should be `$ui-01` and in v2 should be `$layer-01`

5. For focus state, both size variants seem to be off in different ways. They should use the following: 2px `$focus` inside border, with a 1px `$focus-inset` border

Large (focus border is on the outside, and doesn't seem to have focus inset border)
Screenshot 2023-08-04 at 3 44 30 PM

Medium (has focus and focus inset border, but should replace tile border that's still showing in the build)
Screenshot 2023-08-04 at 3 44 15 PM

**Review by RichKummer — COMMENTED** [review]
Hey @emyarod, a couple last items:

## Global
1. When color-scheme is set to `inverse`, the border should be `$border-inverse`. It looks like it's currently coming in as `border-subtle`
Screenshot 2023-08-30 at 11 56 03 AM


## Feature card – large

1. For `Feature card – large`, the Eyebrow should have `8px` spacing at the bottom – currently it's rendering with `16px`.
Screenshot 2023-08-30 at 11 22 36 AM

2. The side padding for the content card should be `32px` from `@max` through `@xlg`, right now it's `64px` when `@max`
Screenshot 2023-08-30 at 11 40 28 AM

3. For `Feature card – large`, the side padding for the content card should be `16px` from `@lg` through `@sm`.
Screenshot 2023-08-30 at 11 24 02 AM

4. For the heading, the type token should be `$heading-04` from `@max` through `@lg`, then `$heading-03` for `@md` and `@sm`. Currently seeing it come in as `$productive-heading-05`.

5. For every breakpoint except `@md`, the body copy token should be `$body-02` (@max – @lg, @sm). For `@md` only, the token should be `$body-01`.

6. For the `@md` breakpoint, there should be truncation if the body copy would put the copy within <32px of the icon at the bottom.

7. The focus state for `Feature card – medium` looks great, but it looks like the `large` version retains it's enabled subtle border when in the focus state.
Screenshot 2023-08-30 at 12 06 08 PM


## Storybook
1. I don't see the update to the grid overhang in Storybook. I know it's a Storybook issue and a nice-to-have, so if you can't get it in this round we can get to it another time.
Screenshot 2023-08-30 at 11 34 48 AM

**Comment by emyarod** [comment]
@RichKummer I believe I got everything! for the storybook grid overhang, you may have been looking at an older deploy preview since it was building/rebuilding a lot while I was making changes earlier. it should look like this now:

image

**Review by RichKummer — COMMENTED** [review]
Hey @emyarod, seeing a few of these addressed, but some are sticking around for `feature card – large`:

## Feature card – large

1. The side padding for the content card should be `32px` when`@xlg`, right now it's `16px`
Screenshot 2023-08-30 at 11 40 28 AM

2. Just want to confirm: for the heading, the type token should be `$heading-04` from `@max` through `@lg`, then `$heading-03` for `@md` and `@sm`. Currently seeing it come in as `$productive-heading-05`.

3. Just want to confirm: for every breakpoint except `@md`, the body copy token should be `$body-02` (@max – @lg, @sm). For `@md` only, the token should be `$body-01`.

4. For the `@md` breakpoint, there should be truncation if the body copy would put the copy within <32px of the icon at the bottom.

5. The focus state for `feature card – large` retains 1px of subtle border when in the focus state.
Screenshot 2023-08-30 at 12 06 08 PM


## Storybook
1. I don't see the update to the grid overhang in Storybook. I know it's a Storybook issue and a nice-to-have, so if you can't get it in this round we can get to it another time.
Screenshot 2023-08-30 at 11 34 48 AM

**Comment by RichKummer** [comment]
@emyarod Just took a quick look and it seems like the issues from my last comment are still showing. The commit messages seem to be addressing these but the preview's the same

**Comment by emyarod** [comment]
it looks like there is now a regression where the focus state will hide the image... need to look more into this

**Comment by RichKummer** [comment]
@emyarod seeing the image come in fine 🎉 . A few other things:

## Global
1. The Focus state seems to be resolved except there's an odd issue where focusing shifts the content around slightly (it's around a 1-2px shift). Seeing in both Medium and Large.

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/15643582/237e2e0d-19fd-47b6-859e-2b089f904678

2. When switching to the `@sm` breakpoint, the icon floats towards the middle of the card vertically – it should be appended to the bottom right. Seeing in both sizes.
Screenshot 2023-10-10 at 4 20 39 PM

Screenshot 2023-10-10 at 4 25 53 PM

## Large

1. The side padding for the content card should be `32px` when `@xlg`, right now it's `16px`.
264397593-651969d1-5c2b-4d00-a4a5-8ef2773cb180

2. It looks like `@md` that the type token for the body copy isn't changing. For every breakpoint except @md, the body copy token should be $body-02 (@max – @lg, https://github.com/sm). For @md only, the token should be $body-01, but looks like it's coming in as $body-02.

3. Also `@md`, the component should maintain a `2:1 aspect ratio` – right now the height goes a bit beyond that. I am seeing the truncation though!

Screenshot 2023-10-10 at 4 37 30 PM

4. Similarly for the heading token:, the type token should be $heading-04 from @max through @lg, then $heading-03 for @md and @sm. Currently not seeing a change at smaller breakpoints.

**Comment by emyarod** [comment]
I'm still investigating the aspect ratio problem but these should be addressed:

- the focus borders should no longer affect the content
- the icons should be appended to the bottom right now
- for the content, is there any guidance on what to put in the examples or is it ok if I just double the amount of lorem ipsum?
- the content padding for large feature cards at `@xlg` breakpoints should be `32px` now
- the background-color for large feature cards should already be `$layer-01` (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10744/files#diff-519d54bfe0dcb5b5a2ffe6549529b1257bd937add3e07ba3c0e90b9bc2f92904R270) is the value of the token not showing correctly?
- the card copy should already be using `body-01` at `@md` only (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10744/files#diff-519d54bfe0dcb5b5a2ffe6549529b1257bd937add3e07ba3c0e90b9bc2f92904R388-R389)

**Comment by RichKummer** [comment]
@emyarod checked through the last few bullets and almost everything looks great ✨ 

I know we're still talking about the aspect ratio/truncation, but when I looked at `@md` I wasn't seeing the body copy token update? Inspect is showing it at `1 rem` across breakpoints. Visually, it doesn't look like the type size changes there. 

Screenshot 2023-10-19 at 4 24 34 PM

**Review by kennylam — APPROVED** [review]
LGTM!

**Comment by RichKummer** [comment]
@emyarod this looks so good! Focus and padding are solved. Some small details:

- [ ] For `large` variant only, the icon seems to have a bit of extra space at the bottom:
Screenshot 2023-11-07 at 4 03 06 PM

- [ ] For the `large` variant, I had the wrong info for the heading above. For the `@lg` breakpoint, the heading should be `heading-03`, the same as `@md` and `@sm`. That's my bad for mixing up the feedback!

- [ ] For the body copy in the Storybook for `feature card - large` could you change it to something shorter. I clipped an example that meets the recommended character count here: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.`

**Comment by emyarod** [comment]
@RichKummer everything should be good to go now!

**Comment by RichKummer** [comment]
@emyarod, this looks great! A few details and this should be set:

## Large
- [ ] The inverse color scheme has a hover on the card background, but the `regular` color scheme doesn't seem to change the background. The background type token should update to `layer-01-hover`. The image does darken correctly though.
- [ ] At the bottom of the image container, there seems to be a few pixels of space between the container and the bottom. It may be the asset, though?
Screenshot 2023-11-16 at 3 24 00 PM
- [ ] Messaged you about the `body copy` issue - crashing if I edit in Storybook. I'm not sure if this is a Storybook issue, though.

**Comment by emyarod** [comment]
@RichKummer I believe everything is resolved now!

**Review by RichKummer — APPROVED** [review]
This looks awesome @emyarod ! 🎉 🎉 🎉

**Pull request merged**
