### PR TITLE
fix(masthead-l1): Ensure L1 submenu closes on focusout in safari

### LINKED ISSUE #10441: [Masthead V2]: L1 dropdowns do not close on focusout in Safari
### Description

JIRA Ticket: https://jsw.ibm.com/browse/ADCMS-3301

The new L1 design uses `<button>` elements to trigger the dropdowns, and Safari doesn't handle focus correctly on button elements ([webkit bug](https://bugs.webkit.org/show_bug.cgi?id=229895)).

We'll need to add a `tabindex` attribute at somepoint in the DOM tree to catch focus to allow the `focusout` element to trigger the dropdown close.

### Component(s) impacted

dds-masthead-l1 (v2)

### Browser

Safari

### Carbon for IBM.com version

Lastest

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

ibm.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://www.ibm.com/products/api-connect

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by pjudge**
### Related Ticket(s)

Fixes #10441 

### Description

On safari, a user is able to open multiple L1 dropdowns at the same time; the previously opened dropdown does not close when another is opened. This PR adds a tabindex as a workaround to this unfortunate safari behavior with buttons. 

Screenshot 2023-05-25 at 10 30 16 AM

### Changelog

**Changed**

- Added `tabindex="-1"` to `<li>` wrapping button dropdowns.

### CODE REVIEW

**Comment by andy-blum** [comment]
> @carbon/ibmdotcom-web-components: [15:22:36] 'test:unit' errored after 2.33 min

We need to run `yarn test:unit:updateSnapshot` since we changed the markup rendered by the component.

**Comment by andy-blum** [comment]
@pjudge Turns out the issue was [solved](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10483/commits/93db0ff07326a4d4d8b2a5feddc2308ea88d5eee) with `yarn format` from the C4IBM root.

**Comment by pjudge** [comment]
@andy-blum It looks like what he discussed on our huddle isn't actually a regression (submenu closing when you click inside of it but not on a link). The behavior is happening on chrome and firefox currently on prod. https://www.ibm.com/products/api-connect

Does that change how you feel about it?

**Comment by pjudge** [comment]
Updating comments to say that despite this being in production already, the bug still needs to be fixed. This PR will remain as a draft for now

**Comment by andy-blum** [comment]
@pjudge is this PR ready for review or is it still a draft?

**Comment by pjudge** [comment]
@andy-blum and I connected during our huddle and decided the other bug will be spun off as a new ticket. Changing this PR to ready.

**Review by jkaeser — APPROVED** [review]
LGTM! Love the nice and elegant fix.

**Review by andy-blum — APPROVED** [review]

**Pull request closed without merging**
