### PR TITLE
chore(back-to-top): update storybook content

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

#5428 #6427 

### Description

This updates the web components `back-to-top` Storybook content. Also adjusts `leadspace` height for mobile breakpoints (web components and React).

@shixiedesign You'll see there are slight differences in some of the components from your comp. I'm not sure some of the variations exist, such as the left-side header section for `ContentBlockSimple`. Feel free to hit me up and we can discuss.

### Changelog

**Changed**

- update `back-to-top` Storybook content
- update `leadspace` height for `<=md` breakpoints.

### CODE REVIEW

**Comment by shixiedesign** [comment]
Hey Kenny, I've marked out and indexed the diffs for us to discuss. I'm guess some of the diffs are limitation in the components themselves? Lemme know: 

1. Lead space background color ideally should extend beyond max width of grid
2. Missing content section heading "Overview"
3. Missing border bottom under the content block 
4. Missing content section heading "Benefits" 
5. Second link list heading is misplaced. Seeing a big padding above heading
6. Missing group level heading. I know we took away Feature card block, so I was thinking this could be `Feature card - medium` inside a `content group`, is that not how it works? 
7. Missing border bottom under the block
8. Extra spacing under heading.`Content section` should have no gap between heading and body copy.
9. Background color should extend beyond max width of grid
10. Extra border bottom here & a bit extra spacing probably related.

image

**Comment by kennylam** [comment]
@shixiedesign Thanks for the comments! Items with strikethrough completed.

If i remember right, the design decision early on was to limit the content area inside the `dotcom-shell` to a maximum width of `99rem` (see the [partners](https://www.ibm.com/partners/) page). I recall having this discussion with Wonil a few times. If this needs to change we'll need to make some pretty big adjustments to the shell.

1. Lead space background color ideally should extend beyond max width of grid
    - `dotcom-shell` max width is set to `99rem`
2. Missing content section heading "Overview"
    - This section heading doesn't exist in the [design](https://ibm.ent.box.com/file/784972761283?s=fjt3gl9b3qkyhhshin2z74az62bz795x) specs for `content-block-simple`. We can create a feature request if this should be an option.
3. ~~Missing border bottom under the content block~~
4. Missing content section heading "Benefits"
    - This section heading doesn't exist in the [design](https://ibm.ent.box.com/file/784972761283?s=fjt3gl9b3qkyhhshin2z74az62bz795x) specs for `content-block-simple`. We can create a feature request if this should be an option.
5. ~~Second link list heading is misplaced. Seeing a big padding above heading~~
6. ~~Missing group level heading. I know we took away Feature card block, so I was thinking this could be Feature card - medium inside a content group, is that not how it works?~~
7. Missing border bottom under the block
    - There is no border in the design/functional [specs](https://ibm.ent.box.com/file/674972982613) of `content-group-section`. We can create a feature request if this should be an option.
8. Extra spacing under heading.Content section should have no gap between heading and body copy.
    - There is no copy under the section header in the [functional](https://ibm.ent.box.com/file/661344525760) specs for `card-section-simple`. We can create a feature request if this should be an option.
9. Background color should extend beyond max width of grid
    - `dotcom-shell` max width is set to `99rem`
10. ~~Extra border bottom here & a bit extra spacing probably related.~~

**Comment by shixiedesign** [comment]
Was chatting with Kenny on Slack and just wanna post it here: 
image

**Comment by shixiedesign** [comment]
Last question is so Dotcom shell’s max width `99rem`: is it what we wanna change to have the background color stretching to full width for all section level components? Trying to figure out how to phrase this feature request.

**Comment by kennylam** [comment]
> Last question @kennylam
> So Dotcom shell’s max width `99rem`: is this what we wanna change to have the background color stretching to full width for all section level components? Trying to figure out how to phrase this feature request. I have a related FR open but only for Lead space and I think I'm not sure it's the correct solution for it: #6177

@shixiedesign Right, the change would have to happen in `dotcom-shell`'s container. Although I don't think a global change to the max-width would be the way to handle it. We'd need to add logic and/or styles to the child components in the container to determine which can go full width or be limited to 99rem.

**Review by shixiedesign — APPROVED** [review]

**Comment by shixiedesign** [comment]
Confused why we are seeing Percy diff in expressive theme? 
image

**Comment by kennylam** [comment]
> Confused why we are seeing Percy diff in expressive theme?

I'm not quite sure either.

**Review by jeffchew — APPROVED** [review]
LGTM

**Comment by jeffchew** [comment]
@kennylam @shixiedesign might be a timing thing. Carbon 10.37.0 was recently merged in, so the baseline might not be up to date with what was presented in this PR at that given time. It's also possible this PR is out of date and is running on Carbon 10.36.0.

**Comment by kennylam** [comment]
@jeffchew Yeah i saw that affect a few other PRs already, but it should be fine once updated.

**Pull request merged**
