### PR TITLE
fix(font-tokens): set scaling param to true for expressive-heading-05

### PR DESCRIPTION
**Pull request by annawen1**
### Related Ticket(s)

Expressive type token value errors #5554
[Lead space - with search] React experimental, sub-headline should be $expressive-heading-05 #5545

### Description

Pass in `true` to scaling parameter so the font size scales up/down according to breakpoint

### Changelog

**Changed**

- set `true` to `expressive-heading-05` tokens

### CODE REVIEW

**Review by jeffchew — APPROVED** [review]
LGTM, does this need design approval too?

**Comment by annawen1** [comment]
> LGTM, does this need design approval too?

Yeah I'll add design just to make sure.

**Comment by shixiedesign** [comment]
Unable to QA the result coz I cannot see Lead space with Search. Turning on feature flag...

**Review by shixiedesign — APPROVED** [review]
Fixed! 🌮

**Pull request merged**
