### PR TITLE
fix(masthead): fixes various masthead styles

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

#6398 
#6399 
#6403 
#6404 
#6410 
#6411 
#6418 
#6419 

### Description

This fixes various styling issues for the `masthead` component in both React and web components.

### Changelog

**Changed**

- update search typeahead hover token to `$hover-ui` #6398
- update profile button width to `48px` #6399
- update left/right padding in masthead nav items to `16px` #6403
- update IBM logo focus #6404
- update masthead nav dropdown items background color to `$ui-background` #6410
- update `L1` platform name selected styles #6411
- `L1` platform name remains visible in all breakpoints #6418
- update spacing between `L1` platform name and navigation items #6419

### CODE REVIEW

**Comment by oliviaflory** [comment]
@kennylam This is looking awesome! 

One request: Can we keep the Platform name in the hamburger menu in Web components? We still have it in React which is great. I think it's visible in the current version of WC, so hopefully not too difficult to bring back?

**WC** 
Screen Shot 2021-07-02 at 9 27 03 AM

**React**
Screen Shot 2021-07-02 at 9 27 12 AM

**Comment by kennylam** [comment]
> One request: Can we keep the Platform name in the hamburger menu in Web components? We still have it in React which is great. I think it's visible in the current version of WC, so hopefully not too difficult to bring back?

@oliviaflory This was added in the recent [Masthead left nav](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6393) updates. It's already been merged. Sorry, I forgot to mention this. You can see it [here](http://ibmdotcom-web-components-canary.mybluemix.net/iframe.html?id=components-masthead--with-l-1).

**Review by oliviaflory — APPROVED** [review]
Looks great!

**Review by jeffchew — APPROVED** [review]
Thanks @kennylam !

**Pull request merged**
