### PR TITLE
fix(leaving-ibm): update open attribute

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

#7740 

### Description

This fixes an attribute in the `leaving-ibm` component to allow it to correctly toggle the open/close states.

Nov-23-2021 10-04-34

### Changelog

**Changed**

- make `open` attribute in `leaving-ibm-composite` boolean

### CODE REVIEW

**Review by jeffchew — APPROVED** [review]
LGTM!

**Comment by jeffchew** [comment]
@kennylam be sure to sign the DCO

**Comment by kennylam** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by kennylam** [comment]
recheck

**Pull request merged**
