### PR TITLE
fix(quote): fixed quote styles

### PR DESCRIPTION
**Pull request by andysherman2121**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5439

### Description

The Quote component had a few width/padding issues that were messing up the alignment of all of the specific quote content. This PR re-aligns those issues.   

### Changelog

**Changed**

- Paddings 

**Removed**

- Percentage calculations

### CODE REVIEW

**Comment by DragosRistici** [comment]
Hey, @andysherman2121 

It appears to be some spacing issue from somewhere. Can you check where's that coming from? Thank you.


Screenshot 2021-11-15 at 16 16 15

**Comment by andysherman2121** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by DragosRistici** [comment]
@andysherman2121 Hey, Andy, a few more things to consider before merging it: 

1. The `Role` and `Company` should have 8cols-32px, at a 640px max-width, like the `Name (dds-quote-source-heading)`
Screenshot 2021-12-02 at 14 07 59

2. Why does the last quotation mark have an 8px spacing before it? If you get a full last row, the space will make the quotation mark to drop alone on the next row.
Screenshot 2021-12-02 at 13 59 15
Screenshot 2021-12-02 at 14 15 50

Screenshot 2021-12-02 at 14 16 57

3. `Corner-bracket` and `double-angle` marks are too close to the quote text on the left side.
Screenshot 2021-12-02 at 14 20 02
 
4. CTA link color token for the inverse theme seems off when i switch between themes.

Screenshot 2021-12-02 at 14 21 30
Screenshot 2021-12-02 at 14 22 23

**Comment by andysherman2121** [comment]
@DragosRistici made all the requested fixes!

**Comment by jeffchew** [comment]
@andysherman2121 can you fix the merge conflicts? You might need to rebuild the snapshot file.

**Comment by DragosRistici** [comment]
Thank you, @andysherman2121 for solving these issues. 

Three things I've noticed though. First, the horizontal rule overhangs 32px left and right instead of 16px.

Screenshot 2021-12-16 at 15 01 14
Screenshot 2021-12-16 at 15 01 11

Second, on the NextJS example, the quote is 
Screenshot 2021-12-16 at 15 06 52
Screenshot 2021-12-16 at 15 07 45

And third, on the WC code sandbox, the quote has some grid issues (its on 7 cols and no 16px horiz rule overhang)
Screenshot 2021-12-16 at 15 11 06


Let me know if you want to open a new issue for these ones. Thx.

**Comment by DragosRistici** [comment]
@andysherman2121  I can open another issue with `Quote clean up – Part 2` if you want.

**Comment by jeffchew** [comment]
@andysherman2121 the diffs are now showing the quote out of place again:

image

**Comment by shixiedesign** [comment]
Hey checking in to see if there's anything I can help here. At a quick look, PR seems to have introduced some unexpected grid changes and didn't yet fix the small breakpoint text width issue. @andysherman2121 lemme know if you'd like to walk through the comments at all.

**Comment by DragosRistici** [comment]
Hey, @andysherman2121, let me know when i can take another look! Thank you.

**Comment by jeffchew** [comment]
Closing this, will probably need to come back to this issue later on.

**Pull request closed without merging**
