### PR TITLE
chore(dependencies): upgrade `carbon-web-components`

### PR DESCRIPTION
**Pull request by asudoh**
Refs #5060 

### Description

To `v1.13.0`.

### Changelog

**Changed**

- Upgrades `carbon-web-components` to `v1.13.0`.

### CODE REVIEW

**Review by andysherman2121 — CHANGES_REQUESTED** [review]
@oliviaflory Left some comments on the Percy build. Looks like the button on Modal isn't right

**Comment by asudoh** [comment]
Good catch @oliviaflory - Fixed.

**Comment by asudoh** [comment]
Seems that Percy flakiness happening for cards with `sameHeight()`. CC @jeffchew

**Review by jeffchew — APPROVED** [review]
LGTM!

@asudoh yes, we never had any luck with same height in Percy, I'm thinking of skipping those in Percy tests.

**Review by andysherman2121 — APPROVED** [review]

**Pull request merged**
