### PR TITLE
fix(masthead): set platform name z-index and background color

### PR DESCRIPTION
**Pull request by annawen1**
### Related Ticket(s)

Masthead with Platform - Divider activates hover state on platform #5484

### Description

There was work (PR: fix(Masthead): remove pseudo element from platform name #5835) to address the ticket by removing the pseudo element from the platform name, but in web components that led to the overflow menu options to show behind the platform name.

This PR addresses the overflow menu items by setting the `z-index` and `background` of the platform name.

BEFORE:
Screen Shot 2021-04-22 at 4 01 25 PM

AFTER:
Screen Shot 2021-04-22 at 3 59 49 PM

### Changelog

**Changed**

- set the `z-index` and `background` of `top-nav-name` component

### CODE REVIEW

**Comment by ariellalgilmore** [comment]
looks good for web components but react is still showing :/

**Review by jeffchew — APPROVED** [review]
LGTM!

**Comment by annawen1** [comment]
> looks good for web components but react is still showing :/

Ah, I thought React was fine but I see it now at a specific breakpoint

**Review by ariellalgilmore — APPROVED** [review]
yayyy looks good! thank you!

**Pull request merged**
