### PR TITLE
feat(scrolling-utility): Add new utility to mimic dotcom-shell functionality

### LINKED ISSUE #8240: [New Utility]: Separate Scrolling Logic
### The problem

Scrolling on a page has issues due to sticky offset, and titles end up hidden. The issue is that the scrolling logic is in the dotcom-shell, but we are not using the dotcom-shell. Due to the risks of modifying nodes of many existing pages, we need a solution that does not require using dotcom-shell.

### The solution

Today, we had a discussion about keeping our current page node structure without the dotcom-shell but still leverage the scrolling logic. @annawen1 mentioned the idea of separating the scrolling logic into a utility.

### Application/website

AEM (Marketing)

### Business priority

Medium Priority = upcoming release but is not pressing

### What time frame would this ideally be needed by (if applicable)

_No response_

### Examples

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)

Closes #8240 

### Description

Adds a new utility class `StickyHeader` that handles the interaction between sticky header components

### Changelog

**New**

- Adds `StickyHeader` class to ibmdotcom-utilities

### CODE REVIEW

**Comment by proeung** [comment]
I'm seeing some test fails for the universal-banner component and others. Can you take a look? https://github.com/carbon-design-system/carbon-for-ibm-dotcom/runs/5392493298?check_suite_focus=true#step:8:3489

**Comment by andy-blum** [comment]
I was looking at these - I'm not sure right now why the banner would fail. I didn't change anything about it's functionality 🤔

**Comment by andy-blum** [comment]
@ariellalgilmore Are we certain we want to yank that functionality right now? This should be written in such a way that components use this utility as a fallback in case the dotcom-shell isn't present, and I haven't been able to test extensively. Some components (leadspace-with-search) haven't been written into this at all.

In the utility we have
```javascript
static isNecessary() {
    return Boolean(
      !root.document.querySelector(`${ddsPrefix}-dotcom-shell-container`)
    );
  }
```
Each component checks if the utility is needed before attempting to use it.
```javascript
firstUpdated() {
    if (StickyHeader.isNecessary()) {
      StickyHeader.global.banner = this;
    }
  }
```
And the object isn't created if nothing ends up calling for it
```javascript
static get global() {
    if (!Object.prototype.hasOwnProperty.call(root, 'stickyHeader')) {
      root.stickyHeader = new StickyHeader();
    }
    return root.stickyHeader;
  }
  ```

**Comment by ariellalgilmore** [comment]
@andy-blum thanks for explaining. that makes sense! I will edit this issue for only creating the utility and create another issue with removing the dotcom shell logic in the future.

**Comment by andy-blum** [comment]
ah crap I just did a bunch of work on the wrong branch 💀

**Comment by ariellalgilmore** [comment]
Hi @andy-blum! I see a lot of checks are failing, could you take a look?

**Comment by andy-blum** [comment]
@ariellalgilmore looks like the tests don't like the nullish coalescing operator? I'll put it back to the `||` and see if that fixes the tests.

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8434/commits/62da83b16313767cb0615b559880b533ce65c20d#diff-0240b6ac9e8974cfcb51cc6749735a60988260d5d79fee5954e510ecd14badb8R202

**Comment by kennylam** [comment]
@andy-blum looks like it's failing the prettier check. You can run a `yarn format` at project root to fix.

**Comment by andy-blum** [comment]
@kennylam should be cleaned up now

@ariellalgilmore The TOC layout knob's been added, but it looks like there's something wrong with the utility for the horizontal layout

**Comment by ariellalgilmore** [comment]
> @ariellalgilmore The TOC layout knob's been added, but it looks like there's something wrong with the utility for the horizontal layout

looks like you need to set a stickyOffset=48 to the horizontal TOC

**Comment by ariellalgilmore** [comment]
thanks for the updates @andy-blum ! so awesome to see all of these components working together!

2 small things:
1.looks like the vertical TOC is now pushing away the masthead. Only the horizontal TOC should push the masthead away i believe
Screen Shot 2022-03-10 at 12 55 13 PM


2. the web components html test app seems to be failing from importing the utility. try changing it from  `'../../../../utilities/src/utilities/StickyHeader/StickyHeader.js';` to
` '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/StickyHeader/StickyHeader';` (related [PR](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8363/files#diff-5f9be5ba26d2a2fd2ea92bc23301d03deff55323fb5d1992988dedbad7b6fce0))

**Comment by andy-blum** [comment]
@ariellalgilmore tests re-running now

**Review by proeung — APPROVED** [review]
Everything looks great in the latest deploy previews!

I think we just need to approve this Percy visual diff change (see [link](https://percy.io/538fc19a/Carbon-for-IBM.com-Web-Components/builds/16454184/changed/926152726?browser=chrome&browser_ids=20&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1280&widths=320%2C1280)), in order to have this PR marked as "Ready for merge". @ariellalgilmore Can you help take a look? Thanks!

**Review by ariellalgilmore — APPROVED** [review]
Looks amazing!! so awesome to see all the components working well together!! thanks for all the updates @andy-blum !

**Comment by oliviaflory** [comment]
Hi @andy-blum this is looking really awesome! Just a few things:

_**Note:** All testing done on Chrome browser Version 98.0.4758.102 (Official Build) (x86_64)_

### L1 + Vertical TOC
- [ ] On scroll the L0 should scroll away and the L1 should be the only navigation shown, right now we see both L0+L0 on scroll and it hides a the title of the TOC anchor links.

L1 prod example:
L1 scroll up-prod--Mar-11-2022 16-01-27

PR  current:
L1 scroll-fixed-current--Mar-11-2022 16-02-07


### L0 or L1 + Universal banner + Horiz TOC
-  [ ] TOC is going behind the L0/L1 on Medium and small breakpoints
L1-UB-HTOC--Mar-11-2022 16-31-41


### Story grid alignment
I know we didn't have a design mock up for this story, but we do need to have everything aligned to the grid like the other Dotcom shell examples so we are demonstrating expected alignment to adopters.
Please let me know if the below examples are enough to go on!

**Vertical TOC stories**
Screen Shot 2022-03-11 at 4 57 48 PM


**Expecting** [Prod example link](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-dotcom-shell--default)
Screen Shot 2022-03-11 at 4 47 04 PM



**Horizontal TOC Stories**
Screen Shot 2022-03-11 at 4 47 49 PM

**Expecting** [Prod example](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-dotcom-shell--with-horizontal-toc)
Screen Shot 2022-03-11 at 4 46 09 PM

**Comment by oliviaflory** [comment]
@andy-blum the vertical TOC stories look correct, thank you for the update!

I may have not been clear enough in the comment above, the L1 + horizontal TOC should behave similarly.
- On scroll L1 pushed L0 out
- Once Horiz TOC reaches the L1, the TOC pushed L1 out. Leaving just TOC
- Ok to show both L1 & L0 on scroll up

Example: [TOC horiz story](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/8434/iframe.html?id=components-dotcom-shell--with-horizontal-toc&knob-Masthead%20Version_DotcomShell=L1&knob-Table%20of%20Contents%20Layout_DotcomShell=horizontal&knob-Has%20Universal%20Banner_DotcomShell=true)

**Review by oliviaflory — APPROVED** [review]
Thank you @andy-blum for the updates!

**Comment by kennylam** [comment]
@andy-blum @proeung Changing target to release branch in anticipation of adding to an upcoming `rc`.

**Comment by proeung** [comment]
@kennylam I'm seeing some merge conflicts coming from branch `release/v1.32.0`. Is this something that you and your team will be resolving or is this something that you like @andy-blum to take a look?

Also, please keep me posted on when these changes are patched up to `v1.32.1` rc, so that I can update the AEM team. Thanks!

**Pull request merged**
