### PR TITLE
fix(layout): wrapping layout story in 12 columns grid

### PR DESCRIPTION
**Pull request by guilhermelMoraes**
### Related Ticket(s)

[Layout] not on grid #5793

### Description

{{Add a human-readable description / detail summary of what the PR is changing and any details around how and why}}

{{If applicable, include a screenshot indicating an example or examples of what the PR is changing in the application}}

### Changelog

**New**

- {{new thing}}

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by shixiedesign** [comment]
Chatting on Slack with Gui. This PR fixes the issue and should be merged. We would have to investigate later if there are some better way to present layout as a component

image

**Review by shixiedesign — DISMISSED** [review]

**Review by shixiedesign — COMMENTED** [review]
Seeing the grid still not lining up on `lg - sm` breakpoints

**Review by IgnacioBecerra — APPROVED** [review]
LGTM, thanks @guilhermelMoraes

**Comment by shixiedesign** [comment]
So I'd hope we can demo 4-12 and 8-4 as specified in the functional spec
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Layout

Once there's no more grid issues, we can merge, and will look into how to communicate the layout to adopters in a separate issue under website guidance.

**Comment by annawen1** [comment]
> Chatting on Slack with Gui. This PR fixes the issue and should be merged. We would have to investigate later if there are some better way to present layout as a component
> 
> image

Adding a comment here on the 3 columns, looking at where the layout class like `bx--layout-2-3` is used it looks like this was set up to sit within the vertical table of contents. The table of contents is 4 columns, with the table index sitting on the leftmost column. The layout then sits within the table of contents, taking 3 of the 4 columns. Hope that makes sense

**Review by annawen1 — APPROVED** [review]
LGTM!

**Pull request merged**
