### PR TITLE
fix(MastheadSearch): carbon upgrade - masthead search button tooltip

### PR DESCRIPTION
**Pull request by annawen1**
### Related Ticket(s)

{{Provide url(s) to the related ticket(s) that this pull request addresses}}

### Description

Carbon upgrade made the tooltip appear on hover for icon only buttons which is the masthead search buttons are using. Set the tooltip to be right aligned so it doesn't get cut off in smaller breakpoints

BEFORE:
Screen Shot 2021-04-12 at 12 51 29 PM

AFTER:
Screen Shot 2021-04-12 at 3 35 26 PM

### Changelog

**Changed**

- set tooltip alignment prop to 'end'

### CODE REVIEW

**Review by jeffchew — APPROVED** [review]
Thanks @annawen1 !

**Comment by annawen1** [comment]
discussing with design at the moment to see if this is actually something we want to keep

**Comment by annawen1** [comment]
spoke with designers, we are keeping the tooltip - just changing the alignment so it doesn't get cut off in smaller breakpoints

**Review by shixiedesign — APPROVED** [review]
Looking good!

**Review by ariellalgilmore — COMMENTED** [review]
looks like the blue focus is missing now? 
Screen Shot 2021-04-12 at 3 00 31 PM

**Pull request merged**
