### PR TITLE
fix(card): updated eyebrow to use label-02

### PR DESCRIPTION
**Pull request by NSDrowned**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6193

### Description

Updated `Card` eyebrow to use `$label-02`. Removed overrides from `feature-card` and `card in card`. As requested, left `featured card - large` override.

### CODE REVIEW

**Review by kennylam — APPROVED** [review]
LGTM thanks @NSDrowned!

**Comment by oliviaflory** [comment]
Hey @NSDrowned could we remove the feature card large override as well? Apologies for changing our mind, we just realized all eyebrows should use the `$label-02` for consistency.

**Comment by NSDrowned** [comment]
@oliviaflory I removed the feature card large override 👍

**Review by ariellalgilmore — APPROVED** [review]
LGTM!

**Review by oliviaflory — APPROVED** [review]
Looks good, thanks @NSDrowned !

**Pull request merged**
