### PR TITLE
fix(cta): aligned feature card stories

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#5542

### Description
Aligned Web Components and React's CTA Feature story.

### Changelog
**Changed**

- ensured Feature CTA is top-left aligned

### CODE REVIEW

**Comment by photodow** [comment]
How close are we aligning these stories? As an example each environment is using a different image.

**Review by photodow — CHANGES_REQUESTED** [review]
- [x] extra spaces in web components copy 

image

- [x] update with real content like what's in design specs.

- [x] I created an issue to fix theming https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6350

- [x] Eyebrow doesn't appear to be required in web components. React is does some really weird layout changes. Both still render the card. Also, where is that requirement coming from?

image

- [x] Is there any reason we are so repetitive in the knob labels? Could we just say `copy`, `href`, `heading`? cc @shixiedesign 

image

- [x] @shixiedesign shouldn't feature card stories be aligned top left? https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6422

- [x] Icon size misalignment, and incorrect. In both react and web components the CTA icon is smaller, than it is in feature card story. Neither of them are the right size except in the large size icon.

**Comment by IgnacioBecerra** [comment]
@photodow @shixiedesign Let me know what the knob labels should look like, all the other requested changes have been fixed in the latest commit 👍

**Comment by shixiedesign** [comment]
> Is there any reason we are so repetitive in the knob labels? Could we just say copy, href, heading? 
Yes the shorter knob labels would be great. 🙏 

> shouldn't feature card stories be aligned top left?
I see that they are top left aligned right now, so we should be good. Expecting all UI components to be 16px from top and 16px from left.

**Comment by photodow** [comment]
> > shouldn't feature card stories be aligned top left?
>
> I see that they are top left aligned right now, so we should be good. Expecting all UI components to be 16px from top and 16px from left.

<br />

I'm definitely seeing centered for both web components and react in.  <br />

image

**Comment by shixiedesign** [comment]
@photodow ah those are in Feature card component. Let's make new issue for it.

**Comment by shixiedesign** [comment]
Hey @IgnacioBecerra 2 things I noticed: 

1. React `CTA - feature` is missing "Heading" knob. Should align to Web components
image

2. `Feature card - medium` in Web components seems affected:
image

**Comment by photodow** [comment]
A couple of (hopefully) small misalignment between the stories. Please reach out if you have any questions.

- [ ] Content overflows in react, and the card expands correctly in web components.

image image

- [ ] Web components cta feature video type has a different title than react.

image 
image

> Do we need a ticket to add the duration to the icon?

- [ ] React video is taking me to another page, while web components video is properly opening up in light box media viewer.

- [ ] The way the feature card is laid out in CTA feature is still not aligned to feature card stories. Feature card is incorrectly centered, and CTA feature is left aligned properly.

**Review by photodow — APPROVED** [review]
Aside from a few issues I opened related to this work... #6350, #6422, #6417 this looks good to me. :+1:

**Pull request merged**
