### PR TITLE
test(e2e): introduce cypress for web components & react storybook

### PR DESCRIPTION
**Pull request by jeffchew**
### Related Ticket(s)

Refs #6139

### Description

This PR fully moves the existing `test-e2e` package to a dedicated cypress test setup for web components and react storybooks. A few tests have been included for `masthead`, `locale-modal`, and `leadspace`. They are largely focused on snapshot testing, though percy has been disabled for now as rendering of dynamic states are still not supported in percy for web components (see https://github.com/percy/cli/issues/280).

Actual cypress tests can be created now though, and also the current tests uses the built-in cypress screenshot feature:

image

And video that shows how the tests are run:

https://user-images.githubusercontent.com/1641214/132697174-a778c055-d3d8-4e01-877d-bd58c2aa7491.mp4

### Changelog

**New**

- Cypress testing for web components and react storybook

**Changed**

- disabled video recording by default to speed up tests

**Removed**

- Removed `test-e2e` package

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
should there be any lockfile and offline package mirror changes that go with this as well? I get unstaged changes when running a yarn install

**Comment by jeffchew** [comment]
> should there be any lockfile and offline package mirror changes that go with this as well? I get unstaged changes when running a yarn install

It should have been updated, but I can double-check. Web components and react are using existing dependencies for cypress already which is probably why there isn't much difference, but I would think that puppeteer would have been deleted.

**Review by IgnacioBecerra — APPROVED** [review]

**Comment by jeffchew** [comment]
@emyarod I ran a reset locally and didn't see any new changes. Did you run a reset on your end?

**Comment by emyarod** [comment]
@jeffchew yeah mine is still running but I will update when it's finished

**Pull request merged**
