### PR TITLE
feat(content-group): v2 style updates

### LINKED ISSUE #10753: [Component] Content group

### PR DESCRIPTION
**Pull request by sangeethababu9223**
### Related Ticket(s)

Closes #10753 

### Description

Style issues with Content Group Component in V2

### Changelog

**Changed**

- Used Card Component instead of CTA Link
- Style updated to match the latest

### CODE REVIEW

**Review by kennylam — APPROVED** [review]
LGTM!

**Comment by oliviaflory** [comment]
Thanks @sangeethababu9223 !

There seems to be a slight difference between the v1 and v2 examples when I add the children elements. In v2 the content items extend beyond the width of the content group, this might have more to do with the content item than the content group? But I am not quite sure. I know @kennylam is still working on the content item 

We do want the content group to be able to accept 8 or 12 column children, similar the content section updates, so I am OK with merging this AS-IS for now and returning to it once we have more of the content components figured out.

**V1**
Screenshot 2023-10-13 at 6 44 03 AM

**V2**
Screenshot 2023-10-13 at 6 42 32 AM

**V1**
Screenshot 2023-10-13 at 6 49 08 AM

**V2**
Screenshot 2023-10-13 at 6 49 38 AM

**Review by RichKummer — COMMENTED** [review]
Hey @sangeethababu9223 , two other things to add to Olivia's comment above:

1. When nesting `content items` into `content group`, the top and bottom margins should merge together. But right now, it looks like the spacing values stack instead. @kennylam and @IgnacioBecerra were solving a similar problem recently, so they may have some insight.

You can see in the following screenshots that the margin spacing is stacking rather than merging together:
Screenshot 2023-10-30 at 11 38 01 AM
Screenshot 2023-10-30 at 11 38 12 AM

2. The last update is that the last nested piece of content inside `content group` should automatically remove the bottom spacing (or merge it) so that there is `48px` spacing between the bottom of the last item and the `CTA`. 

You can see in the following screenshot that the spacing stacks, creating more space at the end than intended.
Screenshot 2023-10-30 at 11 39 18 AM

**Review by oliviaflory — APPROVED** [review]
This looks great, thanks @sangeethababu9223 !

**Pull request merged**
