### PR TITLE
fix(card-pictogram): fixed mobile spacing

### PR DESCRIPTION
**Pull request by andysherman2121**
### Related Ticket(s)

#4807 

### Description

The card pictogram was missing 16px of padding on mobile breakpoint for web components

### CODE REVIEW

**Review by ariellalgilmore — COMMENTED** [review]
Hey @andysherman2121 looks good! Is it possible to add the padding-left to the card copy when you hover over the pictogram

Screen Shot 2021-01-08 at 11 46 21 AM

**Comment by andysherman2121** [comment]
> Hey @andysherman2121 looks good! Is it possible to add the padding-left to the card copy when you hover over the pictogram
> 
> Screen Shot 2021-01-08 at 11 46 21 AM

@ariellalgilmore Yeah! it looks like the other card versions are missing the padding too, not just the pictogram. I'm gonna update all of them

**Comment by andysherman2121** [comment]
@ariellalgilmore Just added the fix for the missing padding on the copy

**Review by ariellalgilmore — APPROVED** [review]
LGTM! Thanks for the updates @andysherman2121!

**Pull request merged**
