### PR TITLE
fix(tabs-extended-media): page wobble while scrolling fix

### PR DESCRIPTION
**Pull request by NSDrowned**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6130

### Description

This only happens in actual devices (tested in safari and chrome in iOS), not in device simulation. Overflow is caused by content items like `dds-content-item-horizontal-media` that use negative left and right margins. 

### Changelog

Disabling horizontal overflow in `dds-tabs-extended-media` fixes the problem.

### CODE REVIEW

**Review by ariellalgilmore — APPROVED** [review]
LGTM!

**Comment by NSDrowned** [comment]
Hello @Praveen-sr, wondering if you could test this before it gets merged?

**Comment by Praveen-sr** [comment]
@NSDrowned Tested with the above links on Mobile, page wobble while scrolling is fixed now.

**Comment by jeffchew** [comment]
Thank you @NSDrowned @ariellalgilmore @Praveen-sr !

**Pull request merged**
