### PR TITLE
chore(carbon): updating dependencies across packages

### PR DESCRIPTION
**Pull request by guilhermelMoraes**
Refs #4372 

### Description

Updating Carbon dependencies.

### Changelog

**Changed**

- Carbon dependencies version to React, Styles, Web-components, Services-store, and utilities.

### CODE REVIEW

**Comment by jeffchew** [comment]
@guilhermelMoraes can you update the snapshot files?

**Comment by jeffchew** [comment]
@oliviaflory @wonilsuhibm can you review this change that Percy picked up? I approved the other upstream changes which looked ok to me.

Screen Shot 2020-11-04 at 4 58 26 PM

https://percy.io/538fc19a/Carbon-Expressive-Theme/builds/7578601?utm_campaign=538fc19a&utm_content=Carbon-Expressive-Theme&utm_source=github_status_public

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @guilhermelMoraes!

**Review by kennylam — APPROVED** [review]
LGTM thanks @guilhermelMoraes!

**Pull request merged**
