### PR TITLE
fix(masthead-top-nav-menu-item): removing the dark background

### PR DESCRIPTION
**Pull request by guilhermelMoraes**
### Related Ticket(s)

Web component: Masthead - On hover over the menu options, background color is black #4734

### Description

Removing the dark background from `dds-top-nav-menu-item`

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
@guilhermelMoraes I guess you didn't want 910 file changes... Probably you meant different target branch?

**Comment by guilhermelMoraes** [comment]
@asudoh thanks for noticing! 😅 Just updated the base branch.

**Review by ariellalgilmore — APPROVED** [review]
LGTM! thanks @guilhermelMoraes!

**Review by asudoh — COMMENTED** [review]
Thanks @guilhermelMoraes for the update. The root cause seems to be https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/v1.13.0/packages/styles/scss/components/masthead/_masthead.scss#L125 getting overriden by Carbon core style. Would you try adding `[role='menuitem']` to the selector at https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/de880d5/packages/styles/scss/components/masthead/_masthead.scss#L282?

**Pull request merged**
