### PR TITLE
fix(masthead): Close left-nav and megamenu when on clickout or escape

### LINKED ISSUE #6676: [Masthead, mega menu] Web Components:  In the `md` breakpoint, Mega menu options do not close when clicked outside the menu options.. - DDS consulting
HC engineer: @andy-blum 
HC Jira Ticket: https://jsw.ibm.com/browse/HC-2187
DDS consulting engineer: Anna Wen

----
## Detailed description

Issue:
Mega menu options do not close when clicked outside the menu options. Anywhere on the page.

**Expecting:** clicking outside the menu on page with an overlay should close the menu. 

**Currently:** clicking outside the menu on the overlaid page doesn't do anything.

## Additional information

- Example 1

----

- Example 2

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)
Fixes:
 - #6676 **(does not fix react package)**
 - #7159

### Description

This PR addresses accessibility & usability concerns around the megamenu and left-nav components.

**Web Components Package**
- Clicking outside megamenu closes the megamenu and returns focus to the megamenu's trigger element
- Hitting `Esc` with an open megamenu closes the megamenu and returns focus to the trigger element
- Clicking in the overlay area with an open left nav closes the left nav and returns focus to the toggle button
- Hitting `Esc` with an open left nav closes the left nav and returns focus to the toggle button

**React Package**
- None yet

### Changelog

**Changed**

- UX & a11y improvements to megamenu and mobile navigation
- Fixes issue in dds-left-nav where menu sections with scrollbars break the toggle functionality

### CODE REVIEW

**Review by JBrandwine — APPROVED** [review]
Mega menu closes when clicking outside of the menu or hitting ESC key and hamburger menu alignment looks correct after clicking back in Web Components and React preview links.

**Comment by proeung** [comment]
@JBrandwine I just wanted to note that this PR only accounted solution for the WC package. The click issue on mobile within the React package is still persistent (see attached).

https://user-images.githubusercontent.com/1815714/133847133-c3e14e82-cda1-49b7-95b1-834f7f3efbf7.mov

Looking at the current React Masthead code, it looks like the `setOverlay` function defined [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/dacbc19d0ff9a32b8e9bfa671b2232044aab28ce/packages/react/src/components/Masthead/MastheadTopNav.js#L59) is coming from the Core Carbon React package (see the import [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/dacbc19d0ff9a32b8e9bfa671b2232044aab28ce/packages/react/src/components/Masthead/MastheadTopNav.js#L11)). If you look at Carbon Core, you'll see the overlay is not removed when `onclick` (https://react.carbondesignsystem.com/?path=/story/components-ui-shell--header-base-w-navigation).

I've reviewed this with @ariellalgilmore and looks like this portion of the need to be implemented on the core package level. In the meantime, I think we can scope the review and testing of this PR to just WC for now.

cc: @annawen1 @andy-blum

**Comment by annawen1** [comment]
Working great, only question I have is when I first load the masthead, focus automatically goes to the "Products & Solutions" menu item. Is this something we are good with?

**Comment by andy-blum** [comment]
@annawen1 thanks for catching that. Looked into it briefly, and I have a fix for the focus on load.

**Review by annawen1 — APPROVED** [review]
Works great now, thanks @andy-blum!

**Pull request merged**
