### PR TITLE
feat(card-hc): add a card variant pulling from the HC design library

### PR DESCRIPTION
**Pull request by proeung**
### Related Ticket(s)

- No public GitHub ticket.
- JIRA ticket from IBM - https://jsw.ibm.com/browse/HC-1468

### Description
- This PR is the initial step to opening the conversation between the Hybrid Cloud and the DDS teams regarding the contribution process of creating a card variant that pulled design elements from the HC Design Library.
- We'd like to see if this card variant can be added as one of the components/variants within the `@carbon/ibmdotcom-web-components` package.
- Some changes within the proposed design or the way the code is organized might be adjusted given the feedback provided by both teams.
- The goal is to have this building block component available within the `@carbon/ibmdotcom-web-components` package so that we can pull down and reference these web components custom elements in our Fractal Library (see link - https://github.ibm.com/MSC-Cloud/hc_fractal/pull/267/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R14)

Screen Shot 2020-12-01 at 4 57 12 PM
Components___Card_-_HC_-_Default_⋅_Storybook_and_Module_2A__Gray_100___IBM_Hybrid_Cloud_Component_Library

### Changelog

**New**

- `<dds-card-hc>`, the text card component pulling from the HC Design Library.
- `<dds-card-hc-footer>`, the card footer 

```
<dds-card-hc href="https://example.com">
  <span slot="eyebrow">eyebrow text</span>
  <span slot="heading">Lorem ipsum dolor sit amet</span>
  <span slot="copy">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</span>
  <dds-card-hc-footer slot="footer">
    <svg slot="icon" focusable="false" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg" fill="currentColor" aria-hidden="true" width="20" height="20" viewBox="0 0 20 20">
      <path d="M11.8 2.8L10.8 3.8 16.2 9.3 1 9.3 1 10.7 16.2 10.7 10.8 16.2 11.8 17.2 19 10z"></path>
    </svg>
  </dds-card-hc-footer>
</dds-card-hc>
```

**Changed**

- Adjust the `copy` prop as slot
- Add overriding styling in the `card-hc.scss`

### CODE REVIEW

**Comment by wonilsuhibm** [comment]
@proeung Thank you for submitting this PR. Do you folks have design specs, functional specs, content model to drive this card by any chance?

Also would love to understand the intent or recommended use case for this card to work out a more suitable name from the system perspective. Would you be interested in presenting this card in the design office hour (Wednesday 10 AM ET)? We can also meet separately too, please let us know.

**Comment by proeung** [comment]
@wonilsuhibm Not a problem and thank you for taking the time to review my PR! 

This PR is intended for us, the development team to figure out the contribution workflow and getting started on the conversation surrounding some of the building block components that we can contribute back to the main library.

As for the specs of this card component, I believe our design team is putting together a document that we can present to you and your team in the upcoming design office hour. I'll be reviewing this PR with Shawn and Annmarie today during our weekly design meeting to walk them through this contribution process and gather real-world metrics on the engagement of this component. I'm happy to meet and chat via Webex if that's helpful as well. Please let me know.

**Comment by annawen1** [comment]
Hi @proeung! Were there any updates to the design or card naming/implementation after conversations in the design office hours? I think we can work together to get this component behind a feature flag!

**Comment by proeung** [comment]
@annawen1 Thanks for checking in. I don't believe we have much traction with this particular card component design variation at the moment. Let me bring this up to our CD again and see if we still want to push forward with this design.

**Comment by proeung** [comment]
Closing this PR for now. We might be revisiting this once we have a consensus on the design.

**Pull request closed without merging**
