### PR TITLE
feat(carousel): introduction

### PR DESCRIPTION
**Pull request by asudoh**
### Related Ticket(s)

Refs #4150.

### Description

Introduces `<dds-carousel>`. Also introduces `<dds-content-section-leading>` and components to be used inside it for the purpose of the content section in `<dds-carousel>`.

Also moves mock resize observer to `tests/utils` given `<dds-carousel>`'s unit test in addition to one of `<dds-table-of-contents>` uses it.

### Changelog

**New**

- `<dds-carousel>`, the carousel component.
- `<dds-content-section-leading>`, the content section's leading content for carousel.
- `<dds-content-section-heading>` the heading content for content section.
- `<dds-content-section-copy>` the copy content for content section.

**Changed**

- Moves mock resize observer to `tests/utils`.

### CODE REVIEW

**Comment by asudoh** [comment]
@jacobottesen-dgc @wonilsuhibm Just in case you want to take early preview at the in-progress work: https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/4478/iframe.html?id=components-carousel--default

The remaining works are:

* Documentation
* Tests
* Cross-browser checks

**Comment by asudoh** [comment]
Now it's ready-for-review.

**Comment by asudoh** [comment]
Made the nav left-aligned per @wonilsuhibm's suggestion.

**Comment by asudoh** [comment]
> Made the nav left-aligned per @wonilsuhibm's suggestion.

Backed it out upon the discussion.

**Comment by jeffchew** [comment]
Looks good so far @asudoh !

I noticed when I set the page size to more than 5, the formatting gets a bit weird:

Screen Shot 2020-11-24 at 2 11 33 PM

Should there be a knob to actually set the number of items as well?

**Comment by jeffchew** [comment]
Also a couple of questions:

1) Curious to know why a `leading` slot is necessary as part of `dds-carousel`? Could the carousel be a sub component within `dds-content-section` instead?

2) Can you create an additional story in storybook to not have a leading section?

**Comment by jeffchew** [comment]
And maybe another thought. Perhaps we should instead extend `dds-content-section` to have the heading, copy and link, then `dds-carousel` is just the content for the content section?

```
<dds-content-section>
  <span slot="heading">Lorem ipsum dolor sit amet</span>
  <span slot="copy">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et ultricies est</span>
  <span slot="cta">
    <dds-link-with-icon slot="footer" href="https://www.ibm.com/standards/web/carbon-for-ibm-dotcom">
      Link text
      <svg
        slot="icon"
        focusable="false"
        preserveAspectRatio="xMidYMid meet"
        xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true"
        width="20"
        height="20"
        viewBox="0 0 20 20"
      >
        <path d="M11.8 2.8L10.8 3.8 16.2 9.3 1 9.3 1 10.7 16.2 10.7 10.8 16.2 11.8 17.2 19 10z"></path>
      </svg>
    </dds-link-with-icon>
  </span>
  <span slot="content">
    <dds-carousel>
      <dds-card href="https://www.ibm.com/standards/web/carbon-for-ibm-dotcom">
        <span slot="heading">Lorem ipsum dolor sit amet</span>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et ultricies est.
        <dds-card-footer>
          <svg
            slot="icon"
            focusable="false"
            preserveAspectRatio="xMidYMid meet"
            xmlns="http://www.w3.org/2000/svg"
            aria-hidden="true"
            width="20"
            height="20"
            viewBox="0 0 20 20"
          >
            <path d="M11.8 2.8L10.8 3.8 16.2 9.3 1 9.3 1 10.7 16.2 10.7 10.8 16.2 11.8 17.2 19 10z"></path>
          </svg>
        </dds-card-footer>
      </dds-card>
      <dds-card href="https://www.ibm.com/standards/web/carbon-for-ibm-dotcom">
        <span slot="heading">Lorem ipsum dolor sit amet</span>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et ultricies est. Mauris iaculis eget dolor nec hendrerit.
        Phasellus at elit sollicitudin, sodales nulla quis, consequat libero.
        <dds-card-footer>
          <svg
            slot="icon"
            focusable="false"
            preserveAspectRatio="xMidYMid meet"
            xmlns="http://www.w3.org/2000/svg"
            aria-hidden="true"
            width="20"
            height="20"
            viewBox="0 0 20 20"
          >
            <path d="M11.8 2.8L10.8 3.8 16.2 9.3 1 9.3 1 10.7 16.2 10.7 10.8 16.2 11.8 17.2 19 10z"></path>
          </svg>
        </dds-card-footer>
      </dds-card>
    </dds-carousel>
  </span>
</dds-content-section>
```

**Comment by asudoh** [comment]
Thank you for the review @jeffchew - The content section thing is an planned action item upon our functional spec review. The bug with narrow screen should be fixed. I think adding knob for number of items per page is a good idea.

**Comment by asudoh** [comment]
Updated `<dds-content-section>` to add copy/footer contents, and used it for carousel story. Also fixed the issue with narrow screen.

**Comment by jeffchew** [comment]
Thanks @asudoh, will take another look.

Can you take a look at the unit tests? They are failing at the moment.

**Comment by jeffchew** [comment]
Not sure if this was captured in functional specs, but wondering if there are any thoughts about suppressing the carousel controls if there is no pagination? Right now it looks like it's just deactivated if I set the knob to 5 items:

Screen Shot 2020-11-25 at 9 13 01 AM

Thoughts @wonilsuhibm @jacobottesen-dgc @photodow ?

**Comment by jeffchew** [comment]
@asudoh one thought, perhaps the `default` story should be just the carousel standalone, and second story would be inside `dds-content-section`?

Or is the intent that carousel is always inside content section @wonilsuhibm @jacobottesen-dgc @photodow ?

**Comment by asudoh** [comment]
Fixed the Percy diff. Wrt hiding the paginator if there is only one page and having a story of standalone carousel, good to have feedback from @wonilsuhibm @jacobottesen-dgc @photodow.

**Comment by wonilsuhibm** [comment]
@asudoh Thank you!. This looks great.

One thing about the timing or speed of the motion—can we use these parameters, to the Carbon specs please?
```
Duration: 187ms
Easing: cubic-bezier(0.2, 0.2, 0.38, 0.9)
```

**Comment by oliviaflory** [comment]
_Adding my comments from Slack conversation_ 

>one thought, perhaps the default story should be just the carousel standalone, and second story would be inside dds-content-section?

I'm ok with having the carousel as a stand alone component. It would allow for a little more flexibility if a team needs the left 4 columns blank for a TOC and they could use the Content block heading style 

>Not sure if this was captured in functional specs, but wondering if there are any thoughts about suppressing the carousel controls if there is no pagination?

Yes, I don't know that we documented this particular case, but the carousel should not display 5 items at once within the 16 column grid. However, makes sense to suppress the controls if there is only one page. IMO a Carousel should require 4+ items...because otherwise you don't need the Carousel. 🤷‍♀️

**Comment by asudoh** [comment]
@wonilsuhibm Thank you for your feedback:

* Duration: The current choice is `$duration--slow-01` from https://www.carbondesignsystem.com/guidelines/motion/overview#duration-tokens. Do you see any alternate token we can pick, or should we drift away from any duration token?
* Easing: The current choice is `motion(standard, productive)` from https://www.carbondesignsystem.com/guidelines/motion/overview#standard-easing. Do you see any alternate token we can pick, or should we drift away from any standard/entrance/exit easing?

**Comment by asudoh** [comment]
Introduced standalone carousel story, and fixed the test.

**Review by jeffchew — APPROVED** [review]
LGTM, thank you @asudoh !

**Pull request merged**
