### PR TITLE
fix(link-with-icon): fixes layout styles

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

#6464 

### Description

Update component styles affecting icon sizes at smaller breakpoints.

### Changelog

**New**

- update link `span` styles to prevent squishing icons at smaller breakpoints

**Removed**

- remove extra markup tags
- redundant styling in web components `link-list`

### CODE REVIEW

**Comment by annawen1** [comment]
@kennylam percy caught some changes with the icon shifting
Screen Shot 2021-06-25 at 8 59 09 AM

**Review by annawen1 — APPROVED** [review]
LGTM!

**Review by DragosRistici — APPROVED** [review]
Looks good to me! Thank you, @kennylam

**Comment by jeffchew** [comment]
@DragosRistici @annawen1 @kennylam you'd better take a look at this before merging this: 
image

**Comment by kennylam** [comment]
@DragosRistici `megamenu` style discrepancies have been fixed.

**Comment by DragosRistici** [comment]
> @DragosRistici `megamenu` style discrepancies have been fixed.

LGTM, @kennylam

**Pull request merged**
