### PR TITLE
feat(data-table): ai updates

### LINKED ISSUE #11499: WC data table gradient updates
Follow up to react work on [#15708](https://github.com/carbon-design-system/carbon/issues/15708)

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

Closes #11499 
### Description

Update data table to new gradient updates with AI slug

### Changelog

**New**

- updated styles to align with gradient updates

**Changed**

- now `table.ts` checks if the headers have a slug and if so applies appropriate attributes to the cells in that column

**Removed**

- there was a border that seemed unnessary causing visual differences from wc and react

### CODE REVIEW

**Review by aagonzales — COMMENTED** [review]
In the "slug with expansion" story the bottom borders of the AI rows aren't going all the way over to the left (its hard to see it in the white theme) 
image

In the Column sort slug, the AI table header looks a bit brighter than it should be (just in the header). 
image

**Comment by ariellalgilmore** [comment]
@aagonzales the deploy preview is updated with the changes!

**Review by aagonzales — APPROVED** [review]
Looks good now! ✅ 👍

**Review by annawen1 — APPROVED** [review]
Let's get it in!

**Pull request merged**
