### PR TITLE
fix(content-block): spacing adjustments

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#9813 
### Description

Adjusting top and bottom border and without border spacing. Adjusted components all touching the content-block component. For some had to seperate out react/wc logic

### Changelog

**Changed**

- style update padding to margin

### CODE REVIEW

**Comment by oliviaflory** [comment]
Stunning @ariellalgilmore ! 

I noticed something on the web components [example pages](https://ibmdotcom-web-components-html-test-upstream.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/9819/example-page-b/index.html) that's funky with Logo grid, and the logo grid story that isn't showing up in prod so I'm curious if anything in this PR is causing it?

When you turned on the Display CTA knob it appears above the logo grid and seems to make the logos smaller / shift in the grid
Screenshot 2022-12-21 at 11 57 43 AM

**Comment by ariellalgilmore** [comment]
Oh yeah good catch. It wasn't coming from this PR and noticed it when i was working on controls, but just updated to have it fixed here! @oliviaflory

**Review by oliviaflory — APPROVED** [review]
Thanks for all your hard work Ari!

**Review by emyarod — APPROVED** [review]
looks good to me!

**Pull request merged**
