### PR TITLE
feat(pagination): update story to Storybook v7

### LINKED ISSUE #11334: [carbon-web-components]: pagination Storybook 7 update

### PR DESCRIPTION
**Pull request by m4olivei**
### Related Ticket(s)

Closes #11334

### Description

Adjustments to pagination component stories to be compatible with Storybook v7.

### Changelog

**Changed**

- Updated pagination Storybook stories for Storybook v7
- Specify `page-input-disabled` attribute of `cds-pagination` as boolean

### CODE REVIEW

**Review by RichKummer — COMMENTED** [review]
Hey @m4olivei , this is looking good, just found a few issues in the controls for Playground:

1. `backwardText` does not update the tooltip for that icon button (but `forwardText` works fine)
Screenshot 2024-01-17 at 2 23 50 PM

2. The `pageInputDisabled` attribute does not seem to be working like the react version.

**Comment by m4olivei** [comment]
Nice catches @RichKummer ! Turns out those are issues on the `main` branch as well. They are simple fixes, so I've fixed them here in the most recent two commits.

**Review by RichKummer — APPROVED** [review]
Awesome, looks great @m4olivei ! Thanks for jumping on the change 🔥

**Review by ariellalgilmore — APPROVED** [review]
LGTM!

**Pull request merged**
