### PR TITLE
fix(content-group-pictogram): icon size fix and alignment

### PR DESCRIPTION
**Pull request by NSDrowned**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5731

### Description

Make sure the pictograms are 80x80 on both Storybooks, as in the specs file

### Changelog

**Changed**

- Fixed SVG size for web components
- Fixed mobile alignment for svg and content in web components

### CODE REVIEW

**Comment by jeffchew** [comment]
Is size supposed to be adjusted for all stories?

image

image

**Comment by RichKummer** [comment]
@jeffchew The original ticket only calls out the Storybooks, but I think ideally we would have the SVG size updated in the example pages.

**Comment by NSDrowned** [comment]
@jeffchew, @RichKummer I'll fix the storybook variations 👍

**Comment by NSDrowned** [comment]
@RichKummer, SVGs have been updated 👍

**Comment by RichKummer** [comment]
It looks like the SVGs are solid on the storybook links, but I am still seeing the NextJS and HTML examples with smaller SVGs. It looks like the container for it is 80x80 but the SVG shows up smaller inside the container.
NextJS-HTML

**Comment by NSDrowned** [comment]
@RichKummer, the nextjs template was using outdated icons, I updated the icon versions and the problem has been fixed:

image

**Comment by RichKummer** [comment]
@NSDrowned I'm seeing it updated in the NextJS template (thank you!). I'm assuming it's the same issue on the HTML template, but that one doesn't look like it was updated. Is that a quick fix we can make to ensure we're consistent?

**Comment by NSDrowned** [comment]
@RichKummer you're right, let me fix that right away

**Comment by NSDrowned** [comment]
@RichKummer icons should have the correct size now 👍

**Review by RichKummer — APPROVED** [review]
LGTM! Thanks for making the last change.

**Review by ariellalgilmore — APPROVED** [review]
LGTM!

**Pull request merged**
