### PR TITLE
feat(CTA): enabling custom video title

### PR DESCRIPTION
**Pull request by guilhermelMoraes**
### Related Ticket(s)

[React & WC] Video CTA: Allow for title & description override #6868
[Feature CTA - video] Component doesn't play video. #7033

### Description

{{Add a human-readable description / detail summary of what the PR is changing and any details around how and why}}

{{If applicable, include a screenshot indicating an example or examples of what the PR is changing in the application}}

### Changelog

**New**

- {{new thing}}

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by ariellalgilmore** [comment]
small thing: when removing the custom caption the default caption does not show. 
In video-player stories the default caption will come back if the custom is removed: https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/6983/index.html?path=/story/components-video-player--default

Screen Shot 2021-09-01 at 2 02 28 PM

**Comment by IgnacioBecerra** [comment]
@guilhermelMoraes Looking good! One thing, it's probably just a storybook thing, but in React neither the title or the footer are being updated. Also for Web Components, it would look better if we can have all three knobs in the same space like in React instead of having the footer knob in a different tab.

**Review by ariellalgilmore — APPROVED** [review]
LGTM! thank you @guilhermelMoraes

**Review by annawen1 — CHANGES_REQUESTED** [review]
Noticed for `web-components` videoplayer w/ the lightbox media viewer, when I change the video caption in the knobs section and then click on the video, the caption hasn't changed from the default. Also noticed the default title in the lightbox media viewer is appearing with the timestamp.

https://user-images.githubusercontent.com/54281166/132381978-e8b18452-67db-483b-aa76-b4ec813d5b40.mp4

**Review by annawen1 — APPROVED** [review]

**Pull request merged**
