### PR TITLE
chore(project): upgrade yarn to v3

### PR DESCRIPTION
**Pull request by kennylam**
### Description

Upgrade to use latest version of Yarn.

### Changelog

**New**

- `cache` dir for zero-install

**Changed**

- upgrade Yarn to 3.3.1
- update package build scripts

**Removed**

- Yarn's offline-mirror folder

### CODE REVIEW

**Comment by annawen1** [comment]
@kennylam looks like Search with Typeahead - React Wrapper is busted:
https://ibmdotcom-web-components-react.s3-web.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/9948/index.html?path=/story/components-search-with-typeahead--default

**Review by ariellalgilmore — APPROVED** [review]
LGTM! tested locally too and didn't see any issues

**Review by IgnacioBecerra — APPROVED** [review]
LGTM, tested this locally and it's looking great! Thanks for this big upgrade @kennylam!

**Review by annawen1 — APPROVED** [review]
LGTM!

**Pull request merged**
