### PR TITLE
chore(lit): upgrading to v2

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#6361

### Description
This PR upgrades Carbon Web Components and IBM.com Web Components to Lit 2.5.0.

In the original effort for upgrading our Web Components, it was discovered that most of the errors came from Carbon Web Components not being upgraded to Lit v2 yet. This meant that CWC had to be upgraded first. Rewriting certain directive files and import names, the CWC upgrade was straightforward. Some styling issues occurred, though they mostly happened due to the new rendering flow in Lit v2.

In IBM.com Web Components, upgrading was slightly more complicated due to the various styling bugs and Storybook files that had to be edited for things to work properly. There are currently a few bugs from the resulting work, which I'll create issues for, mostly focus trapping issues.

### Changelog

**New**

- Added additional checks to correctly style markdown content in our copy components due to the new way Lit render works now
- Updated yarn offline

**Changed**

- Replaced the `lit-html` and `lit-element` imports with the new `lit` import directories
- Replaced `createRenderRoot` with  `shadowRootOptions`, in order to set `delegateFocus` to `true` in certain components
- Rewrote the `spread` directive function due to the breaking change of the `Directive` function in Lit v2

**Removed**

- `ifNonNull` global helper function is now redundant, now using Lit v2's `ifDefined` function which has the exact same functionality
-

### CODE REVIEW

**Comment by kennylam** [comment]
@IgnacioBecerra You should be targeting the `feat/cwc-v2` branch.

**Comment by abdonrd** [comment]
I think it would be good to use the latest version! Lit v2.6.0

https://github.com/lit/lit/releases/tag/lit%402.6.0

**Comment by IgnacioBecerra** [comment]
@abdonrd Oh, I'll update to that version! I was working with 2.5.0 before 2.6.0 was released, thankfully there doesn't seem to be any breaking changes!

**Comment by abdonrd** [comment]
> @abdonrd Oh, I'll update to that version! I was working with 2.5.0 before 2.6.0 was released, thankfully there doesn't seem to be any breaking changes!

Yeah, no breaking changes! Just SSR improvements.

**Comment by IgnacioBecerra** [comment]
I'll be merging this PR to our `feat/cwc-v2` branch and will be opening a new PR targeting our `main` branch to finalize the Lit v2 update.

**Comment by abdonrd** [comment]
@IgnacioBecerra new Lit update with no breaking changes!

https://github.com/lit/lit/releases/tag/lit%402.7.0

**Pull request merged**
