### PR TITLE
fix(cta-block): added padding on mobile breakpoint

### PR DESCRIPTION
**Pull request by andysherman2121**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6073

### Description

There was missing padding on mobile breakpoint causing the cta block to line up directly on the left of the page with 0px between

### CODE REVIEW

**Comment by shixiedesign** [comment]
Hi Andy! The CTA block's issue is fixed. But an unexpected changes I think in CTA section (thanks to Percy!): 

1. CTA section's `sm` shouldn't get affected. Currently seeing extra padding left added: 
image

That's all!

**Comment by andysherman2121** [comment]
> Hi Andy! The CTA block's issue is fixed. But an unexpected changes I think in CTA section (thanks to Percy!):
> 
> 1. CTA section's `sm` shouldn't get affected. Currently seeing extra padding left added:
>    image
> 
> That's all!

Ah good catch. I'll make the fix @shixiedesign

**Comment by andysherman2121** [comment]
@shixiedesign `cta block` and `cta section`'s padding's should both be good! Once Percy runs we'll see if it's all good

**Comment by andysherman2121** [comment]
@shixiedesign welll Percy didn't like that either! Trying something else

**Review by shixiedesign — APPROVED** [review]
Mobile padding is fixed! Notice we still have other breakpoints to worry about but can take them in another issue. Thanks!

**Review by annawen1 — APPROVED** [review]
LGTM!

**Pull request merged**
