### PR TITLE
chore(housekeeping): deprecate experimental components

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#6183

### Description
Removed components from our libraries and its respective flags, tests, and styles.

### Changelog

**Removed**

- `CalloutData`, `PromoBanner`, and `SimpleBanner` components

### CODE REVIEW

**Comment by jeffchew** [comment]
@IgnacioBecerra this might be simpler than this. Because all of these are experimental components, we can just delete these.

**Comment by IgnacioBecerra** [comment]
@jeffchew oohh even better 😈

**Review by jeffchew — DISMISSED** [review]
LGTM!

I see the NextJS and Web components test apps are failing, but I assume those downstream PRs that I approved already should take care of that.

**Comment by jeffchew** [comment]
@IgnacioBecerra can you remove the codesandbox example too?

image

**Comment by jeffchew** [comment]
@IgnacioBecerra oops, one more thing, can you remove the cypress e2e tests? 
image

**Review by annawen1 — APPROVED** [review]
woohoo looks good to me!

**Pull request merged**
