### PR TITLE
feat(button-group): update to v2

### LINKED ISSUE #10724: [Component] Button group

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

Closes #10724 

### Description

Updated Button group to use the v2 `button` which includes `cds-button`. Sets `isExpressive` as the default.

### Changelog

**Changed**

- updates button-group
- updates button with `isExpressive`
- updates storybook, examples, readme

### CODE REVIEW

**Review by IgnacioBecerra — APPROVED** [review]
LGTM, seems like there might be some more snapshot updating?

**Review by kennylam — APPROVED** [review]
LGTM!

**Review by oliviaflory — CHANGES_REQUESTED** [review]
@ariellalgilmore looks almost perfect!

Dark theme tokens aren't coming through quite right in button group for the tertiary button, but look good in CWC.
**Button group**
Screenshot 2023-09-15 at 4 39 04 PM

**CWC** [link to token docs on carbon website](https://carbondesignsystem.com/components/button/style#tertiary-button)
Screenshot 2023-09-15 at 4 39 54 PM

**Comment by ariellalgilmore** [comment]
@oliviaflory ooh good catch! just pushed a fix (storybook issue)

**Pull request merged**
