### PR TITLE
fix(cta): updated button to use expressive

### PR DESCRIPTION
**Pull request by NSDrowned**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6141

### Description

CTA text already using lg size, updated Button to use expressive

image

### CODE REVIEW

**Comment by oliviaflory** [comment]
@NSDrowned Web components looks great!

Seems like Percy caught some upstream changes in the Next JS build, any idea where that could be coming from? Card link text looks smaller and the label sizes look a little more spaced out than expected.

I also didn't see React in this PR, is that separate or would the changes for expressive button be seen in both?

Thanks!

**Comment by NSDrowned** [comment]
@oliviaflory forgot to mention that about react, yes, both are fixed: (React previews are not working I think):

image

image

Let me check what's up with NextJS

**Comment by NSDrowned** [comment]
@oliviaflory I checked the differences reported by Perci and they don't seem related to the button which was the only element updated in this PR.

**Review by oliviaflory — APPROVED** [review]
LGTM!

**Pull request merged**
