### PR TITLE
fix(number-input): fix incorrect controls border for readonly mode

### LINKED ISSUE #11390: [number-input]: incorrect `readOnly` styles
The `read only` control styling is a little off, the buttons keep the border strong, but we would expect the border to be the same as the border under the number. Please refer to the [number input style page](https://carbondesignsystem.com/components/number-input/style#interactive-states) for the correct token color 
Screenshot 2024-01-08 at 3 38 20 PM

_Originally posted by @oliviaflory in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11336#pullrequestreview-1809990176_

### PR DESCRIPTION
**Pull request by ko1ebayev**
### Related Ticket(s)

Closes #11390 

### Description

Fixed incorrect controls styles for readonly number input

### Changelog

**New**

- added some styles

### CODE REVIEW

**Comment by ko1ebayev** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by ko1ebayev** [comment]
recheck

**Comment by ko1ebayev** [comment]
Hey guys I want to work on carbon web components at IBM :)

**Review by emyarod — APPROVED** [review]
looks good to me!

**Pull request merged**
