### PR TITLE
Ccpa

### PR DESCRIPTION
**Pull request by sanjitbauli**
### Related Ticket(s)

[{{Provide url(s) to the related ticket(s) that this pull request addresses}}
](https://jsw.ibm.com/browse/URX-465)

### Description

Show California privacy statement based on user's location.

### CODE REVIEW

**Review by kennylam — APPROVED** [review]

**Comment by kennylam** [comment]
@sanjitbauli Looks like you need to update snapshots.

**Comment by sanjitbauli** [comment]
> @sanjitbauli Looks like you need to update snapshots.

can you help me by providing info about how to do that?

**Comment by kennylam** [comment]
Sure, you can see the docs [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/124afe8f267d3dae1752882480f762993e8d71cf/packages/react/docs/contributing-to-react.md#unit-test-coverage). Basically just run `yarn test:unit:updateSnapshot` in the React package.

**Review by kennylam — APPROVED** [review]
LGTM!

**Pull request merged**
