### PR TITLE
fix(integration-bundle): locking dependency versions for React package

### PR DESCRIPTION
**Pull request by jeffchew**
### Related Ticket(s)

Refs #5340 

### Description

In a recent failed integration bundle test, it was discovered that the
dependency package `@babel/runtime` was updated, which has a
sub-dependency that may have been causing the build failures. The fix
around this is to set the explicit version that is being used by the
React package.

UPDATE: It was discovered that the specific latest version of 
`@babel/preset-env` was causing issues where the version being passed 
was not the correct value, causing a breakage when passed into `semver`.
 This moves the resolution to one patch version back, which appears to 
 fix the issue. This is in the codesandbox examples used in the integration
bundle tests.

### Changelog

**Changed**

- React `package.json`
- csb examples package.json configurations

### CODE REVIEW

**Comment by jeffchew** [comment]
This PR is waiting on https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5350 before this can be merged in. The integration build test picked up an actual bug after the initial bug in the test was fixed, which #5350 is addressing.

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jeffchew!

**Review by kennylam — COMMENTED** [review]
@jeffchew Looks like the error is still happening :(

**Comment by jeffchew** [comment]
> @jeffchew Looks like the error is still happening.

Yeah, I noticed, and in a different place. I'm going to take a look if I need to adjust another test too.

**Comment by jeffchew** [comment]
Closed this in favor of https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5366. Thank you @kennylam !

**Pull request closed without merging**
