### PR TITLE
feat(content-section): combining components

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#8843

### Description
Content section had multiple different components that used different children components, though they look identical and practically the same. This PR combines the stories, adds documentation, and ensures the children components style properly.

### Changelog

**New**

- `dds-content-section` now supports `dds-carousel`, `dds-link-list`, and `dds-card-group`

### CODE REVIEW

**Comment by oliviaflory** [comment]
Really great to see this example and bringing in the `carousel`, `card group`, `link list` and `content block` 

A couple thoughts:
### Content section
This is probably a bug that we haven't caught before because we usually hide the description and CTA, but there should be no space between the Content section heading and the body copy. 
Screen Shot 2022-09-12 at 12 15 49 PM

### Spacing
1. Spacing between the Content section and the child varies throughout our specs 😭 design will probably need to figure out a consistent spacing here, but 16px doesn't feel like enough 
Screen Shot 2022-09-12 at 12 19 36 PM


2. Top padding: the `content-section-layout` top padding and the `content-section-leading` padding are being added together (48+16) = 64
Screen Shot 2022-09-12 at 12 22 13 PM
Screen Shot 2022-09-12 at 12 23 59 PM


3. Bottom padding varies depending on the child, design probably needs to consider if this is the desired outcome / if it matches existing specs
- 64px for link list, carousel, card group
- 160px with Content block

**Comment by IgnacioBecerra** [comment]
@oliviaflory 

I removed the spacing between the heading and the copy 👍 

1. I increased the bottom 16px padding to 32px, let me know what you think. 
2. Ensured the only padding taken into account be `content-section-layout` (48px)
3. Since Content block simple is the only different one, I changed it to match the other spacing to be 64px (only if its a child under content section, main component is not affected)

**Comment by ariellalgilmore** [comment]
> Hey @IgnacioBecerra I am not sure what might be causing this but it looks like they styling is getting removed in some way?
> 
> **Content block simple** (outside storybook) Screen Shot 2022-09-21 at 4 25 21 PM
> 
> **Card group** Screen Shot 2022-09-21 at 4 24 41 PM
> 
> **Carousel** Screen Shot 2022-09-21 at 4 26 49 PM

Hey @IgnacioBecerra this should be fixed with adding all the component imports to storybook (part of storybook6 updates)

**Comment by IgnacioBecerra** [comment]
@oliviaflory FYI the Storybooks are fixed now 👍

**Review by ariellalgilmore — APPROVED** [review]
Web components storybook looks great! can we align react wrapper too

**Comment by oliviaflory** [comment]
@IgnacioBecerra this looks great! 

My only concern is the link list alignment on mobile.

The link text and icons are flush against the browser, but I was expecting them align to the columns in the mobile breakpoint and not slide into the gutter.

If that's part of the default link list on it's own we can merge this PR and fix the bug in the link list to correct.
Screen Shot 2022-10-21 at 12 55 20 PM

Text and icons should align to pink dotted lines:

Screen Shot 2022-10-21 at 12 57 29 PM

**Comment by IgnacioBecerra** [comment]
@oliviaflory Fixed!

**Review by oliviaflory — APPROVED** [review]
LGTM 🎉  Thanks @IgnacioBecerra !!!

**Comment by RichKummer** [comment]
I have read the DCO document and I hereby sign the DCO.

**Pull request merged**
