### PR TITLE
feat(tabs-extended-with-media): make section heading optional

### PR DESCRIPTION
**Pull request by annawen1**
### Related Ticket(s)

Tabs Extended media containing a Title heading section #8691

### Description

Make the section heading of `tabs-extended-with-media` optional by adding a new `section-heading` property. `section-heading` will be disabled by default.

DESIGN PROPOSAL:
Screen Shot 2022-08-17 at 12 19 45 PM

STORYBOOK WITH CHANGES:
Screen Shot 2022-08-17 at 12 14 21 PM

Screen Shot 2022-08-17 at 12 14 13 PM

### Changelog

**New**

- `section-heading` property to `tabs-extended-with-media`.

### CODE REVIEW

**Comment by oliviaflory** [comment]
@annawen1 this looks great! 

Question for you:
I wasn't expecting the Content item horizontal to stretch when the Section heading is turned off and the tabs extend to the first column
**With section heading** image is ~5 columns wide
Screen Shot 2022-08-17 at 4 58 58 PM

**Without section heading** image is a little more than 6 columns wide
Screen Shot 2022-08-17 at 4 59 21 PM


I was expecting the tabs and content item horizontal to shift over to the first column, but maintain their width. 
**Example:**
Screen Shot 2022-08-17 at 5 05 52 PM


Is what I showed above possible or is that not how the tabs container(?) works and whatever is in the container will span the full width

**Comment by ariellalgilmore** [comment]
Looks good! Can we also adjust the react wrapper story to match? 

And just want to clarify, I forgot if we discussed setting the default to having the section heading there? or will we just need to remember to notify adopters that this could be almost a "breaking change" if there section heading disappears

**Comment by annawen1** [comment]
> Looks good! Can we also adjust the react wrapper story to match?
> 
> And just want to clarify, I forgot if we discussed setting the default to having the section heading there? or will we just need to remember to notify adopters that this could be almost a "breaking change" if there section heading disappears

yeah, I'll adjust the react wrapper story as well. 

Good point about the default setting of section heading - if I remember correctly, we wanted the section-heading to be off/not displayed by default?  But if we do want to avoid breaking changes, we should switch to having the section heading displayed on default instead - what do you think @oliviaflory @kennylam?

**Comment by oliviaflory** [comment]
I'm ok with it being a non breaking change, and keeping the section heading displayed as the default. I don't want angry people who expect it to be there and have it go away, I think AEM will be happy as long as it's optional. 

I will defer to @kennylam for final input though

**Comment by annawen1** [comment]
> @annawen1 this looks great!
> 
> Question for you: I wasn't expecting the Content item horizontal to stretch when the Section heading is turned off and the tabs extend to the first column  .....
> Is what I showed above possible or is that not how the tabs container(?) works and whatever is in the container will span the full width

@oliviaflory from what I can tell, yeah the tabs container spans full width of whatever the adopter drops it into - I've adjusted the storybook though to adjust the grid depending on whether the section heading is disabled or not so that the tabs container maintains the same width in the story

**Review by ariellalgilmore — APPROVED** [review]
LGTM! Just need to update snapshots again :D

**Review by kennylam — APPROVED** [review]
LGTM! Yes, I think it should be off by default otherwise it would be a breaking change.

**Pull request merged**
