### PR TITLE
fix(footer): various expressive fixes for language/locale selector

### PR DESCRIPTION
**Pull request by jeffchew**
### Related Ticket(s)

No related issue

### Description

This addresses a couple of issues found in PR #7012:

Issues addressed:

1. Language switcher (React & WC) need to be updated to use `lg`, so the field height is 48px
image

2. Locale switcher (WC)'s icon should be smaller, becoming 16px. Currently it stayed 20px while text label shrunk to 14px:
image

### Changelog

**Changed**

- language selector text style
- locale button icon in web components size

### CODE REVIEW

**Comment by shixiedesign** [comment]
Looks good! Only 1 issue. React, language selector on the Footer - micro: type size is fixed, but the alignment is still off. Appears to be too close to bottom: 
**Current:**
image

**Expecting**
image

**Comment by jeffchew** [comment]
@shixiedesign pushed a fix for the alignment!

**Review by IgnacioBecerra — APPROVED** [review]
LGTM, thanks @jeffchew!

**Review by shixiedesign — APPROVED** [review]
🎉

**Pull request merged**
