### PR TITLE
fix(filter-panel): fixed alignment of filter group items

### PR DESCRIPTION
**Pull request by jeffchew**
### Related Ticket(s)

No related issue

### Description

This addresses an issue with the alignment of the filter panel group items with the expressive theme disabled. 

This was mentioned in the PR #7012 .

7. **Filter panel**
Text and icon are not vertically centered within the accordions 

Screen Shot 2021-09-02 at 11 11 56 AM

### Changelog

**Changed**

- filter panel styles

### CODE REVIEW

**Comment by shixiedesign** [comment]
Almost! When text wrap though, the icon need to align to first line of text, same behavior as link lists. 

image

**Comment by jeffchew** [comment]
@shixiedesign pushed up a fix!

**Review by ariellalgilmore — APPROVED** [review]
LGTM!

**Comment by oliviaflory** [comment]
Awesome! Looks good to me @jeffchew, will let @shixiedesign take a look too

**Review by shixiedesign — APPROVED** [review]
Awesome! Thanks!

**Pull request merged**
