### PR TITLE
[Filter panel] Fix the checked attribute <dds-filter-panel-checkbox> element

### PR DESCRIPTION
**Pull request by m4olivei**
### Related Ticket(s)

Closes https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10692
https://jsw.ibm.com/browse/ADCMS-3819

### Description

Work out the initial filter panel selection when the fitler panel components are mounted with some items being selected.

### Changelog

**Changed**

- `<dds-filter-panel-checkbox>` components initiated as `checked` will reflect in the item count and precence of a clear button.

### CODE REVIEW

**Comment by m4olivei** [comment]
Note that the one Percy snapshot change with Filter Panel is expected as I've updated the Story to have two items checked by default as a way to verify the bug fix.

**Review by kennylam — APPROVED** [review]
LGTM thanks @m4olivei!

**Comment by kennylam** [comment]
Done!

**Comment by m4olivei** [comment]
Thanks @kennylam !

**Pull request merged**
