### PR TITLE
fix(image-with-caption): update caption and storybook

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#6186 
#6169 

### Description

Content item horizontal change eyebrow to use `label-02`
Image with caption change caption to use `caption-02`
Update storybook caption to `This is a caption`

### CODE REVIEW

**Review by kennylam — DISMISSED** [review]
LGTM thanks @ariellalgilmore!

**Comment by oliviaflory** [comment]
Waiting to approve Web components build until after branch updates go through to see if it will work out Percy issues (thanks @ariellalgilmore). 

But everything looks great otherwise!

**Comment by ariellalgilmore** [comment]
> Waiting to approve Web components build until after branch updates go through to see if it will work out Percy issues (thanks @ariellalgilmore).
> 
> But everything looks great otherwise!

@jeffchew There are some weird Percy diffs happening in web components, but not actually showing in the storybook builds. Are these okay to still approve?

**Comment by kennylam** [comment]
> @jeffchew There are some weird Percy diffs happening in web components, but not actually showing in the storybook builds. Are these okay to still approve?

@ariellalgilmore @oliviaflory  Percy diffs look fine to me. It seems recently text size/scale has been altered a tiny bit, resulting in these differences. Overall they are fine, I think.

**Comment by oliviaflory** [comment]
> > @jeffchew There are some weird Percy diffs happening in web components, but not actually showing in the storybook builds. Are these okay to still approve?
> 
> @ariellalgilmore @oliviaflory Percy diffs look fine to me. It seems recently text size/scale has been altered a tiny bit, resulting in these differences. Overall they are fine, I think.

@kennylam Right, it is mostly text which is expected and looks correct. 

However, there are a few things off at the bottom of a few snap shots:

1. Cutting off the Card link in `Content block media` and some others
Screen Shot 2021-07-08 at 10 46 38 AM

2. Not capturing the Card link in `Content block mixed: default` at all, which will be a little weird if/when it does render next time we push an update as a change within a different PR

**Percy**
Screen Shot 2021-07-08 at 10 45 40 AM

**Storybook**
Screen Shot 2021-07-08 at 10 46 08 AM


I don't mind approving for now, I made comments on all the snapshots with errors, and we will see what the Percy team says after Jeff talks to them.

**Review by kennylam — APPROVED** [review]
LGTM thanks @ariellalgilmore!

**Review by oliviaflory — APPROVED** [review]
Thanks for conquering the robots @ariellalgilmore 💪  Looks good!

**Pull request merged**
