### PR TITLE
fix(feature-card): resolve styling issues

### PR DESCRIPTION
**Pull request by emyarod**
### Related Ticket(s)

#6424

### Description

* Web component: arrow size between `lg--xlg` should be 24px

image

* hover transition should be as expected across the card

* image overlay should also darken on light themes and lighten on dark themes now

reviewers should confirm that the removed styles in the web component stylesheet do not cause a regression

### CODE REVIEW

**Review by jeffchew — APPROVED** [review]
LGTM!

**Comment by shixiedesign** [comment]
1. CTA - Feature, WC, is showing the arrow using a wrong color. Is this outside the scope of this PR? 
image

2. Hover state animation should be in scope since it's captured in the bug ticket. I'm still seeing the "flicker" on hover. Happy to jump on a call to explain this. It's subtle but hard to unsee. 
Sep-16-2021 10-19-00

**Comment by emyarod** [comment]
@shixiedesign issues should all be resolved on feature card now!

for the Feature CTA, I updated the icon color and size, and the hover interaction should also be fixed as well. but if the icon alignment issue also applies, I think I should separate that since it is affected by Card/CTA base styles whereas the standalone feature card isn't (and should be visually correct)

**Review by shixiedesign — APPROVED** [review]
Fantastic! Looks great. I realize these issues are also present in Feature card - large. I will make a new issue though. Thanks for the fix!

**Comment by shixiedesign** [comment]
@jeffchew @emyarod Percy results are looking weird, all changed snapshots are "new snapshots". Any clue if Percy is having a bad day?

**Comment by jeffchew** [comment]
> @jeffchew @emyarod Percy results are looking weird, all changed snapshots are "new snapshots". Any clue if Percy is having a bad day?
> image

I was just looking at this too. The snapshot names changed from pipes to forward slashes for some reason...

**Pull request merged**
