### PR TITLE
chore(deps): upgrade to Percy Storybook v4 [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by jeffchew**
### Related Ticket(s)

No related issue

### Description

This is another attempt to upgrade to Percy Storybook v4.

~~This is currently blocked, as Percy CLI is not rendering properly with web components. There is a possible feature coming through as a config, being tracked here:
https://github.com/percy/cli/issues/280~~

Issues related to Percy Storybook SDK, currently tracked in the discussion here:
https://github.com/percy/percy-storybook/discussions/566

### Changelog

**Changed**

- Upgrade `@percy` dependencies to latest versions
- Suppress `percy skip` for `FeatureSection` and `TabsExtended` in React

### CODE REVIEW

**Review by kennylam — APPROVED** [review]
LGTM thanks @jeffchew!

**Comment by jeffchew** [comment]
Updated to beta 76. Still a lot of missing snapshots:

image

**Comment by jeffchew** [comment]
Closing this PR as it's pretty out of sync with `main`. Will open a new PR.

**Comment by jeffchew** [comment]
New PR here: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9068

**Pull request closed without merging**
