### PR TITLE
feat(video-player): add alt prop in VideoPlayer component

### PR DESCRIPTION
**Pull request by ViniciusdSC**
### Description

VideoPlayer component will be able to have a different alt instead of using title for that

### Changelog

**New**

- alt prop in VideoPlayer component

### CODE REVIEW

**Comment by ViniciusdSC** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by jeffchew** [comment]
recheck

**Comment by jeffchew** [comment]
@ViniciusdSC thank you for the contribution! 

Could you run `yarn test:unit:updateSnapshot` on your project in the `react` package folder and push up the changes?

**Comment by ViniciusdSC** [comment]
@jeffchew done

**Review by IgnacioBecerra — APPROVED** [review]
@ViniciusdSC Looks good to me, thanks for your contribution!

**Comment by kennylam** [comment]
recheck

**Comment by vinicius** [comment]
Please, remove my e-mail from this thread. I'm not the right Vinicius.

Vinicius Pinheiro

Computer Science PhD

Software Engineer
+55 21 980567057 <+55+21+980567057>
***@***.***
Rio de Janeiro - RJ, Brazil
[image: linkedin] <https://www.linkedin.com/in/vgamapinheiro/>

**Pull request merged**
