### PR TITLE
fix(callout): changing background-color token

### PR DESCRIPTION
**Pull request by guilhermelMoraes**
### Related Ticket(s)

[Call out] should use inverse tokens #5386

### Description

changing background-color token to `$inverse-02` as per the visual specs.

### CODE REVIEW

**Review by photodow — CHANGES_REQUESTED** [review]
Thank you! Some much needed TLC.

1. Do you plan to address the downstream effects in a separate issue, or would you like feedback on some of them here? For example, the copy and links and such don't have inverse tokens.

image

2. tangentially related, the knobs don't seem to be working in `callout with media`, and theming is not available.

**Comment by guilhermelMoraes** [comment]
@photodow feel free to provide all the feedback here, please.

**Comment by oliviaflory** [comment]
@guilhermelMoraes thanks, background color looks good! 

As James mentioned the link in Call out quote should be $inverse-link, and the text should use $inverse-01 in Call out quote and callout with media. 
I may have not been explicit enough in the issue #5386 calling out the text and links as well.

**Comment by oliviaflory** [comment]
@guilhermelMoraes hover color looks great! 👍 

I see a double focus state on the Call out with media, and can this be `$inverse-focus-ui` please?

Screen Shot 2021-03-22 at 3 24 15 PM

**Comment by jeffchew** [comment]
Screen Shot 2021-03-22 at 5 28 36 PM

@guilhermelMoraes I think was mentioned above, looks like Percy picked this up in Callout Quote.

I'm hoping to also get more e2e percy tests in place to capture more theme variations.

**Review by shixiedesign — APPROVED** [review]
Looks like all the things Olivia and James picked out are fixed! 💪 Thank you Gui!

**Comment by jeffchew** [comment]
Hey @guilhermelMoraes , seeing it darker here too for some reason:

image

**Comment by guilhermelMoraes** [comment]
@jeffchew updated! Now it should be ready to go.

**Review by photodow — CHANGES_REQUESTED** [review]
- [ ] Need to update the active state real quick.

image

- [x] I'm not sure if this is related or not, but for some reason, the link with icon is changing type size on a theme change... Was it doing that before?

Mar-24-2021 15-56-15

- [ ] Itsy bitsy thing, but can we lower case that `Icon` in the text CTA?

**Review by photodow — CHANGES_REQUESTED** [review]
Hey @guilhermelMoraes sorry there is an issue with hover on the dark themes on the link. I don't think that passes accessibility, and appears to be overridden by an RGB value. Do you see this too?

image

- [ ] Just looked in dotcome shell story, and I'm seeing some issues with callout with media in there. Were we able to get the inverse tokens for that one applied?

image

**Review by shixiedesign — COMMENTED** [review]
Hey James catches the best bugs - yeah I was able to verify his comments above: 
1. Hover of the Link in inverse is unaccessible. Unfortunately there's no token in Carbon for it. In dark themes, Link on hover should get `$blue-40`
2. @guilhermelMoraes is callout media's bug out of scope of this PR? If so that's cool, we should make a new bug ticket for it. Looks like the body copy in Callout media is not using token. I don't know how it's build so lemme know if new issue is needed. 

Thanks!

**Comment by jeffchew** [comment]
Just double-checking, the background color for g100 is supposed to be white now, correct?

image

Also the link size still looks like it's smaller than it should be according to Percy.

**Comment by shixiedesign** [comment]
@jeffchew @guilhermelMoraes 
- the background color change on Dark theme is correct ✅ 
- Link size change is not though. We have a [previous bug](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/5647) of g100 theme affecting link type sizes in general, so I'm okay with this bug being fixed in a separate PR.

**Comment by guilhermelMoraes** [comment]
@shixiedesign
1. updated;
2. that's a good question. The theming button is disabled for the [Callout with Media story] (http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-callout-with-media--default). Is this a design decision?

**Comment by shixiedesign** [comment]
Thanks Gui for adding the theme tab to `Callout with media` so I could QA the color token used there. It did expose a new issue #5676. Would be done as a separate PR. Thank you! Looks good to me 👍

**Pull request merged**
