### PR TITLE
fix(localemodal): disable region button when no countries present

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

#7831 

### Description

Fixes a bug in `LocaleModal` where the region button is still clickable even when no countries of that region are available.

**Note**: `Europe` has been disabled for testing purposes.

Dec-08-2021 16-38-07

### Changelog

**Changed**

- update event handler for region buttons with no countries/languages available for localization
- sort country list in `preview.html` by region

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me! the empty region is disabled properly now

**Comment by jeffchew** [comment]
@kennylam hey for web components, the tile doesn't look disabled:

image

How it looks in React:

image

**Review by emyarod — COMMENTED** [review]
after rechecking on narrower viewports, it looks like there's a little weird hover effect on the disabled tile in web components

https://user-images.githubusercontent.com/8265238/145442736-d9d4af62-c592-474d-a044-18951553b208.mov

**Comment by kennylam** [comment]
@jeffchew @emyarod Both of those are existing issues that should probably be addressed separately:

- the `disabled` styles for web components `card-link` do not match the React (and Carbon) version
- the disabled icon shifting position on hover can be seen [here](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-locale-modal--default)

I'll open tickets for both of these issues.

**Review by emyarod — APPROVED** [review]
sounds good! then I think we can merge after restoring the removed locales for testing

**Comment by kennylam** [comment]
> sounds good! then I think we can merge after restoring the removed locales for testing

I left Europe disabled to match the web components version made in [this PR](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/7302#pullrequestreview-769307374). Should we enable them again?

**Comment by jeffchew** [comment]
> > sounds good! then I think we can merge after restoring the removed locales for testing
> 
> I left Europe disabled to match the web components version made in [this PR](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/7302#pullrequestreview-769307374). Should we enable them again?

No let's keep them both to match where Europe is disabled.

**Pull request merged**
