### PR TITLE
fix(footer v1):v1 title was not showing in 672 breakpoint

### PR DESCRIPTION
**Pull request by bruno-amorim**
### Related Ticket(s)

[ADCMS-4397](https://jsw.ibm.com/browse/ADCMS-4397)

### Description

As per another [PR submitted](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11396) for this fix, I'm also submitting this one targeting v1.

Titles for the Footer Group Navs were not being displayed specifically in 672px breakpoint.

### CODE REVIEW

**Comment by jkaeser** [comment]
Closing and re-opening in the hopes of getting the deploy previews to build 🤞

**Review by jkaeser — APPROVED** [review]
Looks great to me! Thanks, @bruno-amorim 👏

**Comment by jkaeser** [comment]
Needs snapshot updates, though. You can get those by running `yarn test:unit:updateSnapshot` from the web-components package root.

**Comment by bruno-amorim** [comment]
Hi @jkaeser 

I have updated the snapshots, would you please give it another look?

Thanks a lot!

**Review by jkaeser — COMMENTED** [review]
@bruno-amorim Snapshot updates look good to me, but I'm seeing failures in the ci-check. Can you take a look at those?

**Review by m4olivei — APPROVED** [review]
Latest commit should fix the unit test 🤞 . Otherwise LGTM.

**Pull request merged**
