### PR TITLE
fix: text line length change

### PR DESCRIPTION
**Pull request by NSDrowned**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5508

### Description

Changed `content-width` mixin to 100% of container - 32px ($layout-03). Added same width calculation to quote (which doesn't use the same mixin because of the width limitation). 

- [x] content item
- [x] content group
- [x] content block
- [x] content section 
- [x] card
- [x] quote

### CODE REVIEW

**Comment by NSDrowned** [comment]
@shixiedesign let me know if this is what you asked for since modifying this mixin changes a lot of components. If not, I'll add overrides just for the components mentioned in the original issue and leave the mixin intact.

**Comment by shixiedesign** [comment]
The text line length change should not affect `sm`. On `sm` breakpoint, we are still expecting 100% container width for text width: 
image

**Comment by NSDrowned** [comment]
@shixiedesign, you're right, let me fix that.

**Comment by shixiedesign** [comment]
Noticing a small thing - the rule inside Quote seems to have gotten shorter. Don't think this is expected. 

image

**Review by kennylam — APPROVED** [review]
Looks good thanks @NSDrowned!

**Review by shixiedesign — APPROVED** [review]
Thank you! Looking good 🌮

**Pull request merged**
