### PR TITLE
fix(back-to-top): update container tokens

### PR DESCRIPTION
**Pull request by emyarod**
### Related Ticket(s)

#6191
#6122

### Description

This PR bumps the container size tokens in the Back to top component up to account for changes on the `feat/expressive-sunset` branch (removal of the [`.bx--btn--icon-only` styles](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/feat/expressive-sunset/packages/styles/scss/themes/expressive/components/_button.scss#L57) import). The Back to top component extended from the `feat/expressive-sunset` branch should now render the icon properly

image

### Changelog

**Changed**

- Back to top button size tokens

### CODE REVIEW

**Comment by emyarod** [comment]
ready for review, just want to make sure it handles the expressive sunset situation correctly!

**Review by shixiedesign — APPROVED** [review]
LGTM! Thank you!

**Comment by shixiedesign** [comment]
Let's wait for a dev approval as well, FYI @emyarod. Looks good to me!

**Review by jeffchew — APPROVED** [review]
Thank you @emyarod !

**Pull request merged**
