### PR TITLE
fix(cta-block): use correct spacing

### LINKED ISSUE #8143: [CTA section]: Updates to spacing
**Engineering info:**  
- Innovation Team engineer: @jkaeser 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2460
- DPO consulting engineer: N/A

-----

### Description

The Web Components version of the CTA section needs a few updates to spacing based on the latest round of designs. 

1. `CTA section` - spacing between description and CTAs should be 32px on `sm` and `md` breakpoints. Currently this is only correct on `lg` and above - `sm` and `md` have more spacing than the 32px.

**md breakpoint in WC Storybook**
md-672-spacing

**md breakpoint in Design Specs**
Design-specs--md-spacing

2. When there are more than one row of content items in `CTA section - with content items`, there should be a horizontal rule between each row after the first row - this is needed for `max` through `md` breakpoints. See [design specs](https://ibm.ent.box.com/folder/109648616047?s=yz1uixuxjf7lge5yvrup3yb3owj70071). On `sm`, there is a horizontal rule between each content item.

**WC Storybook**
WC-Storybook--CTA-section

**Horizontal rule in design specs**
Design-specs--CTA-section

3. Had trouble testing this in WC storybook - when the CTA section is in `sm` breakpoint and has only a Headline and no description or CTA, there should be 32px padding between the Headline and the first content item instead of the normal 64px spacing. Can we confirm that this is the case and update if needed?

**sm breakpoint in design specs**
Mobile-Design-sepcs--CTA-section

 

### Component(s) impacted

CTA Section

### Browser

Chrome

### Carbon for IBM.com version

v1.14.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

C4IBM.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/master/packages/web-components/examples/codesandbox/components/cta-section

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by jkaeser**
### Related Ticket(s)

Resolves #8143

### Description

Matches spacing values used between `DDSCTABlock` sub-elements to the values stipulated in the designs.

### Changelog

**New**

- Adds two knobs to CTA Section stories to toggle display of copy text and CTAs.

**Changed**

- Refactors spacing between `DDSCTABlock` slotted content to better match designs.

### Review

Visit each story and verify the spacing between component elements matches the designs across viewport sizes. Be sure to test each variation of the stories by toggling the **Show Text** and **Show CTA** knobs.

1. With content items: https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/8900/index.html?path=/story/components-cta-section--with-content-items
2. With link list: https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/8900/index.html?path=/story/components-cta-section--with-link-list

### CODE REVIEW

**Comment by RichKummer** [comment]
@jkaeser This is great, and thanks for adding the Storybook options! 
One SB nitpick - could we change the label of the Storybook controls? I think these should be consistent:
* `Show Text` should be `Add Copy`
* `Show CTA` should be `Add CTA`

I noticed another detail - hoping we can fix it with this ticket, but if you need me to separate this into a new ticket let me know:
1. The specs show `32px` vertical spacing between the bottom of the Content item and the horizontal rule, and then `32px` from the bottom of the rule to the next Content item. Right now, the build is showing `64px` for both. `32px` should be the spacing for all breakpoints.

**Spec**
Screen Shot 2022-05-25 at 12 01 23 PM

**Current**
Screen Shot 2022-05-25 at 11 55 23 AM

**Comment by jkaeser** [comment]
> @jkaeser This is great, and thanks for adding the Storybook options! One SB nitpick - could we change the label of the Storybook controls?
> The specs show `32px` vertical spacing between the bottom of the Content item and the horizontal rule, and then `32px` from the bottom of the rule to the next Content item.

@RichKummer Those issues are fixed. Let me know if you catch anything else!

**Comment by RichKummer** [comment]
@jkaeser Took another look - the spacing issue is fixed for the Content item around the rule. Percy caught a slight bump in the space between the Content item text and CTA.

The new build on the right has extra padding - it should be minimum `24px` padding between the copy and the CTA for the longest version of Content item in the set , but for some reason it's bumped up - including on the Storybook page.
Screen Shot 2022-05-25 at 4 22 25 PM

Screen Shot 2022-05-25 at 4 21 50 PM



**Specs**
Screen Shot 2022-05-25 at 4 26 37 PM

**Review by kennylam — APPROVED** [review]
LGTM thanks @jkaeser! Just need design approval.

**Review by RichKummer — APPROVED** [review]
Thanks for making the changes @jkaeser ! LGTM 🥳

**Pull request merged**
