### PR TITLE
fix(content-item-horizontal-thumbnail): adjust mobile spacing

### PR DESCRIPTION
**Pull request by proeung**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7765

### Description

- This PR fixes the spacing issue seen within `Content item horizontal – with thumbnail` on small/mobile breakpoints.

### Changelog

**Changed**

- Spacing between the CTA text links and media should be 32px (see attached).

Screen Shot 2022-01-18 at 4 11 41 PM

### CODE REVIEW

**Review by ariellalgilmore — COMMENTED** [review]
Looks like the thumbnail alignment is slightly off now in md breakpoints and above

Screen Shot 2022-01-19 at 7 06 51 AM

**Comment by proeung** [comment]
@ariellalgilmore Thanks for the review! I just pushed up a fix that should address the alignment issue noted above. You shouldn't see a visual diff on the larger bps.

**Review by ariellalgilmore — APPROVED** [review]
LGTM!

**Review by RichKummer — APPROVED** [review]
LGTM!

**Pull request merged**
