### PR TITLE
fix(same-height): using same height method for card group & cta section

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#5398

### Description
The current CSS grid implementation for both CardGroup and CTA Section work are able to resize properly dynamically depending on the copy content, however it does not work if the heading is longer than a single line. After some discussion, a CSS-only way might actually not be achievable, thus this PR addresses that by bringing back the `sameHeight` utility function for both `CardGroup` and `CTASection`, only targeting the item headings. 

### Changelog

**Changed**

- re-applying the `sameHeight` utility function for `CardGroup` and `CTASection` targeting item headings

### CODE REVIEW

**Review by shixiedesign — COMMENTED** [review]
Ooof I saw this when I tried to add extra content to heading of first card. 
**Current**
image

**Expecting**
image

**Comment by IgnacioBecerra** [comment]
@shixiedesign When using the same height utility it actually takes the height of the longest heading upon rendering, so when using inspect element it wouldn't actually change. I added a card with a longer heading to the Story:

Screen Shot 2021-03-24 at 6 49 00 AM

 I hadn't added the variation in this PR since @NSDrowned was working on doing that in his PR (#5532), but I'll add it here since it fits the scope.

**Comment by photodow** [comment]
- [ ] Does this work with the `eyebrow`?

image

Looks like the answer is no...
image

There may also be an issue here though that they don't have matching content.

- [ ] And CTA?
image

I'm trying to think if `copy` is needed too... My brain isn't workingo n this one, but I think originally they all were supposed to be.

- [ ] Shouldn't these update on screen resize? I'm not seeing that happen.

**Comment by photodow** [comment]
Have you talked to @Praveen-sr about this update to `CTA Section`? I know she's been working that component over at #5530

**Comment by IgnacioBecerra** [comment]
@photodow Updated to include eyebrow and CTA footer + w/resize. I'm not sure if copy is needed since the heading/footer would ensure copy stays the same throughout. 

Examples: 
Screen Shot 2021-03-25 at 2 56 43 PM

Screen Shot 2021-03-25 at 2 57 07 PM

**Review by photodow — CHANGES_REQUESTED** [review]
@IgnacioBecerra looking a lot better.


- [ ] Any idea when I add content to the `heading` in the content items for `CTA section` that the `copy` expands too?

image

- [ ] Also looking at the smallest breakpoint the content is overflowing. At this point I don't think it needs to be the same size so the content should just flow normally.

image

- [ ] I think we should also apply this to react as well? It doesn't look like it's working there right now.

image

**Comment by IgnacioBecerra** [comment]
@photodow I believe the reason for that weird issue with heading increasing height copy might have to do with the current css grid setup. We weren't able to find a workaround for that, so I'm adding copy to the CTA Section's sameHeight utility. Also added functionality to React, though working on fixing the CI Checks.

**Review by photodow — CHANGES_REQUESTED** [review]
It looks like I'm still seeing the second point above on the card group still. I just loaded it, and resized the browser down and now cards has some extra spacing. It should just be the old natural content lead spacing.

image

**Comment by shixiedesign** [comment]
Hey @IgnacioBecerra, awesome to see it working! Thanks for the random content in there to demo the util. I'll leave James to take a final look later next week but it looks good to me! 👍 
I'm seeing the tons of Percy diffs but I know it's probably because we are working on so many things this sprint. They should be all expected...but yeah hard to be sure. Lemme know if you've got a better way to look through them.

**Comment by jeffchew** [comment]
@IgnacioBecerra any update on this?

**Review by photodow — APPROVED** [review]
@jeffchew I've been talking to Ignacio offline about this around the issue mentioned above. I think we decided to create a new ticket around that since it appears to be based on some sort of aspect ratio is applied. I'll create that ticket (#5710), and go ahead and approve this for now.

**Pull request merged**
