### PR TITLE
fix(Masthead): regular dropdown menu visible outside of masthead nav bar

### PR DESCRIPTION
**Pull request by annawen1**
### Related Ticket(s)

[Masthead]: Dropdown menu items are appearing on scroll within the masthead nav bar #4504

### Description

The dropdown menu was appearing within the nav bar and user had to scroll within the nav bar to see the menu items. Setting the overflow to visible allows the dropdown to be visible outside of the nav bar

Screen Shot 2020-11-17 at 4 38 16 PM

### Changelog

**Changed**

- removed the `hasMegapanel` field from one of the nav links in the masthead story data file so this fix is easily testable in storybook (be sure to set the `navigation knob` to `custom` in order to test)
- set `bx--header__search` and `bx--header__nav-container` div `overflow-x` to `visible` so the dropdown is visible outside of the nav bar
- set the z-index and background colors for the IBM logo, search, and profile buttons so it doesn't clash with the overflowing nav items

**Removed**

- web-components specific styles for when the masthead only supported the regular dropdown, the code is now in the corresponding stylesheets

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @annawen1 for the fix!

**Comment by asudoh** [comment]
Update: Do you want to check/update the snapshot?

**Review by ariellalgilmore — CHANGES_REQUESTED** [review]
Screen Shot 2020-11-18 at 6 58 20 AM

Screen Shot 2020-11-18 at 7 00 05 AM

looks like this fix also needs to be applied to the L1 name and the platform for L0

**Review by ariellalgilmore — APPROVED** [review]
Looks great @annawen1! Thanks so much!

**Pull request merged**
