### PR TITLE
[Cloud-Masthead]: Implement lazy load and DOM pruning from masthead v2 on cloud masthead

### LINKED ISSUE #10056: [Cloud-Masthead]: Implement the lazy load approach for the mega-menu on Cloud pages
**Engineering info:**  
- Innovation Team engineer: @m4olivei 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/ADCMS-2964
- DPO consulting engineer: @IgnacioBecerra 

-----

### Description

This is impacting many Cloud pages. So, it is recommended to implement the lazy load approach for the mega-menu on all IBM pages to enable the services provided by Decibel Insight, now, known as Medallia Digital Experience Analytics (DXA). This has been documented here https://w3.ibm.com/w3publisher/digital-behavior-data-management/blog/661ab090-9244-11ed-ae79-25d164e27ac2 and has been previously reported in GiftHub.
Anything done in the megamenu is independent of the pages and should not affect publishing. From my understanding this is needed at just one Cloud page to flow on all others.

### Component(s) impacted

All ibm.com/cloud pages

### Browser

Microsoft Edge

### Carbon for IBM.com version

-

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

-

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

-

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by m4olivei**
### Related Ticket(s)

Resolves #10056

### Description

Adds the performance enhancements that were implemented for Masthead v2 to the Cloud Masthead, specifically:

* https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9595
* https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9602

The first change (quoting @andy-blum [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9595)): Initializes the masthead-container with either the `left-nav` or the `top-nav` depending on the width of the viewport. Additionally swaps one for the other when the viewport crosses the 960px boundary. This should effectively cut the number of masthead nodes in half with very little other changes.

The second change (again quoting @andy-blum [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9602)): Currently the Masthead loads both the SideNav and Megamenu components at the same time, even if they haven't been opened yet. This causes the amount of nodes to increase considerably right away. In order to mitigate this, a fast solution is to dynamically load the required components *only* when the user has interacted with the menus.

This means that the mobile version wouldn't be loading the Megamenu, and the desktop wouldn't load SideNav until/if required. 

Another optimization that was done ensures that the Megamenu component wouldn't get loaded into the DOM unless a user has clicked on the menu beforehand. Then and only then, the megamenu would be loaded in. Once the menu is closed, the component gets removed from the DOM to ensure the total node count doesn't shoot up.

Note that, due to the structure of the Masthead and Cloud Masthead, these changes are not entirely isolated to the Cloud Masthead alone. Specifically, the Masthead is responsible for mega menu rendering, thus the Masthead implements lazy loading of the megamenu which then is inherited by the Cloud Masthead.

### Testing

Testing should cover regression tests on both the Masthead and Cloud Masthead components.

### Changelog

**New**

- Adds support for dynamic imports
- Utliizes dynamic imports to lazy load left nav and megamenu scripts that are only necessary when the user expands the menu.
- Only renders left nav custom elements when we're at the mobile break
- Only renders megamenu custom elements when user expands the menu

### CODE REVIEW

**Comment by andy-blum** [comment]
I think this PR needs to be targeted to `feat/masthead-v2`. Currently the `dds-masthead` component doesn't implement any of the lazy loading/dom-pruning

**Comment by m4olivei** [comment]
> I think this PR needs to be targeted to feat/masthead-v2. Currently the dds-masthead component doesn't implement any of the lazy loading/dom-pruning

My understanding was that the Cloud team is not using v2 yet, so they needed this implementation on `main`, to be released with the regular C4IBM release.

**Comment by proeung** [comment]
@m4olivei is correct. The current `/cloud` web segment on production is currently adopting v1 of the masthead code coming from the `main` branch and we're not looking to switch to v2 at the moment (pending approval from Cloud Stakeholders regarding v2 design updates). This PR will improve the performance of the existing Global and Cloud Masthead v1.

We might see some merge conflicts, once we update our `feat/masthead-v2` with `main`.

Screen Shot 2023-02-24 at 10 52 50 AM

-------

@kennylam @annawen1 Can help take a look at this PR?

**Review by kennylam — APPROVED** [review]
LGTM thanks @m4olivei!

**Pull request merged**
