### PR TITLE
feat(storybook): updated 2 component stories to v7

### LINKED ISSUE #11356: [carbon-web-components]: search select Storybook 7 update

### PR DESCRIPTION
**Pull request by m4olivei**
### Related Ticket(s)

Closes #11356

### Description

Adjustments to search and select component stories to be compatible with Storybook v7.

### Changelog

**Changed**

- Updated search Storybook stories for Storybook v7
- Updated select Storybook stories for Storybook v7

### CODE REVIEW

**Comment by m4olivei** [comment]
Hum, the `<cds-select>` element isn't rendering here. Error in console:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'selectedIndex')
    at get selectedIndex (select-qPaB998O.js:19:496)
    at d.get [as selectedIndex] (lit-element-XNu4h86T.js:9:1284)
    at d.performUpdate (lit-element-XNu4h86T.js:9:5121)
    at d.scheduleUpdate (lit-element-XNu4h86T.js:9:4791)
    at d._$EP (lit-element-XNu4h86T.js:9:4699)
```

I don't get this locally. Will have to do some debugging.

Back to draft.

**Comment by m4olivei** [comment]
I trimmed back the import statements for the story in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11362/commits/c8d76c6d3cb8807ae6b1718ec5362ee92393838e. That triggered the same error, which I was able to debug. Lit's lifecycle code was calling into the `selectedIndex` getter early, before `this._selectNode` (decorated with `@query`) had been populated. Fixed in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11362/commits/820b111fe07a60c470a26657aed13d29fe41f6ac.

**Review by IgnacioBecerra — APPROVED** [review]
LGTM!

**Review by kennylam — COMMENTED** [review]
Looks like `select` has `readOnly` twice. Otherwise looks good!

image

**Comment by m4olivei** [comment]
> Looks like select has readOnly twice. Otherwise looks good!

Nice catch. Fixed!

**Pull request merged**
