### PR TITLE
fix(number-input): ensured icon and container fit within parent properly

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#5598

### Description
With the newest Carbon upgrades, the FormItem/NumberInput components were slightly reworked, which clashed with our current dimension styles for both the button and svg. This update aligns our Expressive theme and the new component updates.

### Changelog

**Changed**

- made the number control buttons fit their container
- increased the svg's dimensions to 20px

### CODE REVIEW

**Comment by oliviaflory** [comment]
Hey @IgnacioBecerra I was actually expecting that in the upgrade we would be adopting the new version of the Number input from Carbon to align with the `-` and `+` symbols. It looks like we've reverted to the previous design with the carets?

Screen Shot 2021-04-08 at 10 53 17 AM

**Comment by IgnacioBecerra** [comment]
@oliviaflory Hm, I see the `-` and `+` symbols when working on this locally, I'll take a look as to why this might be happening on the preview.

**Comment by IgnacioBecerra** [comment]
@oliviaflory There was a dependency bumped down in an upgrade (that contained the new icons) which made the preview use the previous icons. After talking to Jeff, we pushed a change for that and the preview now contains the correct, updated icons. 👍

**Review by oliviaflory — APPROVED** [review]
Looks good to me, thanks @IgnacioBecerra 🎉 

Guessing I'm having trouble logging into Percy to approve changes because of the migration Jeff mentioned 😞

**Review by shixiedesign — APPROVED** [review]
👍 Percy diffs look good too

**Review by jeffchew — APPROVED** [review]
LGTM!

**Pull request merged**
