### PR TITLE
feat(content-group): expose content-group in storybook

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#6701 

### Description

Expose content group for both react and web components

FYI: the copy knob in web components will not update, so I did not include in the knobs

### Changelog

**New**

- stories, codesandbox

**Changed**

- updated styles to match specs

### CODE REVIEW

**Review by photodow — APPROVED** [review]
Sorry, thought I already approved this. My bad! 

There are definitely some pre-existing issues like spacing, and even maybe some issues with its dependencies like `CTA` that we'll still need to circle back on. As far as exposing it goes it looks great. I'm loving these add children options!

**Comment by jeffchew** [comment]
Thank you @ariellalgilmore !

Looking at the codesandbox, it appears to be blank for React:
https://react-codesandbox.s3-web.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/7182/ContentGroup/index.html

**Comment by jeffchew** [comment]
@ariellalgilmore strangely the font for the CDN version looks different: https://webcomponents-codesandbox.s3-web.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/7182/content-group/cdn.html

**Comment by ariellalgilmore** [comment]
> @ariellalgilmore strangely the font for the CDN version looks different: https://webcomponents-codesandbox.s3-web.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/7182/content-group/cdn.html

hmm trying to look into. I see the same thing happening with `content-group-simple` https://webcomponents-codesandbox.s3-web.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/7182/content-group-simple/cdn.html

looks like the problem is due to this:

Screen Shot 2021-09-22 at 12 07 56 PM

**Comment by ariellalgilmore** [comment]
> > > @ariellalgilmore strangely the font for the CDN version looks different: https://webcomponents-codesandbox.s3-web.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/7182/content-group/cdn.html
> 
> > 
> 
> > hmm trying to look into. I see the same thing happening with `content-group-simple` https://webcomponents-codesandbox.s3-web.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/7182/content-group-simple/cdn.html
> 
> > 
> 
> > looks like the problem is due to this:
> 
> > 
> 
> > Screen Shot 2021-09-22 at 12 07 56 PM
> 
> 
> 
> Ok, maybe we can capture this in another PR perhaps? Or you think this is an easy fix?

Yeah i think lets capture in another PR.

**Review by jeffchew — APPROVED** [review]
LGTM!

**Pull request merged**
