### PR TITLE
chore(feature-card): refactored block large and medium into component

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#5416

### Description
This PR deprecates Feature Card Block Medium and Large, and adds a Large variant to the regular FeatureCard component for both React and Web Components.

### Changelog

**New**

- new `large` variant for FeatureCard that replaces `FeatureCardBlockLarge`

**Removed**

- `FeatureCardBlockMedium` and `FeatureCardBlockLarge` are now deprecated

### CODE REVIEW

**Comment by shixiedesign** [comment]
Hi Ignacio! So good to see this PR. I noticed a few grid issues, but the most important right now would be rename Default to `Medium` in web components. I think we would be coming back to look at grid more.

**Comment by shixiedesign** [comment]
Getting more details documented: 

### 1. Grid

- Web comp: Medium variation appears too wide. Should use 8 columns. 
- React: Medium variation is better than on web comp! Bust still not sticking to grid. 

_Current (top web comp, bottom react):_

image

_Expecting_

image

**On mobile**
- Web component: should be full bleed. React is correct
_Current (top web comp, bottom react):_
image


### 2. Dotcom shell got affected

**Comment by shixiedesign** [comment]
### 2. Dotcom shell got affected
- Web component. React looks good.
image

### 3. Content block media got affected
- React not on grid
image

**Comment by IgnacioBecerra** [comment]
@shixiedesign fyi Fixed the issues you mentioned!

**Comment by jeffchew** [comment]
@IgnacioBecerra can you fix the snapshot file?

@shixiedesign just checking if you saw if things were addressed in the latest changes?

**Comment by IgnacioBecerra** [comment]
@jeffchew Yep will do, I'm still working on some additional fixes that came up after talking to designers offline 👍

**Comment by ariellalgilmore** [comment]
Hey @IgnacioBecerra!! looks like there are some merge conflicts :(

**Review by shixiedesign — APPROVED** [review]
Thank you! Looks good! Sorry I missed the GH notification :P

**Comment by IgnacioBecerra** [comment]
@ariellalgilmore Thanks for the comment! I think it was a weird Percy issue since it looked fine on the preview, but I actually had a heading and FeatureCard large in the link list story anyway, so this last commit should render properly.

**Review by kennylam — APPROVED** [review]
LGTM thanks @IgnacioBecerra!

**Pull request merged**
