### PR TITLE
fix(cta-section): [CTA section - with content items]: Pictograms have extra spacing

### PR DESCRIPTION
**Pull request by mwanberg**
### Related Ticket(s)
[
[CTA section - with content items]: Pictograms have extra spacing](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8305)

### Description

"The CTA section that uses pictogram content items adds spacing below the pictogram that should not be there. The spacing between the content item text and pictogram should be 32px."

The extra spacing was caused by the SVG itself. I updated the path within the SVG to fill its available space and now the margins should look more correct. This was appearing in all instances of the Web Components component, not just Firefox and the React wrapper.

**Original:** 
Screen Shot 2022-02-16 at 12 41 45 PM

**Design specs:**
Screen Shot 2022-02-16 at 12 40 18 PM

**Updated:**
Screen Shot 2022-03-04 at 1 20 00 PM

### CODE REVIEW

**Comment by oliviaflory** [comment]
@mwanberg this looks great, thank you!

I just want to double check with you, the original issue was written for `Web Components – React wrapper`, but I'm only seeing the updates in `Web Components` story book (it was correct to fix in Web components first!) Will we be doing the React wrapper work in a separate issue?

**Comment by proeung** [comment]
@oliviaflory I think we can keep everything (Web Components and WC with React Wrapper) in one issue. @mwanberg Let's adjust the React Wrapper Storybook preview to include the proper SVG sizes - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/src/components/cta-section/__stories__/cta-section.stories.react.tsx#L71

**Comment by mwanberg** [comment]
I was so excited about the overall problem that I forgot to check the original. :) The React wrapper has been updated and should be reflected in its preview now.

**Review by proeung — APPROVED** [review]
Looks good on both WC and WC with React Wrapper!

Screen Shot 2022-03-08 at 3 59 36 PM
Screen Shot 2022-03-08 at 3 59 41 PM

**Review by kennylam — APPROVED** [review]
LGTM thanks @mwanberg!

**Review by oliviaflory — APPROVED** [review]
LGTM, thank you @mwanberg !

**Pull request merged**
