### PR TITLE
docs(storybook): add button-cta documentation in CTA readme and update masthead's platform url documentation

### PR DESCRIPTION
**Pull request by annawen1**
### Related Ticket(s)

[Masthead]: Update platform url documentation #8002

### Description

Add documentation for button-cta:
- add `button-cta` codesandbox
- add code snippet for adopter to get started in cta readme

Updated masthead's documentation on how to set up `platformUrl`. Current example shows how it works within `lit-html` template which most adopters are not using. Change documentation to show how to set up with javascript instead.

### Changelog

**New**

- created codesandbox example for `button-cta`

**Changed**

- fix codesandbox example links for cta components in cta readme

### CODE REVIEW

**Comment by jeffchew** [comment]
@annawen1 can you add an integration test for the CTA button?

**Comment by annawen1** [comment]
@jeffchew The innovation team already added [e2e tests](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/tests/e2e-storybook/cypress/integration/cta/button-cta.e2e.js) for the `button-cta` about a month ago, it seems just the documentation and codesandbox example was missing

**Comment by jeffchew** [comment]
> @jeffchew The innovation team already added [e2e tests](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/tests/e2e-storybook/cypress/integration/cta/button-cta.e2e.js) for the `button-cta` about a month ago, it seems just the documentation in the storybook cta readme and codesandbox example was missing

@annawen1 I meant more about the integration tests for the codesandbox examples:

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/web-components/tests/e2e/cypress/integration

**Comment by annawen1** [comment]
> @annawen1 I meant more about the integration tests for the codesandbox examples:
> 
> https://github.com/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/web-components/tests/e2e/cypress/integration

@jeffchew oh gotcha! Done!

**Comment by jeffchew** [comment]
@annawen1 looks like there are some formatting issues:

image

**Comment by annawen1** [comment]
> @annawen1 looks like there are some formatting issues:
> 
> image

@jeffchew formatting fixed!

**Review by IgnacioBecerra — APPROVED** [review]
lgtm, thanks @annawen1!

**Pull request merged**
