### PR TITLE
fix(leadspace-search):  clear button

### PR DESCRIPTION
**Pull request by annawen1**
### Related Ticket(s)

[Lead Space Search]: QA:Brief description: Label of the button should be defined as "clear input" rather than "close" #9860

### Description

Change the default value of the `close-search-button-assistive-text` attribute to "Clear input" instead as it is more descriptive and clearer to user in the case of the search with typeahead

### Changelog

**Changed**

- Change the default value of the `close-search-button-assistive-text` attribute to "Clear input" 
- edit selector to use `part='close-button'` instead of `aria-label` since the aria-label is an attribute that can change values

### CODE REVIEW

**Review by kennylam — APPROVED** [review]

**Comment by RichKummer** [comment]
Hey @annawen1 , Percy picked up an issue where the "X" button for the expanded search field in `masthead` is persisting even when the search bar isn't expanded (even before the user expands the search bar).
Screen Shot 2023-03-01 at 11 37 31 AM

**Comment by annawen1** [comment]
> Deploy preview created for package `Web Components`: https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/10176/index.html
> 
> Built with commit: [b66bffbe383c993eb9fb63f8d19e5c5d27fb9c0e](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/commit/b66bffbe383c993eb9fb63f8d19e5c5d27fb9c0e)

oh whoa weird! Good catch, I'll take a look

**Comment by annawen1** [comment]
> Hey @annawen1 , Percy picked up an issue where the "X" button for the expanded search field in `masthead` is persisting even when the search bar isn't expanded (even before the user expands the search bar). Maybe this is a web components issue? Screen Shot 2023-03-01 at 11 37 31 AM


oh whoa weird! Good catch, I'll take a look

**Review by RichKummer — APPROVED** [review]
LGTM!

**Pull request merged**
