### PR TITLE
fix(masthead): search icon does nothing when input empty

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

#5819 

### Description

Fixes an issue in the `default` React masthead where clicking the search icon while the search component is open with no search value would close the entire component. The expected behavior is for the search component to remain open and do nothing.

### Changelog

**Changed**

- search visibility behavior in `MastheadSearch`

### CODE REVIEW

**Review by shixiedesign — APPROVED** [review]
Looks fixed in my testing in Chrome! Thanks Kenny ⚡

**Comment by shixiedesign** [comment]
Percy found this and seems like a it's probably not a real diff. React doesn't have this bug so shouldn't be affected. 

image

**Comment by jeffchew** [comment]
> Percy found this and seems like a it's probably not a real diff. Prod React is behaving as expected. React doesn't have this bug so shouldn't be affected.
> 
> image

Yes, it's a false positive that's sporadic, haven't found a fix for this yet.

**Review by jeffchew — APPROVED** [review]
LGTM!

**Pull request merged**
