### PR TITLE
chore(merge): merge `feat/carbon-for-ibm-dotcom-v2` into `main`

### PR DESCRIPTION
**Pull request by kennylam**
### Description

Merge `feat/carbon-for-ibm-dotcom-v2` feature branch into `main`.

### Changelog

**New**

- {{new thing}}

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by IgnacioBecerra — APPROVED** [review]
Started reviewing yesterday and finished going through the files just now... looks good to me!

**Comment by abdonrd** [comment]
This PR has been squashed, causing all contribution history to be lost. 😕 
(same with https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11217)

A year's work? has been reduced to a one commit (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/commit/f7fd7e7d4af8ca78d5ce86658095ca39f6d28a33) in the name of @kennylam:
> 4,373 changed files with 106,075 additions and 421,213 deletions.
Screenshot 2023-12-13 at 9 37 57 AM


Example with my profile:
- [carbon-for-ibm-dotcom/pulls?q=is%3Apr+author%3Aabdonrd](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pulls?q=is%3Apr+author%3Aabdonrd) (**15** merged PRs in 2023)
- [carbon-for-ibm-dotcom/commits?author=abdonrd](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/commits?author=abdonrd) (only **1** commit in 2023)

Screenshot 2023-12-13 at 9 42 17 AM


Being an open source project, it is a bit ugly to delete contributions.
Not just for me, but for all the other contributors.

@kennylam @jeffchew can we get this back? Thank you! 🙏

**Comment by jeffchew** [comment]
Thanks for pointing out @abdonrd , I think also should be for all team members that touched the feature branch.

@kennylam , any way to easily merge this in as a merge commit? I know you spent a lot of time resolving the conflicts....

**Comment by abdonrd** [comment]
Fixed, thanks @kennylam!

Screenshot 2023-12-14 at 12 54 04 PM

**Pull request merged**
