### PR TITLE
chore(npm): update version to beta

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

{{Provide url(s) to the related ticket(s) that this pull request addresses}}

### Description

{{Add a human-readable description / detail summary of what the PR is changing and any details around how and why}}

{{If applicable, include a screenshot indicating an example or examples of what the PR is changing in the application}}

### Changelog

**New**

- {{new thing}}

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Review by ariellalgilmore — APPROVED** [review]
LGTM!

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by emyarod — APPROVED** [review]
to match commit message

**Comment by abdonrd** [comment]
Looks like it's not working:

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/actions/workflows/deploy-cwc-v2-beta.yml

**Pull request merged**
