### PR TITLE
fix(masthead): expressive sunset cleanup

### PR DESCRIPTION
**Pull request by emyarod**
### Related Ticket(s)

#7087

### Description

This PR includes several fixes to the `web-components` and `react` masthead component

* "View all products" button should be center aligned in the React version:

image

* L1 menu headers should be vertically centered in the React version:

image

Mobile view

* Back button should be properly positioned in the web components version
* "The essentials" should be 32px tall + 1px for the bottom border in the mobile WC and React versions
* "View all products" should appear correct in the React version

image

### Changelog

**Changed**

- explicitly set `iconInline` in right nav link with icon
- remove React specific padding rule in L1 masthead
- **manually override `body-long-01` styles in masthead leftnav (appears to be due to base font size differences)**
- fix back button positioning
- add `role="menuitem"` to React sidenav menu items

### CODE REVIEW

**Review by kennylam — APPROVED** [review]
LGTM!

**Comment by oliviaflory** [comment]
@emyarod all the changes look great!

I saw a few things, not sure what happened:

1. Looks like all the `bx--side-nav__link` are missing a partial underline in React, most noticeable on the Top platforms menu

| example 1 | example 2 |
| --- | --- |
| Image from iOS |Image from iOS (1)| 

2. The arrow alignment on the category heading is off, it should be right aligned to the menu like the chevrons.

| Current | Expected |
| --- | --- |
| Image from iOS (2)| Screen Shot 2021-09-09 at 4 47 33 PM
|

**Comment by emyarod** [comment]
@oliviaflory from what I could tell those issues appear to be from before the expressive sunset branch merge, but I believe I have resolved them now

---

going off of that though, while taking a look I also found more differences between `web-components` and `react`:

* the category heading arrow doesn't appear in the web components masthead
* the horizontal rule under the category headings have different lengths

web components:
image

react
image


not sure if this is intentional, but if not, I think it should be a separate effort since these existed prior to the expressive theme sunset (as far as I can tell)

I think it would be more manageable to scope this PR and #7103 to just expressive theme deprecation issues

**Review by shixiedesign — APPROVED** [review]
Looks like all the issues are fixed. I didn't see the errors Olivia pointed out too. Thanks!

**Pull request merged**
