### PR TITLE
fix(logo-grid): styles and functionality fixes

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

#6040 

### Description

This aligns both React and web components `logo-grid` to the grid, as well as various other styling fixes. Also includes fixes to the web components version behavior where a space would be rendered for the CTA even when it did not exist.

### Changelog

**New**

- company logos

**Changed**

- align both React and web component versions to the grid
- spacing fixes
- fixes web components CTA footer rendering behavior
- use `dds-hr` instead of CSS border

**Removed**

- CTA from `logo grid` stories

### CODE REVIEW

**Comment by IgnacioBecerra** [comment]
@kennylam Looking great with the new logo images! One quick thing, since we're removing the CTA from the stories, maybe we should also remove the CTA knobs in the Web Components story to match React's.

**Comment by kennylam** [comment]
> maybe we should also remove the CTA knobs in the Web Components story to match React's.
@IgnacioBecerra Good catch, thanks!

**Comment by shixiedesign** [comment]
Grid seems a bit off - rule is 16px too long on each side, and content should start on Column, currently hanging: 

image

**Comment by kennylam** [comment]
> Grid seems a bit off

@shixiedesign Good catch, this was being caused by extra spacing in the Storybook story, which I've now removed.

**Review by shixiedesign — APPROVED** [review]
Looking cleeeaan! Thank you!

**Pull request merged**
