### PR TITLE
chore(deps): upgrade `lerna` to latest

### PR DESCRIPTION
**Pull request by kennylam**
### Description

This upgrades `lerna` to the latest version (`v4.0.0`).

Publish tests:
- [first `rc`](https://dbg-digital-design-team-jenkins.swg-devops.com/view/Carbon%20for%20IBM.com%20-%20NPM/job/Carbon%20for%20IBM.com%20-%20Publish%20-%20Minor/199/console)
- [subsequent `rc`](https://dbg-digital-design-team-jenkins.swg-devops.com/view/Carbon%20for%20IBM.com%20-%20NPM/job/Carbon%20for%20IBM.com%20-%20Publish%20-%20Minor/200/console)
- [full release](https://dbg-digital-design-team-jenkins.swg-devops.com/view/Carbon%20for%20IBM.com%20-%20NPM/job/Carbon%20for%20IBM.com%20-%20Publish%20-%20Minor/201/console)

### Changelog

**Changed**

- upgrade `lerna` to latest

### CODE REVIEW

**Comment by jeffchew** [comment]
@kennylam has the API changed at all with this version? Do we need to make any updates to any of our publish commands?

**Comment by kennylam** [comment]
> @kennylam has the API changed at all with this version? Do we need to make any updates to any of our publish commands?

@jeffchew Not that I saw. I tested all `lerna` scripts and everything went through fine. I can do a few local publish dry runs and see if everything is ok.

**Comment by jeffchew** [comment]
@kennylam just coming back to this, looks like some merge conflicts since it's been open for awhile.

Not a rush, but checking if the publish scripts still looked ok with this? Also, is there a noticeable improvement when upgrading? Does this also address any dependabot issues?

**Review by jeffchew — APPROVED** [review]
LGTM, thank you @kennylam for the thorough testing of this!

**Pull request merged**
