### PR TITLE
feat(cta): add email, schedule, chat, call types

### LINKED ISSUE #9170: [CTA]: Add additional icons and CTA types
**Engineering info:**  
- Innovation Team engineer: 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/ADCMS-2552

-----

### The problem

Based on Drupal data that was analyzed, there are additional CTA types that developers need to add in AEM. They are:

- Email
- Schedule
- Live chat
- Call
Screenshot with proposed icons attached
Frame 196

### The solution

Based on discussions with Putra and Olivia, AEM should be in parody with the C4ibm.com library. In order for this to be accomplished, we will need to add the above listed CTA types to the C4IBM.com library. A design review and discussion happened with the C4ibm.com team on Wednesday 7/20/22 during office hours where the icons were approved to add to the library.

### Application/website

AEM Interfaces Team

### Business priority

Medium Priority = upcoming release but is not pressing

### What time frame would this ideally be needed by (if applicable)

_No response_

### Examples

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)

Closes #9170 

### Description

Adds `email`, `schedule`, `chat`, and `call` CTA types.

### Changelog

**New**

- New CTA types

### CODE REVIEW

**Review by kennylam — APPROVED** [review]
LGTM thanks @andy-blum!

**Review by proeung — COMMENTED** [review]
The additional icons are displaying correctly, however, the `data-ibm-contact=` attribute is missing.

@kennylam @jeffchew If the adopter wants to use any of these contact icons and load in the `CMaaS` script to initialize the live chat, phone, chatbots, consultation, or schedulers (see [link](https://www.ibm.com/standards/web/v19a-archive/components/contact-module/#call-to-actions)). Are we recommending that they apply the `data-ibm-contact=` attribute separately (see below) or is this something we should account for in the component?

```
<dds-button-cta 
    href="#" 
    cta-type="schedule" 
    kind="primary" 
    data-ibm-contact="scheduler-link">
Schedule a consultation
</dds-button-cta>
```

Also, do you think it worth noting in the "Docs" tab that they need to require this script in the header of their HTML page `<script src="https://www.ibm.com/common/digitaladvisor/cm-app/latest/cm-app.min.js" defer></script>` to get the model/lightbox to show up correctly?

**Review by RichKummer — APPROVED** [review]
Took a look through and the new icons are showing up correctly. If there's changes per @proeung 's comment, I'll re-review!

**Comment by kennylam** [comment]
> Are we recommending that they apply the `data-ibm-contact=` attribute separately (see below) or is this something we should account for in the component?

I actually thought this would have been accounted for already with this PR. But perhaps documentation on both the inclusion of the attribute and external script will be enough.

**Comment by proeung** [comment]
> I actually thought this would have been accounted for already with this PR. But perhaps documentation on both the inclusion of the attribute and external script will be enough.

No, it doesn't look like the `data-ibm-contact` attribute has been accounted for in this PR at the moment. 

@andy-blum for the different contact types, let's make sure we have the proper `data-ibm-contact` attribute value added to the CTA component (see - https://www.ibm.com/standards/web/v19a-archive/components/contact-module/#call-to-actions). As for documentation, let's note the inclusion of this script in the header of their HTML page `<script src="https://www.ibm.com/common/digitaladvisor/cm-app/latest/cm-app.min.js" defer></script>` to get the model/lightbox to show up correctly.

**Review by proeung — DISMISSED** [review]
@andy-blum I see that the `data-ibm-contact` attribute and types are added (see - [link](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9311/files#diff-f018e0c053d82c9d36f97f45fd69ec7da7c03c0744b3b52a5395ccd62779a718R145-R148)), but I'm still not seeing updates on the "Docs" tab that outlines the usage of the `cm-app.min.js` script for adotpers.

Also, for testing purposes, you might want to update the CodeSandbox app for the CTA component to include these different Contact Module types so that we can ensure that it renders the proper contact widgets (eg. Let's talk, Scheduler, etc). See changes from this PR as an example - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9359/files

**Comment by andy-blum** [comment]
@proeung Which CTA component do you recommend updating?

- cta-block
- cta-button
- cta-card
- cta-card-link
- cta-feature
- cta-section
- cta-text

My first instinct was cta-button or cta-text, but neither of them currently has more than one cta item. Should we add all the various types to all of these? Add a new cta-contact-method example?

**Comment by proeung** [comment]
> My first instinct was cta-button or cta-text, but neither of them currently has more than one cta item. Should we add all the various types to all of these? Add a new cta-contact-method example?

Yeah, I think having a new `.html` page example that showcases the different CTA contact methods works. We just need to check and verify a couple of examples to ensure that the cm-app script is loading along with the DDO object.

**Comment by andy-blum** [comment]
@proeung I added a CS file for this, but since it's pulling the component from the CDN, I don't think it'll properly reflect the changes in this PR until post-merge.

**Comment by proeung** [comment]
> @proeung I added a CS file for this, but since it's pulling the component from the CDN, I don't think it'll properly reflect the changes in this PR until post-merge.

@andy-blum You can still test it using the ES import/version method, which gets built as part of the `Web Components (Codesandbox Examples)` deploy preview (eg. ES version pulling changes from PR #9359 - https://webcomponents-codesandbox.s3-web.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/9359/masthead/index.html).

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/examples/codesandbox/components/cta-button/index.html#L28

**Review by jkaeser — APPROVED** [review]
All looks good to me. +1

**Comment by RichKummer** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by RichKummer** [comment]
recheck

**Pull request merged**
