### PR TITLE
fix(masthead): set text wrapping for menu dropdown items

### PR DESCRIPTION
**Pull request by annawen1**
### Related Ticket(s)

AEM production L1 navigation - 2nd level entries are abbreviated #5758

### Description

Currently the masthead menu dropdown items are cut off when the label is too long. This PR allows for text wrapping and increases the width of the menu dropdown to 256px.

**CURRENT:**
Screen Shot 2021-07-14 at 12 45 18 PM

**AFTER:**
Screen Shot 2021-07-14 at 3 20 10 PM

You can test it out in the Custom Navigation stories of the Masthead within React and Web components

### Changelog

**New**

- add menu dropdown item with extra long text in the custom nav menu data file

**Changed**

- change scss to accommodate longer text

### CODE REVIEW

**Review by shixiedesign — CHANGES_REQUESTED** [review]
Ooof Anna this might be a big break! Percy caught it at first and I thought it's a glitch but... 
**React's Dotcom mega menu** all got width clipped. This should be fixed. Homepage is using react masthead. 

image

**Review by kennylam — APPROVED** [review]
LGTM thanks @annawen1!

**Comment by annawen1** [comment]
> Ooof Anna this might be a big break! Percy caught it at first and I thought it's a glitch but...
> **React's Dotcom mega menu** all got width clipped. This should be fixed. Homepage is using react masthead.
> 
> image

@shixiedesign @photodow Fixed! Good catch!

**Review by photodow — APPROVED** [review]
:+1: Looks good based on my understanding of the ticket.

**Pull request merged**
