### PR TITLE
fix(footer): title not showing in 672 breakpoint specifically

### PR DESCRIPTION
**Pull request by bruno-amorim**
### Related Ticket(s)
[ADCMS-4397](https://jsw.ibm.com/browse/ADCMS-4397)

### Description
Titles for the Footer Group Navs were not being displayed specifically in 672px breakpoint

Screenshot 2024-01-11 at 15 37 43

### CODE REVIEW

**Review by jkaeser — APPROVED** [review]
Nice work, @bruno-amorim!

**Review by andy-blum — APPROVED** [review]
LGTM - @bruno-amorim can you also open a PR with these changes agains `v1`?

**Comment by kennylam** [comment]
@bruno-amorim Thanks for this! Just need to update the snapshots.

**Comment by bruno-amorim** [comment]
@kennylam 

I updated the snapshots, would you please review it now?
thanks a lot!!!

**Review by jkaeser — COMMENTED** [review]
Same issue here as in #11409 , @bruno-amorim – looks like the ci-check is throwing errors.

**Comment by bruno-amorim** [comment]
Hi @jkaeser 
I fixed the failing tests. Would you please check it now?

**Pull request merged**
