### PR TITLE
feat(masthead-v2): release recent improvements

### PR DESCRIPTION
**Pull request by jkaeser**
### Description

Integrate latest updates to the `main` branch into `feat/masthead-v2`. This includes some fixes/feats we want to apply to the v2 masthead:

- [a9a3429](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9609/commits/a9a342923e186664426cc9828d54685c2722abf5)

### To QA
Visit https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/9609/index.html?path=/story/components-masthead--with-v-2-data and verify there are no visual or functional regressions to the masthead as compared to the live site (i.e. https://www.ibm.com)

### CODE REVIEW

**Comment by KiBeta** [comment]
Looks good to me.

**Comment by andy-blum** [comment]
@kennylam looks like your account is blocking the DCO check?

**Comment by andy-blum** [comment]
recheck

**Comment by jkaeser** [comment]
We're safe to release this now that we can make tagged releases for masthead v2 🎉 

@andy-blum @IgnacioBecerra @KiBeta  can you give this a review? It gets `feat/masthead-v2` up to date with all the changes that have landed in `main` since they diverged. The most important thing is to verify the v2 masthead still works in the deploy preview (https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/9609/index.html?path=/story/components-masthead--with-v-2-data).

It also looks like we're blocked by the DCO Assistant since some of @kennylam's commits aren't associated with his GH account. Anybody have ideas for how to resolve that?

**Review by andy-blum — APPROVED** [review]
LGTM

**Pull request merged**
