### PR TITLE
fix: add file extensions in web-components package

### PR DESCRIPTION
**Pull request by abdonrd**
### Related Ticket(s)

#9069

### Description

Add file extensions in web-components package

### Changelog

**Changed**

- Add file extensions in web-components package

### CODE REVIEW

**Review by ariellalgilmore — APPROVED** [review]
LGTM!

**Comment by 1ucian0** [comment]
Thanks for the fix! We needed it for improving the navigation of qiskit.org/documentation

**Comment by IgnacioBecerra** [comment]
@abdonrd Thanks for the PR! Looks like we might need to solve the merge conflict before we can merge this though

**Comment by abdonrd** [comment]
> @abdonrd Thanks for the PR! Looks like we might need to solve the merge conflict before we can merge this though

Done!

**Pull request merged**
