### PR TITLE
fix(masthead): add-l1-link-target

### PR DESCRIPTION
**Pull request by marcelojcs**
### Related Ticket(s)
[Jira](https://jsw.ibm.com/browse/ADCMS-5826)

### Description
Authors have a need to setup L1 menu items to open in a new tab. It seems like this is a missing feature in the L1 component, even though the data structure supports it.

### Changelog

**New**
This PR adds  the support to the Target attribute to L1 links

### CODE REVIEW

**Comment by m4olivei** [comment]
Hey @marcelojcs , how do I test this?

**Comment by marcelojcs** [comment]
Hi @m4olivei!!
I'm testing like this  
https://gist.github.com/marcelojcs/e1c070ba06a2973cb13ba12eda39a91c

**Comment by m4olivei** [comment]
> Hi @m4olivei!! I'm testing like this https://gist.github.com/marcelojcs/e1c070ba06a2973cb13ba12eda39a91c

Thanks @marcelojcs . Lets add an additional link to that mock L1 data object so that its just part of the Storybook example, and we don't have to modify the code to check this feature.

**Review by m4olivei — CHANGES_REQUESTED** [review]
While this is looking good at Desktop breakpoint, seems like sub menu items are rendered differently at mobile, and if I set `target: '_blank'` for a submenu item and test at mobile breakpoint, the link does not open in a new tab. Here is a patch for the L1 data that I'm testing with locally and then running through all the links I added `target: '_blank'` to ensure they are working:

```patch
diff --git a/packages/web-components/src/components/masthead/__stories__/links.ts b/packages/web-components/src/components/masthead/__stories__/links.ts
index 96c1cc476c..7838c49f69 100644
--- a/packages/web-components/src/components/masthead/__stories__/links.ts
+++ b/packages/web-components/src/components/masthead/__stories__/links.ts
@@ -65,6 +65,7 @@ const mastheadL1Data: MastheadL1 = {
               {
                 title: 'Link item (A1)',
                 url: 'https://example.com',
+                target: '_blank',
               },
               {
                 title: 'Link item (A2)',
@@ -105,6 +106,7 @@ const mastheadL1Data: MastheadL1 = {
               {
                 title: 'Link item (B1)',
                 url: 'https://example.com',
+                target: '_blank',
               },
               {
                 title: 'Link item (B2)',
@@ -126,6 +128,7 @@ const mastheadL1Data: MastheadL1 = {
               {
                 title: 'Link item (B4)',
                 url: 'https://example.com',
+                target: '_blank',
               },
               {
                 title: 'Link item (B5)',
@@ -159,6 +162,7 @@ const mastheadL1Data: MastheadL1 = {
               {
                 title: 'Link item (C1)',
                 url: 'https://example.com',
+                target: '_blank',
               },
               {
                 title: 'Link item (C2)',
@@ -176,6 +180,7 @@ const mastheadL1Data: MastheadL1 = {
               {
                 title: 'Link item (C3)',
                 url: 'https://example.com',
+                target: '_blank',
                 description:
                   'Description text lorem ipsum dolor sit amet commondo ligua eaget',
               },
@@ -209,6 +214,7 @@ const mastheadL1Data: MastheadL1 = {
               {
                 title: 'Link item  (C7)',
                 url: 'https://example.com',
+                target: '_blank',
               },
               {
                 title: 'Link item (C8)',
@@ -250,6 +256,7 @@ const mastheadL1Data: MastheadL1 = {
               {
                 title: 'Link item (D1)',
                 url: 'https://example.com',
+                target: '_blank',
               },
               {
                 title: 'Link item (D2)',
@@ -266,6 +273,7 @@ const mastheadL1Data: MastheadL1 = {
             items: [
               {
                 title: 'Link item (D3)',
+                target: '_blank',
                 url: 'https://example.com',
                 description:
                   'Description text lorem ipsum dolor sit amet commondo ligua eaget',
```

**Review by m4olivei — APPROVED** [review]
LGTM. Thanks.

**Review by andy-blum — APPROVED** [review]

**Pull request merged**
