### PR TITLE
feat(card-group): add option for 2-4 cards per row

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

#5286 #5520 

### Description

This adds the option to set the number of cards per row (2-4 cards) in `CardGroup`/`card-group`. The default number is 3.

### Changelog

**New**

- users can now set the number of cards per row in `CardGroup`/`card-group`

### CODE REVIEW

**Comment by IgnacioBecerra** [comment]
@kennylam So far looking good! I found a couple issues in both versions:

In Web Components, when choosing 4 cards per row and enabling the outline cards knob, it appears that there's a card that's missing the bottom border in the first row:
Screen Shot 2021-06-15 at 10 14 17 AM


The same border bug can also be seen In React with the 4 cards per row, but the footer seems to be clipping into the copy as well:
Screen Shot 2021-06-15 at 10 09 31 AM


Also in the first picture the weird copy height might be caused from the sameHeight utility being applied to each row individually, and the logic for that takes 2/3 cards per row into account. I know #5868 will be fixing this, so not sure if we sure be updating the individual sameHeight logic to consider 4 or let it go for now since it'll get removed anyway.

**Comment by kennylam** [comment]
>I found a couple issues in both versions

@IgnacioBecerra Thanks for looking, yeah I'm aware of these issues as well. The React clipping is caused by the `sameHeight` utility not firing a second time when the card number is changed. This is a common problem in Storybook and one of the reasons we sometimes need to break out variations like this into their own story. I'll take a look at the border issue since this was addressed in a separate PR. If it is too far out of the scope of this I'm going to create an issue and track separately.

**Comment by kennylam** [comment]
@IgnacioBecerra looks like there's already an issue (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6016) open for the borders.

**Comment by shixiedesign** [comment]
Hey @kennylam this is working and good, one challenge is that because the “number of cards per row” is unaware of the grid, changing the values causes cards in the grid to squeeze and stretch. How would adopter achieve the 2x2 layout without having the cards stretch to 5 columns each? 
image

**Comment by kennylam** [comment]
@shixiedesign Grid layout has been adjusted for when there are two cards per column.

**Comment by shixiedesign** [comment]
Thank you!! 

1. Border on 2nd card became a bit broken. Issue persists if I open the canvas in new tab. 
image

2. If we display Card group starting first column of the grid, would we avoid seeing the squished cards issue? If so, It's totally fine to change the display to default starting in column 1
3. Seeing the gray empty card slot sometimes
4. Same height util might need an update? 
image

**Comment by kennylam** [comment]
@shixiedesign Good catch! Had to update the component with the outline work from #6435.

**Comment by shixiedesign** [comment]
1. Outline issue is resolved! 🎉 
2. How about this one? For with it's 4 cards per row, re-align storybook story to start on column 1 instead of column 5 could help?  

> If we display Card group starting first column of the grid, would we avoid seeing the squished cards issue? If so, It's totally fine to change the display to default starting in column 1

3. Try 5 cards, 3 per row, 0 offset. I see the card's body copy are not starting at the same height: 
image

**Comment by kennylam** [comment]
@shixiedesign #2 and 3 done!

**Comment by shixiedesign** [comment]
💣 👍

**Review by shixiedesign — APPROVED** [review]

**Review by annawen1 — APPROVED** [review]
LGTM!

**Pull request merged**
