### PR TITLE
fix(link-with-icon): fixed uncentered arrow icons on Safari

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)

#4492

### Description

Aligned uncentered arrow icons that only happen in Safari. Originally an issue with the specific component below, but upon closure inspection all of the components using `LinkWithIcon` in Safari have an uncentered arrow. They can also be seen below -- all the arrow icons are slightly shifted down a few pixels. 

Compared to Chrome:
Screen Shot 2020-11-24 at 2 56 44 PM

### Changelog

**New**

- added in-line style of `display: flex` to the icon `slot` of `link-with-icon.ts` to ensure the arrows are positioned properly on Safari

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Thank you for jumping in @IgnacioBecerra! A couple of comments:

1. We avoid using inline styles
2. React does not have `<slot>` and I suspect React may be broken. The same effect of styling `<slot>` tends to be achievable with styling its parent element

**Comment by IgnacioBecerra** [comment]
Thanks for the comments @asudoh! Fortunately, the React version shows up normally on Safari, this is only a Web Component issue.

As for the styles, I had first added a property within `_masthead-megamenu.scss` but after noticing it's an issue within `LinkWithIcon`, I applied the inline style so it affected throughout the other components extending it. Since it's actually only used in Megamenu and Card Footer, I went back with the original fix, now adding it to `link_with_icon.scss` as well to fix the other slightly uncentered arrows.

**Comment by asudoh** [comment]
Thank you for elaborating what you tried @IgnacioBecerra! Would you try the following?

1. Adding `display: block` to https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/v1.12.0/packages/styles/scss/components/link-with-icon/_link-with-icon.scss#L25-L31 - `<svg>`'s default `display: inline` adds space to accommodate one for 'y', 'g', etc. characters. `vertical-align: middle` is there presumably to alleviate that, but `display: block` will be a simpler fix given the icon is placed in flex container.
2. Adding `:host(#{$dds-prefix}-megamenu-link-with-icon) { @extend .#{$prefix}--link-with-icon; }` to [`packages/web-components/src/components/masthead/masthead.scss`](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/v1.13.0-rc.0/packages/web-components/src/components/masthead/masthead.scss) - Without that the style of link with icon is not applied to mega menu one.

I believe doing above eliminates the need for  `* { display: flex; }` and `a * { display: flex; }`. Please ping me for any questions. Thanks!

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @IgnacioBecerra!

**Pull request merged**
