### PR TITLE
chore(merge): merge `release/v2.0.0` to `main`

### PR DESCRIPTION
**Pull request by kennylam**
### Description

This merges the `release/v2.0.0` release branch into `main`.

### Changelog

**New**

- {{new thing}}

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by kennylam** [comment]
Deploy previews are failing due to a `@percy/cli` [bug](https://github.com/percy/cli/issues/1459) that the Percy team is aware of. Fix expected to be in place by the end of the week. Might need to disable visual snapshot testing for now to unblock PRs.

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by annawen1 — APPROVED** [review]

**Review by ariellalgilmore — APPROVED** [review]
LGTM!

**Review by IgnacioBecerra — APPROVED** [review]
LGTM!

**Pull request merged**
