### PR TITLE
fix(logo-grid): align to non-gutter grid

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#4970

### Description
Aligning the Web Components Logo Grid In Storybook to non-gutter grid.

### Changelog

**New**

- {{new thing}}

**Changed**

- changed Web Component Logo Grid Storybook to align with CSS grid

### CODE REVIEW

**Review by ariellalgilmore — APPROVED** [review]
LGTM! Thanks @IgnacioBecerra

**Comment by andysherman2121** [comment]
Hey @IgnacioBecerra ! I'm seeing the images and the text slightly off the non-gutter column

Screen Shot 2021-03-02 at 12 59 18 PM

**Comment by ariellalgilmore** [comment]
> LGTM! Thanks @IgnacioBecerra

oops sorry andy is right! I was looking at the wrong link

**Comment by asudoh** [comment]
@IgnacioBecerra Thank you for working on this; And @andysherman2121 is right, the component code needs to be updated, to use `bx--content-layout` CSS class similar to `<dds-content-block-simple>`.

**Comment by IgnacioBecerra** [comment]
Thanks for the comments everyone, using a CSS class similar to `bx--content-layout`, LogoGrid is now within the non-gutter columns.
Screen Shot 2021-03-03 at 4 55 29 PM

**Comment by asudoh** [comment]
Code-wise it looks good to me, unless logo grid uses `<div class="bx--content-block__cta-row">`. Wanted to have @ariellalgilmore and @andysherman2121 chime in on the final styles. Thanks @IgnacioBecerra!

**Comment by ariellalgilmore** [comment]
> Code-wise it looks good to me, unless logo grid uses `<div class="bx--content-block__cta-row">`. Wanted to have @ariellalgilmore and @andysherman2121 chime in on the final styles. Thanks @IgnacioBecerra!

Looks like the cta is suppose to overhang in the gutters so I think we should add `<div class="bx--content-block__cta-row">`. Also, wondering if a new issue needs to be made for the react storybook as it looks off:
Screen Shot 2021-03-04 at 8 12 12 AM

**Comment by IgnacioBecerra** [comment]
After confirming with @ariellalgilmore, seems like the CTA is properly aligned with the current changes.
Will be opening another PR to address the React misalignment specifically.

**Pull request merged**
