### PR TITLE
feat(filter-panel): add view all button for filter groups

### LINKED ISSUE #7405: [Filter panel] Web Component: add View all link for filter groups - DDS Consulting
**Engineering info:**  
- Innovation Team engineer: @jkaeser 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2365
- DPO consulting engineer: @IgnacioBecerra 
- Original Carbon for IBM.com engineering estimate: 5

----

#### User Story

> As a `[user role below]`:
Carbon for ibm.com developer

> I need to:
create/change the `Filter panel`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- **See the Epic (#7376 ) for the Design and Functional specs information**
- Add `View all` button to filter groups. Should default to `us-en`, with an option to change via component attributes for localization.
- See usage recommendations [here](https://www.ibm.com/standards/carbon/components/filter-panel/#number-of-items-per-category).
- Web Components Visual QA testing issue (#7406 )
- Web Components Prod QA testing issue (#7407 )

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] Update the Carbon for ibm.com website component [data file](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json) to be sure the web site Component Status and Storybook links are correct
- [ ] Use the [Visual QA checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist)) to verify design quality
- [ ] If a design is provided, the Designer is included as a Reviewer in the Pull Request
- [ ] Provide a direct link to the deploy preview for the designer in the Pull Request description
- [ ] A comment is posted in the Prod QA issue, tagging Praveen when development is finished

### PR DESCRIPTION
**Pull request by jkaeser**
### Related Ticket(s)

Resolves #7405 

### Description

Adds support for "view all" buttons in `DDSFilterGroupItem` components. 

- The button text defaults to "View all" and can be changed with the `view-all-text` attribute.
- The button appears when the number of filters in the group exceeds the `max-filters` attribute value. This defaults to 7, as per the functional specs.
- When the button appears, the number of filters specified by the `filter-cutoff` attribute are shown at first (defaults to 5 as per functional specs). The hidden filters are revealed once the button has been clicked.
- The shown/hidden filters are reset once the filter group is toggled closed and then re-opened.
   - There is one exception to this: if one of the filters that would be hidden has been selected, all filter items are revealed when re-opening the filter group.

### Changelog

**New**
- "View all" buttons render in `DDSFilterGroupItem` components when a sufficient number of filters are present in the group.

**Changed**

- Split the `DDSFilterPanelComposite`'s modal and desktop rendering into two methods to make it more obvious what's going on.

### CODE REVIEW

**Comment by proeung** [comment]
@jeffchew Is there a reason why this PR is closed? We reverted the changes from this PR from the `main` branch and out of the `v1.31.0` release tag due to an issue from the React Wrapper build, however, this PR is meant for addressing the mentioned here (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8255), unless the React wrapper issue has been resolved and https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7405 is included in the `v1.31.0`. Is that correct?

**Comment by jkaeser** [comment]
Looks like the React Wrapper deploy preview builds without issue. 

Many thanks, @IgnacioBecerra, for figuring out what was breaking it! 👏

**Review by IgnacioBecerra — APPROVED** [review]
Thanks once again for the work in this PR, glad we were able to figure this whole thing out. :D

**Review by proeung — APPROVED** [review]
LGTM as well! The React Wrapper deploy preview is building just fine now.

@IgnacioBecerra @jkaeser Awesome teamwork!

**Pull request merged**
