### PR TITLE
fix(content-group): cta spacing

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#11624 (content-group)

### Description

Content group CTA spacing is off
### Changelog

**New**

- {{new thing}}

**Changed**

- remove extra spacing above CTA and correctly align in gutter if it's a card

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by RichKummer** [comment]
@ariellalgilmore , this is looking good! 
I noticed that when we nest something like `content item` while the `group` has the CTA enabled, the spacing at the bottom of the `content item` is preserved and stacks with the CTA. This is causing extra spacing than intended. 

It might make sense to zero out the bottom margin of the nested item or the top spacing of the CTA to bring that in line.

**Comment by ariellalgilmore** [comment]
@RichKummer updated!

**Comment by RichKummer** [comment]
@ariellalgilmore that bottom spacing looks fixed! I noticed a strange bug when nesting `content item` when it has an image:
When viewed on its own, `content item` with image has the proper spacing between the media and the rest of the content item.
Screenshot 2024-04-23 at 12 38 45 PM

But when nested, some extra spacing appears between the media and the rest of the content item.
Screenshot 2024-04-23 at 12 39 08 PM

This only seems to effect the image version, _not_ the video one for some reason.

**Comment by ariellalgilmore** [comment]
@RichKummer good eyes!! updated in the last commit

**Review by kennylam — APPROVED** [review]
LGTM!

**Review by RichKummer — APPROVED** [review]
LGTM! Thanks for the fixes @ariellalgilmore ! ⭐

**Pull request merged**
