### PR TITLE
fix(MastheadL1): deselect L1 title when there is a selected menu item

### PR DESCRIPTION
**Pull request by annawen1**
### Related Ticket(s)
Corporate Masthead - Specify what is the currently selected element in a L1 menu #5302

### Description

When there is a selected menu item, the L1 title name should not be selected

BEFORE:
Screen Shot 2021-04-01 at 12 48 41 PM

AFTER:
Screen Shot 2021-04-01 at 12 48 31 PM

### Changelog

**Changed**

- add a `aria-selected` attribute to the title when there is no `selecteMenuItem` prop passed in
- adjusted the bottom blue border underneath the L1 title to be 3px to match the selected menu item styling

### CODE REVIEW

**Review by kennylam — APPROVED** [review]
LGTM thanks @annawen1!

**Comment by shixiedesign** [comment]
Selected item (and L1 title chip) seems to be too high by 1 px! :P 
image

**Comment by annawen1** [comment]
> Selected item (and L1 title chip) seems to be too high by 1 px! :P
> image

Alas, so close!

**Comment by shixiedesign** [comment]
Thank you! I am _so._ sorry about the nitpicks but now the blue underline seems too thin now. Should still be 3px. I think it might be the correct thickness but just need to go on top of the gray horizontal rule? 

image

**Close up:** 

image

**Comment by annawen1** [comment]
@shixiedesign can you take a look at the deploy links again? I see the expected results in the deploy link, could be that the deploy links had not been rebuilt yet?

What I see:
Screen Shot 2021-04-05 at 8 50 57 AM

**Comment by oliviaflory** [comment]
@annawen1 I'm seeing the gray bar overlap on [React](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/5698/index.html?path=/story/components-masthead--with-l-1) and [Web Components](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/5698/index.html?path=/story/components-dotcom-shell--with-l-1) preview of L1 stories still too. 🤷‍♀️ 

Screen Shot 2021-04-05 at 9 10 22 AM
Screen Shot 2021-04-05 at 9 10 40 AM

The L0 selected state looks right though!

**Comment by annawen1** [comment]
> @annawen1 I'm seeing the gray bar overlap on [React](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/5698/index.html?path=/story/components-masthead--with-l-1) and [Web Components](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/5698/index.html?path=/story/components-dotcom-shell--with-l-1) preview of L1 stories still too. 🤷‍♀️
> 
> Screen Shot 2021-04-05 at 9 10 22 AM
> Screen Shot 2021-04-05 at 9 10 40 AM
> 
> The L0 selected state looks right though!

🤦 Ugh I was looking at the L0 selected state haha

> @annawen1 I'm seeing the gray bar overlap on [React](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/5698/index.html?path=/story/components-masthead--with-l-1) and [Web Components](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/5698/index.html?path=/story/components-dotcom-shell--with-l-1) preview of L1 stories still too. 🤷‍♀️
> 
> Screen Shot 2021-04-05 at 9 10 22 AM
> Screen Shot 2021-04-05 at 9 10 40 AM
> 
> The L0 selected state looks right though!

@oliviaflory and @shixiedesign 🤦 I was looking at L0 😃 fix for L1 coming...

**Comment by annawen1** [comment]
@oliviaflory @shixiedesign For some reason, the I see the React L1 selected styles applied correctly when I refresh the page or open the deploy preview in incognito

**Comment by shixiedesign** [comment]
The 3px is showing up great now in both wc and react. If it's my cache issue I'm sorry! It looks good now. I did find another thing in React though: 

Blue line is peaking out behind L1 title chip after scrolling, to show overflow items. Should probably go behind the "Stock charts" and scrolling caret. 

image

**Comment by annawen1** [comment]
@shixiedesign @oliviaflory Made the changes we discussed earlier today to leave the selected blue border 1px above the gray parent border

**Review by shixiedesign — APPROVED** [review]
TY Anna!

**Pull request merged**
