### PR TITLE
fix(cloud-mega-menu): adding missing hover bg color

### PR DESCRIPTION
**Pull request by proeung**
### Related Ticket(s)

GH Issue: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7180
HC JIRA Ticket: https://jsw.ibm.com/browse/HC-2207

### Description

- This PR adds the missing hover state background color of `$hover-ui`.

### Testing Instruction

- Visit the `Cloud Masthead` - `/?path=/story/components-masthead--default` and `/?path=/story/components-cloud-masthead--default`
- Ensure that the hover state is using the `$hover-ui` token.

### Expected Display

Screen Shot 2021-09-21 at 1 09 55 PM

### CODE REVIEW

**Review by shixiedesign — APPROVED** [review]
Deploy preview looks good! Thank you!  I think Percy diff is an error. Please double check with a dev reviewer. Thanks!

**Comment by proeung** [comment]
Not sure where this [Percy diff](https://percy.io/538fc19a/Carbon-for-IBM.com-Web-Components/builds/12859429/changed/726738437?browser=chrome&browser_ids=16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=320&widths=320%2C1280) is coming from as the changes in this PR doesn't have any relation to this visual diff result.

**Review by annawen1 — APPROVED** [review]
LGTM!

**Comment by annawen1** [comment]
> Not sure where this [Percy diff](https://percy.io/538fc19a/Carbon-for-IBM.com-Web-Components/builds/12859429/changed/726738437?browser=chrome&browser_ids=16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=320&widths=320%2C1280) is coming from as the changes in this PR doesn't have any relation to this visual diff result.

yeah we've been getting some of those diffs lately...not sure why...🤔

**Comment by jeffchew** [comment]
> > Not sure where this [Percy diff](https://percy.io/538fc19a/Carbon-for-IBM.com-Web-Components/builds/12859429/changed/726738437?browser=chrome&browser_ids=16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=320&widths=320%2C1280) is coming from as the changes in this PR doesn't have any relation to this visual diff result.
> 
> yeah we've been getting some of those diffs lately...not sure why...🤔

We've been getting blank outputs sporadically from Percy, we already reported it to the Browserstack team but haven't received any updates on them fixing the issue yet.

**Pull request merged**
