### PR TITLE
fix(logo-grid): adding bottom margin to logo-grid-item, resolves #9005

### LINKED ISSUE #9005: [Logo grid]: @sm should be two columns for logos
**Engineering info:**  
- Innovation Team engineer: [Prachaya Sinsuwan](https://app.slack.com/team/W4BSY8N2H)
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2505
- DPO consulting engineer: @emyarod 

-----

### Description

Discovered in #8973.

The Web Components version of Logo grid is currently displaying a single column of logos and should be updated to match the newly created React wrapper version. At the `@sm` breakpoint, the logos should be in two columns to match the spec:

**Current WC version**
Screen Shot 2022-06-15 at 4 50 56 PM

**Specs**
Screen Shot 2022-06-14 at 10 36 31 AM

### Component(s) impacted

Logo grid

### Browser

Chrome

### Carbon for IBM.com version

v1.19.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

C4IBM.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/web-components/examples/codesandbox/components/logo-grid

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by paatsinsuwan**
### Related Ticket(s)

fix #9005 

### Description

Adding spacing at the bottom of each logo grid item in small screen

### CODE REVIEW

**Comment by proeung** [comment]
@paatsinsuwan What's the status of this draft PR? Is it almost ready for a review?

**Comment by paatsinsuwan** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by paatsinsuwan** [comment]
recheck

**Review by proeung — COMMENTED** [review]
Looking at the design specs there are some spacings between the logo imagery for the mobile/small breakpoints (see attached).

Screen Shot 2022-08-03 at 4 16 58 PM

I'll defer to @RichKummer for a full design QA review.

**Comment by paatsinsuwan** [comment]
@proeung the spacing line are not highlighting in the tool somehow.  I'm seeing it in the inspector on hover
Screen Shot 2022-08-03 at 4 36 17 PM
.

**Review by proeung — APPROVED** [review]
@paatsinsuwan Thanks, I see it now. Looks good from a code perspective. Now we just need design QA approval.

**Comment by RichKummer** [comment]
Hey @paatsinsuwan, the added horizontal space is really helping! I noticed that there's a bit of extra vertical spacing at the top and bottom of the individual logos - it's a little easier to see on the dark background:
Screen Shot 2022-08-09 at 12 08 44 PM

The result should display `32px` vertical spacing between each logo.

**Comment by paatsinsuwan** [comment]
@RichKummer I made the updates per your design spec.  Ready for another design review.

**Comment by RichKummer** [comment]
@paatsinsuwan, the space between the heading and the first row of logo grid items looks good. I'm still seeing some extra spacing (maybe coming from the logo grid image item itself) that is making the vertical spacing unequal to the horizontal spacing between the logos.

Screen Shot 2022-08-11 at 11 50 33 AM

Screen Shot 2022-08-11 at 11 54 03 AM

I'm seeing you have the `32px` value right for the vertical space, but that extra padding from the image is making it over 32px

**Review by RichKummer — APPROVED** [review]
LGTM! Thanks @paatsinsuwan !

**Pull request merged**
