### PR TITLE
refactor(content-group-simple): use CSS grid for layout

### PR DESCRIPTION
**Pull request by asudoh**
### Related Ticket(s)

Refs #4967.

### Description

Use CSS grid for layout for `<dds-content-group-simple>` to ensure correct Carbon grid alignment and simplify the markup.

### Changelog

**Changed**

- Change to use CSS grid for layout for `<dds-content-group-simple>`.

### CODE REVIEW

**Review by kennylam — COMMENTED** [review]
Looks great @asudoh. Only thing is this extra spacing in `image-with-caption`, I think?

Before/After

image

**Review by kennylam — DISMISSED** [review]
LGTM thanks @asudoh!

**Comment by asudoh** [comment]
> Only thing is this extra spacing in `image-with-caption`, I think?

Great catch @kennylam! Fixed.

**Review by kennylam — APPROVED** [review]
Looks good thanks @asudoh!

**Pull request merged**
