### PR TITLE
feat(copy-button): sync with @carbon/react v11

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#10074 
### Description

Update copy-button to sync with react version

### Changelog

**New**

- copy component button
- now cds-copy-button uses cds-copy
- add animation classes

**Changed**

- updated code-snippet with the new copy-button, but will still need to be updated with the sync process
- updated typos with `slot` should be `span`

**Removed**

- {{removed thing}}

### CODE REVIEW

**Review by kennylam — APPROVED** [review]
LGTM!

**Comment by oliviaflory** [comment]
@ariellalgilmore looks good! One fix: the icon color is not changing in the dark theme, looks like the token needed is `$icon-primary`

**Comment by ariellalgilmore** [comment]
> @ariellalgilmore looks good! One fix: the icon color is not changing in the dark theme, looks like the token needed is `$icon-primary`

updated! thanks!

**Review by oliviaflory — APPROVED** [review]
Beautiful!

**Pull request merged**
