### PR TITLE
fix(card): removes light background override from static card class

### PR DESCRIPTION
**Pull request by NSDrowned**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6737

### Description

In React, `bx--card--static` class was overriding the light background set by `bx--card--light`. Now `cardStatic` and `light` props work separately.

### CODE REVIEW

**Review by ariellalgilmore — APPROVED** [review]
Thank you @NSDrowned!!

**Review by photodow — COMMENTED** [review]
Looks like I'm getting some sort of specificity issue in the card group on NextJS.

image

**Comment by NSDrowned** [comment]
> Looks like I'm getting some sort of specificity issue in the card group on NextJS.
> 
> image

I checked the template and the card groups have the G10 theme hardcoded:

image

Is that how it's supposed to be? ❓

**Comment by NSDrowned** [comment]
@photodow fixed the issue (be sure to clear cache):

image

**Comment by photodow** [comment]
Maybe I'm doing something wrong, but here are a couple of things I'm seeing.

- I'm seeing hover states on static cards.

- I'm seeing static card navigating to another page when clicked on.

- NextJS has some theming issues. Looks correct in Storybook at least?

**Review by photodow — APPROVED** [review]

**Pull request merged**
