### PR TITLE
fix(link-list): remove border hang

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

#6128 

### Description

Fixes incorrect border styles from `link-list-section` component

### Changelog

**Removed**

- add `-margin-left` and remove `margin-right` in non-mobile breakpoints

### CODE REVIEW

**Comment by shixiedesign** [comment]
Expecting lines to not hang at all actually, so that text and lines both start on the column. See below 

image

**Comment by kennylam** [comment]
> Expecting lines to not hang at all actually, so that text and lines both start on the column

@shixiedesign does this apply to `link-list-section` only? Because borders in other link list variations go into the gutter, for example `end of section`

image

**Comment by jeffchew** [comment]
Hey @shixiedesign , just checking if you had feedback for @kennylam 's question above? Wanted to see if this could get merged in soon.

**Comment by shixiedesign** [comment]
Dragos is following up I believe. We've aligned on Slack that we should treat `link list - end of section` and `link list section` consistently:
- hang both sides when single column
- hang left only when more than 1 column, which should give the 16px gap between columns.

**Comment by DragosRistici** [comment]
> Hey @shixiedesign , just checking if you had feedback for @kennylam 's question above? Wanted to see if this could get merged in soon.

@jeffchew @shixiedesign Yep. Followed up with Kenny about it. As soon as the previews will be up, I'll be on it.

**Comment by jeffchew** [comment]
Hey @DragosRistici just checking if this is good to go from a design perspective?

cc: @kennylam

**Comment by DragosRistici** [comment]
> Hey @DragosRistici just checking if this is good to go from a design perspective?
> 
> cc: @kennylam

Hey, @jeffchew, not yet. Kenny will take care of it soon. As soon as I see the update, I'm on it.

**Comment by DragosRistici** [comment]
Thank you, Kenny. This looks good. A few little issues: 


## A. Web Components



### A.1. CTA Block – with Link list

#### A.1.1. The component is off grid at all breakpoints so its hard to test it for this PR
Screenshot 2021-06-24 at 16 54 18
Screenshot 2021-06-24 at 16 51 47
Screenshot 2021-06-24 at 16 51 38



### A.2. CTA section – with Link list

#### A.1.1. The block is off the grid for all breakpoints.  Can't be too precise due to grid issues.
Screenshot 2021-06-24 at 20 06 10


### A.3. Link list section – Default
Looks good from this issue's point of view. 


### A.4. Link list – End of section
#### A.4.1. Mobile does not get right 16px hang
Screenshot 2021-06-24 at 19 47 58




## B. React



#### No issues regarding this PR.

**Comment by kennylam** [comment]
@DragosRistici This PR only addresses the border layout in the `link-list-section` web component.

**Review by shixiedesign — APPROVED** [review]
I think this PR addresses the issue with the rules and should be good to merge. Let's create new issues based on your comments on Link list and CTA block. Thanks!

**Review by jeffchew — APPROVED** [review]
LGTM!

**Comment by DragosRistici** [comment]
> @DragosRistici This PR only addresses the border layout in the `link-list-section` web component.

Sure. I'm good.

**Pull request merged**
