### PR TITLE
fix(card-in-card): create react wrapper

### PR DESCRIPTION
**Pull request by emyarod**
### Related Ticket(s)

#5339

### Description

This PR adds a React wrapper for the Card in card component

### Changelog

**New**

- Card in card React wrapper stories and Code Sandbox example
- link to wrapper story in `react` package docs

### CODE REVIEW

**Comment by shixiedesign** [comment]
Component looks good! Only issue is grid usage in the story is different from Web components. Can we make it the same as web components, with Carbon grid applied? Thanks!

image

**Comment by emyarod** [comment]
the grid should be applied correctly now!

**Review by annawen1 — APPROVED** [review]
LGTM!

**Review by shixiedesign — APPROVED** [review]
👍

**Pull request merged**
