### PR TITLE
fix(featureCard): change styles so user can still click

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

none

### Description

Due to card updates Feature Card in md/sm breakpoints link was broken. This updates styles to fix and allow user to click anywhere on card

### Changelog

**Changed**

- styles to remove position absolute

### CODE REVIEW

**Review by IgnacioBecerra — APPROVED** [review]
LGTM! Thanks @ariellalgilmore !

**Review by shixiedesign — COMMENTED** [review]
Web components looked in great shape, but noticed React `sm` breakpoint the card lost 2x1 aspect ratio: 
Current: 320x144px, expecting 320x160 for both the image and card content piece.

image

**Comment by ariellalgilmore** [comment]
> nents looked in great shape, but noticed React `sm` breakpoint the card lost 2x1 aspect ratio:
> Current: 320x144px, expecting 320x160 for both the image and card content piece.

Thanks Shixie, good catch! Looks like this is happening in [react production mode](https://ibmdotcom-react.mybluemix.net/?path=/story/components-featurecard--default) and out of scope of this PR. Can we make a seperate bug?

**Review by kennylam — APPROVED** [review]
LGTM thanks @ariellalgilmore!

**Comment by jeffchew** [comment]
@shixiedesign trying to catch up on this one, looks like what you mentioned could be a separate issue?

**Review by shixiedesign — APPROVED** [review]
Looks good!! Thank you!

**Pull request merged**
