### PR TITLE
fix(link-list): added proper background on hover and removed underline

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#5568

### Description
In React, `LinkList` CTA class lacked a background change on hover, underlining the text instead. This PR addresses this issue.

Before:
Screen Shot 2021-03-29 at 5 29 01 PM

After:
Screen Shot 2021-03-29 at 5 29 09 PM

### Changelog

**New**

- ensured proper background color appeared upon hover
- removed underline upon hover with LinkList

### CODE REVIEW

**Comment by shixiedesign** [comment]
I wonder if we can fix this in someway so Percy stop seeing the hover text. But anyhow, I approved this diff. 

image

**Review by shixiedesign — COMMENTED** [review]
I understand this issue is for hover state, so this bug might be out of scope - I noticed the focus state of this component is wrong. Lemme know if you can fix it here or I can make a new issue: 

**Current:**
image

**Expected**
`2px solid inside outline in $focus`

image

**Comment by IgnacioBecerra** [comment]
@shixiedesign Added a fix for #5674 into this PR. The underlining shouldn't happen anymore in Card.

**Review by shixiedesign — APPROVED** [review]
Looks good! Thank you so much! 👍

**Review by jeffchew — APPROVED** [review]
LGTM!

**Pull request merged**
