### PR TITLE
fix(drop-down): arrow size and alignment fix

### PR DESCRIPTION
**Pull request by NSDrowned**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5604

### Description

Fixes arrow size and alignment

### CODE REVIEW

**Comment by shixiedesign** [comment]
Dropdown's chevron is fixed! 🎉 There are some unusual variants to Carbon's dropdown and they are also in need of this fix: 

- Combo box is still showing the issue: 
image

- Multi select also 
image

**Comment by NSDrowned** [comment]
@shixiedesign, no problem, I'll fix them too

**Comment by NSDrowned** [comment]
@shixiedesign fixed both of them 👍

**Comment by IgnacioBecerra** [comment]
Ah, there was a MultiSelect issue open (#5606). I'll add you as assignee @NSDrowned!

**Comment by NSDrowned** [comment]
Oh, #5602 also fixed with this PR

**Comment by oliviaflory** [comment]
@NSDrowned Dropdown, multi select, combo box and select all look good! 👍 

Percy is detecting some changes in UI shell and number input, is that because of the upgrade and we should ignore in this PR / Percy approval? I haven't approved them yet because I wanted to double check with how we handle that.

**Comment by jeffchew** [comment]
@NSDrowned just curious why this has a bunch of other changes in the PR, was this cut from master or the chore branch?

**Review by shixiedesign — APPROVED** [review]
Looks good! Thanks!

**Review by jeffchew — APPROVED** [review]
Thank you @NSDrowned !

**Pull request merged**
