### PR TITLE
feat(feature-section): add "Feature section" layout component

### PR DESCRIPTION
**Pull request by proeung**
### Related Ticket(s)
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6246

DDS Tickets: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6118
HC JIRA Ticket: https://jsw.ibm.com/browse/HC-1971

### Description
- This PR adds the "Feature Section" layout component/pattern that's needed in the new "Service" landing page template that will be implemented in the AEM CMS.
- This component is a variant of HC's [Module 11A](https://pages.github.ibm.com/MSC-Cloud/hc_fractal/components/detail/11a--default.html) and this iteration is the first version that will be going into the MVE state of the "Service" landing page.

### Design & Functional Specs
- https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Feature-section

component--feature-card-block-large--visual-specs--max copy

### Changelog

**New Components/Props**

- `<dds-feature-section>` – this new layout component is a variant/extension of the `<dds-feature-card>`.
- `<dds-feature-section-card-link>` – this component is an extension of the `<dds-card-link>` and needed because the feature section component requires a card-link with higher max-width.
- `media-alignment` - a prop  `(right (default) | left)` that can be passed as an attribute.

**Removed**

- N/A

**Note**

- The current implementation of the `<dds-card-link>` UI component doesn't offer CTA types such as Video, document, external, etc. The component looks to be extended from the `dds-card`, where it should be using `dds-cta-card` component.
- Looks like this is a known issue (see - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5740)

**Testing Instructions**
- Visit the `Feature section` - `/?path=/story/components-feature-section--default`
- Ensure that the component matches with the design specs for all breakpoints.

### CODE REVIEW

**Review by andysherman2121 — APPROVED** [review]
@proeung Looks great!

**Comment by proeung** [comment]
@andysherman2121 Thanks for the code review.

Looks like we're still missing design QA for this PR. Can someone from the design team help QA this component? Thanks!

**Comment by skuruvil** [comment]
@proeung Looks great, Here are some of the changes I have identified. Please let me know if you want to discuss these edits. Thank you

**Grid usage on breakpoints** 

1.	This component is full bleed / full width and no margin on both sides
2.	Card Link grid mode is condensed / 16 pix overhang both side
Screenshot 2021-06-17 at 2 24 36 AM

Max:
1.	Text padding on left side is 40px including the 24px margin 
2.	Text padding on top 40px
3.	Card Link width 4 column with 16 pix overhang both side

Xlarge and large:
1.	Text padding on left side is 32 px including the 16px margin 
2.	Text padding on top 32px
3.	Card Link width 4 column with 16 pix overhang both side

Medium:
1.	Text padding on left side is 32 px including the 16px margin 
2.	Text padding on top 32px
3.	Text width calc (7 col – 32px)
4.	Card Link width 4 column with 16 pix overhang both side
5.	Image aspect ratio: 4:3
Screenshot 2021-06-17 at 2 29 32 AM

 
  
Small:
1.	Card Link width: 3 columns

Screenshot 2021-06-17 at 2 32 07 AM


**Interactive states using correct styling**

1.	Card link color seems to be wrong, as per design specs it should be gray 10 (default)




**Themeing**

1.	As per design specs, text card background color token should be $inverse-02 (i.e., in white and gray 10 theme, text card background would be in Gray 80 and all the text colors on the text card should be $inverse-01 (white), including the Eyebrow text.  




**Storybook**

1.	Card Eyebrow and Card copy are optional 
2.	Media Alignment option was not provided in the design specs

**Comment by proeung** [comment]
@skuruvil Thanks for doing the design QA for this PR!

I just pushed up some commits that should address all of your design QA feedback with the exception of the theming question. The Card Link palette looks to be showing up fine for me (see attached). Can you check the "Carbon Theme" knob?

Components___Feature_section_-_Default_⋅_Storybook

**Comment by skuruvil** [comment]
@proeung Putra Roeung Bonaccorsi Thank you for taking the time to discuss today. The confusion around the Theming has resolved. Most of my QA feedback is fixed now, except the grid alignment for the card link on the larger screens.

**Comment by proeung** [comment]
@skuruvil I just pushed up a commit that fixes the grid alignment/max-width of the card-link component. The new preview is building and should be ready for your re-review soon.

**Comment by shixiedesign** [comment]
Hi @proeung ! Only 2 things I noticed: 

1. The arrow in the Card link is not accessible. When Card link is in inverse theme, the arrow should get $inverse-link color which is blue-40
image

2. When media is left aligned, the Card link goes off grid. This is an extra feature. We were not planning on exposing the knob yet 😆 But since you have it...here's a suggestion I came up with on the fly. I think if time is short, simply hiding the knob would do too. 

**Current:**
image

**Proposed new design:**
image

**Comment by proeung** [comment]
@shixiedesign Please see my response below.

> The arrow in the Card link is not accessible. When Card link is in inverse theme, the arrow should get $inverse-link color which is blue-40

This issue should be fixed. Please check the deploy preview once it's done building.

> When media is left aligned, the Card link goes off grid. This is an extra feature. We were not planning on exposing the knob yet 😆 But since you have it...here's a suggestion I came up with on the fly - just keep Card link in the right portion always. I think if time is short, simply hiding the knob would do too.

I just went ahead and adjusted the "Left" alignment layout based on the new purposed design that you mentioned above (see attached video). I don't have the design specs of this particular layout for tablet and mobile breakpoints, so there might be something that I'm missing. Regardless, I'm happy to revert this [commit](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6344/commits/2d9bb5f4d2bc63bbac0a0bdceefb8013d8d0d4ff) and hide the "Media Alignment" knob if you think what I've implemented can be push and review for another sprint.


https://user-images.githubusercontent.com/1815714/123164422-eaf74080-d440-11eb-8031-a5f884aacffd.mov

**Review by shixiedesign — APPROVED** [review]
Looks great! Thank you!

**Comment by shixiedesign** [comment]
Hey @proeung ! Looks great and thank you for making the design fix! Looks like 

1. there's a ci-check that failed so blocking merge 
2. Here's a small issue - apostrophe seems to get rendered as unicode. Just a bit nod. 

image

**Comment by jeffchew** [comment]
@proeung looks like snapshots are out of date here, can you update?

**Comment by proeung** [comment]
@jeffchew @shixiedesign Just pushed up an updated snapshot. Please check again.

**Pull request merged**
