### PR TITLE
feat(expressive-theme): sunset of the expressive theme

### PR DESCRIPTION
**Pull request by jeffchew**
### Related Ticket(s)

Refs https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6747

### Description

This merges the feature branch `feat/expressive-sunset` into the `master` branch. This is the culmination of work from the last few months to effectively remove the expressive theme across `Carbon for IBM.com`.

### Changelog

**Changed**

- Multiple changes, see epic https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5944

**Removed**

- Expressive theme as default from `Carbon for IBM.com`

### CODE REVIEW

**Comment by jeffchew** [comment]
Not sure why status is not updating, but the Percy diff has been generated:

React: https://percy.io/538fc19a/Carbon-for-IBM.com-React/builds/12417706/changed/701006488
Web Components: https://percy.io/538fc19a/Carbon-for-IBM.com-Web-Components/builds/12393601/changed/699715123

**Comment by jeffchew** [comment]
@shixiedesign @oliviaflory fyi, the percy diffs are announcing now, but looks like when the PR was opened, it was initially auto-approved from a previous setting for the feature branch. You probably will still need to review the diffs.

**Comment by shixiedesign** [comment]
Largely looking good! Some observations: 

1. Language switcher (React & WC) need to be updated to use `lg`, so the field height is 48px
image

2. Locale switcher (WC)'s icon should be smaller, becoming 16px. Currently it stayed 20px while text label shrunk to 14px:
image

3. Carousel buttons: the active button's caret size got bigger for some reason: 
image

4. CTA - Text: Token not found! The size of the text is correct (16px) but line height is wrong. Should be 22. This caused the height of the link to be too small: 
image

**Comment by shixiedesign** [comment]
Olivia will likely have more comments. @jeffchew should these be captured as issues and we fix after merge?

**Comment by jeffchew** [comment]
> Olivia will likely have more comments. @jeffchew should these be captured as issues and we fix after merge?

Thank you @shixiedesign !

Would these need to be addressed before `v1.25.0` release? We still have this sprint and half of next sprint before the next code freeze.

Might be good if we merge and capture as issues. If they are urgent we can jump on those right away.

**Comment by jeffchew** [comment]
PR status is not announcing again for percy. Here are the latest builds:

React: https://percy.io/538fc19a/Carbon-for-IBM.com-React/builds/12489214/changed/704983512
Web Components: https://percy.io/538fc19a/Carbon-for-IBM.com-Web-Components/builds/12489417/changed/704991015

**Comment by jeffchew** [comment]
@shixiedesign @oliviaflory PR opened to address the first two items mentioned above: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/7055

**Comment by jeffchew** [comment]
> 4. CTA - Text (WC): Token not found! The size of the text is correct (16px) but line height is wrong. Should be 22. This caused the height of the link to be too small:
>    image
>    React is correct:
>    image

@shixiedesign @oliviaflory Not sure if it's something with dev tools, but in the shadowRoot, the line-height looks correct:

image

**Comment by jeffchew** [comment]
@shixiedesign @oliviaflory opened a PR for item number 6: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/7056

**Comment by oliviaflory** [comment]
Going to continue off of Shixie's list so we can keep some order to these notes:

7. **Filter panel**
Text and icon are not vertically centered within the accordions 

Screen Shot 2021-09-02 at 11 11 56 AM


8. **Leaving IBM** 
The line height of the label looks off, seems to be set to 1.29rem which is 20.64px, which isn't quite right for any of the tokens. Not sure if this is coming directly from Carbon or if it's something we had originally overrode, would love some input from devs on this one!

Screen Shot 2021-09-02 at 11 17 17 AM

**Comment by jeffchew** [comment]
@oliviaflory opened a PR to address item #7: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/7059

**Comment by jeffchew** [comment]
> 8. **Leaving IBM**
>    The line height of the label looks off, seems to be set to 1.29rem which is 20.64px, which isn't quite right for any of the tokens. Not sure if this is coming directly from Carbon or if it's something we had originally overrode, would love some input from devs on this one!
> 
> Screen Shot 2021-09-02 at 11 17 17 AM

Took a look, it seems to be using `label-02`:

image

And looking directly in `@carbon/type`, `1.29rem` is what is being used:

image

**Comment by oliviaflory** [comment]
> > 1. **Leaving IBM**
> >    The line height of the label looks off, seems to be set to 1.29rem which is 20.64px, which isn't quite right for any of the tokens. Not sure if this is coming directly from Carbon or if it's something we had originally overrode, would love some input from devs on this one!
> > 
> > Screen Shot 2021-09-02 at 11 17 17 AM
> 
> Took a look, it seems to be using `label-02`:
> 
> image
> 
> And looking directly in `@carbon/type`, `1.29rem` is what is being used:
> 
> image
> 
> Digging some more, it was updated with this issue: #6205, and done in this PR: #6928

Thanks for looking into it @jeffchew, let's leave it for now and we can open a ticket on Carbon side to fix the line height. No reason to override styles from their package.

**Review by IgnacioBecerra — APPROVED** [review]

**Pull request merged**
