### PR TITLE
feat(date-picker): sync with @carbon/react v11

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#10101 
### Description

sync with @carbon/react update stories and added new props

### Changelog

**New**

- {{new thing}}

**Changed**

- reverted flatpickr version back because old issue was appearing when using range the first date value would not display

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by IgnacioBecerra** [comment]
Looking good! Just missing the `allowInput` and `closeOnSelect` knobs

**Comment by oliviaflory** [comment]
@ariellalgilmore 👏 👏 👏 for taking on date picker

### Read only
- When there is no date selected, the border color is different (darker) than React. I can't find the correct token on the website, but can try to ask the designers 

**React**
Screenshot 2023-04-17 at 2 29 28 PM


**WC**
Screenshot 2023-04-17 at 2 30 27 PM

 
### Disabled
- Disabled knob isn't updating the color token for the `simple` variant

Expecting
Screenshot 2023-04-17 at 4 50 29 PM


### Invalid and Warning
- Warning icons need a dark fill for the ! in the light themes
Screenshot 2023-04-17 at 4 57 46 PM
Screenshot 2023-04-17 at 4 57 53 PM

- Warning and invalid icons are overlapping the `yyyy` in the `simple` variant
- Are the icons also tied to the warning/invalid text container? They seem to move beyond the input field when the text gets long
Screenshot 2023-04-17 at 3 00 40 PM
Screenshot 2023-04-17 at 3 00 59 PM
Screenshot 2023-04-17 at 3 01 18 PM

### Days within calendar
- React shows the says as S / M / T / etc, while WC is showing `Sun` / `Mon` / `Tue`. I didn't see that as a knob option, should we should match the React version?

**React**
Screenshot 2023-04-17 at 4 46 04 PM

**WC**
Screenshot 2023-04-17 at 4 45 49 PM


### Missing Helper text knob in storybook

**Comment by ariellalgilmore** [comment]
updated! the only thing not fixes is the picture below since it also happens in react :/
Screen Shot 2023-04-18 at 9 27 01 AM

**Review by IgnacioBecerra — APPROVED** [review]
LGTM, thanks @ariellalgilmore!

**Review by kennylam — APPROVED** [review]
LGTM!

**Pull request merged**
