### PR TITLE
feat(code-snippet): update story to Storybook v7

### LINKED ISSUE #11311: [carbon-web-components]: code snippet Storybook 7 update

### PR DESCRIPTION
**Pull request by m4olivei**
### Related Ticket(s)

Closes #11311

### Description

Adjustments to code-snippet component to be compatible with Storybook v7.

### Changelog

**Changed**

- Updated code-snippet Storybook component for Storybook v7

### CODE REVIEW

**Comment by m4olivei** [comment]
As an aside, I noticed a couple of bugs with code snippet here, also on the `main` branch:

* Multiline is missing the clipboard icon. Just shows two perpendicular lines on hover:

image

* In the Playground story, after setting `feedback` and `feedbackTimeout`, the feedback dissapears nearly instantly, even with a `feedbackTimeout` of 5000 (5 seconds).

**Review by RichKummer — APPROVED** [review]
LGTM @m4olivei !

One question: would there be a quick way to add the layering design from the react Storybook into this? The format in react does a great job of highlighting the layer structure which feels missing here.

Screenshot 2024-01-08 at 1 44 34 PM

**Comment by m4olivei** [comment]
Thanks for the review @RichKummer !

> One question: would there be a quick way to add the layering design from the react Storybook into this? The format in react does a great job of highlighting the layer structure which feels missing here.

Yes! This is now fixed.

After your comment I dug in a bit more on this point. I discovered that stories for some components, including code-snippet, we were not fully declaring their dependencies for the layering decoration. This gets exposed with the small set of components that we're presently rendering in this branch of Storybook, as we build back up to the full set. I've corrected that in this and all my other PR's that incorporate the same "With Layer" style stories.

**Review by IgnacioBecerra — APPROVED** [review]
LGTM!

**Pull request merged**
