### PR TITLE
fix(various modals): address focus trapping issues

### LINKED ISSUE #8146: [Locale Modale]: Web Components - VO - Focus trapping not working in mobile
**Engineering info:**  
- Innovation Team engineer: @andy-blum 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2393
- DPO consulting engineer: N/A

-----

### Description

Focus trapping is not working for the locale modal in mobile.

One thing to try is to change the sentinel nodes to button elements instead of anchor elements as done in: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8074. This would have to be done in the `carbon-web-components` modal component as locale modal is extending that.

https://user-images.githubusercontent.com/54281166/150870389-0e73f33a-66dc-4045-9021-2c20f3c6b98e.mov

### Component(s) impacted

Locale Modal

### Browser

Safari

### Carbon for IBM.com version

1.30.0-rc.1

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

https://www.ibm.com/standards/carbon/web-components/?path=/story/components-locale-modal--default

### Package

@carbon/ibmdotcom-web-components

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)

Fixes #8146 #7852 https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5670 

### Description

Numerous accessibility fixes related to expressive-modal, locale-modal, locale-search, locale-item, and region-item. The attached video has VO narration and my commentary.

https://user-images.githubusercontent.com/25532785/153033779-9db71024-e7e0-46e2-a14f-60fa4ec6c362.mov

### Changelog

**Changed**

- Fixed focus trapping in modals on iOS
- Numerous accessibility improvements to the locale-modal collection of components

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
it looks like there is now a CI issue with one of the tests for selecting a region

**Comment by andy-blum** [comment]
@emyarod ran the unit test locally and it passed just fine. Also did a manual walkthrough of the code and I don't see anything that seems brittle. I'll update the branch and we'll see how it goes.

Screen Shot 2022-02-09 at 12 54 56 PM

**Comment by andy-blum** [comment]
This PR _should_ also address the issues with focus trapping in `expressive-modal` noted in issue #5670

**Comment by andy-blum** [comment]
... or not. 
Screen Shot 2022-02-09 at 1 29 55 PM

It looks like the tabbing order here jumps from the iframe to the end sentinel and that `relatedTarget` is null for some reason. This will need further investigation & work 😩

**Comment by andy-blum** [comment]
And the unit test still fails 🤔

**Comment by oliviaflory** [comment]
@proeung I can take a look later today!

**Review by proeung — CHANGES_REQUESTED** [review]
@andy-blum Code changes look good overall, however, I'm noticing a style regression issue within the `Local Modal` component where there's extra indent in the `dds-region-item` component (see attached). Can you take a look?

Screen Shot 2022-02-15 at 3 29 09 PM

See Percy Visual diffs - https://percy.io/538fc19a/Carbon-for-IBM.com-Web-Components/builds/15670890/changed/884808610?browser=chrome&browser_ids=20&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1280&widths=320%2C1280

**Comment by oliviaflory** [comment]
## Locale modal

### 1. Alignment of the region button text 
Asia Pacific and Middle East & Africa are off on Desktop and Mobile breakpoints, see [Percy comparison](https://percy.io/538fc19a/Carbon-for-IBM.com-Web-Components/builds/15670890/changed/884808610?browser=chrome&browser_ids=20&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=320%2C1280)

| Current | Expecting | Notes |
| --- | --- | --- |
| Screen Shot 2022-02-15 at 1 22 26 PM |  Screen Shot 2022-02-15 at 1 23 49 PM | Text should be left aligned, and I am not expecting the line to break |
| Screen Shot 2022-02-15 at 1 17 37 PM | Screen Shot 2022-02-15 at 1 19 07 PM | Text should be left aligned, and not expecting a line break. Note: this screen shot is from the updated specs and we have not yet made arrow blue |


### 2. Hover on Europe (disabled button)
- The icon is moving on hover
- The whole button is not showing the hover color change, only 1/3 of the button changes color

I would have expected the disabled button to not have a hover state, and follow the disabled guidance from Carbon button.
_Note: This is hoverable in the current build (a bug!) so I understand if we should fix this in another issue._
https://user-images.githubusercontent.com/45692622/154144433-1e6e2dac-1486-4aaf-a401-8a83de7dfedf.mov



## Percy
Percy is picking up vis changes on the [Content block mixed](https://percy.io/538fc19a/Carbon-for-IBM.com-Web-Components/builds/15670890/changed/884808511?browser=chrome&browser_ids=20&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=320%2C1280) and [Content group cards](https://percy.io/538fc19a/Carbon-for-IBM.com-Web-Components/builds/15670890/changed/884808511?browser=chrome&browser_ids=20&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=320%2C1280) stories, did we change those to buttons too?
Screen Shot 2022-02-15 at 1 37 18 PM

I'm still working on testing in VO on mobile iOS but thought I'd point out these first

**Comment by andy-blum** [comment]
@oliviaflory Thanks for looking this over! The changes you're noting about the text/icons alignment is from switching from `<a>` tags to `<button>` tags. My latest push should remedy those issues. The Europe:hover issue should also be fixed.

The VO cursor reading out the link items is a weird one for sure, and one I wasn't able to find a reliable fix to. It might be better split off as its own issue.

The content block cards will have changed because they are using the expressive-modal component to open the video overlay.

**Comment by oliviaflory** [comment]
Thanks @andy-blum from a visual standpoint this looks good! We can open the disabled state fix and the VO tapping problem in separate issues.

@kennylam  or @IgnacioBecerra are either of you able to confirm the VO is accurate for mobile?

**Review by oliviaflory — APPROVED** [review]
Looks good from a visual standpoint, thanks @andy-blum

**Review by proeung — APPROVED** [review]
LGTM!

**Comment by proeung** [comment]
@kennylam I'm seeing all of the required CI checks are marked successfully, however, this PR doesn't seem to be merging. Can you help take a look? Thanks!

**Comment by kennylam** [comment]
@proeung It's currently queued in position 2.

image

**Pull request merged**
