### PR TITLE
fix(notification): padding and margin fix

### PR DESCRIPTION
**Pull request by NSDrowned**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5607

### Description

- Fixed margins and paddings
- As requested, I added the padding fix to the toast notification

### CODE REVIEW

**Comment by shixiedesign** [comment]
I see that Inline is fixed but the same problem appears to show in Toast. Sorry this is a bit of a scope creep. Is it a relatively easy fix? We can update the issue with this info and increase story points. 

image

**Comment by NSDrowned** [comment]
@shixiedesign, sure, I'll fix that too 👍

**Comment by NSDrowned** [comment]
@shixiedesign, fix for toast is ready:

https://carbon-expressive.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/5661/index.html?path=/story/notifications--toast

👍

**Comment by shixiedesign** [comment]
Thank you! One last nitpick.. I think inline notification's icon and content are 2px too far left. Should start with grid, so Toast is correct. 

Mar-30-2021 16-53-21

**Comment by NSDrowned** [comment]
@shixiedesign done! 👍

**Review by shixiedesign — APPROVED** [review]
Awesome! Thank you so much!

**Review by jeffchew — APPROVED** [review]
Thank you @NSDrowned !

**Comment by annawen1** [comment]
Nothing blocking, but i usually like to do something like `carbon--rem(32px);` since it's easier to gauge spacing with `px` personally but having the direct rems should be ok too

**Comment by NSDrowned** [comment]
@annawen1, ohh, didn't know that one. It will help me out  a lot, thanks! 👍

**Comment by jeffchew** [comment]
@NSDrowned just took the `ready to merge` label off. Was this pulled from the carbon upgrade branch? I don't see it currently targeting that branch.

**Pull request merged**
