### PR TITLE
fix(storybook-image): realligned web component and react images

### PR DESCRIPTION
**Pull request by andysherman2121**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7014

### Description

Our React and Web Component storybooks were misaligned when looking at which images we're using for examples. This PR updates the React storybook images to match the web component storybook. 

Components affected:

Callout with media
Card Group w/Images
Card section images
Content Block Cards
Content Block Segmented
Content Group Simple
Feature Card
Leadspace
Leadspace Block

### CODE REVIEW

**Review by kennylam — APPROVED** [review]
LGTM thanks @andysherman2121!

**Review by emyarod — APPROVED** [review]
looks good to me!

**Comment by jeffchew** [comment]
@andysherman2121 can you update snapshot files and sign the DCO?

**Comment by andysherman2121** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by andysherman2121** [comment]
recheck

**Comment by andysherman2121** [comment]
I have read the DCO document and I hereby sign the DCO.

**Pull request merged**
