### PR TITLE
test(e2e): introduce puppeteer to send e2e percy snapshots

### PR DESCRIPTION
**Pull request by jeffchew**
### Related Ticket(s)

Refs #5474 

### Description

This update introduces puppeteer for Percy, where tests can be
generated to send snapshots of interactive states in Storybook to Percy
for automated visual regression testing.

This also includes moving puppeteer into its own package. The motivation here is that the testing is not reliant on a built local environment, but using lower environments (deploy previews, canary, staging, etc) as the place where e2e tests are run. There is also a large amount of overlap between React and Web Components, where it makes sense to have a single set of tests that can be run on either storybook.

There is also a minor fix to the data-autoid for the navigation items between React and Web components. The web component version was adding a dash before the nav number, where the React version is not.

In addition, there needed to be a way to set the theme in the `Leadspace` component in the full window version in order to test theming in percy, so a `theme` query param has been added for that purpose.

Note, web components tests are not working yet. Will see if these can be fixed in another PR.

The Jenkins job has also been set up to trigger the e2e tests, but is currently not hooked up from the deploy preview CI runner yet. I'll hook this up once this PR is merged in, but I have already ran the CI job manually and has been already posting the results to this PR: 

https://percy.io/538fc19a/Carbon-for-IBM.com-React-e2e/builds/9439782?utm_campaign=538fc19a&utm_content=Carbon-for-IBM.com-React-e2e&utm_source=github_status_public

### Changelog

**New**

- switched out `wdio` with `puppeteer`
- e2e tests for Percy (masthead, localemodal, leadspace)

**Changed**

- updated `chromedriver` to v89
- Tweak to `data-autoid`'s for the web components masthead to match React
- added `theme` query param for leadspace stories

**Removed**

- removed old e2e tests

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Good move to Puppeteer! I think the next step is replacing the "wait for 3s" thing with "wait for particular state" thing. Timeout is one of biggest sources of test flakiness. Thanks @jeffchew!

**Comment by jeffchew** [comment]
> Good move to Puppeteer! I think the next step is replacing the "wait for 3s" thing with "wait for particular state" thing. Timeout is one of biggest sources of test flakiness. Thanks @jeffchew!

Agreed, I was mostly getting the harness in place but can probably pick better elements to wait for with `page.waitForSelector`.

The other thing I was wrangling with is waiting for motion to finish, where I just added a `page.waitForTimeout` for that for now.

**Comment by asudoh** [comment]
Cool, this may be of your interest: https://developer.mozilla.org/en-US/docs/Web/API/Element/getAnimations

**Comment by asudoh** [comment]
BTW, another approach to cope with motion in tests is injecting CSS to disable motion.

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jeffchew!

**Pull request merged**
