### PR TITLE
fix(structured-list): Ensure group header text can go full width

### PR DESCRIPTION
**Pull request by pjudge**
### Related Ticket(s)

Fixes: #10449 

### Description

This PR adds `max-width: 100%` to the group headers (`<th>`) of structured lists so that the text content inside of them may take up the full width of their containers. 

It also adds lorem ipsum text to Group 2 inside the storybook for demonstration purposes.

### Changelog

**Changed**

- Updated the max-width of Structured List group headers. 
- Updated the storybook with Lorem Ipsum for the Group 2 header, to demonstrate new style.

### CODE REVIEW

**Comment by andy-blum** [comment]
Tagging @areagan1030 as she initially reported this.

**Comment by areagan1030** [comment]
@jkaeser Yes, works as expected! Thank you!

**Comment by jkaeser** [comment]
🎉 @pjudge All tests passed! 🎉

**Comment by andy-blum** [comment]
@oliviaflory can you approve the Percy diffs?

**Review by andy-blum — APPROVED** [review]

**Review by oliviaflory — APPROVED** [review]
LGTM!

**Pull request merged**
