### PR TITLE
chore(content-group-pictogram): syncing stories and spacing updates

### PR DESCRIPTION
**Pull request by guilhermelMoraes**
### Related Ticket(s)

[Content group pictograms] Storybooks QA #5666

### CODE REVIEW

**Comment by skuruvil** [comment]
@guilhermelMoraes As per design spec at max width both Intro section and pictogram item extend only till 7 column (Max-width: 640px). But current SB previews, I can see the pictogram item extends to 8 columns. Rest all looks good to me. CC @shixiedesign @DragosRistici 


Screenshot 2021-10-06 at 10 58 02 PM

**Comment by oliviaflory** [comment]
Hey @guilhermelMoraes, the content group pictogram changes look good! Seems aligned to the grid and everything. 

Percy is picking up a lot of changes across different stories, like dotcom shell, tabs extended and footer, that don't have content group pictograms in them. Do you have any idea what might be causing the Percy changes?

**Comment by oliviaflory** [comment]
hey @guilhermelMoraes or @BrunnoM7 it looks like the React build failed, could either of you kick it off again? 

I checked the web components preview and it looks good! 

I'm still seeing the inset comment I made (2.) about the alignment in React content block mixed on the Percy snapshot.

**Comment by jeffchew** [comment]
Sorry @oliviaflory , just saw your note! I just ended up updating the branch to kick off all jobs again, hope it goes through this time!

**Comment by oliviaflory** [comment]
Thanks @jeffchew for fixing the builds!

In React I'm still seeing the shift of the `Content group pictograms` within the `Content block mixed` and `Content block mixed with aside elements` in Storybook and Percy at all breakpoints. If we can get that fixed this will be good to go!
Screen Shot 2021-11-04 at 4 47 30 PM

Screen Shot 2021-11-04 at 4 51 08 PM

Screen Shot 2021-11-04 at 4 48 06 PM

**Comment by guilhermelMoraes** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by guilhermelMoraes** [comment]
recheck

**Comment by oliviaflory** [comment]
Hey @guilhermelMoraes I am still seeing the inset content group pictograms in the Content block, so the alignment on the grid isn't quite right. See [comment above](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/7314#issuecomment-961460326) for the image reference.

I'm not sure what could be causing it, any ideas?

**Comment by shixiedesign** [comment]
Hey @guilhermelMoraes, Web components look good! Trying to see what's left to do on this one. Like @oliviaflory said, only issue I see is a regression in React. I know you might still be working on it, just wanna mention it to you. Let us know when you'd like another look. 

image

**Review by oliviaflory — APPROVED** [review]
LGTM, thank you @guilhermelMoraes for all your hard work!

**Review by BrunnoM7 — APPROVED** [review]
LGTM

**Pull request merged**
