### PR TITLE
test(storybook): exclude storybook e2e tests from browserstack

### PR DESCRIPTION
**Pull request by annawen1**
### Related Ticket(s)

{{Provide url(s) to the related ticket(s) that this pull request addresses}}

### Description

Storybook Docs e2e tests don't need to be run on Browserstack, so add the files to the `exclude` field. 

Also remove the no longer necessary `if` statement in the cloud-masthead test checking for the `env` variable.

### CODE REVIEW

**Review by ariellalgilmore — APPROVED** [review]
LGTM!

**Comment by IgnacioBecerra** [comment]
@annawen1 All of the e2e tests for the cloud masthead are failing... Could be that the component never loads?

**Review by kennylam — APPROVED** [review]
LGTM thanks @annawen1!

**Comment by ariellalgilmore** [comment]
the cloud masthead issue will be fixed in this PR:https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8233

**Comment by jeffchew** [comment]
@annawen1 looks like there's merge conflicts now that #8233 is merged, can you take a look?

**Review by jeffchew — APPROVED** [review]
LGTM!

**Pull request merged**
