### PR TITLE
fix(structured-list): remove margin-bottom in component shadowroot

### LINKED ISSUE #8963: [Structured List]: Remove margin bottom in the shadow root for flexibility & addition of <dds-hr>
**Engineering info:**  
- Innovation Team engineer: @andy-blum 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2485
- DPO consulting engineer: N/A

-----

### Description

- The AEM team is in the midst of adopting the Structure List and noticed some discrepancies related to the rendering of some of the spacing.
- Right now, we have a margin-bottom of `5rem or 80px`  within the structure list shadow root which doesn't align with the spacing between the Structured List and the horizontal rule defined in the template (see attached).
- The spacing should be set to `160px` on max, xlg, lg | `96px` on md | `64px` on sm - cc: @jwitkowski79 
_Test__Jen_W_Product_Features_and__Test__Jen_W_Product_Features_and_Product_Template_Features_Capabilities_MVE_Round6_sketch
Screen Shot 2022-06-08 at 10 30 41 (1)

### Proposed Solution

- Remove margin-bottom and allow for adopters to define the spacing.
the 

### Component(s) impacted

Structured List

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### Carbon for IBM.com version

v.1.34.0 +

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

AEM

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

N/A

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)

Closes #8963 

### Description

Removes margin inherited margin-bottom of the `<section>` wrapper around the `DDSStructuredList`'s shadowroot

### Changelog

**Changed**

- Removes unnecessary spacing from DDSStructuredList

### CODE REVIEW

**Review by RichKummer — APPROVED** [review]
Seeing the spacing removed on the `Structured list` variants. @jwitkowski79 should probably double check for this one

**Review by IgnacioBecerra — APPROVED** [review]

**Comment by proeung** [comment]
@RichKummer This change came from the design QA that @jwitkowski79 conducted on the AEM side for the Structure List component (see - https://jsw.ibm.com/browse/ADCMS-2160?focusedCommentId=8777925&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-8777925). We can hold off on merging this change down until we have @jwitkowski79's approval if you like.

**Comment by RichKummer** [comment]
> @RichKummer This change came from the design QA that @jwitkowski79 conducted on the AEM side for the Structure List component (see - https://jsw.ibm.com/browse/ADCMS-2160?focusedCommentId=8777925&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-8777925). We can hold off on merging this change down until we have @jwitkowski79's approval if you like.

I'd prefer to wait for @jwitkowski79 to take a look and double check. Thanks @proeung !

**Review by jwitkowski79 — APPROVED** [review]
@andy-blum looks good! Thank you!

**Pull request merged**
