### PR TITLE
fix(featured-section): adjust target new tab issue by extending dds-card-cta

### PR DESCRIPTION
**Pull request by proeung**
### Related Ticket(s)

DDS Consulting Issue: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7072
HC JIRA Ticket: https://jsw.ibm.com/browse/HC-2217

### Description
- This PR extends `dds-card-cta` for the `dds-feature-section-card-link` used in the CTA card area, so that adopters can define the CTA type, etc.

### Testing Instructions
Screen Shot 2021-09-24 at 3 14 48 PM

- Visit the `Feature Section` layout Component - `?path=/story/components-feature-section--default`
- Adjust the `CTA Type` to `external`.
- Confirm that the `target="_blank"` attribute is added to the shadow DOM of the `<a>` link and that the CTA opens into a new tab.

### CODE REVIEW

**Comment by skuruvil** [comment]
@proeung Looks good to me, the CTA opens into a new tab now. However, I found another small issue, while clicking the CTA the image gets disappear.
Screenshot 2021-09-27 at 9 32 57 PM

**Comment by proeung** [comment]
@skuruvil The image disappearing on focus is a known issue and I believe it might be related to the changes from this PR (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6769). I'm happy to adjust this issue within this PR, but I'll defer to @NSDrowned as I don't want to revert/affect any changes that he's made.

**Comment by kennylam** [comment]
@proeung FYI unfortunately Julio is no longer with the team. So if you can make that focus fix in this PR, go for it. Thanks!

**Comment by proeung** [comment]
@kennylam Got it. Thanks for letting me know. I just pushed up a fix for the image that disappeared on focus issue. Can you take a look?

**Review by ariellalgilmore — APPROVED** [review]
LGTM! Thanks @proeung

**Review by kennylam — APPROVED** [review]
LGTM thanks @proeung!

**Pull request merged**
