### PR TITLE
test(cta): Add tests for card-type CTAs

### LINKED ISSUE #7755: [Test Scenario] CTA - Card: DDS Consulting
**Engineering info:**  
- HC engineer: Pending 11/30 Sprint Planning
- HC JIRA Ticket: https://jsw.ibm.com/browse/HC-2335
- DDS consulting engineer:

----

### Component and test scenario title

CTA - Card

### Test scenario steps

a. Check card, cta link is loaded 
b. Verify the whole card is clickable
c. Change CTA type on knobs section:
- Verify Jump option
- Verify External option
- Verify Download option
- Verify Video option
d.  Verify on hover, card background turns grey and the content remains same
Note: Card has copy text and  can be customized

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)

Closes #7755 #7756 #7757 

### Description

Adds e2e-storybook test coverage to web component card-like CTA components (React analogs coming soon)

**NOTE:** Tickets for card-cta and card-link-cta ask to test hover states, but it seems cypress isn't able to test CSS `:hover` states, it's only able to trigger `mouseover` events.

### Changelog

**New**

- e2e-storybook test for `dds-feature-cta`
- e2e-storybook test for `dds-card-cta`
- e2e-storybook test for `dds-card-link-cta`

### CODE REVIEW

**Comment by andy-blum** [comment]
@jeffchew the card-is-fully-clickable test will continue to fail on mobile due to #7806 

Looking into the icon mismatches

**Comment by andy-blum** [comment]
@jeffchew #7756 asks for the testing scenario where the different CTA types are loaded up and checked, but no knobs exist on the react CardLink component. Should we skip that test for now, or add in that knob?

**Comment by andy-blum** [comment]
@jeffchew @proeung here's the #7853 should correct the test failures

**Comment by IgnacioBecerra** [comment]
@andy-blum Everything's looking good! @ariellalgilmore and I ran into the same issue where we couldn't test for `:hover` states, but we found a little workaround by checking the component's styles themselves using a custom utility function.

Here's how we're currently checking for Card's hover styles for the pictogram variation:
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/packages/web-components/tests/e2e-storybook/cypress/integration/card/card.e2e.js#L223

Let us know if you have any question if you'd like to implement it!

**Comment by andy-blum** [comment]
#7853 has been updated to fix the feature CTA hover styles. Changes requested by @IgnacioBecerra can be addressed once that PR is approved and merged.

**Comment by andy-blum** [comment]
@IgnacioBecerra & @annawen1 this is ready pending the test results

**Review by annawen1 — APPROVED** [review]
LGTM! Thanks @andy-blum

**Pull request merged**
