### PR TITLE
fix(left-nav): fix expanded menu section focus trapping

### LINKED ISSUE #4776: [Masthead] L1 - On iPhone Voiceover, issues after activating the hamburger menu in mobile - DPO consulting
**Engineering info:**  
- Innovation Team engineer: @andy-blum 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2364
- DPO consulting engineer: @annawen1 

----

## Detailed description

Issue: When the hamburger menu is displayed, Screen reader still identifies the content from the parent page as well. i.e. IBM Logo, Search button etc.

Expected: Screen reader should not identify the parent page content

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)

Fixes #4776 

### Description

Adjusts `dds-request-focus-wrap` event handler, limiting the focus trap's tabbable elements to the children of the expanded menu section and it's shadowroot. 

### Changelog

**Changed**

- Fixed an accessibility issue in the left-nav component in which non-top-level menu sections could lose focus trapping while open

### CODE REVIEW

**Comment by annawen1** [comment]
@andy-blum I tested the deploy preview link in Safari, iPhone 12 with VO but still hear the IBM logo, search read out before it goes back to the menu items.

**Comment by annawen1** [comment]
> Are you able to do a screen recording?

@andy-blum yep, this is from me swiping back and forth trying to get into the menu items

https://user-images.githubusercontent.com/54281166/150594532-c801e58c-3c89-4798-a9a6-6e1b6abf0745.mov

**Comment by andy-blum** [comment]
I believe I've found the source of the issue here, though I haven't been able to get a solution in place.

It seems that swiping left and right with voiceover active is inconsistent with which elements it gives focus to. Below is a screen recording of a [codepen with a list of link & button elements](https://codepen.io/andy-blum/full/ZEazmKv).

https://user-images.githubusercontent.com/25532785/150866884-11897504-3b52-461d-b54d-46df4a11b0b3.MOV

As you can see, `<button>` elements are given focus by the voiceover utility, but `<a>` elements are not. Compare the iOS behavior above with the video below, taken using voiceover with safari on macOS.

https://user-images.githubusercontent.com/25532785/150867589-1a0081f2-0501-4068-a561-e81f02054792.mov

In the first half of this video you see me tabbing through the elements, and all elements receive focus. In the second half I'm using the voiceover rotor to jump across links and then across form elements (buttons). When using the VO rotor, no elements are given focus.

This behavior is 100% the cause of this issue.
- Swiping backwards from the left-nav results in VO reading out the skipnav link, but focus remains on the first item in the menu
- Swiping forwards from the left-nav moves focus and reads out the menu toggle button because it's the next tabbable element in the DOM.
- Swiping forwards from the menu toggle results in VO reading the IBM logo link, but focus remains on the toggle button
- Swiping forwards from the IBM link move focus to the search button, pulling focus out of our focus trap causing the JS to move focus back into the focus trap

The solution I'm trying to get to work locally here is trying to find a way to keep the sentinel nodes (currently anchor tags) to work, be invisible, be unannounced by VO, but to still receive focus in the proper tab order as they do on desktop. So far I've been unsuccessful, but I'll come back to this tomorrow with fresh eyes and undeserved optimism.

**Comment by andy-blum** [comment]
I've opened an issue in the WebKit issue tracker, but I don't have any real hopes that they'll fix this soon.

**Comment by andy-blum** [comment]
https://media.giphy.com/media/Rl9Yqavfj2Ula/giphy.gif

**Comment by annawen1** [comment]
> @annawen1 well that ended up being easier than I anticipated. Just swapped out `<a>` tags for `<button>` tags for the sentinel elements and it worked first try.

@andy-blum just tested on my phone - worked like a charm! 🎉

**Review by annawen1 — APPROVED** [review]
Thanks @andy-blum! LGTM!

**Pull request merged**
