### PR TITLE
fix(select): selected item is not showing for ios/ipados

### LINKED ISSUE #10052: [<bx-select> iOS issue]: Selected item is not showing for iOS/iPadOS 16.3.1
### Description

With using web-components CDN with latest tag, I am generating a <bx-select> object and it seems that the selected value is not appearing in any browser in iPadOS 16.3.1 (Safari latest, Chrome 110.5481.83, Firefox 109.0). The strange thing is that the general web-components example site is working fine with the same iPad device with an example is not. On Windows PC, Mac and Android Mobile/Tablet it works fine. What could be the problem?

### Component(s) impacted

The example site of web-components is working on iOS:
iPadOS_Select_test_1
The test site with the same <bx-select> object is not working on iOS:
iPadOS_Select_test_2
Android is fine:
Android_Select_test
PC is fine:
Windows_PC_Chrome_Select_test_1
ser-images.githubusercontent.com/125467709/219034258-a16e702d-84ab-4c54-a1d4-89d2f8a8a2d1.jpg)

### Browser

_No response_

### Carbon for IBM.com version

v1 latest from CDN

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

Data collecting application

### Package

@carbon/web-components

### CodeSandbox example

https://web-components.carbondesignsystem.com/?path=/story/components-select--default

### Steps to reproduce the issue (if applicable)

With the Storybook (v1.21.0) I can't recreat the problem. It works fine in iOS 16.3.1
iPadOS_Select_test_1

Issue with the test code on iOS 16.3.1 with latest CDN version:
iPadOS_Select_test_2

`<!DOCTYPE html>
<html>
<head>
<title>Test</title>
<link rel="stylesheet" type="text/css" href="https://1.www.s81c.com/common/carbon-for-ibm-dotcom/tag/v1/latest/plex.css" />
<script type="module" src="https://1.www.s81c.com/common/carbon/web-components/tag/latest/select.min.js"></script>
</head>
<body>
<div style="padding: 1rem;">
	<h4>Carbon Web Components Example from Docs</h4>
	<bx-select helper-text="Optional helper text" label-text="Select" placeholder="Optional placeholder text">
	  <bx-select-item-group label="Category 1">
		<bx-select-item value="all">Option 1</bx-select-item>
		<bx-select-item value="cloudFoundry">Option 2</bx-select-item>
	  </bx-select-item-group>
	  <bx-select-item-group label="Category 2">
		<bx-select-item value="staging">Option 3</bx-select-item>
		<bx-select-item value="dea">Option 4</bx-select-item>
		<bx-select-item value="router">Option 5</bx-select-item>
	  </bx-select-item-group>
	</bx-select>
</div>
</body>
</html>`

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by marcelojcs**
### Related Ticket(s)

Closes #10052 
[Jira ticket](https://jsw.ibm.com/browse/ADCMS-4083)

### Description

Fix for Labeles not appearing on Safari / IOS

### Changelog

**Changed**

- How labels on the select component are handled

### CODE REVIEW

**Review by m4olivei — APPROVED** [review]
Looks good to me. `label` being a sort of override for the `textContent`, which is already placed in between the `<option>`, this seems like a good, logical change.

I don't have an iPad, so I can't test there, but I don't see any regressions.

**Comment by andy-blum** [comment]
Verified on iOS safari, Firefox, macOS safari



Screenshot 2023-11-13 at 1 12 21 PM

Screenshot 2023-11-13 at 1 11 51 PM

**Review by andy-blum — APPROVED** [review]
Test failures seem unrelated. Approving & merging from main to hopefully get all-greens

**Comment by marcelojcs** [comment]
New PR Targeting the main branch
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11214

**Pull request closed without merging**
