### PR TITLE
fix(content-group-mixed): fix pictogram item row on md breakpoint

### PR DESCRIPTION
**Pull request by andysherman2121**
### Related Ticket(s)

#2560 

### Description

The pictogram item text wasn't vertically aligned with the rest of the text above and below. The text would continue past where it should break at. 

### Changelog

**New**

Screen Shot 2020-10-21 at 3 52 10 PM

**Changed**

Screen Shot 2020-10-21 at 3 51 11 PM

### CODE REVIEW

**Comment by jeffchew** [comment]
Something weird going on with this, can you take a look @andysherman2121 ?

Screen Shot 2020-10-26 at 1 22 26 PM

**Comment by andysherman2121** [comment]
> Something weird going on with this, can you take a look @andysherman2121 ?
> 
> Screen Shot 2020-10-26 at 1 22 26 PM

@jeffchew yeah i'm working on fixing that now

**Comment by jeffchew** [comment]
Hey @andysherman2121 just checking on this one, this seems to be open for awhile now.

**Comment by andysherman2121** [comment]
> Hey @andysherman2121 just checking on this one, this seems to be open for awhile now.

@jeffchew yeah I was having issues with the grid, i'll push up a fix today

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @andysherman2121!

**Pull request merged**
