### PR TITLE
fix(content-block-media): add missing style import

### PR DESCRIPTION
**Pull request by kennylam**
### Description

Fixes various style issues for `content-block-media`.

### Changelog

**New**

- add `feature-card.scss`

**Changed**

- update max width styles for `feature-card` CTA

### CODE REVIEW

**Comment by jeffchew** [comment]
Thanks @kennylam , the NextJS app looks better now! I noticed though the text color is off with the feature card:

image

**Comment by kennylam** [comment]
> Thanks @kennylam , the NextJS app looks better now! I noticed though the text color is off with the feature card:

@jeffchew Yeah I noticed this as well. Should have a fix soon.

**Review by jeffchew — APPROVED** [review]
Thanks @kennylam !

**Comment by jeffchew** [comment]
@kennylam is this related to a specific issue? You can add storypoints to this PR if not.

**Pull request merged**
