### PR TITLE
chore(sticky-header): port refactor to v2

### PR DESCRIPTION
**Pull request by jkaeser**
### Description
Ports changes made to feat/masthead-v2-dev branch in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11734 to v2 branch.

In order to adequately test the new Sticky Header Sandbox story, I had to clean up the Dotcom Shell stories. The `mock` secret menu item works again now, and I've reduced a good amount of bloat in the stories' markup. While I was at it, I noticed I never updated Dotcom Shell's `navLinks` prop for L0 items to Masthead's new `l0Data` prop, so I added support for that as well.

### Testing
The code changes here are mostly identical to the aforementioned PR, with the only divergences being changes necessary for v2. Please verify each of the Dotcom Shell stories works as expected, taking particular care to test the sticky elements behaviors on both desktop and mobile.

### CODE REVIEW

**Comment by jkaeser** [comment]
I was seeing some strange behavior at mobile viewport resolutions while using Chrome's dev tools. Stuck elements were being positioned something like 40 pixels above the top viewport edge. However, I do not see the same issue when simply resizing my window down, nor do I see it in Firefox or Safari.

It's making me nervous, though, so I'd appreciate if reviewers could test the mobile sticky behaviors quite thoroughly!

**Review by andy-blum — APPROVED** [review]
All the dotcom-shell stories look good to me

**Review by m4olivei — APPROVED** [review]
LGTM!

**Comment by jkaeser** [comment]
> Looks like Percy isn't happy about a missing snapshot? Doesn't seem releated this this...

I'll try closing & reopening the PR to re-run the job first. If that doesn't work, time to call in a Carbon team member.

**Pull request merged**
