### PR TITLE
fix(content-item-horizontal-media): set row width to 100% to render properly within content-group-horizontal

### PR DESCRIPTION
**Pull request by annawen1**
### Related Ticket(s)

Content Item horizontal with media whitespace to right of video #6415

### Description
`content-item-horizontal-media` with the video renders incorrectly when placed into `content-group-horizontal`. Setting the row width to 100% fixes the issue.

**BEFORE:**
Screen Shot 2021-06-23 at 11 04 56 AM

**AFTER:**
Screen Shot 2021-06-23 at 11 03 47 AM

Screen Shot 2021-06-23 at 11 17 33 AM

### Changelog

**Changed**

- set `bx--content-item-horizontal__row` width to 100% for `content-item-horizontal-media`

### CODE REVIEW

**Review by ariellalgilmore — APPROVED** [review]
LGTM! thanks @annawen1

**Comment by oliviaflory** [comment]
Looks good @annawen1!

Trying to figure out these [Percy differences](https://percy.io/538fc19a/Carbon-for-IBM.com-Web-Components/builds/11119051/changed/624231477?browser=chrome&browser_ids=16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=320&widths=320%2C1280), `Content block mixed: Default` and `CTA section simple` are gone? Is that from a different PR in this release?

**Comment by annawen1** [comment]
> Looks good @annawen1!
> 
> Trying to figure out these [Percy differences](https://percy.io/538fc19a/Carbon-for-IBM.com-Web-Components/builds/11119051/changed/624231477?browser=chrome&browser_ids=16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=320&widths=320%2C1280), `Content block mixed: Default` and `CTA section simple` are gone? Is that from a different PR in this release?

Huh weird...I do see it in the deploy preview so not sure what's happening in the snapshots.

**Review by oliviaflory — APPROVED** [review]
Looks good, thanks @annawen1 !

**Pull request merged**
