### PR TITLE
[v1] feat(content-item-horizontal): add shadow parts

### PR DESCRIPTION
**Pull request by m4olivei**
### Related Ticket(s)

[Jira ticket](https://jsw.ibm.com/browse/ADCMS-6329)

### Description

Adds shadow parts to the `<dds-content-item-horizontal>` family of components in order to allow for slight design adjustments in AEM.

### Changelog

**New**

- Added shadow parts for `<dds-content-item-horizontal>` family of components.

### CODE REVIEW

**Review by bruno-amorim — APPROVED** [review]
All changes look good to me! 

Thanks!

**Review by emyarod — APPROVED** [review]
looks good to me!

**Comment by m4olivei** [comment]
Thanks @emyarod . Do you have the powers to pass Percy? The issues look unrelated to adding part attributes here 😕 .

**Comment by emyarod** [comment]
@m4olivei done!

**Pull request merged**
