### PR TITLE
test(masthead): add e2e coverage for cloud masthead (experimental)

### LINKED ISSUE #8133: [Test Scenario]: Cloud Masthead - DDS Consulting
**Engineering info:**  
- Innovation Team engineer: @andy-blum 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2379
- DPO consulting engineer: @annawen1 

-----

### Component and test scenario title

Masthead - Cloud
- This component is marked behind a feature flag and it's available to preview via the experimental deploy preview.
- Enable this component locally
  - Edit your `.env` file and add this line `DDS_CLOUD_MASTHEAD=true`.

### Test scenario steps

**Menu Testing**

1. Check the "IBM" logo is loading and clickable
2. Check the "Cloud" platform name and ensure that it links out to `ibm.com/cloud` and it's clickable. 
2. Check 5 Mega menu options (eg. Products, Solutions, Pricing, Support, and Explore More) are loading with one active(selected) state, and all options are clickable.
3. Click through one of the menu items from the left tabbing list and ensure that it returns the tab panel content.
4. Check Mega menu drop down links and options are clickable/operable
4. Click on the Mobile hamburger menu and ensure that the Mobile Menu (Left Nav) opens and the menu listing is visible
5. Click through the mobile left nav and ensure that the top links are functioning as expected.
6. Add a test case for ensuring that the nav next/previous carets are rendering on the table breakpoints. This is important as we need to ensure that the users are still available to navigate through the masthead once the menu items are longer than the set container.

**Search** - Should be the same as the Default/Global Masthead

1. Check Search edit field is open by default
2. Check Search edit field opens and the user can enter keywords
3. Check Search field auto-suggest results (10 results should be displayed)
4. Verify Menu options must be hidden while the search edit field is open.

**CTAs**

1. Check the "Contact us" CTA and ensure that the `data-ibm-contact="contact-link"` attribute is present. This attribute is needed for the activation of the IBM Cloud Chatbot.
2. Check and ensure that the "Contact us" button is hidden on the Mobile breakpoints.
3. Click on the blue CTA button "Create IBM Cloud account" and ensure that it's clickable.

**Authentication**

1. Click on the "Log in" CTA and ensure that this button is clickable and directs the user to `https://cloud.ibm.com/login`.

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)

Closes #8133 & #8138

### Changelog

**New**

- Adds e2e coverage for the cloud masthead

### CODE REVIEW

**Comment by andy-blum** [comment]
@proeung & @annawen1 This test has been failing locally on 2 items in the dropdown menus, "Logging and Monitoring" and "Application Innovation"

Clicking these items in the test causes the megamenu to close

Screen Shot 2022-01-31 at 3 57 34 PM
Screen Shot 2022-01-31 at 3 57 18 PM
s

**Comment by andy-blum** [comment]
All tests are currently failing because the cloud-masthead component cannot be found. Is there a way to add `DDS_CLOUD_MASTHEAD=true` to the env vars for this test run?

**Comment by proeung** [comment]
@annawen1 Thanks for pushing up the commit for adding the Cloud Masthead env var to the e2e action. I just reassigned this issue (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8138) to you and adjusted the description of this PR, so that we can track where everything is going.

**Review by emyarod — COMMENTED** [review]
it looks like CI is still having trouble with [one of the new tests](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/runs/5027885058) and [one of the files also needs to be formatted with `prettier`](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/runs/5026664474)

**Comment by andy-blum** [comment]
😭  So far we haven't been able to figure out why the tabbed-interface test fails. It works _fine_ if you do everything manually but fails when Cypress tries.
```
dds-masthead | cloud platform (desktop)
    ✓ should have url for IBM logo (3613ms)
    ✓ should have cloud platform name (4120ms)
    ✓ should load top-nav with no more than one active item (4079ms)
    (Attempt 1 of 3) should have tabbed-interface megamenus
    (Attempt 2 of 3) should have tabbed-interface megamenus
    1) should have tabbed-interface megamenus
    ✓ should have functioning search bar with typeahead (7118ms)
    ✓ should have contact, login, and create-account CTAs (5095ms)


1) dds-masthead | cloud platform (desktop)
       should have tabbed-interface megamenus:
     AssertionError: Timed out retrying after 90000ms: expected '<div#panel-0-0>' to be 'visible'

This element `<div#panel-0-0>` is not visible because its parent `<dds-cloud-megamenu-right-navigation>` has CSS property: `visibility: hidden`
      at Context.eval (http://localhost:8081/__cypress/tests?p=tests/e2e-storybook/cypress/integration/masthead/cloud/cloud-masthead.e2e.js:150:33)
```

**Comment by andy-blum** [comment]
I've left [a comment](https://discord.com/channels/755913899261296641/763105090679865354/938533104405069845) in the #help channel of the Cypress Community's discord server.

**Comment by jeffchew** [comment]
@andy-blum @proeung one other thing to add. I realized that these tests will fail if run on Browserstack Automate, since they are running against the live canary and next lower test environments. wondering if we should for now wrap the e2e tests to only run if `DDS_CLOUD_MASTHEAD` is set as `true`?

**Comment by proeung** [comment]
@andy-blum Bummer! I wonder what's causing this issue. If it's memory leak issues in Cypress, then the whole test would have failed. @jeffchew let me know if you have any insight into this tabbed-interface test fails to issue that Andy is experiencing.

Also, just to keep the rest of the Cloud Masthead test coverage moving along, I wonder if it makes sense for us to take the tabbing test out for this round and address it in a different issue. @andy-blum let's time-boxed this work for half a day, if we still can't figure out why it fails, let's revisit this portion of the test in a new issue.

**Comment by andy-blum** [comment]
Changes: 

- Importing `DDS_CLOUD_MASTHEAD` from the node.js environment variables [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8174/files?show-viewed-files=true&file-filters%5B%5D=#diff-931827ac7f003c2743f1be1f0a717aa2e6fdcab800731b1f36c82f7c99a3bf2cR12)
- Checking that that flag is true before attempting any related tests [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8174/files?show-viewed-files=true&file-filters%5B%5D=#diff-a00eb0a05c99c0a2bdfd49f3f79145e86aeeb09e909c68c3c8c42f3cbda2841dR16)
- Avoiding the weird closing problem by clicking the far right side of the tabs [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8174/files?show-viewed-files=true&file-filters%5B%5D=#diff-a00eb0a05c99c0a2bdfd49f3f79145e86aeeb09e909c68c3c8c42f3cbda2841dR65). As far as I can tell, if the click is within the boundaries of the button's inner text node, the megamenu closes.

**Review by proeung — CHANGES_REQUESTED** [review]
Looks good overall, however, there are a couple of things that need adjusting before we can safely merge this work down.

- See my comment regarding the changes around the `urlObject` object.
- Also, I failed to include this in my test scenario issue, but we need to add a test case for ensuring that the nav next/previous carets are rendering on table breakpoint. This is important as we need to ensure that the users are still available to navigate through the masthead once the menu items are longer than the container (see screenshot).

Screen Shot 2022-02-07 at 4 32 20 PM

**Review by proeung — APPROVED** [review]
LGTM!

**Comment by jeffchew** [comment]
Hey @andy-blum ! A number of e2e tests are failing for some reason, can you take a look?

image

**Comment by andy-blum** [comment]
@jeffchew I'm having some problems parsing out what the TypeErrors are here, but what I think the issue is stemming from is the `loadUserStatus()` method on DDSMastheadComposite. It's seding a request to `${location.origin}/api/v6/selected-account?profile=true`. This URL errors out on my local storybook as well as on ibm.com, so I'm not sure what the intended endpoint actually is - regardless, this request 404s and I'm guessing there's a promise in there somewhere that's not handling the rejection properly.

Do you have any suggestions on where to look to confirm/fix this? Should this get spun out to a new ticket?

**Comment by annawen1** [comment]
> @jeffchew I'm having some problems parsing out what the TypeErrors are here, but what I think the issue is stemming from is the `loadUserStatus()` method on DDSMastheadComposite. It's sending a request to `${location.origin}/api/v6/selected-account?profile=true`. This URL errors out on my local storybook as well as on ibm.com, so I'm not sure what the intended endpoint actually is - regardless, this request 404s and I'm guessing there's a promise in there somewhere that's not handling the rejection properly.
> 
> Do you have any suggestions on where to look to confirm/fix this? Should this get spun out to a new ticket?

@andy-blum looks like that request is coming from our `CloudAccountAuthAPI` service? It should only hit that endpoint when we pass in `<dds-cloud-masthead-container auth-method="api" ...> though which in our default cloud story isn't doing...

**Comment by andy-blum** [comment]
@annawen1 a call to that method is happening in `firstUpdated`

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts#L263

Running that method with "personalization" in the console yields the same error

Screen Shot 2022-02-09 at 1 18 35 PM

**Comment by annawen1** [comment]
> @annawen1 a call to that method is happening in `firstUpdated`
> 
> https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts#L263
> 
> Running that method with "personalization" in the console yields the same error
> 
> Screen Shot 2022-02-09 at 1 18 35 PM

hmm I don't see this happening on my most updated `main` branch, nothing with the endpoint in my Networks or Console tab - I've updated with `main` here to see if that changes anything.

**Comment by annawen1** [comment]
the e2e-tests passed! woohoo! 🥳

**Pull request merged**
