### PR TITLE
fix(masthead): Wrap menu content when longer than the mobile or medium breakpoint

### LINKED ISSUE #3518: Mega menu mobile – text wrap
### The problem
_{{A clear and concise description of what the problem this new feature is trying to solve. (ex. I'm always frustrated when...)}}_

When content is longer than the width of the mobile or medium breakpoint menu, the text is cut off with ellipses and the user cannot read the entire description (example below).

Screen Shot 2020-08-11 at 9 50 50 AM

### The solution
_{{A clear and concise description of what you want to happen}}_

I would like the menu to allow text to wrap onto a second line.

Screen Shot 2020-08-11 at 12 32 26 PM

I had included these specs in the original design, however Kenny informed me Carbon handles long text with the ellipses. 

~[02 mega menu reusable pieces mobile@1x.pdf](https://github.com/carbon-design-system/ibm-dotcom-library/files/5058182/02.mega.menu.reusable.pieces.mobile%401x.pdf)~

Link to mega menu spec folder: https://ibm.ent.box.com/folder/118692148518
*Note: page 6 and 7 of the PDF show examples of text wrap*

### Additional information
 _{{Please provide any additional information or resources for reference}}_
 - Functional Spec changes are not needed.
 -

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)
Fixes #3518 and #4003 

### Description
PR overrides styles coming from `@carbon` package as follows:
- Changes `height:3rem` rules to `min-height:3rem` to allow items to expand vertically
- Negates text truncation & ellipses effect, allowing text to wrap to multiple lines
- Adds padding to text-containers to ensure a consistent amount of padding between items & dividers
 
### Changelog

**Changed**
- Masthead menu item text wraps and displays in-full in mobile & tablet sizes

### CODE REVIEW

**Comment by shixiedesign** [comment]
1. Web components are showing the changes, but the title links container is not growing as expected: 
image

**Comment by shixiedesign** [comment]
Thank you for the fix! Only issue still remaining is in **React, title menu or primary menu item** doesn't wrap properly: 

image

**Review by emyarod — COMMENTED** [review]
it looks like the category titles in React aren't growing after wrapping, web components looks good

the `height: auto` rule seems to be overridden by a higher specificity rule in the React version

image

**Comment by andy-blum** [comment]
@emyarod the changes responsible for that came in `fix(masthead): Duplicate style changes for react (30bfc01)` I'm not seeing an issue on the [most recent react preview](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/7126/index.html). Can you double check?

Screen Shot 2021-09-15 at 10 31 33 AM

**Review by emyarod — APPROVED** [review]
image

still visible in the preview but my assumption is it didn't rebuild. I built locally and it seems fine!

image

**Review by shixiedesign — APPROVED** [review]
Looks good!

**Pull request merged**
