### PR TITLE
feat(video-player-composite): support image and caption overrides

### PR DESCRIPTION
**Pull request by emyarod**
### Related Ticket(s)

#6195

### Description

This PR adds support for custom thumbnails and video captions in the `<video-player-container>/<video-player-composite>` web component. If no custom overrides are provided the values will be taken from the Kaltura API

image

### Changelog

**New**

- `thumbnail` and `caption` properties on `<video-player-container>`/`<video-player-composite>`

### CODE REVIEW

**Review by ariellalgilmore — COMMENTED** [review]
LGTM!! Just one question...i think it might not be in scope for this issue, but noticing the video player with lightbox doesn't change the custom caption when opening the lightbox
Screen Shot 2021-08-31 at 2 37 05 PM

**Comment by emyarod** [comment]
good call! I can update that in the lightbox viewer as well, and I'm leaning towards tackling that separately since the linked issue and epic focus on the (non-lightbox) video player

**Review by ariellalgilmore — APPROVED** [review]
@emyarod sounds good. LGTM! Thank you!

**Comment by shixiedesign** [comment]
So beautiful it works! 

image

**Review by shixiedesign — APPROVED** [review]

**Pull request merged**
