### PR TITLE
chore(link-list): introduce heading component

### PR DESCRIPTION
**Pull request by asudoh**
### Related Ticket(s)

Refs #4326.

### Description

Introduces `<dds-link-list-heading>` to make a choice of the approach of `<div>`/`<span>` with specifying `slot` attribute vs. dedicated components to the latter, to align to other components.

The dedicated components approach allows more control over styling.

### Changelog

**New**

- `<dds-link-list-heading>`, the heading for link list.

### CODE REVIEW

**Comment by jeffchew** [comment]
Thank you @asudoh, can you update the documentation too? It still references as a slot.

**Comment by asudoh** [comment]
@jeffchew Seems that the document of `<dds-link-list>` does not refer to heading at all, added it.

@RaphaelAmadeu Seems that the document refers only to card usage... Would you add text usage, too? Thanks!

**Comment by jeffchew** [comment]
> @jeffchew Seems that the document of `<dds-link-list>` does not refer to heading at all, added it.
> 
> @RaphaelAmadeu Seems that the document refers only to card usage... Would you add text usage, too? Thanks!

@asudoh I will approve as-is, we can add more documentation in a separate PR.

**Review by jeffchew — APPROVED** [review]
Thank you @asudoh !

**Pull request merged**
