### PR TITLE
fix(masthead): overflow appearing in max breakpoint

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#5464 

### Description

Masthead overflow webcomponents/react L0 and L1 was visible in the max breakpoints. This adds before and after styles to hide the overflow menu items. 

Screen Shot 2021-03-31 at 7 58 52 AM
Screen Shot 2021-03-31 at 8 02 48 AM

### Changelog

**New**

- l1 inner container `div` with `::before` & `::after` styles

**Changed**

- added styles to `bx--header`
- increased masthead logo z-index, so it's not covered by background

### CODE REVIEW

**Comment by shixiedesign** [comment]
Hi Ari! 
1. In WC, I still see the caret in `Search open by default` story - though if this is hard to fix, I am leaning towards removing this story soon (kenny is working on new one), so I think it's okay to leave it if it's hard to fix.
image

2. In React, I see `With custom navigation` and `With Platform` still have the caret flashing on load
Mar-31-2021 13-47-52

**Comment by ariellalgilmore** [comment]
> Hi Ari!
> 
> 1. In WC, I still see the caret in `Search open by default` story - though if this is hard to fix, I am leaning towards removing this story soon (kenny is working on new one), so I think it's okay to leave it if it's hard to fix.
>    image
> 2. In React, I see `With custom navigation` and `With Platform` still have the caret flashing on load
>    Mar-31-2021 13-47-52

Hi Shixie! These issues are not related to the overflow appearing past the max breakpoint, so they should be handled seperately.

**Comment by ariellalgilmore** [comment]
> Hi Ari!
> 
> 1. In WC, I still see the caret in `Search open by default` story - though if this is hard to fix, I am leaning towards removing this story soon (kenny is working on new one), so I think it's okay to leave it if it's hard to fix.
>    image
> 2. In React, I see `With custom navigation` and `With Platform` still have the caret flashing on load
>    Mar-31-2021 13-47-52

Thanks @shixiedesign ! Updated react so it doesn't flash on load. The search issue should be handled separately

**Review by shixiedesign — APPROVED** [review]
Looks good to me! 👍

**Review by kennylam — APPROVED** [review]
Looks good thanks @ariellalgilmore!

**Pull request merged**
