### PR TITLE
feat(callout-quote): web-component created 

### PR DESCRIPTION
**Pull request by RaphaelAmadeu**
### Related Ticket(s)

#3745 

### Description

I've created the `CalloutQuote` component for the web components package, creating a mixin for `Callout` in order to maintain the code according to the best practices.

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Thank you @RaphaelAmadeu for making the base callout a mix-in! A question; Is there any use case for using the base `<dds-callout>` itself in applications? Wanted to see how the base `<dds-callout>` and the new mixin can be de-duped. Thanks!

**Comment by RaphaelAmadeu** [comment]
> Thank you @RaphaelAmadeu for making the base callout a mix-in! A question; Is there any use case for using the base `<dds-callout>` itself in applications? Wanted to see how the base `<dds-callout>` and the new mixin can be de-duped. Thanks!

I think it's unlikely, as it's an internal component in the React package. This makes me think, maybe we would want to make a component-mixins folder in order to have these components.

**Comment by asudoh** [comment]
>> Thank you @RaphaelAmadeu for making the base callout a mix-in! A question; Is there any use case for using the base `<dds-callout>` itself in applications? Wanted to see how the base `<dds-callout>` and the new mixin can be de-duped. Thanks!
>
> I think it's unlikely, as it's an internal component in the React package. This makes me think, maybe we would want to make a component-mixins folder in order to have these components.

Cool I see, thank you for clarifying @RaphaelAmadeu! - Would `packages/web-components/src/globals/mixins` make sense?

**Comment by RaphaelAmadeu** [comment]
> > > Thank you @RaphaelAmadeu for making the base callout a mix-in! A question; Is there any use case for using the base `<dds-callout>` itself in applications? Wanted to see how the base `<dds-callout>` and the new mixin can be de-duped. Thanks!
> > 
> > 
> > I think it's unlikely, as it's an internal component in the React package. This makes me think, maybe we would want to make a component-mixins folder in order to have these components.
> 
> Cool I see, thank you for clarifying @RaphaelAmadeu! - Would `packages/web-components/src/globals/mixins` make sense?

I thought we could include it there, but I think that we should separate global mixins from internal component ones.

**Comment by asudoh** [comment]
> > > > Thank you @RaphaelAmadeu for making the base callout a mix-in! A question; Is there any use case for using the base `<dds-callout>` itself in applications? Wanted to see how the base `<dds-callout>` and the new mixin can be de-duped. Thanks!
> > > 
> > > I think it's unlikely, as it's an internal component in the React package. This makes me think, maybe we would want to make a component-mixins folder in order to have these components.
> > 
> > Cool I see, thank you for clarifying @RaphaelAmadeu! - Would `packages/web-components/src/globals/mixins` make sense?
>
> I thought we could include it there, but I think that we should separate global mixins from internal component ones.

I see makes sense, how about `packages/web-components/src/component-mixins`?

**Review by asudoh — APPROVED** [review]
Thank you for all the updates @RaphaelAmadeu! 🎉

**Review by kennylam — APPROVED** [review]
LGTM thanks @RaphaelAmadeu!

**Pull request merged**
