### PR TITLE
fix(storybook): various react story fixes

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#9119
#9117
#9116

### Description
Fixing some of the React Stories:
- Feature Card
- Content group
- Content Section

### Changelog
**Changed**

- changing the way parameters are being passed to the stories

### CODE REVIEW

**Comment by kennylam** [comment]
@IgnacioBecerra Looks like the `cta` knob for `content-group` isn't working.

**Comment by ariellalgilmore** [comment]
> @IgnacioBecerra Looks like the `cta` knob for `content-group` isn't working.

you can look how i handled that here: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/074c64ccccb1123d2fc0b0d47c1c996df7b41633/packages/react/src/components/ContentBlock/__stories__/ContentBlock.stories.js#L64-L74

**Comment by IgnacioBecerra** [comment]
Had to make a small change to the `ContentGroup` due to Storybook erroring out when trying out the new solution, but now all knobs should work 👍

**Review by kennylam — APPROVED** [review]
LGTM!

**Pull request merged**
