### PR TITLE
fix(card): ensure copy can render markdown

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#7481

### Description
This PR ensures that the copy elements in Card and Content Section can render markdown properly. The approach used in Card queries the slotted `p` tag and applies the markdown utility function. While a simpler method may be creating a `card-copy` component that extends `DDSMarkdown`, I refrained from doing so to avoid a breaking change for adopters using Card. Feel free to let me know what you think about doing that approach instead and simply mentioning it in the release notes.

Note: 
Testing markdown in Storybook seems to only work once (i.e. inputting `*test*`, deleting it, and trying the same thing will result in the text being wrapped in asterisks without formatting. 

However, if an adopter uses markdown in the copy of the Card component, it will render properly.

Screen Shot 2021-12-13 at 3 10 55 PM

### Changelog

**Changed**

- Card copy can now use markdown
- Content section copy now extends `DDSMarkdown` component

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
> creating a `card-copy` component that extends `DDSMarkdown`

I think this would be fine given that the component was supposed to have this functionality already. Since the concern is around it being a breaking change it should be ok to make this update in v2

looks good to me, just needs a few CI test updates

**Review by emyarod — COMMENTED** [review]
one thing I noticed, characters like `#` and `&` won't render properly in the card copy with the markdown parser

related https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7469

**Comment by IgnacioBecerra** [comment]
@emyarod I was able to get the `#` to render, but yeah the ampersand was getting removed. It seemed to have been getting stripped using the regex expression after the `&` became `&amp` when parsed through `marked()`, so I removed that part from the expression so it can remain there.

Screen Shot 2021-12-14 at 2 20 14 PM
Screen Shot 2021-12-14 at 2 19 43 PM

**Review by emyarod — APPROVED** [review]
looks good to me! should we create a separate issue for the storybook rendering problems?

**Comment by jeffchew** [comment]
@IgnacioBecerra just double checking if the font size change  in the link list was intentional here? or perhaps this is coming from an outdated baseline?

image

**Comment by IgnacioBecerra** [comment]
@jeffchew yeah that change isn't coming from this PR, the actual font size isn't changing with these changes

**Comment by jeffchew** [comment]
@IgnacioBecerra there seems to be something going on with the card group too, I don't see this on latest canary and double checked that it's happening on your fork:

image

**Comment by IgnacioBecerra** [comment]
@jeffchew Found out what was happening -- once there is a `dds-content-block-copy` in the page, the `renderer` function it uses to convert its text to `<dds-content-block-paragraph` overrides the default one in the `markdownToHtml` utility, which affects the rest of the components using it.

In other words, any use of the utility after using `content-block-copy` will always be wrapped with at `<dds-content-block-paragraph`, which includes the `p` tags in Card that we’re modifying in this PR. A way to circumvent the big text in the cards is to just remove the styles from the rendered `content-block-paragraph` element. 

As mentioned in an earlier comment, creating a `dds-card-copy` component that extends `ddd-markdown` will solve the problem properly as it will have its own renderer, but since it will be a breaking change we could have this feature for v2 next year.

**Comment by jeffchew** [comment]
@IgnacioBecerra thank you for updating, the diffs look much better!

There's still a slight diff for this, wondering if we need a design eye to take a glance at this?

image

**Review by jeffchew — APPROVED** [review]
Thanks @IgnacioBecerra !

**Pull request merged**
