### PR TITLE
chore(cwc): import carbon web components repo

### PR DESCRIPTION
**Pull request by annawen1**
### Related Ticket(s)

[carbon-web-components]: migrate repository to monorepo [#980](https://github.com/carbon-design-system/carbon-web-components/issues/980)

### Description

{{Add a human-readable description / detail summary of what the PR is changing and any details around how and why}}

{{If applicable, include a screenshot indicating an example or examples of what the PR is changing in the application}}

### Changelog

**New**

- {{new thing}}

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by grommett** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by abdonrd** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by asudoh** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by abdonrd** [comment]
recheck

**Pull request closed without merging**
