### PR TITLE
chore(carbon): upgrade to v10.31.0

### PR DESCRIPTION
**Pull request by jeffchew**
### Related Ticket(s)

#5410 

### Description

This upgrades to Carbon v10.31.0. Because there are fixes that need to be made before we merge down as a whole, a separate branch was created to consolidate changes before we fully merge.

### Changelog

**Changed**

- Carbon dependencies upgraded to `v10.31.0`

**Removed**

- Various redundant devDependencies

### CODE REVIEW

**Comment by jeffchew** [comment]
Note, I will be turning off the integration build and bundle tests as a required CI check for now, as there is a fix that is needed in order for this to pass. I'm going to create an issue for this.

**Comment by jeffchew** [comment]
Issue created for the white Masthead icons. Approving the diff for now until the issue is fixed.
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5596

**Comment by jeffchew** [comment]
Issue created for misalignment of the caret in input dropdown:
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5597

**Comment by jeffchew** [comment]
Issue created for the NumberInput in expressive theme: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5598

**Comment by jeffchew** [comment]
Issue created for the UI Shell Header icon size issue: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5599

**Review by shixiedesign — APPROVED** [review]
Thank you for kicking start this work!

**Review by oliviaflory — APPROVED** [review]
👍  thanks Jeff!

**Pull request merged**
