### PR TITLE
fix(content-block): aside element take 3 columns only

### PR DESCRIPTION
**Pull request by guilhermelMoraes**
### Related Ticket(s)

[Content block] Aside elements should take 3 columns #6081

### Description

{{Add a human-readable description / detail summary of what the PR is changing and any details around how and why}}

{{If applicable, include a screenshot indicating an example or examples of what the PR is changing in the application}}

### Changelog

**New**

- {{new thing}}

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Review by photodow — COMMENTED** [review]
- [x] ~Web components it still takes up 4 columns~
image

- [ ] React is rendering it as 3 columns, but it starts on the wrong column it appears.

image

- [ ] Web components also doesn't hang on the right hand side.

image

**Comment by shixiedesign** [comment]
A few unexpected changes: 

1. WC: content group banner layout was broken:

image

2. React: still starting on the wrong column: 

image

3. React, `sm`: missing right side hanging rule

image

**Review by shixiedesign — APPROVED** [review]
Web components look good! React we will capture as issue and fix later.

**Review by jeffchew — APPROVED** [review]
LGTM!

**Pull request merged**
