### PR TITLE
fix(masthead-v2): switch to mobile nav at smaller breakpoint

### LINKED ISSUE #9821: [Masthead v2]: Switch to mobile menu happens too early
### Description

The v2 masthead breaks to a mobile navigation at 960px. Instead, it should switch at 800px.

Innovation Team Tracking ticket: https://jsw.ibm.com/browse/ADCMS-2652

### Component(s) impacted

DDSMasthead

### Browser

Chrome

### Carbon for IBM.com version

v2.0.0-alpha

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

C4IBM, C4AEM

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://www.ibm.com/

### Steps to reproduce the issue (if applicable)

1. Open any page on ibm.com that uses the v2 masthead
2. Reduce your browser viewport width to 959px or less
3. See the masthead change from desktop to mobile layout

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by jkaeser**
### Related Ticket(s)

Resolves #9821 

### Description

The masthead was breaking to the mobile version too early, below 960px. The design team informed us it should break below 800px instead.

### Changelog

**Changed**

- Updates DDSMasthead to break to mobile version below 800px instead of 960px.

### To Test

Visit the "Masthead / With V2 Data" Story ([direct link](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/9939/iframe.html?args=&knob-platform%20name%20(platform)=&knob-show%20the%20profile%20functionality%20(has-profile)=true&knob-show%20the%20search%20functionality%20(has-search)=true&knob-search%20placeholder%20(searchPlaceholder)=Search%20all%20of%20IBM&knob-selected%20menu%20item%20(selected-menu-item)=Consulting%20&%20Services=&knob-The%20user%20authenticated%20status%20(user-status)=Unauthenticated&knob-use%20mock%20nav%20data%20(use-mock)=true&id=components-masthead--with-v-2-data&viewMode=story)) and examine the behavior of the "view all" CTAs in the following menus:
1. **Faceted Megamenu**: CTA in the right column.
2. **Simple Megamenu (Featured)**: CTA in the left column
3. **Simple Megamenu**: CTA in the only column

### CODE REVIEW

**Comment by oliviaflory** [comment]
@jkaeser this looks ok to me, but I'd feel more comfortable having @jwitkowski79, Amanda or Joseph weigh in here due to the conflicting documentation (see below). 

The original [JIRA issue ADCMS-2652](https://jsw.ibm.com/browse/ADCMS-2652) states the breakpoint should be less than **768px**
> Description
> At exactly 959px, the L0/Masthead shifts to the mobile slideout menu. This shouldn't occur until bps less than 768px.
>
>This occurs in both Drupal and AEM.

The issue opened on this board #9821 says the breakpoint should be less than **800px**

And the Functional specs state the breakpoint should be less than **960px**  in a few places
- [2.0.0](https://www.figma.com/file/35JfN0Sg4ltIIjM7jBDKMk/Navigation?node-id=2325%3A136631&t=59W6GiIR8gUbv65M-1) (See comment on this board specifically asking if it should be 800px)
- [2.0.1](https://www.figma.com/file/35JfN0Sg4ltIIjM7jBDKMk/Navigation?node-id=3179%3A178629&t=59W6GiIR8gUbv65M-1)
- [2.0.2](https://www.figma.com/file/35JfN0Sg4ltIIjM7jBDKMk/Navigation?node-id=3867%3A205335&t=59W6GiIR8gUbv65M-1)

**Review by andy-blum — APPROVED** [review]
Width == 1350px
Screenshot 2023-01-11 at 10 40 10 AM

Width == 1055px
Screenshot 2023-01-11 at 10 40 33 AM

Width == 799px
Screenshot 2023-01-11 at 10 41 21 AM

**Comment by jwitkowski79** [comment]
As per @oliviaflory request, I took a look at this to get a second pair of eyes on it and it looks good to me.

**Review by oliviaflory — APPROVED** [review]
Looks good from the design side!

**Comment by jkaeser** [comment]
@carbon-design-system/carbon-for-ibm-com-admins Does this error from Kodiak mean anything to you? I think it's stopping this PR from auto-merging.
```
 ⚠️ config error (missing branch protection for baseRef: 'feat/masthead-v2-dev')
```

**Comment by kennylam** [comment]
@jkaeser Yep it looks like branch protections were never turned on for the new dev branch. I'll turn them on to match `feat/masthead-dev`.

**Comment by proeung** [comment]
@kennylam I tried re-running the failed job but got the following (see attached). I'm re-running the full e2e tests again and seeing if this time it'll go through. I'd love to get this work merged down soon if we can.

Screen Shot 2023-02-07 at 8 48 54 AM

**Pull request merged**
