### PR TITLE
fix(locale-modal): add title to regions list

### PR DESCRIPTION
**Pull request by emyarod**
### Related Ticket(s)

#8855

### Description

Screen Shot 2022-08-29 at 1 58 45 PM

This PR adds a title attribute to the `dds-regions` component of the locale modal so that the header title is read by the screen reader even after the component auto focuses on the first region button

### Changelog

**New**

- `title` attribute on `dds-regions`

### CODE REVIEW

**Review by ariellalgilmore — APPROVED** [review]
LGTM! should we have Ram or Gopi check the ddeploy preview before merging?

**Comment by emyarod** [comment]
> LGTM! should we have Ram or Gopi check the ddeploy preview before merging?

yes I think we should!

**Comment by Rasubra8** [comment]
@emyarod 
The Issue is partially fixed. 
Screen reader announces extraneous text when we check the dialog label by pressing the key "insert+T". Along with the label, SR announces the following text. Note: The same issue is found in the second modal that we get after selecting a region. 
"Close modal United States — English Select geographic area
dialog" Please refer the screen shot attached for jaws output. 
Expected result:
Remove the extraneous announcement. And as mentioned earlier, the following label can be given for the dialog.
The label can be given as Select geographic area for the first modal and language and location selection for the second one that is displayed after selecting the region
Dialog 2 jaws output
Dialog 1 jaws output

**Comment by emyarod** [comment]
@Rasubra8 I believe the fix for this may introduce a breaking change so this may need to be delayed until the next major version release

**Pull request merged**
