### PR TITLE
test(structured-list): add e2e storybook testing

### LINKED ISSUE #8778: [Test Scenario]: Structured List (Default, with row headers, with subheaders, with complex content)
**Engineering info:**  
- Innovation Team engineer: @andy-blum 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2467
- DPO consulting engineer: 

-----

### Component and test scenario title

Structured List - (Default, with row headers, with subheaders, with complex content)
https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components/?path=/story/components-structured-list--default

### Test scenario steps

**Structured List - Default**

1. Check and make sure that there's data in the header cell. 
2. Ensure that the horizontal scroll is working as expected when viewing on small breakpoints (eg. mobile, tablet).

**Structured List - with row headers**

1. Ensure that there are row headers

**Structured List - with subheaders**

1. Check and make sure the subheaders are rendering.
2. Ensure that the horizontal scroll is working as expected when viewing on small breakpoints (eg. mobile, tablet).

**Structured List - with complex content**

1. Ensure that the tooltip body shows up on hover
2. Ensure that Carbon tags are showing up.

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)

Closes #8778

### Description

Adds e2e storybook testing for the structured list component

### CODE REVIEW

**Review by proeung — APPROVED** [review]
LGTM!

**Review by annawen1 — APPROVED** [review]
LGTM!

**Comment by annawen1** [comment]
Checking why a bunch of the deploy previews are failing at the moment....

**Comment by andy-blum** [comment]
@annawen1 looks like all the deploys are up now. Good to merge?

**Comment by annawen1** [comment]
> @annawen1 looks like all the deploys are up now. Good to merge?

@andy-blum yep! Smashing the red button!

**Pull request merged**
