### PR TITLE
chore(components): unify slot names

### PR DESCRIPTION
**Pull request by asudoh**
### Related Ticket(s)

Refs #4112.

### Description

Changes all `<slot name="cta">` occurrences to `<slot name="footer">` to neutralize the purpose of the `<slot>`.

The only exception is one in `<dds-cta-section>` where there is a CTA in the middle and one in the footer. Used `<slot name="action">` for the former.

### Changelog

**Changed**

- All `<slot name="cta">` occurrences to `<slot name="footer">` to neutralize the purpose of the `<slot>`.

### CODE REVIEW

**Review by jeffchew — APPROVED** [review]
Thanks @asudoh !

**Comment by jeffchew** [comment]
BTW we might want to make a note in our release notes in the next release about the slot name changes since it's an API change.

**Comment by asudoh** [comment]
👍 Makes sense @jeffchew!

**Comment by jeffchew** [comment]
Added a note to our pinned issue: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4079

**Pull request merged**
