### PR TITLE
fix(MastheadProfile): render profile menu flipped when html dir is rtl

### PR DESCRIPTION
**Pull request by annawen1**
### Related Ticket(s)

Nav Menu cut off when in Arabic language #5595

### Description

On rtl languages, the profile menu needs to be flipped so that it is not cut off. Solution is to detect the `dir` attribute of the document and set the `flipped` prop of the masthead profile overflow menu appropriately. 

Screen Shot 2021-03-25 at 5 42 16 PM

### Changelog

**Changed**

- set `flipped` prop to masthead profile overflow menu based on the `dir` attribute of the html

### CODE REVIEW

**Comment by jeffchew** [comment]
Wonder if we should start doing some AVT over the RTL environment?

**Comment by annawen1** [comment]
> Wonder if we should start doing some AVT over the RTL environment?

seems like we are getting some RTL bugs coming in now so it might be something I guess we can consider

**Comment by ariellalgilmore** [comment]
looks like this actually isn't a bug and appearing fine on storybook. The person who submitted this did not install the rtlcss npm package

**Comment by jeffchew** [comment]
@annawen1 just checked and doesn't look like overflow is working in RTL: https://ibmdotcom-react-rtl.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/5638/index.html?path=/story/components-masthead--with-custom-navigation, clicking the arrow doesn't appear to do anything.

**Comment by jeffchew** [comment]
@annawen1 should we close this if the adopter needs to install `rtlcss` instead?

**Comment by annawen1** [comment]
> @annawen1 should we close this if the adopter needs to install `rtlcss` instead?

Still waiting on adopter to confirm is installing `rtlcss` works, but we can just close this in the meantime

**Pull request closed without merging**
