### PR TITLE
fix(bx-header-menu): add button role

### LINKED ISSUE #10392: [masthead]: QA - dds-megamenu-top-nav-menu should use button element/role to open megamenu panel
### Description

The L0 dropdown parents use `<a>` tags with an href value of `javascript:void 0`, but the [link role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/link_role) here is wrong.

> The link role is used to identify an element that creates a hyperlink to a resource that is in the application or external.

Instead, these elements should be `<button>` elements or _at least_ have the [button role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role)

> The button role identifies an element as a button to assistive technology such as screen readers. A button is a widget used to perform actions such as submitting a form, opening a dialog, canceling an action, or performing a command such as inserting a new record or displaying information.

Screenshot 2023-04-24 at 4 40 40 PM

Screenshot 2023-04-24 at 4 40 56 PM

### Component(s) impacted

DDSMegamenuTopNavMenu

### Browser

Chrome

### Carbon for IBM.com version

latest

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

ibm.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components/iframe.html?args=&id=components-masthead--default&viewMode=story

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by pjudge**
### Related Ticket(s)

Fixes #10392

### Description

This PR adds `role="button"` to the `<a>` tags inside the L0 menu. This improves accessibility by identifying these elements are acting as buttons. 

> The button role identifies an element as a button to assistive technology such as screen readers. A button is a widget used to perform actions such as submitting a form, opening a dialog, canceling an action, or performing a command such as inserting a new record or displaying information.

### Changelog

**New**

- Markup for `<a>` tags in dropdown menu items now includes `role="button"`.

### CODE REVIEW

**Comment by pjudge** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by andy-blum** [comment]
Code looks good to me, but I'm adding @oliviaflory as a reviewer as well.

One thing that came out of the masthead v2 updates was that items in the L0/L1 were getting different cursors because the l1 is using `<button>` elements and the l0 is using `<a>` elements. Browser defaults tend to apply the `pointer` (hand) cursor to anchor tags while they apply the `default` (arrow) cursor to buttons. See [this deploy preview](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/10430/iframe.html?args=&knob-platform%20name%20(platform)=&knob-show%20the%20profile%20functionality%20(has-profile)=true&knob-show%20the%20search%20functionality%20(has-search)=true&knob-search%20placeholder%20(searchPlaceholder)=Search%20all%20of%20IBM&knob-selected%20menu%20item%20(selected-menu-item)=Products&knob-The%20user%20authenticated%20status%20(user-status)=Unauthenticated&knob-use%20mock%20nav%20data%20(use-mock)=true&id=components-masthead--with-l-1&viewMode=story) to see the different cursors side-by-side

**Review by andy-blum — APPROVED** [review]

**Review by annawen1 — APPROVED** [review]
LGTM

**Review by oliviaflory — APPROVED** [review]
LGTM!

**Pull request merged**
