### PR TITLE
fix(leadSpace): multiple visual bugs

### PR DESCRIPTION
**Pull request by NSDrowned**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4385

### Breakpoint `max - lg`
Default state:
- [x] 1. Spacing top should be 64px (48px on `md, sm`)
- [ ] 2. Sub head text style should be `$expressive-heading-05` which is 60px
- [x] 3. Grid of field should be 10 columns wide, hang both sides into gutter (no hang on `sm`) 
- [x] 4. Spacing between search icon and text should be 16px here (8px on `md, sm`)
- [x] 5. Spacing bottom should be 64px (48px on `md, sm`)
- [x] 6. Bottom rule missing for all breakpoints less than `max`

Typing state: 
- [x] 1. Type style of input text is wrong. Should be `$expressive-heading-03` 
- [x] 2. "X" icon should be 24px in size (20px on `md, sm`). Padding 20 left and right, making the icon centered on a 64x64px square background

### Breakpoint `md` default & typing state
- [x] 1. Heading and subhead's type size seems a little off. Currently 36, only slightly different from spec (32), please double check if this should still use `$expressive-heading-06 and -05`
- [x] 2. Grid of search field. Should hang both sides into gutter, at width 6 columns
- [x] 3. Bottom rule missing

### Breakpoint `sm` default & typing state
- [x] 1. Bottom rule missing

### CODE REVIEW

**Review by shixiedesign — COMMENTED** [review]
Thank you! I see many things are fixed but we are sill missing: 

- should be `expressive-heading-05`
image
- Bottom rule / border bottom should be using `$ui-03`, currently too dark. 
image


- On `xlg - md` search field doesn't sit on grid 
- Upon clicking into text field, the placeholder text should clear
- Typing text is too small. Should be `$expressive-heading-03` (20px) 

image

- On `sm`, 'x' icon is misplaced. Should be centered in a 48px square, 14px in from edge of the search field 
Current: 
image

Expected: 
image

**Comment by NSDrowned** [comment]
- Should be expressive-heading-05

Already set to 05 =/ 

image

- Bottom rule / border bottom should be using $ui-03, currently too dark.
**Changed to $ui-03**

- On xlg - md search field doesn't sit on grid
**Removed gutter hang**

- Upon clicking into text field, the placeholder text should clear
**Added rule that makes placeholder transparent on focus**

- Typing text is too small. Should be $expressive-heading-03 (20px)
**Fixed, it was only set for the placeholder**

- On sm, 'x' icon is misplaced. Should be centered in a 48px square, 14px in from edge of the search field
**Fixed**

**Comment by jeffchew** [comment]
@shixiedesign any other feedback on this? This PR is getting a bit stale.

**Review by shixiedesign — APPROVED** [review]
Looks good!! Thank you for making the fixes @NSDrowned 🎉

**Review by jeffchew — APPROVED** [review]
Thanks Julio!

**Pull request merged**
