### PR TITLE
fix(cardGroup): storybook improvements

### PR DESCRIPTION
**Pull request by NSDrowned**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5415

### Description

- [x] Apply grid to card group, so the component should be snap to the grid col 5-16
- [x] Apply different amount of content in cards to demo `same height util` in action:
_Added random lorem phrase functionality_
- [x] New substory: with card in card (already existed in web components)
- [x] New substory: with card in card and image card

### CODE REVIEW

**Comment by shixiedesign** [comment]
Thank you Julio! 

-[ ] For "Apply different amount of content in cards to demo same height util in action: Added random lorem phrase functionality" The random lorem need to happen in **Card title** , and it looks like the "same hight util" is still not working? Maybe I'm not inspecting right. Lemme know.
image

- [ ] `xlg` breakpoint grid usage seems incorrect. Card group should occupy all 12 column. Currently: 
image
Expecting: 
image

**Review by photodow — CHANGES_REQUESTED** [review]
Can we remove the `with images and cta` story? We don't want adopters doing this.

image

**Comment by shixiedesign** [comment]
Hi Julio, looking good and almost there - removing same-height util from scope of this PR, there is still 1 issue with the grid between `md` 672px and `lg` 1028px breakpoint: 
Currently cards drop to 4th-8th column:
Mar-23-2021 21-16-46
Expected, cards display as 2 per row, taking all 8 columns:
image

**Review by shixiedesign — COMMENTED** [review]
Hi Julio, looking good and almost there - removing same-height util from scope of this PR, there is still 1 issue with the grid between `md` 672px and `lg` 1028px breakpoint: 
Currently cards drop to 4th-8th column:
Mar-23-2021 21-16-46
Expected, cards display as 2 per row, taking all 8 columns:
image

**Comment by NSDrowned** [comment]
@shixiedesign, you're right. It should be ok now.

**Review by shixiedesign — APPROVED** [review]
Great! Thank you!

**Review by kennylam — APPROVED** [review]
LGTM thanks @NSDrowned! Looks like you just need to resolve a few conflicts.

**Review by photodow — APPROVED** [review]

**Comment by jeffchew** [comment]
@NSDrowned looks like there are approvals across but there are CI check issues, can you take a look?

**Comment by NSDrowned** [comment]
@jeffchew fixed 👍

**Pull request merged**
