### PR TITLE
fix(masthead): avoid rendering L0 if L1 is there

### PR DESCRIPTION
**Pull request by asudoh**
### Related Ticket(s)

Refs #4677.

### Changelog

**Changed**

- A change to avoid rendering L0 if L1 is there.

### CODE REVIEW

**Review by jeffchew — APPROVED** [review]
thanks @asudoh !

**Comment by jeffchew** [comment]
@asudoh can you reopen this and target the `master` branch? I had to roll back on the release branch.

**Comment by asudoh** [comment]
My apologies for @jeffchew. Seems that the code has been merged by our "release branch to master sync" bot: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/commits/master

**Comment by asudoh** [comment]
Created: #4690

**Pull request merged**
