### PR TITLE
fix(masthead): clean up storybook demos

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#6409

### Description
Removed the interactive `useMockData` knob as well as the `platform` knob for the Default and Custom Navigation story.

### Changelog
**Removed**

- removed Masthead knobs for `useMockData` and `platform` for certain stories.

### CODE REVIEW

**Review by ariellalgilmore — APPROVED** [review]
LGTM!

**Comment by photodow** [comment]
Thanks for this @IgnacioBecerra. Here are a couple things I noticed...

- [ ] on load in react is two words and one word in web components. Looks like olivia suggested it as one word.
- [ ] Is Olivia suggesting we remove the L1 story? Or not touch it?
- [ ] platform name appears to still be there in react.
- [ ] Do we need the repetitive knob labels? (e.g. `(selected-menu-item)`)

**Comment by IgnacioBecerra** [comment]
@photodow thanks for the review! Going by the issue, I don't think there's anything to clean in the L1 story. 

As for the platform, seems like we're only getting rid of the knob, not the story itself?

And as for the repeated knob labels, as those are also currently in Web Components, I believe we have them so adopters know which attributes to use to modify the Masthead accordingly. I can remove them from React in this PR if desired.

**Review by photodow — APPROVED** [review]

**Comment by ariellalgilmore** [comment]
@IgnacioBecerra looks like just need to update snapshots

**Pull request merged**
