### PR TITLE
fix(content-item-horizontal): fixed grid issues

### PR DESCRIPTION
**Pull request by andysherman2121**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5990

### Description

Content item horizontal wasn't aligning with the grid for the default and with thumbnail variation. This PR adds CSS grid to fix the issues.

### CODE REVIEW

**Comment by andysherman2121** [comment]
> The _with Media_ and _with Thumbnail_ versions look great. For default, I'm seeing about 4px between the body copy and the grid: Screen Shot 2021-10-08 at 3 15 46 PM
> 
> `sm` and `md` align properly, it's just off by a small amount on the larger screensizes.

@RichKummer just fixed! thanks for the review Rich. Let me know if it looks good now

**Comment by RichKummer** [comment]
> @andysherman2121 @RichKummer checking the diffs, it is stacking in the dotcom shell even at 1280px. Is this correct?
> 
> image

It shouldn't be stacking until `sm` for the default Content item horizontal - I'm seeing the same thing.

**Comment by andysherman2121** [comment]
@RichKummer just added the fix! React breakpoints should be good now

**Comment by jeffchew** [comment]
@andysherman2121 looks like your snapshots are out of date.

**Comment by jeffchew** [comment]
@shixiedesign I noticed the same thing, I think the branch was out of date and was diffing an old version of the branch to `master`. I did an update so the deploy previews and percy runs should kick off again.

cc: @andysherman2121

**Comment by shixiedesign** [comment]
@andysherman2121 still seeing extra padding-right on copy of Content item horizontal -- thumbnail, but that's all! 

**Current:**
image
**Spec**
image

**Pull request merged**
