### PR TITLE
fix(cloud-mega-menu): add style and polish the Cloud mega menu & keep platform visible on all bps

### PR DESCRIPTION
**Pull request by proeung**
### Related Ticket(s)

DDS Ticket: N/A
HC JIRA Ticket: https://jsw.ibm.com/browse/HC-1813

### Description
- This PR implements styles and any other remaining polishing items for the Mega Menu design enhancements that are part of the "Unified Cloud Masthead + Mega Menu Project" (see project overview doc - https://ibm.ent.box.com/notes/775640792107).
- This is a follow-up PR to @annawen1's work for adding the baseline tabbing functionality to the cloud mega menu component - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5751 

### Design Spec
https://ibm.ent.box.com/file/774092317795

### Changelog

Screen Shot 2021-04-21 at 9 58 17 AM

**New Components**

- `<dds-cloud-megamenu>` – an extended component of `<dds-megamenu>` that allows us to apply styles to the host component that's cloud design specific.
- `<dds-cloud-top-nav-name>` - – an extended component of `<dds-top-nav-name>` that allows us to apply styles to the host component that's cloud design specific, thus making this top nav name visible on all breakpoints.
-
**Removed**

- N/A

**Notes**
- There's a known issue within the mobile hamburger menu where the regular dropdown menu items are not showing up correctly. @annawen1 has opened a fix PR for this issue and the PR can be reviewed here - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5839

**Testing Instructions**
- Visit the `Cloud Masthead` Storybook variant - `/?path=/story/components-cloud-masthead--default`
- Ensure that the mega menu component matches with the design specs for all breakpoints.

### CODE REVIEW

**Comment by shixiedesign** [comment]
Talked to @proeung about this. Noticed a small error but I now understood what these PRs are. Will remove "design review" label and let the code review happen per usual. Lila will be doing a final round of design review after all the related PRs are merged.

**Comment by proeung** [comment]
@shixiedesign I just added a commit that reverts the border-top change within the "View All" CTA based on our conversation (see - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5853/commits/0d703dc2f2d4abbde94df706c9ef3b6817d7ea2c). I'll defer to you and @ltitle on whether we want to extend the borderline globally or just within Cloud masthead. Regardless I think can be addressed in the overall design QA.

As for removing the line between the platform name and the menu items, we'll address it in the global styling [PR](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5716), since it's a design change that's meant for both masthead and this PR is only relevant to the cloud mega menu.

Components___Cloud_Masthead_-_Default_⋅_Storybook-1

--------

@annawen1 This PR is ready for code review.

**Review by annawen1 — APPROVED** [review]
LGTM! Thanks @proeung! 🎆

**Review by ariellalgilmore — COMMENTED** [review]
Looks great!!! The only thing I was wondering if 'AI' should link to something and if the `<a>` should wrap around the arrow icon as well for when users hover. 
 
Screen Shot 2021-04-27 at 6 41 26 AM

**Comment by proeung** [comment]
@ariellalgilmore Thanks for the review! I just moved the SVG icon into the `<a>` tag within the `dds-cloud-megamenu-category-heading` component - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5853/commits/ca0145860b7f76a66aa417b126fab783fcca23b6#diff-b7a418f098e30e30cd17d54d7e19d26c19ac632a167a3467d9b039fb95f53396R38

**Review by ariellalgilmore — APPROVED** [review]
Thanks @proeung! Looks great!

**Pull request merged**
