### PR TITLE
fix(masthead): account for platform name in active item logic

### PR DESCRIPTION
**Pull request by jkaeser**
### Related Ticket(s)
Resolves https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7794.

### Description

There are currently two ways menu items can be set to "active" and receive a blue underline:
1. Manually: Set the `selected-menu-item` property on the `<dds-masthead-composite>` element
2. Automatically: A menu item has a URL that is identical the the current page's URL.

Additionally, there is a concept of a "platform" supported by the optional `platform` and `platformUrl` properties. When these properties are set, a bolded link appears first in the masthead's L1 nav, and the tricky part is that this link also has logic for whether or not it is set to active. This logic was aware of the manually set active menu items, but it did not account for the automatically set ones.

### Changelog

**Changed**

- Adds `_hasAutoSelectedItems` internal property to track whether automatically selected menu items are present or not.
- Uses `_hasAutoSelectedItems` internal property as a factor when determining if platform link should receive active styles.

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
looks good to me! is this something we should add as a knob to storybook or include in the docs?

**Comment by proeung** [comment]
@emyarod Great point! I wonder if it's useful to add a knob that allows you to insert the URL of the SB page URL for menu items like “Link 2”. The "selected menu item" will need to conditionally set to empty if this knob has a value (see attached). This will be good for testing purposes, but I don't want it to hold us back from getting a solution out in the next release since this is a bug that the AEM adopters are seeing on PROD.

Screen Shot 2021-12-16 at 2 30 21 PM

**Comment by emyarod** [comment]
@proeung yep understood, if we could track the effort for storybook in a separate issue that would be great! as for this ticket I think a note about it in the docs/props table should be fine for now

**Review by annawen1 — APPROVED** [review]
LGTM! Thank you @jkaeser for the fix!

**Review by proeung — APPROVED** [review]
LGTM!

------

@annawen1 @emyarod Thank you both for the review!

**Pull request merged**
