### PR TITLE
fix(masthead): left-nav back link alignment

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#6622 

### Description

Back link will align center in masthead left-nav. I was only able to replicate the issue in browserstack (not xcode sim).

### Changelog

**Changed**

- styles to align left at back link not just the text

### CODE REVIEW

**Review by kennylam — APPROVED** [review]
LGTM thanks @ariellalgilmore!

**Comment by shixiedesign** [comment]
Hey @ariellalgilmore I'm trying to check but not able to reproduce the error in prod or staging. I'm guessing the iphone OS really matters here? If you are able to see the fix in Browserstack, I'm good to give it a thumbs up. Lemme know.

**Review by shixiedesign — APPROVED** [review]
Looks the same as canary now on chrome. I have slight concern the icons are not aligning, but will re-visit as a new bug later. This PR solves the alignment issue on mobile safari

image

**Comment by ariellalgilmore** [comment]
pushed an update. after trying with the deploy previews on browserstack it didn't work, but for some reason worked with my local.

**Comment by ariellalgilmore** [comment]
Screen Shot 2021-09-02 at 2 34 05 PM
confirmed fix

**Pull request merged**
