### PR TITLE
feat(cta): merging components into one

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
 #8841

### Description
This PR merges all the CTA components into one

### Changelog

**Changed**

- CTA is now an individual component that contains the other CTA components within

### CODE REVIEW

**Comment by ariellalgilmore** [comment]
@IgnacioBecerra this is looking awesome! 

We will probably need to update this file here too: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/tools/get-rollup-config.js#L108-L110.

And looks like some tests need some updating since the storybook changed!

**Comment by oliviaflory** [comment]
@IgnacioBecerra This looks nice from what I can tell from a design perspective :D 

A few questions:
1. Based on the decision to go with Option 1 stated in #8841: Should the CTA story be removed? Or are we keeping that to show how the different CTAs variations? 
2. Do we need to update the functional specs to state that the "CTA" is no longer pulling from a CTA component?

**Comment by IgnacioBecerra** [comment]
Thanks for the review Olivia!
1. I feel like we should keep the CTA story since it is still a component that adopters can use, and they might not know about it if it's not there. 
2. Hm I don't think I understand this question, all of these CTA component variations are under the same component with this new PR.

**Comment by oliviaflory** [comment]
@IgnacioBecerra I think I may have mis-understood the direction when I first read the issue. All good!

**Review by oliviaflory — APPROVED** [review]
LGTM!

**Comment by IgnacioBecerra** [comment]
@oliviaflory Ah, gotcha! Yeah we're gonna need to, we'd only need a single functional spec for the CTA component. The different types should be denoted in them.

**Pull request merged**
