### PR TITLE
chore(deps): upgrade marked to 1.2.9

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

#7931 

### Description

This upgrades the `marked` packaged to `v1.2.9`.

### Changelog

**New**

- `marked` upgraded to `v1.2.9`
- add `smartypants` option to `marked`, allowing replacement of normal quotes, dashes, etc. to their 'smart' versions

**Changed**

- update React and web components Storybook markdown to fix indentation. As of `>=1.2.3`, lists were updated to match the CommonMark spec where sub-item lists must be indented to the column of at least the first non-whitespace character (see [example](https://spec.commonmark.org/dingus/?text=%23%23%23%20Incorrect%20indentation%0A%0A1.%20First%20ordered%20list%20item%0A2.%20Another%20item%0A%20%20*%20Unordered%20sub-list.%0A%0A%23%23%23%20Correct%20indentation%0A%0A-%20First%20ordered%20list%20item%0A-%20Another%20item%0A%20%20-%20Unordered%20sub-list.%0A%20%20%20%20-%20Yet%20another%20sub-list)), e.g.:

      1. list 1
         - list item a
           - list item a.a

### CODE REVIEW

**Comment by jeffchew** [comment]
@kennylam thank you for jumping on this! Are the diffs in Percy intentional? I saw that you also updated the example content too.

**Comment by kennylam** [comment]
> Are the diffs in Percy intentional?

@jeffchew Yep! The diffs are all the changes from normal to smart quotes, now that the `smartypants` option has been enabled.

**Comment by jeffchew** [comment]
@kennylam looking at one of the downstream diffs, looks like the card section carousel got affected, wondering if this would have caused this change somehow?

image

**Comment by kennylam** [comment]
> wondering if this would have caused this change somehow?

No, nothing from this PR would make those layout changes. Perhaps something related to #7871?

**Comment by jeffchew** [comment]
> > wondering if this would have caused this change somehow?
> 
> No, nothing from this PR would make those layout changes. Perhaps something related to #7871?

Yeah possibly, I was in the middle of reviewing another PR and noticed the same thing happening. Going to approve this one!

**Review by jeffchew — APPROVED** [review]
Thank you @kennylam !

**Comment by jeffchew** [comment]
@kennylam a request was made by @oliviaflory , can you take a look?

**Comment by kennylam** [comment]
@oliviaflory Good catch! Should be fixed now.

**Review by oliviaflory — APPROVED** [review]
LGTM, thanks @kennylam !

**Pull request merged**
