### PR TITLE
feat(card-pictogram): add design updates to improve mobile accessibility & hover interactions

### PR DESCRIPTION
**Pull request by proeung**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7553

### Description

- This PR adds design updates to improve the visibility of card copy content on the mobile breakpoints as well as adding motion/hover interactions on larger breakpoints.
- See EPIC for more detail - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6739
- Link to animation/hover interaction specs - https://ibm.box.com/s/ykv2ukr3twyfx2nrro3rn7ge4iqoz48x

### Changelog

**New**

- `.#{$prefix}--card__motion` - a new class for applying the card pictogram hover interactions.

**Changed**

- Move Card Pictogram related styles from `packages/web-components/src/components/card/card.scss` to `packages/styles/scss/components/card/index.scss`, so that these changes are available for use in other packages.

https://user-images.githubusercontent.com/1815714/144290175-1ebdb608-a1aa-4cc1-9454-764f6046f7b0.mov

### CODE REVIEW

**Comment by RichKummer** [comment]
Hey @proeung , this is looking great! One issue I found is that when the window changes breakpoints from `md` to `lg`, the body text animation runs over the header.

**Video**
https://user-images.githubusercontent.com/15643582/144436203-01d52b93-4989-45d6-98fa-076a96b744d9.mov

Ideally, when going from `md` to `lg`, the card just changes to the initial state for desktop (only heading and pictogram) without an animation running over it.

**Review by emyarod — COMMENTED** [review]
on a side note, should we allow the card height to grow as the viewport width shrinks?

image

**Comment by proeung** [comment]
@RichKummer @emyarod This PR is ready for a re-review.

**Review by RichKummer — APPROVED** [review]

**Review by IgnacioBecerra — APPROVED** [review]
LGTM, the hover animation looks really nice! thanks @proeung!

**Review by jeffchew — CHANGES_REQUESTED** [review]
@proeung can you double check the e2e test? This one in particular is failing:

image

**Comment by shixiedesign** [comment]
Hey @proeung this is beautifully done! Sorry to nitpick, just a few small issues and all on focus state: 

1. When card is on focus, we should trigger the hover effect as well so keyboard users have a chance to read the card copy. 

Dec-03-2021 08-38-12

2. Focus outline when Card is "Outlined" is 3 px while default is 2px. Expecting 2px
image


3. Focus outline when Card is "Inversed" should be 2px blue + 1px white in order to avoid the outline disappearing on white theme: 

Current: 
Dec-03-2021 08-44-11

Expected - according to default card's specs, focus outline should be as below.
image


I also have question if the screen reader is able to read the copy.

**Comment by proeung** [comment]
@shixiedesign No worries! I just pushed up a commit that shows the copy on `focus` and addresses border styling issues that you've noticed on the `outlined` and `Inverse` styles.

@jeffchew The errors seen within the e2e test should be fixed as well.

**Comment by shixiedesign** [comment]
Hi @proeung Noticed another style change. There should be a padding right of 2rem on `md—max` breakpoint on the heading. `sm` don't need this padding.

**Current:**
image
**Expected:**
image

 I'm around before 3pm ET and feel free to when you are done! Thanks so much for making all these fixes 🌹

**Comment by skuruvil** [comment]
@shixiedesign @proeung Sorry, couple of other things I have noticed

1. It seems like we have not applied a minimum 32px bottom/top margin for the heading. I think similar to body copy card should grow taller to accommodate lengthier heading too. 
Screenshot 2021-12-06 at 4 23 54 PM

2. Position of a pictogram at the bottom is supposed to be the default variant
3.  @sm breakpoint text may take 100% of the container width, right now I think we have applied 32px padding at the right side. But that is something I can see across all the card variants (default, static, etc...)
Screenshot 2021-12-06 at 4 35 17 PM

**Comment by jeffchew** [comment]
Thanks @proeung , looks like other tests are failing now though:

image

**Comment by proeung** [comment]
@jeffchew Those errors are popping up because the border is no longer being applied to the card host component, but within `.bx--card` to address the focus styling issue that @shixiedesign mentioned here (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/7795#issuecomment-985533253). I just pushed up a commit and that should fix the error log.

----------

@shixiedesign @skuruvil The long heading overlapping issue is a result of the text being positioned as `absolute` to get the nice transition in and out. I pushed up an example of the hover motion work with the heading and copy positioned as `relative` and the height set to 0, however, you don't get that smooth transition out effect. Below are screenshots of the differences as well as the pros and cons of each implementation. Take a look and let me know what you guys think.

### **Heading with `absolute` position**

**Pros**
- Creates nice transition in and out.
- Restrict heading copy to just 2 to 3 lines, we can add line-clamp.

**Cons**
- Heading text is overlapped when the character length goes to 5 lines unless we grab the height of the card heading and apply it to the card height. This requires additional dev time.

https://user-images.githubusercontent.com/1815714/144922119-8d543c3a-0139-4691-ae00-00faebe86502.mov


### **Heading and copy using height 0**

**Pros**
- Heading can be set to 5 or more lines without overlapping the icon.
- Height of the card grows based on the length of the heading text.

**Cons**
- No transitions out
- Card with a heading that spans 5 or more lines and with a short copy, there will be a change in the card heigh, unless used within the Card Group component which is where the sameHeight() function is beingappiled.

https://user-images.githubusercontent.com/1815714/144922146-f6df88ba-0b00-4dc9-94b8-f3cd9827eea8.mov

**Comment by shixiedesign** [comment]
Thanks @proeung for demo'ing the two approaches. I've got a weak spot for beautiful animation so my vote is definitely the first one. Also, I noticed the second approach added a bug - if copy is long, height of card grow on hover/focus abruptly. 

Dec-07-2021 01-53-36

**Review by shixiedesign — APPROVED** [review]
Looks good! Thank you.

**Comment by jeffchew** [comment]
Hey @proeung , looks like in React it still can't find the border:

image

**Comment by proeung** [comment]
@jeffchew Looks like React 2e2 tests came back clear now.

**Review by jeffchew — APPROVED** [review]
Thank you for fixing @proeung !

**Pull request merged**
