### PR TITLE
chore(lit): add lit-html/lit-element as core dependencies

### PR DESCRIPTION
**Pull request by jeffchew**
### Related Ticket(s)

Refs https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7546

### Description

This moved `lit-element` and `lit-html` into the main `dependencies` for `Carbon for IBM.com Web Components`. Documentation has been added to highlight this.

This PR also alphabetizes the scripts on the root `package.json`.

### Changelog

**Changed**

- Web Components `package.json` dependencies for `lit-element`/`lit-html`
- Root `'package.json` alphabetized scripts

### CODE REVIEW

**Review by ariellalgilmore — APPROVED** [review]
LGTM! Thanks for adding this!

**Comment by jeffchew** [comment]
Holding on this for a moment, looking into the Cypress errors in the CSB examples:

```The `classMap` directive must be used in the `class` attribute and must be the only part in the attribute.```

**Comment by jeffchew** [comment]
I'm wondering if the error seen is something legitimate? In `lit-html` version `1.3.0` (which the project is now set to use), it has some documentation about it:

https://github.com/lit/lit/blob/f43b811405be32ce6caf82e80d25cb6170eeb7dc/packages/lit-html/src/directives/class-map.ts#L38

https://lit.dev/docs/templates/custom-directives/#limiting-a-directive-to-one-expression-type

Looking back at `1.2.0` of `lit-html`, which is what the csb examples were using before, here is the error which also seems to be part of `class-map.ts`:

https://github.com/lit/lit/blob/d4a0b986639a36c6997dd0ffe1d3eb79f15dfd23/src/directives/class-map.ts#L68

**Comment by jeffchew** [comment]
Digging more into this, downgrading `lit-html` and `lit-element` doesn't appear to be an option because it seems to also will want to downgrade typescript to below v4 for the project to compile properly. 

I'm trying to understand how we're using `classMap`, but offhand seems like it shouldn't be an issue with the way we're using it?

**Comment by jeffchew** [comment]
Thank you @abdonrd for the support on this! Looks like the dependency update and resolving resolution on `lit-html` is the fix for the integration build issues!

**Pull request merged**
