### PR TITLE
chore(storybook): fix web component Storybook container classes

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

#5002 

### Description

Update conditional classes for web component Storybook container.

### Changelog

**Changed**

- `dds-ce-demo-devenv--container` is now optional for web component stories

### CODE REVIEW

**Review by andysherman2121 — APPROVED** [review]
Nice work kenny 👍

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @kennylam on jumping into this!

**Comment by asudoh** [comment]
@kennylam @ariellalgilmore Did we want to cut another RC? Or not because we see this is a storybook issue? CC @RobertaJHahn

**Comment by ariellalgilmore** [comment]
> @kennylam @ariellalgilmore Did we want to cut another RC? Or not because we see this is a storybook issue? CC @RobertaJHahn

@asudoh We are pushing this to the next release because it's just a storybook issue

**Pull request merged**
