### PR TITLE
test(footer): add e2e tests for default language only and micro

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#7423 #7426
### Description

Create e2e tests for Default Language Only and Micro Footer. 

cypress caught that the Default Language Only footer language selector was not clickable, so adding padding to the large breakpoints in storybook

### Changelog

**New**

- e2e test Default Langauge Selector for desktop/mobile
- e2e test Micro for desktop/mobile

### CODE REVIEW

**Comment by ariellalgilmore** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by jeffchew — APPROVED** [review]
LGTM!

**Comment by shixiedesign** [comment]
Hey @ariellalgilmore I can take a look at storybook - but looks like build failed?

**Comment by ariellalgilmore** [comment]
@shixiedesign just re-built but you should see the changes in the deploy previews

**Review by shixiedesign — APPROVED** [review]
Thank you! Yes the padding helped. There might be a Percy diff at some point. I can come back to review that later.

**Pull request merged**
