### PR TITLE
fix(sticky-header): table-of-contents positioning

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)

Followup to #10342 

### Description

This change fixes a bug in which the table of contents is not properly positioned along with the L0/L1 masthead menus

> **Note**
> Because the stickyHeader is a globally-scoped utility and could be initialized by _any_ component that imports it, we'll need to cherry-pick this PR's commit to the `feat/masthead-v2-dev` branch so the `main` branch components and the `feat/masthead-v2` branch components aren't causing race conditions

https://user-images.githubusercontent.com/25532785/235171270-8da551b7-54d5-46ff-afea-f1acb3d19bf5.mov

Direct link to deploy preview testing page: https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/10408/iframe.html?knob-Masthead%20Version=L1&id=components-dotcom-shell--without-shell&viewMode=story

### Changelog

**Changed**

- Updates table-of-contents/stickyHeader integration

### CODE REVIEW

**Comment by andy-blum** [comment]
Link to test this PR: https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/10408/iframe.html?knob-Masthead%20Version=L1&id=components-dotcom-shell--without-shell&viewMode=story

**Review by jkaeser — APPROVED** [review]
LGTM! Fixes that mostly remove lines are 👨‍🍳's 💋.

**Comment by jkaeser** [comment]
@andy-blum Looks like you need to regenerate the testing snapshots, however.

**Review by kennylam — APPROVED** [review]
LGTM!

**Pull request merged**
