### PR TITLE
fix(masthead): L1 platform not showing in hamburger menu

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

#5896 
### Description

Current `L1` platform implementations in React and web components are inconsistent, and in React simply do not work. This makes both implementations consistent in their naming and data structures. Also fixes some styling inconsistencies in the web components version.

### Changelog

**Changed**

- `title` for L1 is now `platform` (same as `L0`)
- update Storybook stories for React and web components
- update web components masthead styles

**Removed**

- `title` and `titleUrl` from web components `L1`

### CODE REVIEW

**Review by shixiedesign — APPROVED** [review]
Looks good! Thanks ⚡

**Review by ariellalgilmore — COMMENTED** [review]
Looks good!! I just don't see the platform name on L1 appearing in mobile in dotcom shell stories on web components

**Comment by kennylam** [comment]
> I just don't see the platform name on L1 appearing in mobile in dotcom shell stories on web components

Doh! I forgot to update the `Dotcom shell` stories. Good catch @ariellalgilmore!

**Review by ariellalgilmore — APPROVED** [review]
Thank you!!! Looks good!

**Pull request merged**
