### PR TITLE
fix(card-group): add region role to card-group-item

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#4614 

### Description

Card-section-images not reading role for each card. Added `role` to be set to `region` in `card-group-item`

### CODE REVIEW

**Comment by annawen1** [comment]
@ariellalgilmore I tried VO on my mac and it doesn't seem to pick up the `region` role still :/

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @ariellalgilmore!

**Comment by jeffchew** [comment]
> @ariellalgilmore I tried VO on my mac and it doesn't seem to pick up the `region` role still :/

Hey Ari, can you check if this is an issue still?

**Comment by ariellalgilmore** [comment]
> > @ariellalgilmore I tried VO on my mac and it doesn't seem to pick up the `region` role still :/
> 
> Hey Ari, can you check if this is an issue still?

yes it is. working on it

**Comment by ariellalgilmore** [comment]
closing this for now as it seems a lot of accessibility issues will be changed at the card component level

**Pull request closed without merging**
