### PR TITLE
fix(video-player): update hover and active state styles

### PR DESCRIPTION
**Pull request by emyarod**
### Related Ticket(s)

#5753
#5514

### Description

This PR updates the video player overlay hover and active states to more match the updated component spec. The overlay should now be `ui-05` and have new opacity values on hover (8%) and active (12%)

Default

image

Hover

image

Active

image

### CODE REVIEW

**Comment by shixiedesign** [comment]
Talked to Andrew, the deploy preview is not showing the changes. Will wait for an update.

**Comment by emyarod** [comment]
I'm going to trigger the preview build again, hopefully the changes show in the updated one

**Comment by emyarod** [comment]
the changes seem to be showing up in the preview now @shixiedesign !

**Review by kennylam — COMMENTED** [review]
Looks good @emyarod! Just want to confirm that the play button does not change on `focus`?

**Comment by emyarod** [comment]
yes I believe the play button receives no changes on focus cc @shixiedesign

the PR title was based on the original epic which included focus changes, will update that!

**Review by kennylam — APPROVED** [review]
LGTM thanks @emyarod!

**Comment by shixiedesign** [comment]
Hey @emyarod looks great! It's a subtle animation. I only noticed the play icon seems to be not getting a transition time. It's animation is instant. If Animation inspector for speed is set to 25%, the change in play icon is still instant. But there's a chance my eyes are playing tricks on me. If you can, just double check and lemme know please!

**Comment by emyarod** [comment]
@shixiedesign the svg icon should be updated with the transitions now!

**Review by shixiedesign — APPROVED** [review]
Fantastic ⭐

**Pull request merged**
