### PR TITLE
fix(dotcom-shell): add scroll eventListener

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#5573 

### Description

Adjust web component toc to push masthead out of the way at md/sm breakpoints and all breakpoints for toc-horizontal. 

### Changelog

**New**

- eventListener for scroll when toc and masthead intersect
- resizeObserver

**Removed**

- styles on TOC that force top: 48px

### CODE REVIEW

**Review by kennylam — COMMENTED** [review]
Looks good @ariellalgilmore! Small thing – can we use `${ddsPrefix}`/`${prefix}` for `dds`/`.bx`, respectively.

**Review by IgnacioBecerra — APPROVED** [review]
LGTM, thanks @ariellalgilmore!

**Review by shixiedesign — APPROVED** [review]
Gonna approve based on video recording Ari shared on Slack. We will take another look when Dotcom shell and this PR both merges!

**Comment by jeffchew** [comment]
@ariellalgilmore @kennylam this looks unrelated to this PR, but there is something a bit odd with the search open story in mobile. When you focus into the search field, the logo goes away and the search field bumps over to I guess the right place. We might want to track this in a separate issue. FYI @shixiedesign .

image

**Comment by jeffchew** [comment]
@ariellalgilmore also possibly not related, but noticing that the e2e test to click open the search isn't appearing in Percy, but functionally when I tested it in the deploy preview it seems fine.

image

**Comment by ariellalgilmore** [comment]
@jeffchew yeah the first one should not be related to this PR. Also, I tested the second issue in the deploy preview and it worked for me too. Maybe we can just make an issue tracking this as well?

**Pull request merged**
