### PR TITLE
fix(link-with-icon): add icon line wrap behavior by default

### PR DESCRIPTION
**Pull request by emyarod**
### Related Ticket(s)

#5705

### Description

This PR changes the default Link with icon component behavior so that the icon will wrap to the next line the component length gets too long

Verify that icons in the following components/variants will wrap with longer link text

* Callout link with icon
* Card footer
* Content block horizontal
* Content block segmented
* Content group banner
* CTA - Text
* Link list (horizontal)
* Link list (vertical)
* Link with icon

image

and Link list section, Link list (default), Link list (End Of Section)  icons do not wrap with longer text (behavior remains unchanged)

image

Since the Link with icon component is a dependency for several other components, also verify that components such as callout link with icon and megamenu link with icon appear correct

### Changelog

**New**

- nonreflected `iconInline` property on Link with icon component (extended to Link list and Card link footer)

**Changed**

- icon line wrap behavior on link with icon and several dependent components

### CODE REVIEW

**Comment by jeffchew** [comment]
This diff doesn't seem to look right @emyarod:

image

**Comment by emyarod** [comment]
@jeffchew this is the behavior I mentioned where the icon can wrap before the final word. not sure if we can achieve the original desired behavior without modifying the markup or resorting to some css hacks but I checked with Shixie on if we still want to proceed with this cc @shixiedesign

**Comment by shixiedesign** [comment]
Hey @jeffchew yes the wrapping behavior caught by Percy is expected. 

This bugfix should fix many stances of the wrong wrapping. Currently I'm still seeing the incorrect icon wrap in `CTA`, `Content block segmented`, `Content block horizontal`. I cannot easily test all the content blocks for CTA. Does this mean `Content blocks` are not dependent on Link with icon? Lemme know if these are out side the scope of this PR. 

### Still seeing the wrong icon wrapping behavior in the following components: 

**CTA - Text** 
image

**Content block horizontal**
image

**Content block segmented**
image

**Comment by emyarod** [comment]
> Currently I'm still seeing the incorrect icon wrap in `CTA`, `Content block segmented`, `Content block horizontal`. I cannot easily test all the content blocks for CTA. Does this mean `Content blocks` are not dependent on Link with icon?

from what I can tell they do not depend on Link with icon, and I can look into adding the same behavior to those components. I'm not sure on how we want to scope these changes but for easier testing it may be good to split it up since I'm still unfamiliar with which components depend on which. Interested in hearing more thoughts on if/how we should split up the PR!

**Comment by emyarod** [comment]
CTA - Text, Content block horizontal, and Content block segmented should also see the same text wrap behavior now!

**Comment by shixiedesign** [comment]
Noticed React needs these update as well. Already discussed on Slack.

**Comment by emyarod** [comment]
the React versions should now receive the same changes!

**Review by shixiedesign — APPROVED** [review]
Awesome! Thank you for the fix!

**Review by jeffchew — APPROVED** [review]
Thank you @emyarod !

**Comment by RobertaJHahn** [comment]
Issue (#6837 ) has been created to manage the React work mentioned in Andrew's comment above.

**Pull request merged**
