### PR TITLE
fix(content-item-horizontal-media): Switched the default alignment fr…

### PR DESCRIPTION
**Pull request by iwhitcomb**
…om left to right.

### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5486

### Description

I changed the alignment knob from left to right to adhere to the design system standard.

### Changelog

**Changed**

- Simple change of the default left variable to right on the alignment knob.

### CODE REVIEW

**Review by andysherman2121 — APPROVED** [review]
Looks good to me! Thanks  @iwhitcomb

**Review by photodow — CHANGES_REQUESTED** [review]
I think we need to update more than just the story. We need to set the component's default itself.

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/c1b9bdeb1acfa3dada2b694b8fd131bf3a4c1cbf/packages/web-components/src/components/content-item-horizontal/content-item-horizontal-media.ts#L28-L36

**Comment by shixiedesign** [comment]
Low priority fix, but seems like the `Copy` knob isn't working? When I add or remove content in text input of `Copy`, the body copy below headline remains unchanged.

image

**Review by andysherman2121 — CHANGES_REQUESTED** [review]
Agreeing with @shixiedesign The copy knob isn't working

**Review by photodow — APPROVED** [review]
Looks like my request for changes from my expectations is good as far as my understanding goes so I'm going to go ahead and approve from my perspective to avoid me being a blocker. I'll lean on Andy to double-check the code and make sure it works as expected, but it sounds like he's been working with you on this so I trust it's good.

**Comment by iwhitcomb** [comment]
@andysherman2121 this appears to be an issue with the default display as well.

**Comment by andysherman2121** [comment]
> @andysherman2121 this appears to be an issue with the default display as well.

@iwhitcomb what appears to be an issue on default display?

**Comment by iwhitcomb** [comment]
> @iwhitcomb what appears to be an issue on default display?

@andysherman2121 the copy knob isn't working. It's definitely an issue somewhere higher up in the hierarchy so possibly more widespread than just these 2 components. I haven't been able to pinpoint the issue yet though.

**Comment by andysherman2121** [comment]
@iwhitcomb You're right, the copy knob isn't working in a few components. (content group simple). @shixiedesign Seems like the copy issue is a more widespread problem not specific to this component. I think we should make a new story for it to be fixed throughout the codebase

**Review by andysherman2121 — APPROVED** [review]

**Review by shixiedesign — APPROVED** [review]
Thank you! BTW @iwhitcomb I did notice some grid issues with the component but it's not relevant to this PR's issue. It could also have slipped through when we first added it because our design team haven't got the standards figured out. It already looks great but in general we just want to make sure it renders on the grid, even in storybook. Thanks! https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5649

**Pull request merged**
