### PR TITLE
feat(structured-list): Add new structured list component

### LINKED ISSUE #8388: [Structured list] Web Component:  enhancement and new variant
**Engineering info:**  
- Innovation Team engineer: @andy-blum 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2421
- DPO consulting engineer: @emyarod 

-----

Carbon for ibm.com developer

> I need to:
create/change the `Structured list`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information
- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- The React version is created as a wrapper to the Web Components version
- **See the Epic (#8385) for the Design and Functional specs information**
- Visual QA testing issue (#8386)
- Prod QA testing issue (#8387)

### 1. Structured list enhancement
- Ability to include paragraph breaks
- Ability to add checkmark icon in row items
- Ability to add tooltip
Screen Shot 2022-02-25 at 11 44 45 AM

### 2. Structured list with row headers (vertical)
New variant of current structured list
- Ability for Rows to have heading style (no column headers) 
Screen Shot 2022-02-25 at 11 47 15 AM

### 3. 8 columns
Not sure if this is an enhancement or new, I think structured list can already span 8 columns?
Screen Shot 2022-02-25 at 11 48 46 AM

#### Additional Information
- [Design specs](https://ibm.ent.box.com/folder/157071416507)
- [Carbon web components structures list](https://web-components.carbondesignsystem.com/?path=/story/components-structured-list--default)
- [Carbon React structured list](https://react.carbondesignsystem.com/?path=/story/components-structuredlist--simple)

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Create React wrapper
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] add the trigger to create the React Wrapper
 - [ ] create the React storybook stories and related documentation
- [ ] Update the Carbon for ibm.com website component [data file](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json) to be sure the web site Component Status and Storybook links are correct
- [ ] Use the [Visual QA checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist)) to verify design quality
- [ ] Update the e2e test scripts, if needed. 
- [ ] Confirm e2e test results have no major errors.
- [ ] A comment is posted in the Prod QA issue (#8387) when development is finished.  
- [ ] The `dev complete` label is added to the Prod QA issue (#8387).

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)

closes #8388 

### Description

Adds structured list element to carbon-for-ibm-dotcom.

### Changelog

**New**

- dds-structured-list

### Remaining Tasks
- [ ] Match styles to functional specs
- [ ] Port WC to React

### CODE REVIEW

**Review by kennylam — COMMENTED** [review]
Thanks @andy-blum! I know it's still in draft but here are a few things I noticed.

Also, for each of the `structured-list-*` components, I think extending the existing [`structured-list`](https://github.com/carbon-design-system/carbon-web-components/tree/main/src/components/structured-list) would be simpler? This avoids duplicating code and keeps it in sync with upstream changes to `carbon-web-components` (and by extension the Carbon core components).

**Comment by andy-blum** [comment]
@kennylam 

> I think extending the existing [structured-list](https://github.com/carbon-design-system/carbon-web-components/tree/main/src/components/structured-list) would be simpler?

I was deliberately avoiding the upstream structured list for two reasons:

1) The upstream structured list has a lot of [selection/input logic](https://github.com/carbon-design-system/carbon-web-components/blob/main/src/components/structured-list/structured-list-row.ts#L83-L109). It seems like this component was at one point used like a form element?

2) The upstream component essentially mimics the HTML table markup, which is great, but [it requires a lot of markup](https://github.com/carbon-design-system/carbon-web-components/blob/main/src/components/structured-list/structured-list-story.ts#L31-L65) to achieve the result. The approach [I'm taking here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8469/files#diff-64542722340b74a47fa838b1f73177218fdb6b8d8dd815c6fb8641b6aeb8ebf7R18-R35) should be significantly simpler to achieve the same result.

Thoughts moving forward?

**Comment by kennylam** [comment]
@andy-blum The problem is that this introduces a duplicate component (and css) to maintain when there is already an existing one to leverage. While the streamlined, simplified markup is great, it comes at the expense of a whole lot of duplicated code. Also, I think the event handlers and input logic will still be used with the expanding rows and checks-on-click. Unless I'm missing something in the updated designs, I don't see why we can't extend the `carbon-web-components` version?

cc: @oliviaflory @emyarod

**Comment by andy-blum** [comment]
@kennylam I have a second branch opened up locally where I'm extending the carbon-web-components. I'm going to leave this PR up for now in case I need to copy anything over from it.

**Comment by kennylam** [comment]
Thanks @andy-blum!

**Pull request closed without merging**
