### PR TITLE
fix(feature-card): remove redundant flex-wrap

### PR DESCRIPTION
**Pull request by asudoh**
### Related Ticket(s)

Refs #4171.

### Description

Fixes a bug that is observed where `<dds-feature-card>` is placed in a grid whose width is notably smaller than browser viewport.

Also made changes to our stories using grid to unify similar other stories, using common story parameter and CSS classes.

### Changelog

**Changed**

- Fixes a bug that is observed where `<dds-feature-card>` is placed in a grid whose width is notably smaller than browser viewport.
- Changes to our stories using grid to unify similar other stories.

### CODE REVIEW

**Comment by asudoh** [comment]
@ariellalgilmore @RaphaelAmadeu Please let me know if you have any concerns with the changes to the stories. Thanks!

**Review by ariellalgilmore — COMMENTED** [review]
Thanks @asudoh! This makes a lot of sense and will help for future development. Seems like it's causing extra padding around components in react though

**Comment by asudoh** [comment]
Thanks @ariellalgilmore for pointing it out - Adjusted the padding, wondering if it works better. Please don't hesitate to speak up otherwise, thanks!

**Comment by asudoh** [comment]
May address: #4128

**Review by jeffchew — APPROVED** [review]
Nice add, thank you @asudoh !

**Comment by ariellalgilmore** [comment]
@asudoh looks pretty good! Sorry just saw you updated the padding. I see now though the padding in web components is different than in react. For example, cardgroup and featurecard are all positioned directly at the top in react, but in web components there is an extra space between the top and the component. Also, card seems to be centered aligned instead of left aligned. I think in an application this won't make a difference, but when testing it might throw the designers or QA team off

**Review by kennylam — APPROVED** [review]
Looks good thanks @asudoh! Looks like Ari's comments refer to the storybook containers and how our components are presented. We probably need to standardize the layouts between our react and web component stories. But that is separate from this issue.

**Comment by asudoh** [comment]
@ariellalgilmore @kennylam Thank you for reviewing!

> Looks like Ari's comments refer to the storybook containers and how our components are presented. We probably need to standardize the layouts between our react and web component stories.

Exactly, was trying to create the standard layout for those stories and tried to make it sensible for Web Components. Once it makes sense to everybody it should be applied to React, too. That said, please definitely don't hesitate to point out if any stories looks odd (besides the difference from React).

**Pull request merged**
