### PR TITLE
fix(contentBlockMixed): align to non-gutter grid

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#4962 

### Description

Align to non-gutter grid line. Also updated stories to match react storybook options. 

### Changelog

**Changed**

- use CSS grid for layout for `<dds-content-block-mixed>`.

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
LGTM basically, one question; Did we need any CodeSandbox updates? Thanks @ariellalgilmore!

**Comment by ariellalgilmore** [comment]
> LGTM basically, one question; Did we need any CodeSandbox updates? Thanks @ariellalgilmore!

Good catch! looks like a codesandbox was never created for this component.

**Comment by asudoh** [comment]
Thank you for clarifying @ariellalgilmore! Another question; Seems that there are changes to two other components. Do their stories and CodeSandbox need any update? Or are they not necessary...?

**Comment by ariellalgilmore** [comment]
> Thank you for clarifying @ariellalgilmore! Another question; Seems that there are changes to two other components. Do their stories and CodeSandbox need any update? Or are they not necessary...?

The other components are not necessary. I will create a codesandbox example for content-block-mixed though and include in this PR.

**Review by asudoh — APPROVED** [review]
Thanks @ariellalgilmore for the update!

**Pull request merged**
