### PR TITLE
fix(cloud-masthead): ensure megamenu bottom graident sticks to bottom

### PR DESCRIPTION
**Pull request by annawen1**
### Related Ticket(s)

#7232

### Description

Cloud megamenu has a gradient at the bottom of the megamenu that user sees when the megamenu is scrollable. When user scrolls however, the gradient is stuck in the same position. Seems the megamenu needs a set `bottom` value

Screen Shot 2021-09-21 at 4 15 25 PM

FIX:
Screen Shot 2021-09-21 at 4 21 52 PM

### Changelog

**Removed**

- `bottom: auto`

### CODE REVIEW

**Review by IgnacioBecerra — APPROVED** [review]

**Comment by shixiedesign** [comment]
@annawen1 I just caught this bug the other yesterday! Here's the issue https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/7232. I added it to PR description, but not sure if you'd like to assign yourself or what's the standard.

**Review by shixiedesign — APPROVED** [review]

**Comment by annawen1** [comment]
> @annawen1 I just caught this bug the other yesterday! Here's the issue https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/7232. I added it to PR description, but not sure if you'd like to assign yourself or what's the standard.

oh great! I'll assign myself!

**Review by andy-blum — COMMENTED** [review]
@proeung & @annawen1 This `bottom: auto` was added because other wise you can't click out of the dropdown menu unless you go all the way into the bottom 4rem of the viewport where this element's margin is.

**Comment by annawen1** [comment]
> @proeung & @annawen1 This `bottom: auto` was added because other wise you can't click out of the dropdown menu unless you go all the way into the bottom 4rem of the viewport where this element's margin is.

Gotcha, new PR to add the `bottom: auto` back and set the gradient pseudo element positioning to `fixed` instead: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/7253

**Pull request merged**
