### PR TITLE
chore(masthead-v2): update dev branch with main changes

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)

[ADCMS-2944](https://jsw.ibm.com/browse/ADCMS-2944)

### Description

Marges changes from `main` into `masthead-v2-dev`

### CODE REVIEW

**Review by proeung — COMMENTED** [review]
Wow! This merge from `main` is long overdue!

@andy-blum @jkaeser Is there going to be a follow-up PR or merge to the [masthead-v2.1](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/tree/feat/masthead-v2.1) branch? I'd like to use this to create a Jenkins job that uploads the WC CDN version to the EI server and builds out a package version tag.

**Review by jkaeser — APPROVED** [review]

**Comment by proeung** [comment]
@andy-blum https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9939 has been merged to the `masthead-v2.1` and `masthead-v2-dev` can be updated.

**Comment by proeung** [comment]
@andy-blum @jkaeser I'm good to squash and merge this PR now that we don't have any more PRs going into `masthead-v2.1`. Can I get a thumbs up, if you both agree?

Also, remind me, are we good to update the `masthead-v2.1` branch with `masthead-v2-dev` or should we bypass he `masthead-v2.1` branch and roll everything into the `masthead-v2` aka main branch,  since we've removed the auto-publishing of the CDN build? I'm open to any suggestions.

**Comment by jkaeser** [comment]
> @andy-blum @jkaeser I'm good to squash and merge this PR now that we don't have any more PRs going into `masthead-v2.1`. Can I get a thumbs up, if you both agree?
> 
> Also, remind me, are we good to update the `masthead-v2.1` branch with `masthead-v2-dev` or should we bypass the `masthead-v2.1` branch and roll everything into the `masthead-v2` aka main branch, since we've removed the auto-publishing of the CDN build? I'm open to any suggestions.

@proeung Looks like Andy merged `feat/masthead-v2.1` into this branch, which is a fine approach to take IMO. There's some tests and ci-check issues to fix, but once those are taken care of we can squash and merge this, then open a PR to merge `feat/masthead-v2-dev` into `feat/masthead-v2`. That PR will give us a deploy preview to share with the designers to get their final v2.1 approval.

Does that sound good to everyone?

**Comment by andy-blum** [comment]
I'd prefer to not be as far away from `main`, and would prefer PRs in the future directly to `masthead-v2-dev`

```mermaid
graph TD;
    feat/masthead-v2-->main-v2
   
    feat/masthead-v2-dev-->feat/masthead-v2;
    new-features-->feat/masthead-v2-dev;
    hot-fixes-->feat/masthead-v2;
```

**Comment by jkaeser** [comment]
> I'd prefer to not be as far away from `main`, and would prefer PRs in the future directly to `masthead-v2-dev`

I agree with this chart with the exception that in my mind `feat/masthead-v2` serves the purpose of `main-v2`.

**Comment by proeung** [comment]
Merge is blocked due to failed CI checks. @andy-blum Can you take a look?

Screen Shot 2023-02-15 at 9 58 59 AM

**Comment by andy-blum** [comment]
Currently working on this

**Comment by proeung** [comment]
More CI checks issues. Looks like some components are missing or names needed to be adjusted for the Cloud Masthead e2e test. Also, feels like we can remove this test since we'll be deprecating Cloud Masthead in the L0/Masthead v2.

Screen Shot 2023-02-15 at 1 04 13 PM

**Comment by andy-blum** [comment]
Waiting for #10053 to pass & merge in before completing this.

**Comment by proeung** [comment]
Closing and reopening this PR to trigger a new Masthead CDN build file for testing purposes.

**Pull request merged**
