### PR TITLE
feat(search-with-typeahead): add scoped search support

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#7627

### Description
This PR changes the SearchWithTypeahead API slightly so it's able to retrieve scoped results from different categories within IBM, such as PartnerWorld or Developer as examples. This can be tested under the `Masthead - with scoped results` in WC Storybook. Change the scope by clicking on the filter select button while the results are displayed to see how they change between scopes.

### Changelog

**New**

- scoped search in search with typeahead

**Changed**

- added scope to `SearchWithTypeahead` API query if requested

### CODE REVIEW

**Review by kennylam — COMMENTED** [review]
Looks good @IgnacioBecerra! Just a few comments.

**Comment by RichKummer** [comment]
Hey I took a look and for the most part it's looking really good! I noticed that in the design specs, the comments say that the browser / device default would be used for the selector. Is that what it's using right now? I just want to confirm, the specs used the spinner (no need to change if the dropdown is right).

**Design specs**
Screen Shot 2022-01-27 at 6 23 21 PM

**iPhone 11**
IMG_1995 2

Also, when I tested it on my iphone/tablet, the selector looked fine, but when I tried the `sm` and `md` sizes in browser in Safari, the selector didn't populate with any text. I'm not sure a lot of people will hit that issue but it caught my eye as it was going through:

**Chrome - Macbook**
Screen Shot 2022-01-27 at 5 53 53 PM

**Safari - Macbook**
Screen Shot 2022-01-27 at 5 53 33 PM

**Comment by IgnacioBecerra** [comment]
@RichKummer It seems that the wheel has been changed in the latest iOS, but the functionality remains. As for the Safari thing you noticed, I was able to fix it in the latest commit 👍  Nice job catching that!

**Review by kennylam — APPROVED** [review]
LGTM thanks @IgnacioBecerra!

**Review by RichKummer — APPROVED** [review]
Thanks for fixing the Safari issue, LGTM!

**Pull request merged**
