### PR TITLE
fix(quote): added hang to component

### PR DESCRIPTION
**Pull request by RaphaelAmadeu**
### Related Ticket(s)

#5433 

### Description

I've updated the styles for `DDSQuote` so the component matches the design specs with the hang in the quote mark and line.

Before:
image

After:
image

### CODE REVIEW

**Comment by shixiedesign** [comment]
Almost! Need to move to the right 1 more column: 

**Current quote start on column 5:** 
image

**Expecting quote to start on column 6:**
image

**Comment by RaphaelAmadeu** [comment]
@shixiedesign I've updated the story, so the Quote component starts on column 6 now.

**Comment by shixiedesign** [comment]
Also noticed `Callout` component could need some update to maintain the changing quote.

**Comment by kennylam** [comment]
@RaphaelAmadeu Did you maybe create this PR off the wrong branch? There are a lot of offline tarballs included.

**Pull request closed without merging**
