### PR TITLE
feat(leadspace): add short variation

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#6929

### Description

Create leadspace short variation. 

### Changelog

**New**

- short size
- storybook with short variation and for react-wrapper story

**Changed**

- cleaned up unnessary classes and styles
- cleaned warning in leadspace search

### CODE REVIEW

**Comment by IgnacioBecerra** [comment]
I saw a small issue on the `Short with image` variation where in the lg breakpoint and above, the image seems to get slightly cut off. Wondering if the use of `height: fit-content` in `dds-leadspace-image` or some kind of similar property might help, as seen in the After image below, but would like feedback from designers to see their thoughts on this. (cc: @RichKummer)

Before (current):
Screen Shot 2021-08-31 at 1 43 15 PM


After (with `fit-content`):
Screen Shot 2021-08-31 at 1 45 05 PM

**Comment by kennylam** [comment]
> Wondering if the use of `height: fit-content`

`height: auto` would also work.

**Comment by ariellalgilmore** [comment]
Thanks @IgnacioBecerra and @kennylam updated the height!

**Review by RichKummer — APPROVED** [review]
The added `height-auto` solved the issue on `max`. The behavior on `md` where the image drops is intended, I'll update the design specs in sketch to match.

**Pull request merged**
