### PR TITLE
fix(language-selector): added clear label attribute

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#4889

### Description

The component now has the role of `edit combo` to ensure the screen readers convey its purpose to the users. The clear button also lacked a label to convey functionality upon click/enter. 

### Changelog

**New**

- added clear button label property

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Hi @IgnacioBecerra thank you for trying to fix this - Would you want to try fixing this directly in `carbon-web-components` unless this needs to be included in `v1.15.0`?

**Comment by IgnacioBecerra** [comment]
@asudoh Yeah, I think that's a good idea. I don't think we need to get this into the release right away, and besides this is a change that should be coming from ComboBox itself.

**Comment by IgnacioBecerra** [comment]
There was a button label attribute for ComboBox, so that addition can be reflected on our side.

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @IgnacioBecerra for the update!

**Pull request merged**
