### PR TITLE
fix(language-selector): update menu bottom spacing

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

#6302 

### Description

Updates `bottom` positioning for language selector item menu so it aligns properly with combobox.

### Changelog

**Changed**

- language selector list menu `bottom` changed to 47px

### CODE REVIEW

**Review by IgnacioBecerra — DISMISSED** [review]
LGTM, thanks @kennylam !!

**Comment by shixiedesign** [comment]
Two minor issues only on Web components: 
1. The original issue requested to reposition the Short to be middle of page for easier QA in the future. React looks good.
2. Looks good on Micro and Default, but **on Short**, the dropdown is covering the select by 1 px 😳 React looks good.

image

**Comment by kennylam** [comment]
> Two minor issues only on Web components:

Good catch @shixiedesign, fixed!

**Review by IgnacioBecerra — APPROVED** [review]
approving again since last review went stale, and I see the issue Shixie brought up has been fixed

**Review by shixiedesign — APPROVED** [review]
💯

**Pull request merged**
