### PR TITLE
feat(card-static): create React static card, light and border options

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#6042

### Description
Introduces the React version of Card static, which also includes a Light theme and an optional border around Card.

### Changelog

**New**

- React Card can now be Static, with a light theme and optional border

**Changed**

- Card storybook knob changes to align more closely to Web Component's

### CODE REVIEW

**Review by shixiedesign — COMMENTED** [review]
Hmm looks like React didn't build and it's not in React wrapper? Am I missing something?

**Comment by DragosRistici** [comment]
While waiting for the React deploy, @IgnacioBecerra , please [check this issue](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6255). The container issue for the text CTA is also causing the @Praveen-sr 6229 issue that [can be found here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6229).

**Comment by IgnacioBecerra** [comment]
FYI: The Tag Group/Tag addition to the React Card had to be removed from this PR as we weren't able to fix the blocking ci-check. The current change add the light theme, border, and static variation. Tags will be added in a separate PR in the future.

**Comment by shixiedesign** [comment]
Hi Ignacio! Looks good. A few nitpicks, but these style issues are also happening to Web components too. Mostly on the CTA link: 

1. Focus state styling is wrong
image

2. Hover state styling is wrong
image

**Comment by IgnacioBecerra** [comment]
@shixiedesign Thanks for the feedback! I fixed these two style bugs in both React and Web Components Card Static. You mentioned this is also happening in the CTA Link, but I wasn't able see this behavior anywhere else. 

Could you capture the specifics and open up a new issue for it? You can assign me to it since I already know what's causing this.

**Comment by jeffchew** [comment]
@shixiedesign checking if we're good with this one, we will bring in the tag group in a separate PR.

cc: @IgnacioBecerra

**Review by ariellalgilmore — APPROVED** [review]
LGTM! thank you @IgnacioBecerra !

**Comment by shixiedesign** [comment]
@IgnacioBecerra the text part of is looking better but the arrow still didn't get the color change: 
**Current:**
image
**Expecting** arrow to get the color `$hover-primary-text` too
image

**Review by shixiedesign — APPROVED** [review]
Thank you!!

**Comment by jeffchew** [comment]
@IgnacioBecerra Just noticed this diff, wonder if this is a false positive? 
image

cc: @shixiedesign @ariellalgilmore

**Comment by IgnacioBecerra** [comment]
@jeffchew I actually just looked at the build and double checked with the Web Components version, and I can confirm it's a false positive.

**Comment by jeffchew** [comment]
Appears to be a false positive, weird that this happened:
image

**Pull request merged**
