### PR TITLE
fix(megamenu): fixed mega menu link height

### PR DESCRIPTION
**Pull request by andysherman2121**
### Related Ticket(s)

https://github.com/carbon-design-system/ibm-dotcom-library/issues/4034

### Description

Changed mega menu link height from 36px to 32px

### CODE REVIEW

**Comment by kennylam** [comment]
@andysherman2121 Looks like maybe you forgot the category headline?

image

**Review by kennylam — COMMENTED** [review]
@andysherman2121 Looks like maybe you forgot the category headline?

image

**Comment by andysherman2121** [comment]
> @andysherman2121 Looks like maybe you forgot the category headline?
> 
> image

@kennylam good catch! just updated. thanks kenny

**Review by kennylam — APPROVED** [review]
Looks good thanks @andysherman2121!

**Pull request merged**
