### PR TITLE
fix(logo-grid): remove links

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#4549 

### Description

remove links from logo

### Changelog

**Removed**

- `a` wrapper
- `href` props
- `:hover` styles
- documentation updates

### CODE REVIEW

**Comment by IgnacioBecerra** [comment]
Thanks @ariellalgilmore for fixing this! It seems that this is also present in the Web Components version of this (#4425). Maybe it would be good if both issues could be addressed in this PR?

**Comment by ariellalgilmore** [comment]
> Thanks @ariellalgilmore for fixing this! It seems that this is also present in the Web Components version of this (#4425). Maybe it would be good if both issues could be addressed in this PR?

oh yeah @RaphaelAmadeu actually fixed the web component version already in this [PR](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/4541)

**Review by IgnacioBecerra — APPROVED** [review]
@ariellalgilmore Ah gotcha, hadn't seen it! Good job!

**Review by kennylam — APPROVED** [review]
Looks good thanks @ariellalgilmore!

**Pull request merged**
