### PR TITLE
fix(content-group): spacing above and below

### PR DESCRIPTION
**Pull request by NSDrowned**
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5425

### Description

Update 2nd-tier spacing from 96px to 64px.

### CODE REVIEW

**Comment by shixiedesign** [comment]
Hey Julio, this issue is a bit confusing. Lemme try to clarify: 

#### The idea is to change this current spacing (64 top, 64 bottom): 

image

#### To this [spacing specified here](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/guidelines/type-pairing-and-spacing#content-group) **(32 top, 48 bottom)**: 

image

## So this PR haven't addressed the problem: 

Example, `Content group pictogram` margin top didn't change but is expected to reduce to 32px. Margin bottom disappeared completely but is expected to 48px.

image
image

**Comment by NSDrowned** [comment]
@shixiedesign ohhh, ok, I understand. I thought it was 64px all around. Let me fix that.

**Comment by NSDrowned** [comment]
Hello @shixiedesign, I have updated all margins for all components related to `content-block` and `content-group`. I removed any paddings the components had so they will all be ruled by the same set of margins (hope that's ok). I also used `spacing-07` for both top and bottom margins in `sm` like the table pointed out.

The only story that doesn't appear to have the same spacing is `content-group-pictograms` because it comes with extra padding caused by this class (not related to the component):

image

Let me know if you want it gone ⚰️

**Comment by shixiedesign** [comment]
Discussing on Slack with Julio... more soon

**Comment by NSDrowned** [comment]
@shixiedesign updates are up 👍

**Comment by shixiedesign** [comment]
All looks good except the `content-group-pictograms` in Web components. It's probably what you described in the previous comment? I think we just need to get rid of the extra spacing from the demo class and we should be good 👍 

image

**Comment by NSDrowned** [comment]
@shixiedesign removed the padding! 👍

**Review by shixiedesign — APPROVED** [review]
Awesome! Thank you!

**Review by jeffchew — APPROVED** [review]
Thanks @NSDrowned !

**Pull request merged**
