### PR TITLE
fix(language-selector): use select component features for mobile

### PR DESCRIPTION
**Pull request by annawen1**
### Related Ticket(s)

Web component: Footer - Language only - On mobile and tab, native default selector is not enabled #4864

### Description

Create a `language-selector-mobile` version that extends the `Select` component so that the native mobile select is displayed on mobile breakpoints

### Changelog

**New**

- breakdown `<dds-language-selector> ` into `<dds-language-selector-mobile>` and `<dds-language-selector-desktop>`
- `<dds-language-selector-mobile>` utilizes the `Select` component while `<dds-language-selector-desktop>` utilizes the `ComboBox` component

### CODE REVIEW

**Comment by annawen1** [comment]
There's an issue with the option values not appearing on the native select, have a PR up on carbon-web-components to resolve that: https://github.com/carbon-design-system/carbon-web-components/pull/573

Screen Shot 2021-01-13 at 4 56 21 PM

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @annawen1! Do you want to bring in `v1.11.1` version of `carbon-web-components`?

**Review by asudoh — COMMENTED** [review]
Thanks @annawen1 for the updates!

**Review by jeffchew — CHANGES_REQUESTED** [review]
Screen Shot 2021-01-14 at 8 44 51 AM
Screen Shot 2021-01-14 at 8 44 59 AM

Percy picked this one. Micro version looks off. Can you take a look @annawen1 ?

**Review by jeffchew — APPROVED** [review]
LGTM!

**Pull request merged**
