### PR TITLE
chore: merge v1.32.1 release branch

### PR DESCRIPTION
**Pull request by emyarod**

### CODE REVIEW

**Comment by jeffchew** [comment]
@emyarod this probably should be a manual merge, otherwise the tag would get lost with the deleted branch?

**Comment by emyarod** [comment]
@jeffchew wouldn't this be similar to https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8610?

**Comment by jeffchew** [comment]
> @jeffchew wouldn't this be similar to #8610?

Ok, maybe this is why the latest builds have been failing since 1.32.0?

**Comment by emyarod** [comment]
I see, so would this just be a direct push to `main`?

**Comment by jeffchew** [comment]
> I see, so would this just be a direct push to `main`?

Possibly, either that or we enable a merge commit (not a squash commit) for just this PR?

**Comment by jeffchew** [comment]
> > I see, so would this just be a direct push to `main`?
> 
> Possibly, either that or we enable a merge commit (not a squash commit) for just this PR?

I take that back, the tag is still on the release branch itself.

**Comment by emyarod** [comment]
ok I see so a direct push to `main` branch would be the only option then?

**Comment by jeffchew** [comment]
Yes I think so...I'm wondering what we do with the `1.32.0` tag. I see that the branch is still around and hasn't been deleted yet. Perhaps we just re-tag the squash merge with those tags once we delete the branch...

**Review by jeffchew — APPROVED** [review]
LGTM!

**Pull request merged**
