### PR TITLE
fix(card-group): support RTL borders & padding

### LINKED ISSUE #11755: [card-group]: Borders / padding is LTR specific for the dds-card-group component
### Description

The dds-card-group component has LTR specific padding hardcoded, leading to layout issue in RTL languages. This is v1 specific. v2 uses outlines to achive borders in a CSS logical porperties friendly way.

Affected code in v1: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/v1/packages/web-components/src/components/card-group/card-group.ts#L247-L299

### Component(s) impacted

<dds-card-group>
<dds-card-group-item>

### Browser

Chrome

### Carbon for IBM.com version

v1.43.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

ibm.com

### Package

@carbon/web-components

### CodeSandbox example

https://author-p131558-e1282741.adobeaemcloud.com/content/adobe-cms/language-masters/ar/test-page1.html?wcmmode=disabled

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by jkaeser**
### Related Ticket(s)

Closes #11755

### Description

We programmatically set borders & padding for cards within `<dds-card-group>` elements, and we've only been accounting for LTR writing directions. This PR uses logical properties so these borders and paddings look correct in RTL documents.

While working on this I noticed an issue where certain tracked elements could be undefined, causing an error that halts execution. Ultimately this resulted in the "empty" elements we generate for certain card groups to fail to be created, and the dark gray background appearing when it shouldn't. I fixed this with simple optional accessors.

### Testing

Verify the borders and gaps between Cards appear correctly in [the Card Group story in the RTL deploy preview](https://ibmdotcom-web-components-rtl.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/11760/index.html?path=/story/components-card-group--default). Compare to [the Card Group in the default deploy preview](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/11760/index.html?path=/story/components-card-group--default) if necessary.

Specifically check that no background is visible in the last row's empty space when using the "Outlined cards (1px border)" **Grid mode** option.

### Changelog

**Changed**

- `<dds-card-group>` children will receive correct border & padding values in RTL writing mode documents.
- Prevents undefined elements from halting code execution and causing gray background to show when it shouldn't.

### CODE REVIEW

**Review by m4olivei — APPROVED** [review]
Looks good! Nice work.

**Comment by oliviaflory** [comment]
@jkaeser cc @andy-blum 

The text looks great!

The only thing that looks off is the arrow icons.
1. My understanding is directional icons would be mirrored (see examples attached)
2. The arrow icon in the card group has a 32px right padding on it which makes it not align with the text as expected, it's floating in the card

Extra space to the right of the arrow or CTA
Screenshot 2024-05-03 at 9 58 17 AM
Screenshot 2024-05-03 at 10 02 06 AM


Expectation
Screenshot 2024-05-03 at 10 15 49 AM

**Comment by jkaeser** [comment]
@oliviaflory Good catch! This got merged before I could address it, but that's okay. Matt has fixed the arrow direction problem in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11748, which should be merged soon. I believe that only leaves the extra spacing to the right to fix. I'll open up an issue for it.

Thanks for taking a look at this one!

**Comment by jkaeser** [comment]
Created https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11762 for the spacing issue.

**Pull request merged**
