### PR TITLE
fix(card): added text wrapping to cta text

### PR DESCRIPTION
**Pull request by BrunnoM7**
### Related Ticket(s)

[Card] CTA text doesn't wrap #6935

### Description

Corrects the over extension of the CTA text in the Card by wrapping it.

### Changelog

**New**

- Added the boolean property `iconInline` to `card-footer` component
- If the `iconPlacement` is set a `right` and `iconInline` is `true` text CTA will have the wrap behavior.

### CODE REVIEW

**Review by shixiedesign — APPROVED** [review]
Looks good! Thank you

**Review by emyarod — APPROVED** [review]
looks good to me!

**Comment by jeffchew** [comment]
Hey @BrunnoM7 , once you sign the DCO this can get merged in.

**Comment by BrunnoM7** [comment]
I have read the DCO document and I hereby sign the DCO.

**Pull request merged**
