### PR TITLE
fix(masthead-v2): QA design feedback updates

### LINKED ISSUE #9310: [Masthead v2.0.0]: bugs identified in 2.0.0 (Phase 1)
**Engineering info:**  
- Innovation Team engineer: @jkaeser 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/ADCMS-2570

-----

### Description

List of bugs identified by design QA

### Component(s) impacted

Masthead v2

### Browser

Chrome

### Carbon for IBM.com version

v2 feature branch

### Application/website

Carbon for AEM

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/masthead-v2/web-components/?path=/story/components-masthead--default

### Steps to reproduce the issue (if applicable)

reduce browser width to anything between 800–959px wide

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by jkaeser**
### Related Ticket(s)

Resolves #9310 

### Description

Various updates and fixes based on design QA feedback.

### Changelog

**New**

- Adds platform knob to masthead stories

**Changed**

- Updates color tokens for L0 nav items, utility menu icons, and megamenu links
- Updates type tokens in megamenus that use the listing layout
- Prevents tabbed megamenu layout errors at certain breakpoints
- Aligns megamenu category link arrows to top of element

### CODE REVIEW

**Review by proeung — APPROVED** [review]
Looks good from a code perspective.

As for design QA, @oliviaflory and @JaniceChristineM can you help QA this PR to ensure all of the items identified in this issue (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9310#issuecomment-1231865951) has been addressed? Thanks!

**WC Preview** - https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/9324/index.html?path=/story/components-masthead--with-v-2-data

**Comment by oliviaflory** [comment]
@jkaeser @proeung  I just looked over the changes and it is looking really great!

Missing:

### 1. Platform name
Knob for "platform name" doesn't do anything to the storybook preview, this could be a storybook issue but want to confirm that you can have a platform name in the L0.

### 2. Link item container size – the container is now 30px tall, but we are expecting 32px
I have a couple ideas on how we could fix it:
- Option 1: update type token to $body-long-01 which will change the line height to 20px and increase the container to 32px
- Option 2: update the top and bottom padding for the link items to 7px to increase the container size to 32px

It looks like we are using `$body-short-01` but the specs call for `$body-long-01`

I would recommend we select the solution that matches whatever type token we are using in the H3s, I am having trouble finding which tokens are being used in inspect. I will reach out to John on slack to have him help me figure out which would be the best solution! We will need to know which solution was chosen so that we can update the specs

This issue is also in the tabbed masthead model with the tab items and it would be great to make those match!

### Out of Phase 1 scope:
Just reviewed John's comment that these are not in scope of the first release and should be addressed separately. Do we want to put them into Phase 2 or as separate issues?
- [Mobile caret color ](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9310#issuecomment-1231898250)
- [Mega menu tab order ](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9310#issuecomment-1231903629)

**Comment by jkaeser** [comment]
@oliviaflory I fixed those issues you called out. Can you take another look when you have the chance? Thanks!

I think creating separate issues for the out of scope work is best.

**Comment by oliviaflory** [comment]
@jkaeser thanks, should I assume you went with Option 1 and updated the type token to `$body-long-01`?

**Comment by jkaeser** [comment]
> @jkaeser thanks, should I assume you went with Option 1 and updated the type token to `$body-long-01`?

Yep!

**Review by oliviaflory — APPROVED** [review]
Design updates LGMT, thanks @jkaeser

**Comment by proeung** [comment]
@oliviaflory Thanks for the review! I went ahead and move the two items that you and @jkaeser discussed into separate issues that we'll take a look at when phase 2 of the Masthead V2.0.1 project starts. See our JIRA Epic for more detail - https://jsw.ibm.com/browse/AEMSITES-177

- https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9337
- https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9338

cc: @sirkitree

**Pull request merged**
