### PR TITLE
feat(masthead): hide and show upon scroll on mobile

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)
#6046

### Description
This PR adds a feature to the React masthead that hides it upon scroll on mobile if the page contains only the Masthead L0 and Table of Contents component. This also used to be a feature on the Web Components version, but due to some logic updates a few months ago the functionality remained unable to run. This PR restores this feature on WC.

This can be tested in the default Dotcom Shell story in both React and WC environments in a mobile breakpoint.

### Changelog

**New**

- added hide/show masthead scroll functionality to react

**Changed**

- restored hide/show masthead scroll functionality in web components

### CODE REVIEW

**Comment by kennylam** [comment]
@IgnacioBecerra Doesn't this functionality exist already?

https://www.ibm.com/standards/carbon/react/iframe.html?id=components-dotcom-shell--with-l-1

**Comment by IgnacioBecerra** [comment]
@kennylam Not with the Masthead + the ToC alone

**Comment by kennylam** [comment]
> It does exist, but not with the Masthead L0 + the ToC alone.

Right, sorry what I meant was could we not use the existing functionality to determine the sticky status and adjust CSS accordingly?

**Comment by IgnacioBecerra** [comment]
@kennylam The way it's currently set up in React, the Masthead + L1 just disappears once it gets over a certain threshold instead of smoothly scrolling out by being "pushed out" by the element taking its place, which is how WC does it. This makes it so at least the L0 + ToC behaves like it should.

**Comment by oliviaflory** [comment]
Thanks @IgnacioBecerra this looks great!

Did you change anything in the React [masthead with L1](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/7982/index.html?path=/story/components-dotcom-shell--with-l-1) story? I noticed that masthead is randomly disappearing if you interact with the TOC then scroll back up. Tested on my iPhone 12 Pro in Safari

https://user-images.githubusercontent.com/45692622/149419486-1c005906-c851-44bc-83f9-415d18448ef3.mp4


I'm hoping the [React Percy](https://percy.io/538fc19a/Carbon-for-IBM.com-React/builds/14918493/changed/843210771?browser=chrome&browser_ids=20&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=320%2C1280) difs are false positives because it's showing all the smart quotes removed, but I thought Kenny had merged that in already?

Similar comment for the [Web Components Percy}(https://percy.io/538fc19a/Carbon-for-IBM.com-Web-Components/builds/14918453/changed/843208664?browser=chrome&browser_ids=20&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=320%2C1280) difs, smart quotes look removed and there's a few things registering as new snapshots that shouldn't bee new, like card group with images??

**Comment by IgnacioBecerra** [comment]
https://user-images.githubusercontent.com/24970122/149464371-ccbf75f2-473c-49f7-a86c-793360273f9b.MOV

@oliviaflory I checked and seems like the bug is already present in Canary.

As for the Percy diffs, it might be outdated, I updated the branch so let's see if they still come up.

**Comment by oliviaflory** [comment]
@IgnacioBecerra everything looks good on storybook but we did lose the masthead in the [Next JS](https://percy.io/538fc19a/Carbon-for-IBM.com-NextJS-Test-App-Upstream/builds/15018825/changed/848936519?browser=chrome&browser_ids=20&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280) Percy snapshots 🥲 
Is that normal and it will restore after the PR is merged?

**Review by oliviaflory — APPROVED** [review]
LGTM, thanks @IgnacioBecerra !

**Review by ariellalgilmore — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
