### PR TITLE
fix(table-of-contents): fix subtree observer callback

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)

[ADCMS-2489](https://jsw.ibm.com/browse/ADCMS-2489)

### Description

Fixes a bug in the contentObserverCallback that would erroneously remove elements from the `_targets` property by only scraping one slot

### Changelog

**Changed**

- modified contentObserverCallback logix
- runs contentObserverCallback on change to `name` and `data-title` attributes in assigned nodes & their subtrees

### CODE REVIEW

**Review by jkaeser — CHANGES_REQUESTED** [review]
The code changes look good! Can you update the `_contentMutationObserver`'s documentation comment to indicate we're no longer only observing the default slot?

**Review by IgnacioBecerra — APPROVED** [review]
LGTM, thanks @andy-blum !

**Review by RichKummer — APPROVED** [review]
LGTM!

**Review by jkaeser — APPROVED** [review]

**Comment by andy-blum** [comment]
@IgnacioBecerra is this ready to merge?

**Pull request merged**
