### PR TITLE
fix(cta-card): video heading style fix

### LINKED ISSUE #8273: [CTACard]: video heading is blue
### Description

Heading should not be blue

Screen Shot 2022-02-14 at 3 19 25 PM
 

### Component(s) impacted

CTACard

### Browser

Chrome

### Carbon for IBM.com version

1.31.0-rc.1

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Application/website

carbon for ibm.com

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/react/?path=/story/components-cta--card

### Steps to reproduce the issue (if applicable)

1. go to https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/react/?path=/story/components-cta--card
2. select video knob

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by sangeethababu9223**
### Related Ticket(s)

Closes #8273 

### Description

CTA Card - Video Heading color was not correct.

### Changelog

**Removed**

- Removed CTA Video Heading  color

91D67984-6477-452A-A12C-C8C058FC6F4F

### CODE REVIEW

**Comment by sangeethababu9223** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by annawen1 — APPROVED** [review]
LGTM!

**Review by annawen1 — COMMENTED** [review]
Screenshot 2023-08-10 at 9 13 50 AM

looks like the link-list video variation gets affected.

**Review by annawen1 — COMMENTED** [review]
Screenshot 2023-08-10 at 9 13 50 AM


looks like the link-list video variation gets affected.

**Comment by annawen1** [comment]
recheck

**Review by annawen1 — APPROVED** [review]
Looks good!

**Review by RichKummer — APPROVED** [review]
LGTM! Thanks @sangeethababu9223 🎉 🎉 🎉

**Pull request merged**
