### PR TITLE
chore(masthead-v2): update main v2 branch with dev/L0 v2.1 changes

### PR DESCRIPTION
**Pull request by jkaeser**
### Description

JIRA ticket: https://jsw.ibm.com/browse/ADCMS-2985

This PR should simply be getting `feat/masthead-v2` up to date with the changes from `feat/masthead-v2-dev`.

#### Why are there nearly 1000 associated commits?
I believe the reason is that in addition to integrating `feat/masthead-v2.1` feature work, `feat/masthead-dev` also recently merged in the latest from `main` ([8f9e0ba](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/commit/8f9e0bae3da5936da3c1e2f77b91c862d4d8f737)). Back in November 2022, we _also_ merged what was then the latest from `main` into `feat/masthead-v2`, but this was after `feat/masthead-v2-dev` already split off. This somehow caused git to be unable to find the two branches' common ancestor.

To fix this, I reverted the merge from 11/22, then merged `feat/masthead-v2-dev` into `feat/masthead-v2`, which applied cleanly.

### Testing Instructions

Please take a final, sweeping look at [the Masthead demo](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/10066/iframe.html?args=&knob-platform%20name%20(platform)=&knob-show%20the%20profile%20functionality%20(has-profile)=true&knob-show%20the%20search%20functionality%20(has-search)=true&knob-search%20placeholder%20(searchPlaceholder)=Search%20all%20of%20IBM&knob-selected%20menu%20item%20(selected-menu-item)=Consulting%20&%20Services=&knob-The%20user%20authenticated%20status%20(user-status)=Unauthenticated&knob-use%20mock%20nav%20data%20(use-mock)=true&id=components-masthead--with-v-2-data&viewMode=story) and verify it meets the [L0 v2.1 design & functional specs](https://www.figma.com/file/35JfN0Sg4ltIIjM7jBDKMk/Navigation?node-id=3179%3A173922&t=nXDyl46h5rLGsr4y-0). Note any issues you find on this PR. Thanks!

### Changelog

**New**

- Integrates latest changes from `feat/masthead-v2-dev`, including L0 v2.1 design updates.

### CODE REVIEW

**Comment by kennylam** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by jkaeser** [comment]
Looks like things are working as expected: https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/10066/iframe.html?args=&knob-platform%20name%20(platform)=&knob-show%20the%20profile%20functionality%20(has-profile)=true&knob-show%20the%20search%20functionality%20(has-search)=true&knob-search%20placeholder%20(searchPlaceholder)=Search%20all%20of%20IBM&knob-selected%20menu%20item%20(selected-menu-item)=Consulting%20&%20Services=&knob-The%20user%20authenticated%20status%20(user-status)=Unauthenticated&knob-use%20mock%20nav%20data%20(use-mock)=true&id=components-masthead--with-v-2-data&viewMode=story

**Review by jwitkowski79 — CHANGES_REQUESTED** [review]
@jkaeser @Putra
Hello!Thanks for working on this! I have some feedback below:
### Spacing
1. Spacing between heading level 2 with descriptions and the link list should be increased 24px. Spacing between heading level 2 without descriptions and the link list should stay at 16px.

What I'm seeing:
53005867-E1EC-43FB-992C-D2D472C0F1A4

Expected:
Screen Shot 2023-02-22 at 11 42 49 AM

2. On mobile: 8px spacing is needed between heading level one and description text below 

What I'm seeing:
D56D678B-076E-404B-96B6-F09AC1B98260

Expected:
A44BEC1A-B356-43F8-9F20-5007CE8F4AC3_4_5005_c

### Grid alignment
1. On desktop breakpoints, some rows are not aligned to the grid. 

What I'm seeing:
13053569-F300-433A-A74D-766FD2E03EC6
A978C10A-BD3C-4E98-AC56-326C8FE96650

Expected:
Screen Shot 2023-02-22 at 11 50 31 AM

### Horizontal scroll bar and vertical bar
1. There's a horizontal scroll bar appearing in some areas when it's not needed. Can we remove this?

2. There's also a gray vertical bar that appears on the right size of the nav. Can we also remove this?

What I'm seeing:
FF2844D6-EB3D-433A-990F-046AF71F1A53

### Focus states
1. When tabbing through the focus states, the main menu will scroll when it reaches the heading level 1.  See attached video below: 

https://user-images.githubusercontent.com/2040791/220701071-c410e4c3-a470-4e6f-890b-6278f8053dfc.mp4

I think that's it! I would also love @oliviaflory feedback on this too

**Review by jwitkowski79 — CHANGES_REQUESTED** [review]
@jkaeser @proeung Hello! All feedback has been addressed except I'm still seeing some columns that are off the grid. Anyway we can closer align these? Thank you!!
98F3E07F-9F8D-4CA4-9370-0C477012A3C1

**Comment by jkaeser** [comment]
> @jkaeser @proeung Hello! All feedback has been addressed except I'm still seeing some columns that are off the grid. Anyway we can closer align these? Thank you!!

@jwitkowski79 Hrm, I've not been able to replicate that misalignment so far. Which browser are you using?

**Comment by jkaeser** [comment]
@jwitkowski79 Fixed the issue with @andy-blum's help: scrollbars, which are set on a system level, were squishing scrollable area's contents. Can you take another look when you have a chance? Thanks!

**Review by jwitkowski79 — APPROVED** [review]
@jkaeser Everything aligns to the grid now. Thanks for working on this! Approved!

**Review by proeung — APPROVED** [review]

**Comment by oliviaflory** [comment]
@jwitkowski79 @proeung everything looks pretty good!

One thing I caught in the `Simple Megamenu (Featured)` example is at the 800px breakpoint, the content layout isn't matching the design specs

**Current**
The `Featured` area is condensing similar to the `Faceted` menu, but according to the design specs the Featured area should span horizontally.
Screenshot 2023-02-28 at 4 24 02 PM
Screenshot 2023-02-28 at 4 29 23 PM


**Expecting**
Screenshot 2023-02-28 at 4 25 21 PM

I am not sure what we are expecting in the mobile layout here, but it could be confusing that the H1 "Heading" is placed above `Training` `Community` and `Resources` when it is intended as the umbrella heading for `What is..`, `Developer education`, etc.


Screenshot 2023-02-28 at 4 32 31 PM


---- 

Small fixes we could address outside this PR (they are also not speced in the design file):
1. The mobile `Back` button doesn't have a hover change when also on focus
2. In mobile the `View all` link doesn't have the same hover state as the desktop (but it should if we can!)

**Review by oliviaflory — APPROVED** [review]
Looks good! @proeung and I discussed addressing my latest comments about the `Featured` example in a separate PR

**Comment by jwitkowski79** [comment]
@jkaeser @proeung Just took a look at @oliviaflory comment and agree that this can be addressed in a followup PR. One thing I did want to comment on based on @oliviaflory feedback on the `Simple Megamenu (Featured):` mobile menu: 

> I am not sure what we are expecting in the mobile layout here, but it could be confusing that the H1 "Heading" is placed above Training Community and Resources when it is intended as the umbrella heading for What is.., Developer education, etc.

I believe the organization of the flow on mobile needs to be updated so the H1 at the top of the page makes sense.  Here's a visual example on desktop and how it breaks down on mobile. 
L0 Navigation - Fauceted - h2-with-descriptions
Nav

So `Heading` would become an item to tap on the second level tap, and all of the items in the featured side bar would also appear on level 2. @oliviaflory This is what I remember and what is documented in the Figma file. Just wanted to check if we're on the same page so we can document this update in the new PR

**Comment by kennylam** [comment]
@oliviaflory Not sure why the DCO is failing for me, but feel free to squash/merge this if everything looks good.

**Comment by proeung** [comment]
Squash/merge this PR now and the remaining feedback will be addressed in a separate PR. Issue to follow

**Pull request merged**
