### PR TITLE
[Locale API]: Adjust fallback layer logic v1

### PR DESCRIPTION
**Pull request by m4olivei**
### Related Ticket(s)

Follow up to https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11404 for v1

### Description

See v2 PR for details https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11404

### Changelog

**Changed**

- Test isolation. Stand up and tear down mocks between each test such that we have a clean SUT
- Restore the indended fallback sequence
- Make `LocaleAPI.getLocale` and LocaleAPI.getLang` behave the same and deprecate `LocaleAPI.getLang`
- Remove most tests for `getLang`, they are effectively the same as `getLocale` now.
- Improve LocaleAPI JSDoc.

### CODE REVIEW

**Review by kennylam — APPROVED** [review]
LGTM!

**Comment by andy-blum** [comment]
Looks like ci-check is failing - @m4olivei can you investigate to see if this is a false positive?

```
@carbon/ibmdotcom-web-components:   dds-search-with-typeahead
...
@carbon/ibmdotcom-web-components:       ✗ should redirect to the search result upon selecting a search result
@carbon/ibmdotcom-web-components: 	Expected spy _redirect to have been called with:
@carbon/ibmdotcom-web-components: 	  [ 'https://www.ibm.com/search?lnk=mhsrch&q=test&lang=en&cc=US' ]
@carbon/ibmdotcom-web-components: 	but it was never called.
...
```

**Comment by m4olivei** [comment]
It doesn't fail locally. Re-running with a clopen.

**Comment by m4olivei** [comment]
Fixed the unit test by extending the wait time in the test that was failing. As far as I can tell not directly related to the changes here. I could reproduce on my local by cutting down the timeout time. https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11418/commits/18c223bba912b1b4a294832d11287a9c07fd8261

**Pull request merged**
