### PR TITLE
test(integration-ui): fix integration ui tests

### PR DESCRIPTION
**Pull request by kennylam**
### Description

Updates various UI integration tests which were failing.

### Changelog

**Changed**

- update missing images for `table-of-contents`
- update megamenu link/title names for `masthead`
- update megamenu mock data
- add megamenu properties to translation service-store
- update `expressive-modal` storybook path

### CODE REVIEW

**Comment by jeffchew** [comment]
@kennylam fyi, tests are getting limited to branches with the pattern `test/*`, but we can still get this one in to make sure that at least what's there isn't broken:

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/4480

**Comment by kennylam** [comment]
> @kennylam fyi, tests are getting limited to branches with the pattern `test/*`, but we can still get this one in to make sure that at least what's there isn't broken:

Yep, I saw your PR

**Review by jeffchew — APPROVED** [review]
LGTM!

**Comment by jeffchew** [comment]
@kennylam can you fix the merge conflicts?

**Review by asudoh — APPROVED** [review]
LGTM 👍, nice change - Thanks @kennylam for doing this!

**Comment by kennylam** [comment]
> @kennylam can you fix the merge conflicts?
Done, thanks!

**Pull request merged**
