### PR TITLE
fix(card-group): Image height of the last card

### PR DESCRIPTION
**Pull request by NSDrowned**
### Related Ticket(s)

React: Card section - images: image height of the last card #4810

### Description

The image on the last card is 1px taller. This happens because the right padding is removed on the last card to hide the dark border. The missing padding allows the image to be 1px taller.

### Changelog

**Changed**

- `_card-group.scss to fix the height

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Hi @NSDrowned congrats to (if I'm right) your first PR! Honestly I wish there is a way not having to tweak the card size, but I want to defer to other devs.

**Comment by NSDrowned** [comment]
Thank you (yes, my first) and I agree @asudoh, it felt kind of hacky. All the other solutions I came up with required modifying the HTML structure, but let me try to figure out a different (CSS only) solution.

**Comment by NSDrowned** [comment]
Pushed a new CSS only approach (No more % height calculation). I added the padding that was removed from the last card to another spot of the card so that there won't be any missing padding that will affect the image height. This will only apply to the last card.

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @NSDrowned for the update!

**Review by kennylam — APPROVED** [review]
LGTM thanks @NSDrowned!

**Pull request merged**
