### PR TITLE
fix(LocaleModale): region card layout

### PR DESCRIPTION
**Pull request by kennylam**
### Related Ticket(s)

#4628 

### Description

Add missing markup structure of `region-item` that was affecting layout of region cards

### Changelog

**Changed**

- add missing `content` div

### CODE REVIEW

**Comment by jeffchew** [comment]
@kennylam can you retarget to the release branch?

**Review by asudoh — COMMENTED** [review]
LGTM 👍 once the target branch is changed - Thanks @kennylam!

**Comment by kennylam** [comment]
> LGTM 👍 once the target branch is changed - Thanks @kennylam!

Done, thanks @asudoh!

**Review by asudoh — APPROVED** [review]
Thanks @kennylam for the update!

**Pull request merged**
