### PR TITLE
fix(content-group-banner-6794): fix before pseudo-element bug on safari

### PR DESCRIPTION
**Pull request by proeung**
### Related Ticket(s)

GH Issue: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6794
HC JIRA Ticket: https://jsw.ibm.com/browse/HC-2130

### Description

- This PR removes the use of `::before` pseudo-element on components/slots that was previously used to create the divided line because Safari can't recognize the pseudo-elements like `::before` and `::after` in the Shadow Dom.
- 
### Testing Instruction

- Visit the `Content group banner` in Safari- `/?path=/story/components-content-group-banner--default`
- Ensure that the divider line between title and CTA is showing up correctly in Safari on larger breakpoints.

### Expected Display

Screen Shot 2021-08-11 at 3 23 00 PM

### CODE REVIEW

**Comment by ariellalgilmore** [comment]
Thanks @proeung! Looks like Percy caught a change that the divider should be aligned to the edge of the column in the max breakpoint vs in the middle for xl and lg breakpoints

Screen Shot 2021-08-12 at 8 45 02 AM

**Comment by shixiedesign** [comment]
Hi! Yes thanks for the fix - like Ari mentioned, I think the only thing is the text links didn't start on the column: 
**Current:** 
image

Expecting as spec image Ari posted above ☝️

**Comment by proeung** [comment]
@ariellalgilmore @shixiedesign Great catch! I just pushed up a commit that should fix the spacing issue.

**Review by shixiedesign — APPROVED** [review]
👍 ⚡

**Review by ariellalgilmore — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
