### PR TITLE
fix(masthead): change brand-name to platform

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#5022 

### Description

Change `brand-name` to platform for consistency with React

### Changelog

**Changed**

- property name from `brand-name` to `platform`
- knobs from `brandName` to `platform`

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
LGTM basically. The change in attribute name is a breaking change and wanted to have @jeffchew to chime in. Thanks @ariellalgilmore!

**Comment by jeffchew** [comment]
> LGTM basically. The change in attribute name is a breaking change and wanted to have @jeffchew to chime in. Thanks @ariellalgilmore!

@ariellalgilmore @asudoh 
Yes, this is a breaking change. It's unknown how many people are using this now in web components. But I'm wondering if we can introduce `brand-name`, and have any deprecation notice that `platform-name` will be removed in a future version?

**Comment by ariellalgilmore** [comment]
> > LGTM basically. The change in attribute name is a breaking change and wanted to have @jeffchew to chime in. Thanks @ariellalgilmore!
> 
> @ariellalgilmore @asudoh
> Yes, this is a breaking change. It's unknown how many people are using this now in web components. But I'm wondering if we can introduce `brand-name`, and have any deprecation notice that `platform` will be removed in a future version?

Okay sounds good. So keep brand-name for now and just change the story knob to platform?

**Comment by asudoh** [comment]
Given @ariellalgilmore is changing the attribute name from `brand-name` to `platform` instead of the way around, I'm wondering if @jeffchew meant to deprecate `brand-name`. @jeffchew Is it the case...? Thanks!

**Comment by jeffchew** [comment]
> Given @ariellalgilmore is changing the attribute name from `brand-name` to `platform` instead of the way around, I'm wondering if @jeffchew meant to deprecate `brand-name`. @jeffchew Is it the case...? Thanks!

Yes, if the purpose of this is to align to the prop name in React. We shouldn't ditch `brand-name` entirely though as it's breaking, I was suggesting keeping it as a deprecated attribute and would throw a warning in console if it's being used.

**Comment by ariellalgilmore** [comment]
> > Given @ariellalgilmore is changing the attribute name from `brand-name` to `platform` instead of the way around, I'm wondering if @jeffchew meant to deprecate `brand-name`. @jeffchew Is it the case...? Thanks!
> 
> Yes, if the purpose of this is to align to the prop name in React. We shouldn't ditch `brand-name` entirely though as it's breaking, I was suggesting keeping it as a deprecated attribute and would throw a warning in console if it's being used.

ah I see! Thanks @jeffchew, just updated!

**Review by kennylam — APPROVED** [review]
LGTM thanks @ariellalgilmore!

**Pull request merged**
