### PR TITLE
chore(rollup): adding plugin to minify HTML template literals

### PR DESCRIPTION
**Pull request by bruno-amorim**
### Related Ticket(s)

Closes # [ADCMS-4317
](https://jsw.ibm.com/browse/ADCMS-4317)
### Description

Adding a rollup plugin to the C4IBM build step to minify HTML template literals to reduce the DOM node count in web component shadow DOM subtrees.

### CODE REVIEW

**Review by m4olivei — CHANGES_REQUESTED** [review]
This should be targetted at the `v1` branch, now that `main` is where v2 development is happening.

This same minification is being worked on for `v2` by @marcelojcs in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11207

**Comment by m4olivei** [comment]
> This should be targetted at the `v1` branch, now that `main` is where v2 development is happening.
> 
> This same minification is being worked on for `v2` by @marcelojcs in #11207

@bruno-amorim reminder that this is still true. The PR here should be retargetted to the `v1` branch.

**Comment by andy-blum** [comment]
because the `gulp-minify-html-literals` plugin is mysteriously wiped from the internet, we'll just yank it out of this PR and rely on the rollup solution for CDN users.

**Comment by jkaeser** [comment]
Tests are failing, and it's difficult to ascertain the reason why since this PR's diff is awfully bloated. I've reapplied the important changes over in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11216, and tests are passing there.

**Pull request closed without merging**
