### PR TITLE
feat(tab-extended-vertical): add "Vertical" Orientation

### PR DESCRIPTION
**Pull request by proeung**
### Related Ticket(s)

DDS Consulting Issue: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6614
HC JIRA Ticket: https://jsw.ibm.com/browse/HC-2066

### Description
- This PR adds in the "Orientation" prop that allows adopters to set the orientation of the Extended Tabs layout component to display as `horizontal (default)` or `vertical`.

### Design & Functional Specs
- https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Tabs-extended#22-orientation 

Screen Shot 2021-08-05 at 3 45 33 PM

### Changelog

**New Components/Props**

- `Orientation` - this prop/attribute allows adopters to set the orientation of the Extended Tabs component to horizontal (default) or vertical.

**Removed**

- N/A

### Note

- The layout component/band that's designed for the GEO page in AEM requires `card-link` component, however, this particular card component doesn't have the same functional specs as the `<dds-card-group-item>` component, which can make it difficult to assemble within AEM.
- We might want to possible extend the `<dds-card-link>` component to the following:
```
<dds-card-group>
   <dds-card-group-link-item href="https://example.com">
   </dds-card-group-link-item>
</dds-card-group>
```

### Testing Instructions
- Visit the `Tab Extended` layout component - `/?path=/story/components-tabs-extended--default`
- Navigate to the "Knobs" tab and set `Orientation` to `vertical`
- Ensure that the "Vertical" tabs component matches with the design specs for all breakpoints.

### CODE REVIEW

**Comment by proeung** [comment]
@shixiedesign @photodow While testing the assembling of the Tabs Extended to look like this Geo home layout component (see attached). I noticed some follow-up work that we need to do on the WC package side (see my "note" section - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6826#issue-704987352). Let me know what you both think.

**Comment by proeung** [comment]
@emyarod Thanks for the review! I just pushed up a commit that should fix the hover issue that you mentioned above.

@shixiedesign or @photodow Any thoughts about what I mentioned here - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6826#issuecomment-893770697?

**Comment by shixiedesign** [comment]
Hi Putra! Sorry I'm still a bit distracted from moving. Re your note above, do you mean that the current dds Card group component cannot accept Card link? If so, we should make a fix to Card group, so that the card group can arrange card links on a grid just like regular Cards. If my understanding is correct, please feel free to open an issue. 

Taking a look at the component now.

**Comment by shixiedesign** [comment]
Hey @proeung ! Thanks! It looks great. I'm noticing the specs for it isn't exactly complete and I will patch that hole momentarily... sorry about that, but you did a great job interpreting the states of the component based on existing Tabs extended! I think it looks good, and only a few comments: 

1. `max - lg` breakpoint: content area is not aligned to grid: 
image

2. Currently the first tab is showing Card group in content area. Ideally we use a simple string in content area to indicate it's just an empty slot and can be used for many different components. 
image

3. `md` breakpoint, accordion currently have a bug (in horizontal tabs too). Expecting the accordion horizontal rule to hang both sides: 
image

4. Same comment on `sm` breakpoint
image

5. Motion should be great if we can animate the underlines of the tabs same as how Hybrid cloud library has it. I believe it was something like this: 
tabs-vertical

**Comment by proeung** [comment]
@shixiedesign Thanks for the review! Please see my response below.

> Hi Putra! Sorry I'm still a bit distracted from moving. Re your note above, do you mean that the current dds Card group component cannot accept Card link? If so, we should make a fix to Card group, so that the card group can arrange card links on a grid just like regular Cards. If my understanding is correct, please feel free to open an issue.

No worries! My current understanding is that the current `<dds-card-group>` component does not accept the card-link component. We might want to possibly extend the <dds-card-link> component to the following (see below). I think we can capture this change in a separate ticket but just wanted to bring it up as it's going to be difficult for AEM or other adopters to assemble the band/section outlined here - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6501.

```
<dds-card-group>
   <dds-card-group-link-item href="https://example.com">
   </dds-card-group-link-item>
</dds-card-group>
```

> max - lg breakpoint: content area is not aligned to grid:

Fixed

> Currently the first tab is showing Card group in content area. Ideally we use a simple string in content area to indicate it's just an empty slot and can be used for many different components.

I adjusted the SB preview to include the simple text sting, however, I think from a library documentation perspective, it's still good to showcase to users (eg. designers or UXers) the capability of this component where you can add other UI components to make a band/component layout. Perhaps, this is something we should consider adding to the design guidelines/docs if there's any.

> md breakpoint, accordion currently have a bug (in horizontal tabs too). Expecting the accordion horizontal rule to hang both sides:

Fixed

> Same comment on sm breakpoint

Fixed

> Motion should be great if we can animate the underlines of the tabs same as how Hybrid cloud library has it. I believe it was something like this (on hover text darken & underline grows. onClick previous blue underline fades out quickly 90ms and the new selected item's underline turns blue).

Happy to add this animation, however, I just wanted to note that the current underlines are using the `border-bottom` property and if we want to add this left-to-right animation, we'll need to refactor the current code that's being used within the tab items for both orientations (Horizontal and Vertical), unless you just want to scope this to just the vertical tabs. Also, we'll need to adjust the hover direction on RTL as well. Anywho, let me know what you think.

**Review by kennylam — APPROVED** [review]
LGTM thanks @proeung! Looks like you just need to update the unit test.

**Comment by shixiedesign** [comment]
@proeung Ha fantastic point for RTL getting the other dir animation. Let's avoid too much refactor and I can add motion to a future ticket! 

Okay, I just open a ticket for Card group modification. Please review if the description is accurate. https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/6876

> Perhaps, this is something we should consider adding to the design guidelines/docs if there's any.

Yes this example will be captured in the website!

**Comment by shixiedesign** [comment]
Also gonna tag @skuruvil to review this one moving forward.

**Comment by proeung** [comment]
@shixiedesign The 3 items that you've noticed should be fixed now. Please take a look when the deploy preview is ready.

**Comment by skuruvil** [comment]
@proeung couple of updates

1. Tabs label should wrap to 2 lines at 3 columns (not at 4 columns)
Screenshot 2021-08-17 at 9 29 50 PM

2. Based on the discussion with Shixie we have agreed to update the space between the labels to 24px

Screenshot 2021-08-17 at 9 33 03 PM

3. We have updated the type tokens for labels 
Tab label selected : `$productive-heading-02`, `$text-01 `
Tab label enabled: `$body-short-02`, `$text-02 `
Tab label hover: `$body-short-02`, `$text-01 `
Here is the updated visual spec [](https://ibm.ent.box.com/file/847598629410 )

Note: **We may need to do these updates for Tab Extended Horizontal too**

Screenshot 2021-08-17 at 10 03 38 PM

Thank you

**Comment by skuruvil** [comment]
@proeung looks great to me. I don't have any further changes, Thank you

**Comment by proeung** [comment]
@skuruvil Wonderful!

@jeffchew @annawen1 @ariellalgilmore Can I get a code review so that we can get this PR merged down?

**Review by ariellalgilmore — APPROVED** [review]
LGTM!

**Pull request merged**
