### PR TITLE
fix(cta-block): remove margin top from video container

### PR DESCRIPTION
**Pull request by annawen1**
### Related Ticket(s)

CTA Block wrong alignment when using different media items #6414

### Description

`video-player-container` has a top margin applied to itself, which causes spacing issues when placed within another component. The issue becomes visible when user tries to align both video and images in the `cta-block` or `cta-section` components.

This fix resolves some spacing mismatching in `callout-with-media` as well.

**CURRENT:**
Screen Shot 2021-07-14 at 5 20 38 PM

**AFTER:**
Screen Shot 2021-07-14 at 5 17 46 PM

### Changelog

**Changed**

- set the margin-top styling for `cta-block-item__media` to maintain original spacing
- - set margin top in video-player story

**Removed**

- margin-top styling on the `video-player-container`

### CODE REVIEW

**Comment by DragosRistici** [comment]
i'll take this one @annawen1

**Review by kennylam — APPROVED** [review]
Thanks @annawen1!

**Comment by DragosRistici** [comment]
Looking good, Anna. This little thing that we've talked about (extra spacing on all items, not only with media) on Slack and we should be good to go. Will check it again in the morning. 
Screenshot 2021-07-15 at 23 09 16

**Comment by annawen1** [comment]
@DragosRistici after looking more into this and looking at the design specs, I believe there was extra spacing added to the `text` and `button` content items that isn't supposed to be there. I removed the spacing so that there is a total of 64px between the CTA section copy and the content items.

Screen Shot 2021-07-15 at 5 13 04 PM

I set the class to be `hidden` when there are no media items passed, so the spacing is now consistent to 64px. (48px bottom padding from the "Browse tutorial" link + 16px from top margin of the content item)
Screen Shot 2021-07-15 at 5 45 26 PM
Screen Shot 2021-07-15 at 5 45 10 PM


Let me know if this is wrong and I'll remove those changes!

**Comment by DragosRistici** [comment]
A little thing, @annawen1 , on mobile, the section heading lost the grid. 

Screenshot 2021-07-16 at 18 16 54

**Review by DragosRistici — APPROVED** [review]
LGTM, @annawen1! Thank you!

**Pull request merged**
