### PR TITLE
refactor(quote): add callout quote styles for inverse color scheme

### PR DESCRIPTION
**Pull request by emyarod**
### Related Ticket(s)

#8837

### Description

This PR updates the inverse color theme Quote component to match the Callout Quote component

### CODE REVIEW

**Comment by RichKummer** [comment]
@emyarod noticed the CTA color token seems to be off in the inverse `Quote`. CTA should be `$inverseLink` (same as Callout quote)

Screen Shot 2022-06-16 at 6 23 35 PM

**Comment by emyarod** [comment]
@RichKummer the inverted link color should be fixed now!

**Comment by emyarod** [comment]
@RichKummer like colors should be fixed on both color schemes, and the spacing should be back to normal as well!

**Review by RichKummer — APPROVED** [review]
LGTM! Thanks for making the changes @emyarod !

**Pull request merged**
