### PR TITLE
chore(quote): change slot names to dash-case

### PR DESCRIPTION
**Pull request by asudoh**
### Related Ticket(s)

Refs #4230.

### Description

Changes slot names of `<dds-quote>` from pascal case to dash-case to align the naming pattern to other components.

### Changelog

**Changed**

- The slot names of `<dds-quote>` from pascal cse to dash-case.

### CODE REVIEW

**Review by jeffchew — APPROVED** [review]
Thanks @asudoh !

**Comment by jeffchew** [comment]
@asudoh one thing though, the documentation isn't updated, and can the slots get documented too?

**Comment by asudoh** [comment]
Great catches @jeffchew - Updated.

**Comment by asudoh** [comment]
@jeffchew Thank you for catching missing `source-copy` slot content! Fixed.

**Pull request merged**
