### PR TITLE
test(table-of-contents): restore scrollspy tests

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)

#7770 

### Description

Currently, PR only restores tests so they run in the pipeline. I'm unable to get them to fail locally so we'll need to let the CI infrastructure highlight the test failures.

### CODE REVIEW

**Comment by jeffchew** [comment]
@andy-blum looks like an error came out of that test:

image

**Comment by andy-blum** [comment]
@jeffchew The 'details' link to the e2e test is inaccessible to me. Is there a way to gain access to that?

**Comment by jeffchew** [comment]
> @jeffchew The 'details' link to the e2e test is inaccessible to me. Is there a way to gain access to that?

I gave you access, let me know if you still don't see it.

**Comment by andy-blum** [comment]
@jeffchew I'm getting a connection timeout error

**Comment by jeffchew** [comment]
> @jeffchew I'm getting a connection timeout error

You will have to be connected to IBM VPN to access.

**Review by emyarod — COMMENTED** [review]
looks like there are some merge conflicts which need to be resolved, otherwise looks good to me!

**Comment by andy-blum** [comment]
@jeffchew I think we're still waiting for more info on why this is failing. You said you were able to do ad hoc browserstack runs?

**Comment by jeffchew** [comment]
> @jeffchew I think we're still waiting for more info on why this is failing. You said you were able to do ad hoc browserstack runs?

Yes, though we would need to create on an upstream branch. We can then trigger it from Jenkins to point to that branch to run.

**Comment by jeffchew** [comment]
> @jeffchew I think we're still waiting for more info on why this is failing. You said you were able to do ad hoc browserstack runs?

Created a branch, will trigger a browserstack build to see what happens:
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/tree/test/table-of-contents

**Comment by jeffchew** [comment]
@andy-blum we can probably keep this branch open to test against the non-browserstack test runs in Github Actions, might be good to see the results after you fix the merge conflicts.

**Comment by annawen1** [comment]
Doesn't seem like we're getting original issues in the TOC e2e tests anymore. Closing this PR.

**Pull request closed without merging**
