### PR TITLE
fix(cta-section) fix various style errors at sm breakpoint

### PR DESCRIPTION
**Pull request by huntermacd**
### Related Ticket(s)

JIRA: https://jsw.ibm.com/projects/HC/issues/HC-2292
GH: #7480 

### Description

This PR addresses a handful of design discrepancies on the cta section with items component. Spacing was adjusted and a horizontal rule was added between row items.

### Changelog

**Changed**

- content-block.scss
- cta-block.scss
- cta-section.scss

### CODE REVIEW

**Comment by proeung** [comment]
@DragosRistici Thanks for conducting design QA for this PR! The items that you've noted above look to be spacing/padding bugs that @jwitkowski79  outlined in this issue (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7482).

In an effort to stick to the scope outlined in the original issue and keep this PR moving forward (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7480), I think it's probably good to limit the design QA to the `sm` breakpoints and address the rest of the design QA feedback in this issue (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7482). @shixiedesign Let me know what you think as well.

**Comment by huntermacd** [comment]
@proeung @DragosRistici Pushed my changes. There are spacing adjustments to all breakpoints, but I've restricted the horizontal dividing lines to small breakpoint only.

**Comment by DragosRistici** [comment]
@huntermacd @proeung I see a few issues with these changes though: 

1. It adds a second bottom border to the `CTA section – with content items` story when the CTA Block border is checked.
Screenshot 2021-11-05 at 18 25 11


2. The `CTA section - with link list` story is missing spacing above the link list heading.  
Screenshot 2021-11-05 at 18 28 33

**Comment by huntermacd** [comment]
@DragosRistici Should there only be a bottom border when that attribute is present? Otherwise there's no bottom border period, right?

**Comment by huntermacd** [comment]
@DragosRistici Never mind. I understand. Updated!

**Comment by huntermacd** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by jeffchew** [comment]
Some strange spacing things happening across multiple pages, not sure if this was intended?

image

**Comment by huntermacd** [comment]
Thanks, @jeffchew!

Updated.

**Comment by annawen1** [comment]
hey @huntermacd, looks like percy still reporting some changes in desktop, can you take a look?

Screen Shot 2021-11-11 at 3 44 54 PM

**Review by DragosRistici — APPROVED** [review]
Thank you, @huntermacd and @proeung, this looks good! I've seen that the horiz rules are now only on sm breakpoint. Makes sense. Thx!

**Review by kennylam — APPROVED** [review]
LGTM thanks @huntermacd!

**Pull request merged**
