### PR TITLE
fix(masthead-search): delay position for cursor focus

### PR DESCRIPTION
**Pull request by ariellalgilmore**
### Related Ticket(s)

#6173 

### Description

Cursor was rendering in center of the search for a second before jumping to the left align position. 
https://user-images.githubusercontent.com/20210594/119724167-378c3380-be23-11eb-9ced-0879aca47544.MP4

### Changelog

**Changed**

- move focus call to end of function

### CODE REVIEW

**Comment by kennylam** [comment]
@ariellalgilmore This was only occurring with the `search open onLoad` story and it would autofocus on the search bar, correct? Since the autofocus has been removed, is this change still needed?

**Comment by ariellalgilmore** [comment]
> @ariellalgilmore This was only occurring with the `search open onLoad` story and it would autofocus on the search bar, correct? Since the autofocus has been removed, is this change still needed?

This happens on all the masthead stories on mobile when you open the search the cursor flashes for a second in the middle then realigns to the left.

**Review by IgnacioBecerra — APPROVED** [review]
Tested out on my phone, works as expected. Thanks @ariellalgilmore!

**Comment by kennylam** [comment]
> This happens on all the masthead stories on mobile when you open the search the cursor flashes for a second in the middle then realigns to the left.

Got it, I see.

**Pull request merged**
